"""Build isolated new owned-loot and grant audits; never rebuild central DSOs."""
import argparse,hashlib,json,os,shlex,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--output',type=Path,default=ROOT/'port/game-data/reports/player-creation-v2-host-audit.json');a=ap.parse_args()
 sources=['port/game-data/loot_tables_v2.hpp','port/game-data/loot_tables_v2.cpp','port/game-data/fresh_inventory_v2.hpp','port/game-data/fresh_inventory_v2.cpp','port/level-world/player_initial_grants_v2.hpp','port/level-world/player_initial_grants_v2.cpp','port/game-data/items.hpp','port/game-data/items.cpp','port/game-data/player_savegame_v1.hpp','port/game-data/player_savegame_v1.cpp','port/game-data/skill_tables.hpp','port/game-data/skill_tables.cpp','port/game-data/tests/loot_tables_v2.cpp','port/game-data/tests/fresh_inventory_v2.cpp','port/level-world/tests/player_initial_grants_v2.cpp']
 before={p:sha(ROOT/p) for p in sources};base=['g++','-std=c++17','-O1','-g','-Wall','-Wextra','-Werror','-Wno-misleading-indentation','-fno-fast-math','-ffp-contract=off','-fsanitize=address,undefined','-fno-omit-frame-pointer']
 tasks=[('loot',['port/game-data/loot_tables_v2.cpp','port/game-data/items.cpp','port/game-data/tests/loot_tables_v2.cpp'],['port/game-data/reference/player-creation-v2/fixtures.bin','.local-inputs/items-discovery']),('fresh',['port/game-data/fresh_inventory_v2.cpp','port/game-data/loot_tables_v2.cpp','port/game-data/items.cpp','port/game-data/tests/fresh_inventory_v2.cpp'],['port/game-data/reference/player-creation-v2/fresh-fixtures.bin','.local-inputs/items-discovery']),('grants',['port/level-world/player_initial_grants_v2.cpp','port/game-data/player_savegame_v1.cpp','port/game-data/skill_tables.cpp','port/level-world/tests/player_initial_grants_v2.cpp'],['port/level-world/reference/player-initial-grants-v2/fixtures.bin','port/level-world/reference/player-initial-grants-v2/skill-fixtures.bin','.local-inputs/skill-tables'])]
 audits={};executables={};commands=[];wslroot='/mnt/'+ROOT.drive[0].lower()+'/'+ROOT.as_posix()[3:]
 for name,cpp,args in tasks:
  exe='.local-inputs/player-creation-v2/'+name+'-host-audit';build='cd '+shlex.quote(wslroot)+' && '+shlex.join(base+cpp+['-o',exe]);subprocess.run(['wsl','-e','bash','-lc',build],check=True);commands.append(build)
  command='cd '+shlex.quote(wslroot)+' && ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 UBSAN_OPTIONS=halt_on_error=1 '+shlex.join([exe,*args]);r=subprocess.run(['wsl','-e','bash','-lc',command],capture_output=True,text=True);(ROOT/'.local-inputs/player-creation-v2'/f'{name}-host.stdout').write_text(r.stdout);(ROOT/'.local-inputs/player-creation-v2'/f'{name}-host.stderr').write_text(r.stderr);r.check_returncode();audits[name]=json.loads(r.stdout);assert audits[name]['validation']=='PASS' and audits[name]['mismatches']==0 and not r.stderr;rbin=ROOT/exe;executables[exe]=sha(rbin);commands.append(command)
 assert before=={p:sha(ROOT/p) for p in sources}
 golds=['port/game-data/reference/player-creation-v2/fixtures.bin','port/game-data/reference/player-creation-v2/fresh-fixtures.bin','port/level-world/reference/player-initial-grants-v2/fixtures.bin','port/level-world/reference/player-initial-grants-v2/skill-fixtures.bin'];inputs=['.local-inputs/items-discovery/loot_table_pyarray.bin','.local-inputs/items-discovery/loot_table_pyarraynames.bin','.local-inputs/items-discovery/loot_table_pystructnames.bin','.local-inputs/skill-tables/skills_pyarray.bin','.local-inputs/skill-tables/skills_pyarraynames.bin','.local-inputs/skill-tables/skills_pystructnames.bin']
 report={'validation':'PASS','host_audits':audits,'source_sha256':before,'executable_sha256':executables,'gold_sha256':{p:sha(ROOT/p) for p in golds},'cache_input_sha256':{p:sha(ROOT/p) for p in inputs},'script_sha256':sha(__file__),'original_sha256':sha(ROOT/'.local-inputs/libDungeonHunter2.so'),'sanitizers':['address','undefined','leak'],'sanitizer_findings':0,'commands':commands,'scope':'Isolated source-built owners/kernels. Native effect/availability/update services are explicit fixture or required-provider boundaries; no full campaign readiness, real auto-equip effects, or APK execution claim.'}
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
if __name__=='__main__':main()
