"""Freeze the bounded startup preload and explicit unsupported playback evidence."""
import hashlib,json
from pathlib import Path
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[3];ROOT=REPO/'port/level-world'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 arm_path=ROOT/'reports/visual-fx-preload-arm64-differential.json';host_path=ROOT/'reports/visual-fx-preload-host-audit.json';probe_path=HERE/'probe.json';reader_path=HERE/'resource-host-audit.json';arm=json.loads(arm_path.read_text());host=json.loads(host_path.read_text());probe=json.loads(probe_path.read_text());reader=json.loads(reader_path.read_text());assert all(r['validation']=='PASS'for r in [arm,host,probe,reader]);assert arm['mismatches']==host['sanitizer_findings']==reader['sanitizer_findings']==0;assert arm['binary_gold_sha256']==sha(HERE/'preload-fixtures.bin')==host['gold_sha256'];assert probe['manifest_sha256']==arm['manifest_sha256']==sha(HERE/'original-functions.json');assert probe['script_sha256']==sha(HERE/'probe.py')
 for r in [arm,host,reader]:assert all(sha(REPO/n)==v for n,v in r['source_sha256'].items())
 assert reader['native_reader']['skipped_tracks']==3 and reader['native_reader']['ignored_instances']==4 and not reader['native_reader']['GPU_executed'];assert probe['queue_requests']==[283]and host['host_audit']['real_fx77_repeats']==200
 files=[ROOT/x for x in ['visual_fx_preload.hpp','visual_fx_preload.cpp','tests/visual_fx_preload.cpp','tests/visual_fx_preload_differential.py','tests/visual_fx_preload_host.py','tools/build_visual_fx_preload_oracle.ps1']]+[HERE/x for x in ['NOTES.md','original-functions.json','reference/original-functions.asm','probe.py','probe.json','callers.py','callers.json','callers.asm','preload-fixtures.bin','preload-fixtures.json','resource-probe.cpp','resource-host.py','resource-host-audit.json']]+[arm_path,host_path,Path(__file__)]
 record={'validation':'PASS','original_sha256':arm['original_sha256'],'cache_sha256':probe['cache_sha256'],'source_and_proof_sha256':{p.relative_to(REPO).as_posix():sha(p)for p in files},'registration_ready':True,'native_full_library_metadata_ready':False,'native_FX_playback_ready':False,'mandatory_playback_gaps':['SceneManager/AssetManager factory and ownership','particle instances and source28 channels','source86 material channel','material SelfIllum virtual side effects','actual loop callback/sequence/free-pool lifecycle','shader/texture/GPU backend'],'private_snapshot':host['private_snapshot'],'packaged_APK':False,'scope':__doc__};(HERE/'native-source-freeze.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps({'validation':'PASS','freeze_sha256':sha(HERE/'native-source-freeze.json'),'registration_ready':True,'native_FX_playback_ready':False}))
if __name__=='__main__':main()
