include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/production-targets.cmake")
function(dh2_loader_attach_noncharacter_catalog_v67 target)
 cmake_parse_arguments(ARG "" "CATALOG_DIR;LOADER_DIR;WORLD_DIR" "" ${ARGN})
 if(NOT TARGET "${target}" OR NOT ARG_CATALOG_DIR OR NOT ARG_LOADER_DIR OR NOT ARG_WORLD_DIR)
  message(FATAL_ERROR "V67 requires existing owner target and coherent catalog/loader/world directories")
 endif()
 dh2_loader_attach_catalog_auxiliary_v67("${target}" CATALOG_DIR "${ARG_CATALOG_DIR}" LOADER_DIR "${ARG_LOADER_DIR}" WORLD_DIR "${ARG_WORLD_DIR}")
 get_target_property(source_dir "${target}" SOURCE_DIR)
 get_target_property(existing "${target}" SOURCES)
 set(existing_absolute)
 foreach(file IN LISTS existing)
  if(NOT file MATCHES "^\\$<")
   get_filename_component(path "${file}" ABSOLUTE BASE_DIR "${source_dir}")
   list(APPEND existing_absolute "${path}")
  endif()
 endforeach()
 set(catalog_sources production_noncharacter_catalog_v67.cpp production_noncharacter_composition_v67.cpp catalog_containers_v67.cpp catalog_environment_v67.cpp catalog_generic_v70.cpp catalog_colbox_v71.cpp catalog_floor_v72.cpp catalog_projectiles_v99.cpp)
 set(loader_sources canonical_light_point_v53.cpp canonical_light_point_factory_v53.cpp game_object_arrays_owner_v81.cpp canonical_colbox_v71.cpp canonical_floor_v72.cpp canonical_projectile_v99.cpp projectile_resource_services_v99.cpp)
 set(world_sources canonical_openable_graph_v21.cpp light_set_name_owner_v3.cpp canonical_room_zone_v3.cpp canonical_room_zone_factory_v3.cpp)
 set(added)
 foreach(group IN ITEMS catalog loader world)
  string(TOUPPER "${group}" kind)
  foreach(file IN LISTS ${group}_sources)
   get_filename_component(path "${ARG_${kind}_DIR}/${file}" ABSOLUTE)
   if(NOT EXISTS "${path}")
    message(FATAL_ERROR "V67 actual production source missing: ${path}")
   endif()
   if(NOT path IN_LIST existing_absolute)
    list(APPEND existing_absolute "${path}")
    list(APPEND added "${path}")
   endif()
  endforeach()
 endforeach()
 if(added)
  target_sources("${target}" PRIVATE ${added})
  set_source_files_properties(${added} PROPERTIES COMPILE_OPTIONS "-Wno-misleading-indentation")
 endif()
 # Existing owner already provides actual V21 scene/animation/physics and V57
 # Item transport implementation. Do not add candidate/vendor owner copies.
 target_compile_features("${target}" PUBLIC cxx_std_17)
 target_include_directories("${target}" BEFORE PRIVATE "${ARG_CATALOG_DIR}" "${ARG_LOADER_DIR}" "${ARG_WORLD_DIR}")
endfunction()
