#include "character_template_frame_v39.hpp"
#include <cassert>
#include <fstream>
#include <iostream>
#include <iterator>
using namespace dh2;
std::vector<std::uint8_t> bytes(const std::string& name){std::ifstream f(name,std::ios::binary);assert(f);return {std::istreambuf_iterator<char>(f),{}};}
struct Record {std::shared_ptr<character::RetainedCharacterActorV1> actor;};
int main(int argc,char** argv){assert(argc==2);std::string root=argv[1],error;auto recordsBytes=bytes(root+"/character_templates_pyarray.bin"),names=bytes(root+"/character_templates_pyarraynames.bin"),schema=bytes(root+"/character_templates_pystructnames.bin");loader::CharacterTemplateAssetsV35 owner;assert(owner.load({recordsBytes.data(),recordsBytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},error));auto tables=owner.borrow();
 auto app=std::make_shared<world::ApplicationSpawnRandomOwnerV4>();auto world=std::make_shared<int>(1);unsigned predicates=0;
 auto predicate=[&](std::uintptr_t id,bool& player,std::string&){assert(id>=100);++predicates;player=false;return true;};
 auto make=[&](unsigned id,const std::string& templ){auto r=std::make_shared<Record>();r->actor=std::make_shared<character::RetainedCharacterActorV1>(id,world,"Character",character::RetainedCharacterConstructionV7::fresh_canonical);auto properties=r->actor->properties();assert(properties.fields.write_string(properties.fields.context,0x1398,templ,error));return r;};
 auto record=make(100,"Swamp_CommonType1");auto alias=std::shared_ptr<character::RetainedCharacterActorV1>(record,record->actor.get());character::CharacterLoaderFieldsV38 fields;assert(alias->loader_fields_v38(alias,fields,error));loader::CharacterTemplateFrameV39 frame;
 assert(loader::CharacterTemplateFrameV39::bind(alias,app,&app->channel(0),tables,predicate,frame,error));data::LootRandom8V2 foreign{};loader::CharacterTemplateFrameV39 untouched;assert(!loader::CharacterTemplateFrameV39::bind(alias,app,&foreign,tables,predicate,untouched,error));
 auto existing=std::make_shared<character::RetainedCharacterActorV1>(101,world,"Character");assert(!loader::CharacterTemplateFrameV39::bind(existing,app,&app->channel(0),tables,predicate,untouched,error));
 std::weak_ptr<Record> weak=record;record.reset();alias.reset();fields.receiver_lease.reset();assert(!weak.expired());std::int32_t row=-999;assert(frame.select_nonplayer_template(row,error)&&app->channel(0).calls==1&&app->channel(1).calls==0&&predicates==1&&row>=0);auto seed=app->channel(0).seed;assert(frame.select_nonplayer_template(row,error)&&app->channel(0).seed==seed&&app->channel(0).calls==1&&predicates==1);
 auto second=make(102,"Swamp_CommonType2");auto second_alias=std::shared_ptr<character::RetainedCharacterActorV1>(second,second->actor.get());loader::CharacterTemplateFrameV39 frame2;assert(loader::CharacterTemplateFrameV39::bind(second_alias,app,&app->channel(0),tables,predicate,frame2,error));assert(frame2.select_nonplayer_template(row,error)&&app->channel(0).calls==2&&app->channel(1).calls==0&&predicates==2);
 auto missing=make(103,"not-an-original-template");loader::CharacterTemplateFrameV39 missing_frame;auto missing_alias=std::shared_ptr<character::RetainedCharacterActorV1>(missing,missing->actor.get());assert(loader::CharacterTemplateFrameV39::bind(missing_alias,app,&app->channel(0),tables,predicate,missing_frame,error));assert(missing_frame.select_nonplayer_template(row,error)&&row==-1&&app->channel(0).calls==2);assert(missing_alias->loader_fields_v38(missing_alias,fields,error)&&*fields.template13ca==-1);
 auto empty=make(104,"");loader::CharacterTemplateFrameV39 direct;auto empty_alias=std::shared_ptr<character::RetainedCharacterActorV1>(empty,empty->actor.get());assert(loader::CharacterTemplateFrameV39::bind(empty_alias,app,&app->channel(0),tables,predicate,direct,error));assert(!direct.select_nonplayer_template(row,error)&&app->channel(0).calls==2);
 loader::CharacterTemplateFrameV39 player;assert(loader::CharacterTemplateFrameV39::bind(empty_alias,app,&app->channel(0),tables,[](auto,bool& v,std::string&){v=true;return true;},player,error));assert(!player.select_nonplayer_template(row,error)&&error.find("SG_Load")!=std::string::npos&&app->channel(0).calls==2);
 assert(empty_alias->loader_fields_v38(empty_alias,fields,error));*fields.properties13c8=97;*fields.template13ca=77;loader::CharacterTemplateFrameV39 cached;assert(loader::CharacterTemplateFrameV39::bind(empty_alias,app,&app->channel(0),{}, {},cached,error));assert(cached.select_nonplayer_template(row,error)&&row==97&&*fields.template13ca==77&&app->channel(0).calls==2);
 std::cout<<"PASS actual_actor_cache_binding=1 record_alias_lifetime=1 shared_application_two_actors=1 no_rng_on_cached_missing_direct_player=1 adoption_foreign_rng_rejected=1\n";
}
