#include "character_is_player_v41.hpp"
#include <cassert>
#include <fstream>
#include <iostream>
using namespace dh2::character;
int main(int argc,char** argv){assert(argc==2);std::int32_t type=0;std::string archetype,error="old";auto lease=std::make_shared<int>(1);unsigned calls=0;CharacterIsPlayerFieldsV41 fields{lease,42,&archetype};CharacterIsPlayerServicesV41 services{[&](auto id,std::int32_t& out,std::string&){assert(id==42);++calls;out=type;return true;}};unsigned cases=0,original=0;
 {std::ifstream gold(argv[1]);assert(gold);std::string line;while(std::getline(gold,line)){auto one=line.find('\t'),two=line.find('\t',one+1);assert(one!=std::string::npos&&two!=std::string::npos);type=std::stoi(line.substr(0,one));const auto hex=line.substr(one+1,two-one-1);archetype.clear();for(std::size_t i=0;i<hex.size();i+=2)archetype.push_back(static_cast<char>(std::stoi(hex.substr(i,2),nullptr,16)));bool result=false;assert(character_is_player_v41(fields,services,result,error)&&result==bool(std::stoi(line.substr(two+1))));++original;}assert(original==63);}
 for(type=-1;type<=4;++type)for(const auto& value:{"","PlayerCharacter","PlayerCharacterKnight","xPlayerCharacter","playercharacter","NPC_PlayerCharacter","PlayerCharacter PlayerCharacter","PlayerCharacte"}){archetype=value;bool result=true;assert(character_is_player_v41(fields,services,result,error)&&error.empty());assert(result==(type?type==1:archetype.rfind("PlayerCharacter",0)==0));++cases;}
 type=0;archetype=std::string("PlayerCharacter\0ignored",23);bool result=false;assert(character_is_player_v41(fields,services,result,error)&&result);++cases;
 archetype="xPlayerCharacter";assert(character_is_player_v41(fields,services,result,error)&&!result);archetype="PlayerCharacterMage";assert(character_is_player_v41(fields,services,result,error)&&result);type=3;assert(character_is_player_v41(fields,services,result,error)&&!result);fields.live_archetype=nullptr;type=1;assert(character_is_player_v41(fields,services,result,error)&&result);type=0;result=true;assert(!character_is_player_v41(fields,services,result,error)&&result);fields.live_archetype=&archetype;CharacterIsPlayerServicesV41 missing;assert(!character_is_player_v41(fields,missing,result,error)&&result);
 std::cout<<"PASS original_matched="<<original<<" native_predicate_cases="<<cases<<" live_type_archetype_changes=1 missing_type0_archetype_preserves_out=1 nonzero_type_skips_archetype=1 missing_provider_explicit=1 service_calls="<<calls<<'\n';}
