#include "../faery_tables.hpp"
#include <fstream>
#include <iostream>
#include <cstring>
using namespace dh2::data;using Raw=std::vector<std::uint8_t>;
namespace {unsigned checks=0,guards=0;void check(bool b){++checks;if(!b)throw std::runtime_error("Faery check "+std::to_string(checks));}unsigned word(std::istream& f){unsigned n;f.read(reinterpret_cast<char*>(&n),4);check(bool(f));return n;}Raw blob(std::istream& f){Raw b(word(f));f.read(reinterpret_cast<char*>(b.data()),b.size());check(bool(f));return b;}Raw file(const char* p){std::ifstream f(p,std::ios::binary);check(bool(f));return {std::istreambuf_iterator<char>(f),{}};}Bytes bytes(const Raw& b){return {b.data(),b.size()};}}
int main(int argc,char** argv){try{check(argc==5);auto data=file(argv[2]),names=file(argv[3]),schema=file(argv[4]);FaeryTables owner;std::string error;check(owner.load(bytes(data),bytes(names),bytes(schema),error));auto pin=owner.borrow();check(pin.lists().size()==4&&pin.faeries().size()==16&&pin.list_table_consumed()==100&&pin.records_consumed()==699&&pin.names_consumed()==253&&pin.schema_consumed()==101);check(pin.list_index("DEFAULT")==0&&pin.faery_index("Fake_Celest")==2);check(pin.lists()[0]==std::vector<std::int32_t>({2,4,5,6,3}));for(auto id:pin.lists()[0])check(pin.faeries()[id].script.empty());std::ifstream gold(argv[1],std::ios::binary);check(word(gold)==0x31594146);auto nr=word(gold),nl=word(gold),nt=word(gold);for(unsigned i=0;i<nr;++i){auto b=blob(gold);FaeryProjection36 want;gold.read(reinterpret_cast<char*>(&want),36);auto s=blob(gold);FaeryProjection36 out{};FaerySpan16 view{};unsigned used;check(!dh2_faery_decode_record(&out,&view,&used,b.data(),b.size())&&used==b.size()&&!std::memcmp(&out,&want,36)&&view.bytes==s.size()&&!view.reserved);if(!s.empty())check(!std::memcmp(s.data(),view.data,s.size()));if(i<16)check(!std::memcmp(&pin.faeries()[i].scalar,&want,36)&&pin.faeries()[i].script==std::string(s.begin(),s.end()));}
 for(unsigned i=0;i<nl;++i){auto b=blob(gold),want=blob(gold);FaerySpan16 out{};unsigned used;check(!dh2_faery_decode_list(&out,&used,b.data(),b.size())&&used==b.size()&&out.bytes==want.size());if(!want.empty())check(!std::memcmp(out.data,want.data(),want.size()));if(i<4)check(pin.lists()[i].size()*4==want.size()&&!std::memcmp(pin.lists()[i].data(),want.data(),want.size()));}
 for(unsigned i=0;i<nt;++i){auto b=blob(gold);FaerySummary16 want,out{};gold.read(reinterpret_cast<char*>(&want),16);check(bool(gold)&&!dh2_faery_tables_measure(&out,b.data(),b.size())&&!std::memcmp(&out,&want,16));}check(gold.peek()==EOF);check(!owner.load(bytes(data),bytes(names),bytes(schema),error));++guards;pin={};
 for(unsigned i=0;i<data.size();++i){check(!owner.load({data.data(),i},bytes(names),bytes(schema),error));check(owner.borrow().faeries().size()==16);++guards;}
 for(unsigned i=0;i<names.size();++i){check(!owner.load(bytes(data),{names.data(),i},bytes(schema),error));++guards;}
 for(unsigned i=0;i<101;++i){check(!owner.load(bytes(data),bytes(names),{schema.data(),i},error));++guards;}
 auto wrong=schema;wrong[8]^=1;check(!owner.load(bytes(data),bytes(names),bytes(wrong),error));++guards;FaeryProjection36 p{},before{};std::memset(&p,0xa5,36);before=p;FaerySpan16 span{};unsigned used=0xa5a5a5a5;for(unsigned n=0;n<28;++n){check(dh2_faery_decode_record(&p,&span,&used,data.data(),n)==1&&used==0xa5a5a5a5&&!std::memcmp(&p,&before,36));++guards;}
 check(dh2_faery_decode_record(&p,reinterpret_cast<FaerySpan16*>(&p),&used,data.data(),data.size())==1);++guards;check(dh2_faery_tables_measure(reinterpret_cast<FaerySummary16*>(data.data()),data.data(),data.size())==1);++guards;alignas(FaeryProjection36) unsigned char unaligned[37];check(dh2_faery_decode_record(reinterpret_cast<FaeryProjection36*>(unaligned+1),&span,&used,data.data(),data.size())==1);++guards;
 pin=owner.borrow();auto retained=pin.faeries()[1].script;owner=FaeryTables{};data.clear();data.shrink_to_fit();names.clear();schema.clear();check(pin.faeries()[1].script==retained&&pin.list_index("DEFAULT")==0);
 std::cout<<"{\"validation\":\"PASS\",\"checks\":"<<checks<<",\"record_comparisons\":"<<nr<<",\"list_comparisons\":"<<nl<<",\"table_checks\":"<<nt<<",\"atomic_guards\":"<<guards<<",\"retained_after_owner_inputs_destroyed\":true,\"actual_default_five_null_scripts\":true}\n";
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
