#include "../loot_power_creation_v7.hpp"
#include "../fresh_inventory_owned_v4.hpp"
#include "../../engine-ui/item_text_owner_v5.hpp"
#include "../../level-world/character_design_services.hpp"
#include "../../script-runtime/script_constants.hpp"
#include <cstdio>
#include <cerrno>
#include <fstream>
#include <iostream>
#include <cstring>
#include <array>
using namespace dh2::data;using Raw=std::vector<std::uint8_t>;static unsigned checks;
static void ck(bool b,const std::string& e="Check failed"){++checks;if(!b)throw std::runtime_error(e+" at check "+std::to_string(checks));}
static Raw file(const std::string& p){std::ifstream f(p,std::ios::binary);ck(bool(f),p);return {std::istreambuf_iterator<char>(f),{}};}
static Bytes bytes(const Raw& r){return {r.data(),r.size()};}
static dh2::ui::LocalizationBytes localized_bytes(const Raw& r){return {r.data(),r.size()};}
struct Reader{const Raw& b;std::size_t at{};std::uint32_t u(){ck(at+4<=b.size());std::uint32_t n;std::memcpy(&n,b.data()+at,4);at+=4;return n;}Raw block(){auto n=u();ck(n<=b.size()-at);Raw r(b.begin()+at,b.begin()+at+n);at+=n;return r;}};
static void word(Raw& b,std::uint32_t x){auto* p=reinterpret_cast<const std::uint8_t*>(&x);b.insert(b.end(),p,p+4);}
extern "C" std::uint32_t dh2_loot_power_creation_fixture_v7(const std::uint8_t*,std::uint8_t*);
struct Environment{
 std::string assets,private_files;dh2_script_constants* constants=dh2_script_constants_create();dh2::character::DebugSwitches* debug=dh2_character_debug_create();unsigned opens{},closes{},debug_calls{};
 ~Environment(){dh2_script_constants_destroy(constants);dh2_character_debug_destroy(debug);}
};
static int debug_open(void* p,const char* uri,std::uintptr_t* lease){auto& c=*static_cast<Environment*>(p);auto* f=std::fopen((c.private_files+"/"+uri).c_str(),"rb");if(!f)return errno==ENOENT?0:-1;*lease=reinterpret_cast<std::uintptr_t>(f);return 1;}
static int debug_close(void*,std::uintptr_t lease){return std::fclose(reinterpret_cast<FILE*>(lease))?-1:0;}
static bool debug_call(Environment& c,bool load,const char* key,std::int32_t& result){dh2::character::DebugFileServices24 s{&c,debug_open,debug_close};++c.debug_calls;if(load)return dh2_character_debug_load(c.debug,&s)==1;std::uint32_t v;auto status=dh2_character_debug_get(&v,c.debug,key,&s);std::memcpy(&result,&v,4);return status==1;}
static bool constant(void* p,const char* g,const char* k,std::uint32_t& v,std::string& e){std::int32_t w;if(dh2_script_constants_get(static_cast<Environment*>(p)->constants,g,k,&w)){e="Required real constant absent";return false;}std::memcpy(&v,&w,4);return true;}
static bool open(void* p,const char* uri,bool& found,Raw& data,std::uintptr_t& lease,std::string& e){auto& c=*static_cast<Environment*>(p);auto* f=std::fopen((c.assets+"/original-cache/data/"+uri).c_str(),"rb");found=bool(f);if(!f){if(errno==ENOENT)return true;e="Actual locale open failed";return false;}lease=reinterpret_cast<std::uintptr_t>(f);++c.opens;if(std::fseek(f,0,SEEK_END)){e="Actual locale seek failed";return false;}auto n=std::ftell(f);if(n<0||std::fseek(f,0,SEEK_SET)){e="Actual locale size failed";return false;}data.resize(n);if(std::fread(data.data(),1,data.size(),f)!=data.size()){e="Actual locale read failed";return false;}return true;}
static bool close(void* p,std::uintptr_t lease,std::string&){++static_cast<Environment*>(p)->closes;return std::fclose(reinterpret_cast<FILE*>(lease))==0;}
static bool text_debug(void* p,const char* key,std::string&){std::int32_t value;auto& c=*static_cast<Environment*>(p);return debug_call(c,true,nullptr,value)&&debug_call(c,false,key,value);}
struct Context{Environment* env;dh2::ui::ItemTextOwnerV5* text;ItemPresentationOwnerV5* powers;LootPowerCreationV7* creation{};bool fail_append{},empty_append{},reenter{};unsigned append_calls{};};
static bool power(void* p,const LootPowerRequestV7& q,std::int32_t& result,std::string& e){auto& c=*static_cast<Context*>(p);if(q.operation==LootPowerOperationV7::add_power){++c.append_calls;if(c.fail_append){e="Declared reached append failure";return false;}if(c.empty_append)return true;if(c.reenter){c.reenter=false;LootEntry32V2 entry{};entry.words[1]=0;std::string nested;ck(!c.creation->add_powers(entry,*q.item,0,0,0,{p,power},nested)&&nested.find("reentry")!=std::string::npos);}return c.powers->add_power(*q.item,q.power,q.difficulty,c.text->services(),e);}return debug_call(*c.env,q.operation==LootPowerOperationV7::debug_load,q.key,result);}
static bool inventory(void* p,FreshInventoryOwnedV4&,const OwnedInventoryRequestV4& q,OwnedInventoryResponseV4& response,std::string& e){auto& c=*static_cast<Context*>(p);auto text=c.text->services();if(q.operation==OwnedInventoryOperationV4::update_name)return item_update_name_v5(*q.item,text,e);if(q.operation==OwnedInventoryOperationV4::update_stats)return item_update_stats_v5(*q.item,text,e);if(q.operation==OwnedInventoryOperationV4::update_requirements)return item_update_requirements_v5(*q.item,text,e);if(q.operation==OwnedInventoryOperationV4::debug_load||q.operation==OwnedInventoryOperationV4::debug_query)return debug_call(*c.env,q.operation==OwnedInventoryOperationV4::debug_load,q.name,response.value);e="Unimplemented inventory effect reached";return false;}
int main(int argc,char** argv){try{
 ck(argc==6);std::string e;std::array<Raw,9> raw;const char* names[]={"item_powers_pyarray.bin","item_powers_pyarraynames.bin","item_powers_pystructnames.bin","item_powers_monopoly_pyarray.bin","item_powers_monopoly_pyarraynames.bin","item_powers_monopoly_pystructnames.bin","num_prob_records_v7.bin","loot_table_pyarraynames.bin","loot_table_pystructnames.bin"};for(unsigned i=0;i<9;++i)raw[i]=file(std::string(argv[2])+"/"+names[i]);LootPowerInputsV7 input{bytes(raw[0]),bytes(raw[1]),bytes(raw[2]),bytes(raw[3]),bytes(raw[4]),bytes(raw[5]),bytes(raw[6]),bytes(raw[7]),bytes(raw[8])};
 ItemPowerTablesV5 definitions;ck(definitions.load(input.powers,input.power_names,input.power_schema,e),e);LootPowerResourcesV7 resources;ck(resources.load(input,definitions.borrow(),e),e);
 auto pinned=resources.borrow();ck(pinned.lists().size()==121&&pinned.quantities().size()==39&&pinned.powers().rows().size()==937);ck(!resources.load(input,definitions.borrow(),e));unsigned guards=1;
 for(unsigned i=0;i<9;++i){auto bad=input;Bytes* fields[]={&bad.powers,&bad.power_names,&bad.power_schema,&bad.monopoly,&bad.monopoly_names,&bad.monopoly_schema,&bad.quantities,&bad.loot_names,&bad.loot_schema};fields[i]->size=1;LootPowerResourcesV7 candidate;ck(!candidate.load(bad,definitions.borrow(),e));ck(!candidate.borrow());++guards;}
 {LootPowerResourcesV7 candidate;ck(candidate.load(input,definitions.borrow(),e),e);auto bad=input;bad.power_names.size=1;ck(!candidate.load(bad,definitions.borrow(),e));ck(candidate.borrow().lists().size()==121);++guards;}
 // Every frozen original case, on the same native C++ kernels and coordinator.
 auto gold=file(argv[1]);Reader r{gold};ck(r.u()==0x3756504c);auto count=r.u();unsigned weighted=0,quantity=0,value=0;
 while(count--){auto command=r.block(),expected=r.block();Reader c{command};auto op=c.u();LootRandom8V2 random{c.u(),c.u()};auto n=c.u();std::int32_t out=0;auto status=-1;
  if(op==0){std::vector<LootPowerChoiceV7> rows(n);for(auto& row:rows){row.power=static_cast<std::int32_t>(c.u());auto w=c.u();std::memcpy(&row.probability,&w,1);}std::uint32_t result;status=dh2_loot_power_select_v7(&result,&random,rows.data(),n);std::memcpy(&out,&result,4);++weighted;}
  else if(op==1){auto bonus=static_cast<std::int32_t>(c.u());std::vector<LootQuantityChoiceV7> rows(n);for(auto& row:rows){auto w=c.u();std::memcpy(&row,&w,4);}status=dh2_loot_quantity_v7(&out,&random,rows.data(),n,bonus);++quantity;}
  else{ck(op==2);auto bonus=static_cast<std::int32_t>(c.u());ItemRecord164 record{};for(auto& w:record.words)w=static_cast<std::int32_t>(c.u());std::vector<LootPowerGold8V7> powers(n);for(auto& p:powers){p.multiplier=static_cast<std::int32_t>(c.u());p.bonus=static_cast<std::int32_t>(c.u());}status=dh2_loot_item_value_v7(&out,&random,&record,powers.data(),n,bonus);++value;}
  ck(status==0&&c.at==command.size());Raw actual;word(actual,std::uint32_t(out));word(actual,random.seed);word(actual,random.calls);ck(actual==expected);
 }
 auto cases=r.u();Raw commands,expected;word(commands,cases);for(unsigned i=0;i<cases;++i){auto command=r.block(),result=r.block();commands.insert(commands.end(),command.begin(),command.end());word(expected,result.size());expected.insert(expected.end(),result.begin(),result.end());}ck(r.at==gold.size());Raw fixture;for(const auto& b:raw){word(fixture,b.size());fixture.insert(fixture.end(),b.begin(),b.end());}fixture.insert(fixture.end(),commands.begin(),commands.end());Raw actual(expected.size()+1024);auto length=dh2_loot_power_creation_fixture_v7(fixture.data(),actual.data());ck(length==expected.size());actual.resize(length);ck(actual==expected);
 // Real localized text and authoritative V4 storage, no formatter/query stubs.
 auto lb=file(std::string(argv[2])+"/loot_table_pyarray.bin");LootTablesV2 loots;ck(loots.load(bytes(lb),input.loot_names,input.loot_schema,e),e);
 auto cb=file(std::string(argv[3])+"/character_properties_pyarray.bin"),cn=file(std::string(argv[3])+"/character_properties_pyarraynames.bin"),cs=file(std::string(argv[3])+"/character_properties_pystructnames.bin");CharacterTable characters;ck(load_characters(bytes(cb),bytes(cn),bytes(cs),characters,e),e);
 Environment env;env.assets=argv[4];env.private_files=argv[5];ck(env.constants&&env.debug);auto constants=file(env.assets+"/original-cache/data/pydata/common_text_pycst.bin");dh2_script_constants_reload receipt{};ck(!dh2_script_constants_load(env.constants,constants.data(),constants.size(),&receipt)&&receipt.consumed==constants.size());dh2::ui::HudTextV1 text;auto tb=file(env.assets+"/original-cache/data/pydata/common_text_pyarray.bin"),tn=file(env.assets+"/original-cache/data/pydata/common_text_pyarraynames.bin"),ts=file(env.assets+"/original-cache/data/pydata/common_text_pystructnames.bin");ck(text.load(localized_bytes(tb),localized_bytes(tn),localized_bytes(ts),e)&&text.switch_pack(0,false,e),e);dh2::ui::LocalizationServices loc{&env,open,close,text_debug,constant,nullptr,nullptr};dh2::ui::ItemTextOwnerV5 adapter(loots.borrow().items(),characters,text,{loc});
 LootRandom8V2 random{1,0};LootPowerCreationV7 creation(pinned,random);ItemPresentationOwnerV5 presentation(definitions.borrow());Context ctx{&env,&adapter,&presentation,&creation};auto properties=std::make_shared<PropertyState>();FreshInventoryOwnedV4 owner(0x100000001,loots.borrow(),random,12,properties);OwnedInventoryServicesV4 services{&ctx,inventory};unsigned localized=0,stored=0;
 // Declared source-field fixture permits all 363 independent creation cases
 // on the same inventory. The ordinary full-notification boundary is checked
 // immediately afterward and is never accepted by the production provider.
 owner.project_unlimited(true);
 for(unsigned id=0;id<pinned.lists().size();++id)for(int mode=0;mode<3;++mode){std::unique_ptr<ItemInstanceV1> item;ck(owner.create_item(664,1,item,services,e),e);auto* identity=item.get();LootEntry32V2 entry{};entry.words[1]=id;ck(creation.add_powers(entry,*item,0,1,mode,{&ctx,power},e),e);ck(loot_item_value_v7(*item,owner.table(),definitions.borrow(),random,0,adapter.services(),e),e);ck(!item->name.empty());auto* p=presentation.powers(*item);if(p)for(auto& v:*p)ck(!v.description.empty());++localized;std::int32_t index;ck(owner.add_item(item,true,false,index,services,e),e);ck(!item&&index>=0&&owner.items().at(index)->item.get()==identity);++stored;}
 owner.project_unlimited(false);std::unique_ptr<ItemInstanceV1> full_item;ck(owner.create_item(664,1,full_item,services,e),e);auto* full_identity=full_item.get();std::int32_t full_index;ck(!owner.add_item(full_item,true,false,full_index,services,e));ck(!full_item&&owner.items().back()->item.get()==full_identity&&e=="Unimplemented inventory effect reached");++guards;
 // Failure prefix and provider guards must stay observable.
 ItemInstanceV1 sample;sample.id=664;LootEntry32V2 entry{};entry.words[1]=0;ctx.empty_append=true;ck(!creation.add_powers(entry,sample,0,1,0,{&ctx,power},e));ck(e.find("append one")!=std::string::npos);ctx.empty_append=false;++guards;
 ctx.fail_append=true;ck(!creation.add_powers(entry,sample,0,1,0,{&ctx,power},e)&&sample.powers.empty());ctx.fail_append=false;++guards;
 ctx.reenter=true;ck(creation.add_powers(entry,sample,0,1,0,{&ctx,power},e),e);ck(!sample.powers.empty());++guards;ck(presentation.forget(sample,e));
 ItemInstanceV1 missing;missing.id=664;missing.value=-123;ck(!loot_item_value_v7(missing,owner.table(),definitions.borrow(),random,0,{},e)&&missing.value!=-123);++guards;
 LootRandom8V2 before=random;std::int32_t sentinel=42;ck(dh2_loot_quantity_v7(&sentinel,&random,nullptr,0,0)==-2&&sentinel==42&&!std::memcmp(&before,&random,8));++guards;ck(dh2_loot_quantity_v7(reinterpret_cast<std::int32_t*>(&random),&random,nullptr,0,0)==-1);++guards;
 for(const auto& slot:owner.items())ck(presentation.forget(*slot->item,e));resources=LootPowerResourcesV7{};definitions=ItemPowerTablesV5{};for(auto& b:raw)b.clear();ck(creation.resources().lists().size()==121&&pinned.powers().rows().size()==937);ck(env.opens==env.closes);
 std::cout<<"{\"validation\":\"PASS\",\"weighted_original_cases\":"<<weighted<<",\"quantity_original_cases\":"<<quantity<<",\"value_original_cases\":"<<value<<",\"coordinator_original_cases\":"<<cases<<",\"genuine_localized_powered_items\":"<<localized<<",\"same_inventory_stored_items\":"<<stored<<",\"required_lifetime_guards\":"<<guards<<",\"actual_localization_opens\":"<<env.opens<<",\"genuine_debug_calls\":"<<env.debug_calls<<",\"checks\":"<<checks<<",\"mismatches\":0,\"unlimited_inventory_source_field_fixture\":true,\"required_full_notification_prefix_verified\":true,\"full_AddLoot_caller\":false}\n";return 0;
 }catch(const std::exception& x){std::cerr<<x.what()<<'\n';return 1;}}
