#include "../loot_table_selection_v8.hpp"
#include <fstream>
#include <iostream>
#include <cstring>
#include <stdexcept>
using namespace dh2::data;
namespace {using Raw=std::vector<std::uint8_t>;unsigned checks{};void check(bool b,const std::string& e={}){++checks;if(!b)throw std::runtime_error(e.empty()?"Original loot table mismatch":e);}Raw file(const std::string& name){std::ifstream f(name,std::ios::binary);check(bool(f),name);return {std::istreambuf_iterator<char>(f),{}};}Bytes span(const Raw& b){return {b.data(),b.size()};}void word(Raw& b,unsigned v){auto* p=reinterpret_cast<const std::uint8_t*>(&v);b.insert(b.end(),p,p+4);}struct Reader{const Raw& b;std::size_t at{};unsigned u(){check(at+4<=b.size());unsigned v;std::memcpy(&v,b.data()+at,4);at+=4;return v;}Raw block(unsigned n){check(at+n<=b.size());Raw out(b.begin()+at,b.begin()+at+n);at+=n;return out;}};
struct Services{int infinite{},counts[3]{};std::vector<unsigned> calls;static bool invoke(void* p,const LootEntryRequestV8& q,int& out,std::string&){auto& s=*static_cast<Services*>(p);using O=LootEntryOperationV8;switch(q.operation){case O::debug_load:s.calls.push_back(0);out=0;return true;case O::debug_query:if(!std::strcmp(q.key,"InfiniteLootDrops")){s.calls.push_back(1);out=s.infinite;return true;}if(!std::strcmp(q.key,"isTracingItemPctRoll")){s.calls.push_back(2);out=0;return true;}if(!std::strcmp(q.key,"isTracingItemInventory_Loot")){s.calls.push_back(6);out=0;return true;}return false;case O::mage_count:s.calls.push_back(3);out=s.counts[0];return true;case O::rogue_count:s.calls.push_back(4);out=s.counts[1];return true;case O::warrior_count:s.calls.push_back(5);out=s.counts[2];return true;default:return false;}}};}
int main(int argc,char** argv){try{check(argc==3);const std::string cache=argv[2];std::string error;const char* names[]={"item_powers_pyarray.bin","item_powers_pyarraynames.bin","item_powers_pystructnames.bin","item_powers_monopoly_pyarray.bin","item_powers_monopoly_pyarraynames.bin","item_powers_monopoly_pystructnames.bin","num_prob_records_v7.bin","loot_table_pyarraynames.bin","loot_table_pystructnames.bin"};std::array<Raw,9> raw;for(unsigned i=0;i<9;++i)raw[i]=file(cache+"/"+names[i]);LootPowerInputsV7 input{span(raw[0]),span(raw[1]),span(raw[2]),span(raw[3]),span(raw[4]),span(raw[5]),span(raw[6]),span(raw[7]),span(raw[8])};ItemPowerTablesV5 definitions;check(definitions.load(input.powers,input.power_names,input.power_schema,error),error);LootPowerResourcesV7 resources;check(resources.load(input,definitions.borrow(),error),error);auto records=file(cache+"/loot_table_pyarray.bin");LootTablesV2 tables;check(tables.load(span(records),input.loot_names,input.loot_schema,error),error);
 auto gold=file(argv[1]);Reader r{gold};check(r.block(4)==Raw({'L','T','S','8'}));auto n=r.u();unsigned emitted=0;for(unsigned i=0;i<n;++i){auto id=r.u();LootRandom8V2 random{r.u(),r.u()};Services service;service.infinite=int(r.u());for(auto& c:service.counts)c=int(r.u());auto expected=r.block(r.u());LootTableSelectionV8 selector(tables.borrow(),resources.borrow(),random,{&service,Services::invoke});std::vector<const LootEntry32V2*> selected;if(!selector.select(int(id),selected,error)){std::cerr<<"case "<<i<<" table "<<id<<" "<<error<<'\n';return 1;}Raw actual;word(actual,random.seed);word(actual,random.calls);word(actual,unsigned(selected.size()));for(auto* entry:selected){auto* b=reinterpret_cast<const std::uint8_t*>(entry->words);actual.insert(actual.end(),b,b+32);}word(actual,unsigned(service.calls.size()));for(auto call:service.calls)word(actual,call);if(actual!=expected){std::size_t k=0;while(k<actual.size()&&k<expected.size()&&actual[k]==expected[k])++k;std::cerr<<"case "<<i<<" table "<<id<<" mismatch byte "<<k<<" actualsize "<<actual.size()<<" expectedsize "<<expected.size()<<'\n';return 1;}emitted+=unsigned(selected.size());check(true);}check(r.at==gold.size());std::cout<<"{\"validation\":\"PASS\",\"original_cases\":"<<n<<",\"actual_cache_entries_selected\":"<<emitted<<",\"checks\":"<<checks<<",\"full_AddLoot_item_creation\":false}\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
