#include "../player_save_quest_sync_v3.hpp"
#include <cassert>
#include <iostream>
using namespace dh2::data;
int main(){std::string error;auto lease=std::make_shared<int>(1);unsigned calls=0;
 PlayerSavegameV1 save;save.set_character(0x100000005ull);assert(save.source_quest_sync_ready14_v3()==0&&save.slot()==-1);PlayerSaveQuestSyncOwnerV3 sync(save);PlayerSaveQuestSyncServicesV3 s;s.owner=lease;s.online=[&](bool& value,auto&){++calls;value=false;return true;};assert(sync.try_sync(s,error)&&save.source_quest_sync_ready14_v3()==1&&calls==1);assert(sync.try_sync(s,error)&&calls==2);
 s.online=[](bool& value,auto&){value=true;return true;};s.is_local_player=[&](auto identity,bool& value,auto&){assert(identity==save.character());++calls;value=true;return true;};assert(sync.try_sync(s,error)&&calls==3); // online already-ready still performs local lookup
 for(unsigned failure=0;failure<=4;++failure){PlayerSavegameV1 fresh;PlayerSaveQuestSyncOwnerV3 owner(fresh);std::vector<unsigned> steps;PlayerSaveQuestUnpackServicesV3 u;u.owner=lease;auto step=[&](unsigned index){steps.push_back(index);return index!=failure;};u.initialize_volatile_quests=[&](auto& receiver,auto&){assert(&receiver==&fresh);return step(1);};u.seek_stream_zero=[&](auto&){return step(2);};u.unpack_volatile_quests=[&](auto& receiver,bool flag,auto&){assert(&receiver==&fresh&&flag);return step(3);};u.compile_volatile_quests=[&](auto& receiver,bool flag,auto&){assert(&receiver==&fresh&&flag);return step(4);};assert(owner.unpack_sync(u,error)==(failure==0));assert(fresh.source_quest_sync_ready14_v3()==(failure==0));assert(steps.size()==(failure?failure:4));}
 PlayerSavegameV1 host;host.set_character(19);PlayerSaveQuestSyncOwnerV3 host_owner(host);s.is_local_player=[](auto identity,bool& value,auto&){assert(identity==19);value=true;return true;};s.local_hosting=[](bool& value,auto&){value=true;return true;};s.pack_send_volatile_quests=[&](auto& receiver,auto&){assert(&receiver==&host&&receiver.source_quest_sync_ready14_v3()==0);return true;};s.destroy_quest_stream=[&](auto&){assert(host.source_quest_sync_ready14_v3()==1);return false;};assert(!host_owner.try_sync(s,error)&&host.source_quest_sync_ready14_v3()==1); // mutation precedes source stream destructor
 PlayerSavegameV1 remote;PlayerSaveQuestSyncOwnerV3 remote_owner(remote);s.is_local_player=[](auto,bool& value,auto&){value=true;return true;};s.local_hosting=[](bool& value,auto&){value=false;return true;};s.current_level=[](auto& identity,auto& phase,auto&){identity=42;phase=37;return true;};s.hosting_ready710=[](auto& byte,auto&){byte=1;return true;};assert(remote_owner.try_sync(s,error)&&remote.source_quest_sync_ready14_v3()==0);s.current_level=[](auto& identity,auto& phase,auto&){identity=42;phase=38;return true;};s.receive_quest_sync={};assert(!remote_owner.try_sync(s,error)&&remote.source_quest_sync_ready14_v3()==0);
 std::cout<<"Same Save quest-sync source offline/online/local/host/destructor/unpack ordering PASS; positive quest/messaging endpoints declared fixtures\n";
}
