#include "../player_gear_effects_v5.hpp"
#include "../../engine-ui/item_text_owner_v5.hpp"
#include "../../level-world/character_design_services.hpp"
#include "../../script-runtime/script_constants.hpp"
#include <cstdio>
#include <cerrno>
#include <set>
#include <iomanip>
#include <fstream>
#include <iostream>
#include <cstring>
using namespace dh2::data;using Raw=std::vector<std::uint8_t>;static unsigned checks;
static void ck(bool b){if(!b)throw std::runtime_error("Gear owner V5 check "+std::to_string(checks));++checks;}
static Raw file(const std::string& p){std::ifstream f(p,std::ios::binary);ck(bool(f));return {std::istreambuf_iterator<char>(f),{}};}
struct Reader{const Raw& b;std::size_t at{};void copy(void* p,std::size_t n){ck(n<=b.size()-at);std::memcpy(p,b.data()+at,n);at+=n;}std::uint32_t u(){std::uint32_t n;copy(&n,4);return n;}};
struct TextEnvironment {
 std::string assets,private_files;dh2_script_constants* constants=dh2_script_constants_create();
 dh2::character::DebugSwitches* debug=dh2_character_debug_create();
 unsigned opened{},closed{},debug_missing{};std::set<std::string> opened_paths;
 ~TextEnvironment(){dh2_script_constants_destroy(constants);dh2_character_debug_destroy(debug);}
};
static bool text_constant(void* p,const char* g,const char* k,std::uint32_t& v,std::string& e){std::int32_t w;int s=dh2_script_constants_get(static_cast<TextEnvironment*>(p)->constants,g,k,&w);if(s){e="Genuine constant absent";return false;}std::memcpy(&v,&w,4);return true;}
static bool text_open(void* p,const char* uri,bool& found,Raw& bytes,std::uintptr_t& lease,std::string& e){auto& c=*static_cast<TextEnvironment*>(p);std::string path=c.assets+"/original-cache/data/"+uri;auto* f=std::fopen(path.c_str(),"rb");found=f!=nullptr;if(!f){if(errno!=ENOENT){e="Actual localization open failure";return false;}return true;}lease=reinterpret_cast<std::uintptr_t>(f);++c.opened;c.opened_paths.insert(path);if(std::fseek(f,0,SEEK_END)){e="Actual file seek failure";return false;}auto n=std::ftell(f);if(n<0||std::fseek(f,0,SEEK_SET)){e="Actual file size failure";return false;}bytes.resize(n);if(std::fread(bytes.data(),1,bytes.size(),f)!=bytes.size()){e="Actual file read failure";return false;}return true;}
static bool text_close(void* p,std::uintptr_t lease,std::string&){++static_cast<TextEnvironment*>(p)->closed;return !std::fclose(reinterpret_cast<FILE*>(lease));}
static int debug_open(void* p,const char* name,std::uintptr_t* lease){auto& c=*static_cast<TextEnvironment*>(p);auto* f=std::fopen((c.private_files+"/"+name).c_str(),"rb");if(!f){if(errno!=ENOENT)return -1;++c.debug_missing;return 0;}*lease=reinterpret_cast<std::uintptr_t>(f);return 1;}
static int debug_close(void*,std::uintptr_t lease){return std::fclose(reinterpret_cast<FILE*>(lease))? -1:0;}
static bool text_debug(void* p,const char* name,std::string& e){auto& c=*static_cast<TextEnvironment*>(p);dh2::character::DebugFileServices24 s{&c,debug_open,debug_close};unsigned v;if(dh2_character_debug_load(c.debug,&s)!=1||dh2_character_debug_get(&v,c.debug,name,&s)!=1){e="Genuine DebugSwitches failure";return false;}return true;}
struct Context{PlayerGearEffectsV5* gear;dh2::ui::ItemTextOwnerV5* text;TextEnvironment* environment;unsigned properties{},vitals{},skin{},presentation_real{},debug_real{};std::uintptr_t visual{};};
static bool effects(void* p,FreshInventoryOwnedV4&,const OwnedInventoryRequestV4& q,OwnedInventoryResponseV4& result,std::string& e){auto& c=*static_cast<Context*>(p);
 if(q.operation==OwnedInventoryOperationV4::update_gear_properties){++c.properties;return c.gear->update_properties(e);}if(q.operation==OwnedInventoryOperationV4::validate_hp_mp){++c.vitals;return c.gear->validate_hp_mp(e);}if(q.operation==OwnedInventoryOperationV4::skin){++c.skin;return c.gear->update_skin(&c.visual,{},e);}
 if(q.operation==OwnedInventoryOperationV4::update_name||q.operation==OwnedInventoryOperationV4::update_stats||q.operation==OwnedInventoryOperationV4::update_requirements){++c.presentation_real;auto t=c.text->services();if(!q.item){e="Missing actual owned item";return false;}if(q.operation==OwnedInventoryOperationV4::update_name)return item_update_name_v5(*q.item,t,e);if(q.operation==OwnedInventoryOperationV4::update_stats)return item_update_stats_v5(*q.item,t,e);return item_update_requirements_v5(*q.item,t,e);}
 if(q.operation==OwnedInventoryOperationV4::debug_load||q.operation==OwnedInventoryOperationV4::debug_query||q.operation==OwnedInventoryOperationV4::current_player){++c.debug_real;result={};if(q.operation==OwnedInventoryOperationV4::current_player){result.identity=0;return true;}dh2::character::DebugFileServices24 ds{c.environment,debug_open,debug_close};if(q.operation==OwnedInventoryOperationV4::debug_load)return dh2_character_debug_load(c.environment->debug,&ds)==1;unsigned v;if(dh2_character_debug_get(&v,c.environment->debug,q.name,&ds)!=1)return false;result.value=v;return true;}
 e="Unreconstructed required V5 effect in fixture";return false;
}
int main(int argc,char** argv){try{ck(argc==8);std::string e;auto cache=std::string(argv[2]);auto bytes=file(cache+"/loot_table_pyarray.bin"),names=file(cache+"/loot_table_pyarraynames.bin"),schema=file(cache+"/loot_table_pystructnames.bin");LootTablesV2 table;ck(table.load({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));cache=argv[3];bytes=file(cache+"/item_powers_pyarray.bin");names=file(cache+"/item_powers_pyarraynames.bin");schema=file(cache+"/item_powers_pystructnames.bin");ItemPowerTablesV5 powers;ck(powers.load({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));
 cache=argv[4];bytes=file(cache+"/character_properties_pyarray.bin");names=file(cache+"/character_properties_pyarraynames.bin");schema=file(cache+"/character_properties_pystructnames.bin");CharacterTable chars;ck(load_characters({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},chars,e));PropertyRules rules;ck(load_property_rules(chars,rules,e));
 cache=argv[5];bytes=file(cache+"/character_classes_pyarray.bin");names=file(cache+"/character_classes_pyarraynames.bin");schema=file(cache+"/character_classes_pystructnames.bin");ClassTables classes;ck(load_classes({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},classes,e));std::vector<ClassRow> rows;for(auto& x:classes.rows)rows.push_back({x.data(),std::uint32_t(x.size())});
 TextEnvironment env;env.assets=argv[6];env.private_files=argv[7];ck(env.constants&&env.debug);
 auto constants=file(env.assets+"/original-cache/data/pydata/common_text_pycst.bin");dh2_script_constants_reload receipt{};ck(!dh2_script_constants_load(env.constants,constants.data(),constants.size(),&receipt)&&receipt.consumed==constants.size());
 dh2::ui::HudTextV1 text_owner;auto text=file(env.assets+"/original-cache/data/pydata/common_text_pyarray.bin"),text_names=file(env.assets+"/original-cache/data/pydata/common_text_pyarraynames.bin"),text_schema=file(env.assets+"/original-cache/data/pydata/common_text_pystructnames.bin");ck(text_owner.load({text.data(),text.size()},{text_names.data(),text_names.size()},{text_schema.data(),text_schema.size()},e)&&text_owner.switch_pack(0,false,e));
 dh2::ui::LocalizationServices loc{&env,text_open,text_close,text_debug,text_constant,nullptr,nullptr};dh2::ui::HudTextEnvironmentV1 text_environment{loc};dh2::ui::ItemTextOwnerV5 text_adapter(table.borrow().items(),chars,text_owner,text_environment);
 auto gold=file(argv[1]);Reader r{gold};char magic[4];r.copy(magic,4);ck(!std::memcmp(magic,"GEV5",4));auto cases=r.u();unsigned steps=0,properties=0,vitals=0,skin=0,fixture=0;
 for(unsigned k=0;k<cases;++k){auto baseid=r.u(),selected=r.u(),count=r.u();auto state=std::make_shared<PropertyState>();reset_properties(rules,*state,&chars.rows.at(baseid));auto view=property_view(rules,*state);ck(dh2_class_recalc_base(rows.data(),rows.size(),state->base.data(),&view)==0);PropertyState initial;r.copy(&initial,sizeof initial);ck(!std::memcmp(state.get(),&initial,sizeof initial));LootRandom8V2 random{1,0};FreshInventoryOwnedV4 owner(0x100000001,table.borrow(),random,12,state);if(selected)owner.swap_equipment();PlayerGearEffectsV5 gear(owner,view,rows.data(),rows.size(),powers.borrow());Context context{&gear,&text_adapter,&env};OwnedInventoryServicesV4 services{&context,effects};
  for(unsigned i=0;i<count;++i){auto op=r.u(),a=r.u(),b=r.u(),c=r.u(),expected=r.u();(void)c;std::int32_t result=0;
   if(op==0)ck(owner.add_fixed_loot(std::int32_t(a),services,e));else if(op==2)ck(owner.character_auto_equip(a,result,services,e));else if(op==5)owner.swap_equipment();else if(op==4)ck(owner.unequip_from_slot(a,std::int32_t(b),services,e));else if(op==15)ck(gear.update_properties(e)&&gear.update_skin(&context.visual,{},e)&&gear.validate_hp_mp(e));else ck(false);
   ck(std::uint32_t(result)==expected);PropertyState after;r.copy(&after,sizeof after);if(std::memcmp(state.get(),&after,sizeof after)){auto* av=reinterpret_cast<const std::int32_t*>(state.get());auto* ev=reinterpret_cast<const std::int32_t*>(&after);for(unsigned j=0;j<896;++j)if(av[j]!=ev[j])std::cerr<<"case "<<k<<" step "<<i<<" op "<<op<<" sheet "<<j/224<<" property "<<j%224<<" actual "<<av[j]<<" expected "<<ev[j]<<"\n";}ck(!std::memcmp(state.get(),&after,sizeof after));++steps;
  }
  properties+=context.properties;vitals+=context.vitals;skin+=context.skin;fixture+=context.presentation_real;auto saved=*state;PropertyState other;auto mismatch=property_view(rules,other);PlayerGearEffectsV5 bad(owner,mismatch,rows.data(),rows.size(),powers.borrow());ck(!bad.update_properties(e)&&!std::memcmp(state.get(),&saved,sizeof saved));std::uintptr_t visual=0x100000010;ck(!gear.update_skin(&visual,{},e)&&!e.empty());ck(!gear.update_skin(nullptr,{},e));
 }
 ck(r.at==gold.size());unsigned real_power_text=0,source_null_descriptions=0;
 auto ps=text_adapter.services();ItemPresentationOwnerV5 power_text(powers.borrow());for(unsigned id=0;id<powers.borrow().rows().size();++id){ItemInstanceV1 item;item.id=664;bool ok=power_text.add_power(item,id,0,ps,e);if(ok){ck(item.powers.size()==1&&power_text.powers(item)->size()==1);++real_power_text;}else{if(powers.borrow().rows()[id].scalars.description==-1&&e=="Item text source localized null-pointer continuation unsupported"){++source_null_descriptions;ck(item.powers.size()==1);}else throw std::runtime_error("Actual power text ID "+std::to_string(id)+": "+e);}ck(power_text.forget(item,e));}
 ck(env.opened==env.closed);std::cout<<"{\"validation\":\"PASS\",\"actual_starter_classes\":3,\"original_owner_cases\":"<<cases<<",\"original_owner_steps\":"<<steps<<",\"native_property_effects\":"<<properties<<",\"native_vitals_effects\":"<<vitals<<",\"original_null_visual_skin_branches\":"<<skin<<",\"genuine_localized_item_text_deliveries\":"<<fixture<<",\"actual_power_localized_descriptions\":"<<real_power_text<<",\"source_null_power_descriptions_unsupported\":"<<source_null_descriptions<<",\"real_localization_file_opens\":"<<env.opened<<",\"real_private_missing_file_opens\":"<<env.debug_missing<<",\"checks\":"<<checks<<",\"mismatches\":0,\"actual_localization_files\":[";bool comma=false;for(const auto& path:env.opened_paths){if(comma)std::cout<<',';comma=true;std::cout<<std::quoted(path);}std::cout<<"]}\n";return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}

