#include "../animation_markers.hpp"
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <vector>
using namespace dh::foundation;
void check(bool ok,const std::string&e){if(!ok)throw std::runtime_error(e);}
bool same(const std::vector<MarkerOccurrence>&a,const std::vector<MarkerOccurrence>&b){if(a.size()!=b.size())return false;for(size_t i=0;i<a.size();++i)if(a[i].marker.index!=b[i].marker.index||a[i].cycle!=b[i].cycle||a[i].elapsed_ms!=b[i].elapsed_ms||a[i].generation!=b[i].generation)return false;return true;}
std::vector<std::uint8_t> read(const std::string&path){std::ifstream f(path,std::ios::binary);check(bool(f),"Missing "+path);return {std::istreambuf_iterator<char>(f),std::istreambuf_iterator<char>()};}
std::uint32_t word(const std::uint8_t*p){return p[0]|std::uint32_t(p[1])<<8|std::uint32_t(p[2])<<16|std::uint32_t(p[3])<<24;}
int main(int argc,char**argv){try{
 std::string e;std::int32_t times[]={100,150,200};const char*start[]={"start"};const char*middle[]={"hit","hit"};const char*end[]={"end"};dh2::animation::EventGroup groups[]={{1,start},{2,middle},{1,end}};dh2::animation::EventView view{4,3,reinterpret_cast<const std::uint8_t*>(times),groups};AnimationMarkers track;check(track.load(view,100,200,e),e);
 MarkerCursor cursor;check(AnimationMarkers::restart(cursor,e),e);std::vector<MarkerOccurrence> out;check(track.advance(cursor,0,true,out,e),e);check(out.size()==1&&out[0].marker.name=="start","initial start missing");check(track.advance(cursor,0,true,out,e)&&out.empty(),"zero advance repeated");check(track.advance(cursor,100,true,out,e),e);check(out.size()==4&&out[0].marker.name=="hit"&&out[1].marker.name=="hit"&&out[0].marker.group!=out[1].marker.group&&out[2].marker.name=="end"&&out[3].marker.name=="start","group/loop boundary order");
 MarkerCursor large,small;check(AnimationMarkers::restart(large,e)&&AnimationMarkers::restart(small,e),e);std::vector<MarkerOccurrence> all,parts;check(track.advance(large,350,true,all,e),e);for(auto step:{0,25,25,50,100,150}){check(track.advance(small,step,true,out,e),e);parts.insert(parts.end(),out.begin(),out.end());}check(same(all,parts),"partitioned advancement differs");
 auto restored=small;check(track.advance(restored,0,true,out,e)&&out.empty(),"restored cursor repeated");auto detached=all;check(AnimationMarkers::restart(large,e),e);check(same(detached,all),"restart mutated detached batch");check(track.advance(large,0,true,out,e)&&out.size()==1&&out[0].generation==2,"reentry generation");
 MarkerCursor shot;check(AnimationMarkers::restart(shot,e),e);check(track.advance(shot,500,false,out,e)&&out.size()==4&&shot.elapsed_ms==100,"one-shot clamp");check(track.advance(shot,1,false,out,e)&&out.empty(),"one-shot repeat");
 auto backup=shot;out=all;check(!track.advance(shot,UINT64_MAX,false,out,e)&&shot.elapsed_ms==backup.elapsed_ms&&same(out,all),"overflow atomicity");MarkerCursor many;out=all;check(!track.advance(many,100000000,true,out,e)&&!many.started&&same(out,all),"emission bound atomicity");check(!track.load(view,200,100,e)&&track.markers().size()==4,"failed load lost track");
 std::uint8_t frames[]={8};const char*name[]={"authored"};dh2::animation::EventGroup fg[]={{1,name}};dh2::animation::EventView fv{1,1,frames,fg};AnimationMarkers frame;check(frame.load(fv,0,1000,e),e);auto stamp=frame.markers()[0];check(stamp.authored_time_ms==266&&dh2_events_find(&fv,stamp.time_ms)==0&&dh2_events_find(&fv,stamp.time_ms-1)==-1,"original frame threshold mismatch");
 if(argc>1){for(const auto*file:{"prince_idle_shield.bdae","prince_walk_1hand.bdae","prince_1hand_combo_01.bdae","skeleton_attack_01.bdae","slime_attack_01.bdae"}){auto bytes=read(std::string(argv[1])+"/animations/"+file);dh2::resources::BresView bv{};check(dh2_bres_open(&bv,bytes.data(),bytes.size())==dh2::resources::BresError::ok,"BRES");const auto s=static_cast<std::int32_t>(word(bytes.data()+bv.root_offset+28)),n=static_cast<std::int32_t>(word(bytes.data()+bv.root_offset+32));AnimationMarkers real;check(real.load(bytes.data(),bytes.size(),s,n,e),file+std::string(": ")+e);MarkerCursor rc;check(AnimationMarkers::restart(rc,e)&&real.advance(rc,static_cast<std::uint64_t>(std::int64_t(n)-s),false,out,e),e);std::cout<<file<<" range "<<s<<".."<<n<<" markers "<<real.markers().size()<<'\n';for(const auto&m:real.markers())std::cout<<"  "<<m.name<<" authored="<<m.authored_time_ms<<" dispatch="<<m.time_ms<<" entry="<<m.entry<<" group="<<m.group<<'\n';}}
 std::cout<<"animation marker tests passed\n";
}catch(const std::exception&ex){std::cerr<<ex.what()<<'\n';return 1;}}
