#include "original_character.hpp"
#include "asset_catalog.hpp"
#include <cmath>
#include <iostream>
#include <limits>
#include <stdexcept>
using namespace dh::foundation;
void check(bool value,const std::string& error){if(!value)throw std::runtime_error(error);}
std::vector<Vec3> points(const CharacterVisual& visual){std::vector<Vec3> result;for(const auto& mesh:visual.meshes())for(const auto& v:mesh.vertices){check(std::isfinite(v.position.x)&&std::isfinite(v.position.y)&&std::isfinite(v.position.z),"nonfinite posed vertex");result.push_back(v.position);}return result;}
bool equal(const std::vector<Vec3>& a,const std::vector<Vec3>& b){check(a.size()==b.size(),"pose geometry domain changed");for(std::size_t i=0;i<a.size();++i)if(std::abs(a[i].x-b[i].x)+std::abs(a[i].y-b[i].y)+std::abs(a[i].z-b[i].z)>.001)return false;return true;}
int main(int argc,char**argv){try {
    check(argc==2,"original staged asset root required");AssetCatalog assets(argv[1]);CharacterVisualConfig config;config.model_path="models/prince_modular.bdae";config.template_clip_path="animations/prince_template_anim.bdae";config.clips={{"idle","animations/prince_idle_shield.bdae"},{"walk","animations/prince_walk_1hand.bdae"}};config.skin_id_contains="_default_warrior-mesh-skin";config.expected_controller_count=4;config.motion_node_id="auto";config.consume_root_motion=true;
    CharacterVisual visual,reference;std::string error;check(visual.load(assets,config,error),error);check(reference.load(assets,config,error),error);check(visual.update(.2,error),error);const auto before=points(visual);const auto clock=visual.animation_elapsed_seconds();const auto motion=visual.root_motion_delta();
    SkeletalPose idle,walk;check(visual.sample_local_pose("idle",0,idle,error),error);check(visual.sample_local_pose("walk",400,walk,error),error);check(equal(before,points(visual)),"independent sampling modified live geometry");check(visual.animation_elapsed_seconds()==clock&&visual.root_motion_delta().y==motion.y,"independent sample changed live clock/motion");
    check(reference.restart("walk",false,error),error);check(reference.update(.4,error),error);check(visual.apply_local_pose(walk,error),error);check(equal(points(reference),points(visual)),"published raw-local sample differs from actual sampled skinned pose");check(visual.animation_elapsed_seconds()==clock&&visual.root_motion_delta().y==motion.y,"publishing pose changed live motion clock");
    const auto published=points(visual);auto invalid=walk;invalid[0].id="wrong-source-node";check(!visual.apply_local_pose(invalid,error),"wrong node pose accepted");check(equal(published,points(visual)),"invalid pose changed rendered geometry");invalid=walk;invalid[0].translation[0]=std::numeric_limits<float>::infinity();check(!visual.apply_local_pose(invalid,error),"nonfinite pose accepted");check(equal(published,points(visual)),"nonfinite pose changed geometry");SkeletalPose preserved=walk;check(!visual.sample_local_pose("walk",900,preserved,error),"outside source range accepted");check(preserved.size()==walk.size()&&preserved[0].id==walk[0].id,"failed independent sample changed output");
    OriginalPoseBlend blender;check(blender.select(100,error),error);const auto outgoing=blender.current_slot();SkeletalPose mixed;auto sampler=[&](std::uint32_t slot,SkeletalPose& output,std::string&){output=slot==outgoing?idle:walk;return true;};check(blender.evaluate(0,sampler,mixed,error),error);check(visual.apply_local_pose(mixed,error),error);const auto startPose=points(visual);check(blender.select(50,error),error);check(blender.evaluate(50,sampler,mixed,error),error);check(visual.apply_local_pose(mixed,error),error);check(!equal(startPose,points(visual))&&!equal(published,points(visual)),"original half-fade did not publish intermediate skinned pose");check(blender.evaluate(100,sampler,mixed,error),error);check(visual.apply_local_pose(mixed,error),error);check(equal(published,points(visual)),"original fade endpoint differs from actual walk pose");
    check(visual.update(.1,error),error);check(std::abs(visual.root_motion_delta().y)<.001,"independent pose publication polluted live root history");
    std::cout<<"PASS original35-node independent samples, compensated skin publication, two-slot intermediate/final pose, clock/motion isolation, atomic failures\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 1;}}
