#include "../original_actor_navigation.hpp"
#include "../source_module_floors.hpp"
#include "../source_root_scopes.hpp"
#include "../source_world_objects.hpp"
#include "../actor_movement.hpp"
#include "../../level-world/move_state.hpp"
#include <iostream>
#include <stdexcept>
#include <cmath>
#include <iomanip>
using namespace dh::foundation;
void check(bool x,const std::string&e){if(!x)throw std::runtime_error(e);}
int main(int argc,char**argv){try{
 check(argc==2,"Actual original shared assets required");AssetCatalog assets(argv[1]);std::string error;auto lease=std::make_shared<int>(1);
 dh2::navigation::NavigationObject pf{};OriginalActorNavigationBindings early;early.actor_lease=lease;early.identity=99;early.object=&pf;OriginalActorNavigation fresh(early);check(fresh.construct_defaults(error),error);check(!pf.user&&pf.motion.floor==UINT32_MAX,"Source constructor-null PF fields differ");dh2::physical::NativeBody missing{};dh2::physical::CharacterBodyConfig config{};check(fresh.update_pf(99,missing,config,error)&&!pf.user,"Actual user0 source gate requires no floors/bounds/registry");check(!fresh.initialize_pf(error),"Unbound actual floor world accepted");
 const auto bytes=assets.read("original-cache/data/3d/modules/swamp/swamp.bdae");dh2::resources::BresView bres{};check(dh2_bres_open(&bres,bytes.data(),bytes.size())==dh2::resources::BresError::ok,"Actual module BRES rejected");dh2::scene::Scene scene;check(dh2::scene::load(bres,scene,error),error);
 unsigned selected=UINT32_MAX;for(unsigned i=0;i<scene.instances.size();++i)if(scene.graph.at(scene.instances[i].node_index).name.find("floor")!=std::string::npos){selected=i;break;}check(selected!=UINT32_MAX,"Original module source floor missing");
 auto floors=std::make_shared<dh2::floors::World>();OriginalSourceFloorBinding floor;floor.instance=selected;floor.room=0;floor.mesh_local_quaternion={0,0,0,1};floor.mesh_local_scale={1,1,1}; // Explicit unoptimized child-pose fixture, not a claim OptimizeStatic is identity.
 check(append_original_module_floors(bres,scene,{floor},*floors,error),error);check(dh2::floors::build_graph(*floors,error)&&dh2::floors::post_load(*floors,error),error);check(floors->records.size()==1&&floors->sewn,"Actual source floor graph/postload absent");
 std::array<float,3> point{};bool found=false;for(const auto&triangle:floors->records[0]->triangles){for(unsigned k=0;k<3;++k)point[k]=(triangle.points[0][k]+triangle.points[1][k]+triangle.points[2][k])/3.f;float height=point[2];if(dh2::floors::height(*floors,point.data(),height)){point[2]=height;found=true;break;}}check(found,"Actual authored selector could not find triangle fixture position");
 std::array<float,6> relative{-100,-50,-10,100,50,10},absolute{};for(unsigned k=0;k<6;++k)absolute[k]=relative[k]+point[k%3];dh2::navigation::NavigationObject object{};std::array<dh2::navigation::ObstacleEntry,8> entries{};std::array<unsigned,8> floor_keys{};dh2::navigation::ObstacleRegistry registry{entries.data(),0,8,floor_keys.data(),0,8};
 OriginalActorNavigationBindings b;b.actor_lease=lease;b.world_lease=floors;b.identity=100;b.position160=point.data();b.relative144=relative.data();b.absolute12c=absolute.data();b.object=&object;b.obstacles=&registry;b.floors=floors.get();b.static84=[](std::uint8_t&out,std::string&){out=0;return true;};OriginalActorNavigation navigation(b);check(navigation.construct_defaults(error)&&navigation.initialize_pf(error),error);check(object.user==100&&object.radius==200&&object.motion.floor!=UINT32_MAX,"Actual InitObject source fullmax extent or floor differs");
 check(navigation.update_pf(100,missing,config,error)&&object.radius==100&&registry.count==0,"No native body source halfmax radius/disabled obstacle differs");
 auto physical_world=std::make_shared<dh2::physical::NativeWorld>();const float limits[]{-1000,-1000,1000,1000};physical_world->load(limits);dh2::physical::NativeBody actual{};dh2::physical::CharacterBodyInput input{};input.owner=reinterpret_cast<void*>(100);input.new_physical=&actual;input.character_type=4;input.absolute_bounds[0]=-60;input.absolute_bounds[1]=-60;input.absolute_bounds[2]=60;input.absolute_bounds[3]=60;check(dh2_character_body_config(&config,&input)==0,"Original body definition fixture failed");dh2::physical::WorldObject owner{};actual={physical_world->create_character(config,&owner),config.radius,config.pinned};check(actual.body,"Actual native fixture body absent");
 check(navigation.physical_callback()(100,actual,config,error),error);check(std::abs(object.radius-60)<.0001f&&registry.count==1&&entries[0].object==100&&entries[0].floor==object.motion.floor,"Native source radius/actual floor obstacle registry differs");check(object.obstacle_weight==50&&object.obstacle_extent==20,"Original Character obstacle traits differ");
 Vec3 admitted{};bool allowed=false;const Vec3 current{point[0],point[1],point[2]};check(navigation.validate_direction(current,{0,0,0},admitted,allowed,error),error);std::uint32_t directAllowed=0;float directZero[3]{};const dh2::navigation::DirectionRequest directRequest{&floors->collision_world,point.data(),object.radius,object.motion.flags,0};check(dh2_nav_validate_direction(&directAllowed,directZero,&directRequest)==0,"Original zero-vector probe failed");check(allowed==bool(directAllowed)&&admitted.x==directZero[0]&&admitted.y==directZero[1]&&admitted.z==directZero[2],"Zero-vector source direction seam differs");std::cout<<"SourceZeroDirection allowed="<<allowed<<" delta="<<admitted.x<<","<<admitted.y<<","<<admitted.z<<'\n';
 OriginalActorNavigationMoveResult admission;check(navigation.validate_position(current,admission,error),error);std::cout<<"PositionKind="<<admission.kind<<" valid="<<admission.position_valid<<" grounded="<<admission.grounded<<"\n";check(admission.position_valid&&admission.grounded,"Actual source position admission differs");auto previous=object;auto saved=admission;floors->source_motion_policy_v95.maximum_height_delta=-1;check(!navigation.validate_position(current,admission,error)&&object.motion.position[0]==previous.motion.position[0]&&admission.kind==saved.kind,"Invalid SAME floor motion policy mutated PF/output");floors->source_motion_policy_v95.maximum_height_delta=100;
 auto lateRegistry=std::make_shared<dh2::navigation::ObstacleRegistry>();std::array<dh2::navigation::ObstacleEntry,8> lateEntries{};std::array<unsigned,8> lateFloorKeys{};*lateRegistry={lateEntries.data(),0,8,lateFloorKeys.data(),0,8};dh2::navigation::NavigationObject lateObject{};OriginalActorNavigationBindings late;late.actor_lease=lease;late.world_lease=physical_world;late.identity=101;late.position160=point.data();late.object=&lateObject;late.static84=b.static84;OriginalActorNavigation lateNavigation(late);check(lateNavigation.construct_defaults(error),error);const auto* sameObject=&lateObject;check(lateNavigation.attach_world({floors,lateRegistry,floors.get(),lateRegistry.get()},relative.data(),absolute.data(),error)&&lateNavigation.initialize_pf(error),error);check(&lateObject==sameObject&&lateObject.user==101&&lateObject.radius==200,"Late world binding reset/copied source PFObject or InitObject extent");check(lateNavigation.update_pf(101,actual,config,error)&&lateRegistry->count==1&&std::abs(lateObject.radius-60)<.0001f,"Late native-radius producer differs");
 check(navigation.validate_position({current.x,current.y,current.z+200},admission,error),error);check(admission.kind==3&&admission.position_valid&&admission.grounded&&admission.position.z==object.motion.position[2],"Source height-limit clamp differs from true admission");floors->source_motion_policy_v95.ignore_height_delta=1;check(navigation.validate_position({current.x,current.y,current.z+200},admission,error),error);check(admission.kind==2&&admission.position_valid&&admission.grounded,"Actual SAME world height-override policy not used");floors->source_motion_policy_v95.ignore_height_delta=0;
 physical_world->destroy(actual.body);check(navigation.update_pf(100,actual,config,error)&&registry.count==0&&object.radius==100,"Native detach obstacle removal/source halfmax differs");
 std::vector<ActorDefinition> definitions;check(load_actor_definitions(assets,"original-cache/data/scene/001_swamp.mlx",definitions,error),error);SourceWorldObjects sourceObjects;SourceRootScopes scopes;check(sourceObjects.load(definitions,error)&&scopes.load(assets,"original-cache/data/scene/001_swamp.mlx",definitions,error)&&scopes.bind(sourceObjects,error),error);auto completeWorld=std::make_shared<dh2::floors::World>();SourceModuleFloors modules(completeWorld);for(const auto& trace:scopes.modules().entries()){SourceModuleFloorRequest request;request.trace=trace;request.pose_phase=SourceModulePosePhase::constructor_degrees;request.admitted=true;for(const auto& record:scopes.module_records())if(record->receiver->base().identity()==trace.receiver.identity)request.record=record;std::shared_ptr<SourceModuleFloorRoom> completeRoom;check(modules.load(assets,request,completeRoom,error),error);}check(modules.post_load(error)&&modules.rooms().size()==9&&completeWorld->records.size()==16,"Actual root floor world differs from source module receipt");
 const float startPoint[]{1090.75f,-212.202f,258};dh2::navigation::NavigationObject sourcePF{};check(!dh2_nav_object_defaults(&sourcePF),"Source PF defaults failed");dh2::navigation::ObjectInitRequest initial{&completeWorld->collision_world,&sourcePF,41816,{startPoint[0],startPoint[1],startPoint[2]},200,0,0};check(!dh2_nav_init_object(&initial),"Actual source opening PF init failed");const float sourcePrevious[]{1138.32f,-199.164f,255};std::copy_n(sourcePrevious,3,sourcePF.motion.position);const float candidate[]{1141.5f,-199.164f,255};dh2::navigation::HeightHit cached{};cached.height=candidate[2];std::copy_n(sourcePF.motion.normal,3,cached.normal);const int cachedFound=dh2_nav_floor_height(&cached,completeWorld->collision_world.floors[sourcePF.motion.floor].selector,candidate);dh2::navigation::HeightHit worldwide{};worldwide.height=candidate[2];const int worldFound=dh2_nav_world_height(&worldwide,&completeWorld->collision_world,candidate,0);float validated[]{candidate[0],candidate[1],candidate[2]};dh2::navigation::PositionResult sourceResult{};check(!dh2_nav_validate_position(&sourceResult,&completeWorld->collision_world,&sourcePF.motion,validated,&completeWorld->source_motion_policy_v95),"Concrete actual root-world position probe failed");std::cout<<"Actual9Room16FloorCandidate="<<candidate[0]<<","<<candidate[1]<<","<<candidate[2]<<" cachedFloor="<<sourceResult.old_floor<<" cachedFound="<<cachedFound<<" cachedHeight="<<cached.height<<" worldFound="<<worldFound<<" worldFloor="<<worldwide.floor<<" worldHeight="<<worldwide.height<<" floorType="<<completeWorld->collision_world.floors[sourceResult.old_floor].traits.type<<" capability="<<sourcePF.motion.flags<<" maxHeightDelta="<<completeWorld->source_motion_policy_v95.maximum_height_delta<<" ignoreHeight="<<completeWorld->source_motion_policy_v95.ignore_height_delta<<" resultValid="<<sourceResult.valid<<" kind="<<sourceResult.kind<<" output="<<validated[0]<<","<<validated[1]<<","<<validated[2]<<'\n';
 check(cachedFound==1&&worldFound==1&&std::fabs(cached.height-255)<.001f&&sourceResult.kind==2&&sourceResult.valid==1&&validated[0]==candidate[0],"Concrete source positive candidate evidence differs");
 bool gridClamp=false;for(float x=1138;x<=1350&&!gridClamp;x+=4)for(float y=-230;y<=-150&&!gridClamp;y+=4){float requested[]{x,y,255};auto cache=sourcePF.motion;dh2::navigation::PositionResult result{};check(!dh2_nav_validate_position(&result,&completeWorld->collision_world,&cache,requested,&completeWorld->source_motion_policy_v95),"Actual source neighborhood admission failed");if(result.kind==3&&result.valid){const float point[]{x,y,255};dh2::navigation::HeightHit hit{};hit.height=255;const int found=dh2_nav_floor_height(&hit,completeWorld->collision_world.floors[result.old_floor].selector,point);std::cout<<"ActualNeighborhoodHeightClamp="<<x<<","<<y<<",255 cachedFound="<<found<<" height="<<hit.height<<" type="<<completeWorld->collision_world.floors[result.old_floor].traits.type<<" valid="<<result.valid<<" kind="<<result.kind<<"\n";gridClamp=true;}}
 std::cout<<std::setprecision(9);for(float z:{255.f,255.000061f}) {const float liveCandidate[]{1140.5708f,-196.916412f,z};dh2::navigation::HeightHit cacheHit{},worldHit{};cacheHit.height=worldHit.height=z;const auto cacheStatus=dh2_nav_floor_height(&cacheHit,completeWorld->collision_world.floors[0].selector,liveCandidate);const auto worldStatus=dh2_nav_world_height(&worldHit,&completeWorld->collision_world,liveCandidate,0);float nearest=z;const bool nearestHit=dh2::floors::height(*completeWorld,liveCandidate,nearest);const auto& record=*completeWorld->records[0];dh2::collision::Floor allTriangles{};allTriangles.triangles=record.triangles.data();allTriangles.count=static_cast<unsigned>(record.triangles.size());std::copy_n(record.bounds.minimum,3,allTriangles.minimum);std::copy_n(record.bounds.maximum,3,allTriangles.maximum);dh2::collision::Result raw{};const int rawHit=dh2_collision_floor(&raw,&allTriangles,liveCandidate);unsigned xyInside=0;for(const auto& triangle:record.triangles){const auto& a=triangle.points[0];const auto& b=triangle.points[1];const auto& c=triangle.points[2];const double area=(double(b[0])-a[0])*(double(c[1])-a[1])-(double(b[1])-a[1])*(double(c[0])-a[0]);if(area==0)continue;const double px=liveCandidate[0],py=liveCandidate[1];const auto side=[&](const float* u,const float* v){return (double(v[0])-u[0])*(py-u[1])-(double(v[1])-u[1])*(px-u[0]);};const double s0=side(a,b),s1=side(b,c),s2=side(c,a);if((s0>=0&&s1>=0&&s2>=0)||(s0<=0&&s1<=0&&s2<=0))++xyInside;}std::cout<<"ActualLiveClampXY="<<liveCandidate[0]<<","<<liveCandidate[1]<<" z="<<z<<" cached="<<cacheStatus<<" world="<<worldStatus<<" nearest="<<nearestHit<<" rawTriangles="<<rawHit<<" doubleXYInside="<<xyInside<<" sourceFloorBoundsZ="<<record.bounds.minimum[2]<<".."<<record.bounds.maximum[2]<<"\n";check(cacheStatus==0&&worldStatus==0&&!nearestHit&&rawHit==0&&xyInside==0,"Exact observed clamp point no longer a genuine source XY geometry miss");}
 const float liveCurrent[]{1137.43018f,-200.057037f,255.000061f};float heading[]{3.140625f,3.140625f,0};const float originalHeadingLength=std::hypot(heading[0],heading[1]);std::uint32_t headingValid=0;const dh2::navigation::DirectionRequest headingRequest{&completeWorld->collision_world,liveCurrent,sourcePF.radius,sourcePF.motion.flags,0};check(!dh2_nav_validate_direction(&headingValid,heading,&headingRequest),"Actual source heading boundary probe malformed");std::cout<<"ActualSeparateHeading diagnostic="<<headingValid<<" output="<<heading[0]<<","<<heading[1]<<","<<heading[2]<<" magnitude="<<std::hypot(heading[0],heading[1])<<"\n";check(std::fabs(std::hypot(heading[0],heading[1])-originalHeadingLength)<.001f,"Source heading slide did not preserve supplied magnitude");
 std::array<float,3> manualPosition{liveCurrent[0],liveCurrent[1],liveCurrent[2]};dh2::navigation::NavigationObject manualPF{};OriginalActorNavigationBindings manualFields;manualFields.actor_lease=lease;manualFields.world_lease=completeWorld;manualFields.identity=41816;manualFields.position160=manualPosition.data();manualFields.object=&manualPF;manualFields.static84=b.static84;OriginalActorNavigation manualNavigation(manualFields);check(manualNavigation.construct_defaults(error)&&manualNavigation.attach_world({completeWorld,lateRegistry,completeWorld.get(),lateRegistry.get()},relative.data(),absolute.data(),error)&&manualNavigation.initialize_pf(error),error);
 ActorMovementConfig motorConfig;motorConfig.bodyRadius=(relative[3]-relative[0])*.5f;motorConfig.bodyHeight=relative[5]-relative[2];auto motor=std::make_shared<ActorMovement>(motorConfig);motor->setPosition({manualPosition[0],manualPosition[1],manualPosition[2]});check(motor->setDesiredHeading({1,1,0}),"Actual manual motor heading setup rejected");std::uint32_t sourceFlags=0,movementType=0;check(!dh2_move_focus_begin(&sourceFlags,&movementType),"Original Move OnFocus source fields failed");unsigned reads=0,publishes=0,debugCalls=0;OriginalManualHeadingBindings manual;manual.controller_lease=motor;manual.read_heading=[&](auto& out,auto&){++reads;const auto& h=motor->state().desiredHeading;out={{h.direction.x,h.direction.y,h.direction.z},h.sourceAngleRadians,unsigned(h.active),0};return true;};manual.publish_heading=[&](const auto& h,auto&){++publishes;return motor->setDesiredHeading({h.direction[0],h.direction[1],h.direction[2]});};manual.source_policy=[&](auto& flags,auto& boundary,auto&){flags=sourceFlags;boundary=1;return true;};manual.skip_boundary=[&](auto& skip,auto&){++debugCalls;skip=0;return true;};OriginalManualHeadingResult manualResult;check(manualNavigation.update_manual_heading(manual,manualResult,error),error);check(manualResult.path_policy_enabled&&manualResult.boundary_checked&&manualResult.direction_valid==1&&publishes==1&&debugCalls==1&&motor->state().desiredHeading.direction.x>.999f&&std::fabs(motor->state().desiredHeading.direction.y)<.001f,"Source manual heading edge-slide was not published to SAME motor");
 sourceFlags=0;manualPosition[0]+=1;const auto oldReads=reads,oldPublishes=publishes;check(manualNavigation.update_manual_heading(manual,manualResult,error),error);check(!manualResult.path_policy_enabled&&reads==oldReads&&publishes==oldPublishes&&manualPF.motion.position[0]==manualPosition[0],"Source policyoff did not copy PF first or wrongly touched heading");check(!dh2_move_focus_begin(&sourceFlags,&movementType),"Source Move focus reset failed");manualPosition={1140.5708f,-196.916412f,255};check(motor->setDesiredHeading({1,1,0}),"Diagnostic-zero heading fixture rejected");check(manualNavigation.update_manual_heading(manual,manualResult,error),error);check(manualResult.boundary_checked&&manualResult.direction_valid==0&&publishes==oldPublishes+1&&motor->state().desiredHeading.active,"False source direction diagnostic incorrectly vetoed heading publication");manual.skip_boundary={};const auto preservedHeading=motor->state().desiredHeading;check(!manualNavigation.update_manual_heading(manual,manualResult,error)&&motor->state().desiredHeading.direction.x==preservedHeading.direction.x,"Unbound reached boundary Debug silently succeeded/changed heading");
 manualPosition={liveCurrent[0],liveCurrent[1],liveCurrent[2]};dh2::navigation::PathController controller{};controller.destination[0]=manualPosition[0]+200;controller.destination[1]=manualPosition[1]+200;controller.destination[2]=manualPosition[2];controller.validate_boundary=1;dh2::navigation::PathObject sourcePath{};dh2::navigation::ControllerWorkspace workspace{};OriginalActorPathBindings full;full.controller_lease=lease;full.controller=&controller;full.path=&sourcePath;full.workspace=&workspace;full.source_policy=[&](auto& out,auto&){dh2::move::Policy projected{};check(!dh2_move_policy(&projected,&sourceFlags),"Source flags projection failed");out={projected.update_path,0,0,projected.position_from_physics};return true;};full.skip_boundary=[](auto& skip,auto&){skip=0;return true;};full.publish=[&](auto&){return motor->setDesiredHeading({controller.heading.direction[0],controller.heading.direction[1],controller.heading.direction[2]});};dh2::navigation::ControllerResult pathResult{};check(manualNavigation.update_path(full,pathResult,error),error);check(controller.path_requested==1&&pathResult.boundary_checked&&controller.heading.direction[0]>.999f&&controller.position[0]==manualPosition[0]&&manualPF.motion.position[0]==manualPosition[0],"Borrowed actual UpdatePath source coordinator order/heading differs");
 std::cout<<"PASS sourceUser0EarlyReturn=true actualFloorBRES=true fullInit200_halfUpdate100_nativeUpdate60=true actualObstacleRegistry=true borrowedManualHeading=true sourceUpdatePath=true unoptimizedPoseFixture=true noFullMovementFrameClaim=true\n";
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}

