#include "original_attack_sequence.hpp"
#include <iostream>
#include <cmath>
#include <stdexcept>
using namespace dh::foundation;
void check(bool value,const std::string& error){if(!value)throw std::runtime_error(error);}
AnimationMarkers marker_track(int start,int end,const std::vector<std::pair<int,std::string>>& markers){std::vector<std::uint8_t> times(markers.size()*4);std::vector<const char*> names(markers.size());std::vector<dh2::animation::EventGroup> groups(markers.size());for(std::size_t i=0;i<markers.size();++i){const auto value=static_cast<unsigned>(markers[i].first);for(unsigned b=0;b<4;++b)times[i*4+b]=std::uint8_t(value>>(b*8));names[i]=markers[i].second.c_str();groups[i]={1,&names[i]};}AnimationMarkers result;std::string error;check(result.load({4,static_cast<unsigned>(markers.size()),times.data(),groups.data()},start,end,error),error);return result;}
int main(int argc,char**argv){try {
    std::string error;OriginalCombatVisualPlan plan;OriginalCombatSequencePlan sequence;sequence.state="fixture-action";sequence.id=1;sequence.type=2;
    for(unsigned group=0;group<2;++group)for(unsigned phase=0;phase<3;++phase){OriginalCombatPhase p;p.sourcePath={group,phase};p.ancestors={{static_cast<int>(group),2,1,99,100,1,{}}};p.clipName="g"+std::to_string(group)+"p"+std::to_string(phase);p.speed=phase==0?2:phase==1?.5:1.5;p.redirect=0;p.blendOut=100;sequence.phases.push_back(p);}plan.sequences.push_back(sequence);OriginalSequencePolicies policies{{2,{2,1,0,"fixture-group"}}};
    std::map<std::string,AnimationMarkers> tracks;for(const auto& phase:sequence.phases)tracks.emplace(phase.clipName,marker_track(100,200,{{100,"begin"},{150,"middle"},{200,"end"}}));
    std::string current;double sourceElapsed=0;std::vector<std::string> entered;
    CombatVisualBinding base{[&](const std::string& name,bool,std::string&){current=name;sourceElapsed=0;return true;},[&](const std::string& name,int& start,int& end,std::string&){start=tracks.at(name).start_ms();end=tracks.at(name).end_ms();return true;},[&](const std::string& name,std::string&)->const AnimationMarkers*{return &tracks.at(name);},[&](double seconds,std::string&){sourceElapsed+=seconds;return true;}};
    OriginalAttackSequenceServices services{base,[&](const std::string& name,std::string&){current=name;sourceElapsed=0;entered.push_back(name);return true;}};
    OriginalAttackSelection selection;selection.state="fixture-action";selection.choices[{}]=1;OriginalAttackSequence playback;check(playback.prepare(plan,policies,selection,services,"virtual-action",error),error);check(playback.phases().size()==3,"both random groups played");check(playback.phases()[0].source.sourcePath[0]==1,"wrong explicit group");check(std::abs(playback.phases()[0].rate-2)<1e-6,"redirect ancestor speed incorrectly compounded");check(std::abs(playback.phases()[0].wall_duration_seconds-.05)<1e-9,"blend shortened clip");
    auto binding=playback.binding();int start=0,end=0;check(binding.range("virtual-action",start,end,error),error);check(start==0&&end==317,"variable rate total differs");check(binding.select("virtual-action",false,error),error);check(binding.update(.1,error),error);check(entered==std::vector<std::string>{"g1p0","g1p1"},"subframe phase entry order differs");check(std::abs(sourceElapsed-.025)<1e-9,"incoming phase did not receive wall remainder at its rate");check(binding.update(.3,error),error);check(playback.finished()&&entered.size()==3,"recovery did not complete");check(binding.select("virtual-action",false,error),error);check(entered.size()==4&&sourceElapsed==0,"repeated action did not restart first clip");
    auto bad=selection;bad.choices.clear();check(!playback.prepare(plan,policies,bad,services,"bad",error),"random group was guessed");check(playback.phases().size()==3,"failed prepare changed active program");auto badPolicies=policies;badPolicies[2].loop=-1;check(!playback.prepare(plan,badPolicies,selection,services,"bad",error),"infinite loop accepted");check(!playback.prepare(plan,{},selection,services,"bad",error),"missing redirect policy guessed");
    // Restart clears a clip's pending delta. Every phase must deliver its motion
    // before that restart, including phases whose authored MoveGO is disabled.
    auto motionPlan=plan;motionPlan.sequences[0].phases[4].moveGO=1;
    double pendingMotion=0,deliveredMotion=0,enabledMotion=0;unsigned deliveries=0;
    auto motionServices=services;
    motionServices.visual.update=[&](double seconds,std::string&){pendingMotion=seconds;return true;};
    motionServices.restart_clip=[&](const std::string&,std::string&){pendingMotion=0;return true;};
    motionServices.take_motion=[&](){const auto delta=pendingMotion;pendingMotion=0;return Vec3{static_cast<float>(delta),0,0};};
    motionServices.apply_motion=[&](Vec3 delta,bool enabled,std::string&){++deliveries;deliveredMotion+=delta.x;if(enabled)enabledMotion+=delta.x;return true;};
    OriginalAttackSequence motionPlayback;check(motionPlayback.prepare(motionPlan,policies,selection,motionServices,"motion-action",error),error);
    check(motionPlayback.begin(error)&&motionPlayback.advance(10,error),error);
    check(deliveries==3&&std::abs(deliveredMotion-.3)<1e-6&&std::abs(enabledMotion-.1)<1e-6,"phase restart lost motion or MoveGO policy");
    auto unpaired=motionServices;unpaired.apply_motion={};check(!motionPlayback.prepare(motionPlan,policies,selection,unpaired,"bad-motion",error),"unpaired motion services accepted");
    motionServices.apply_motion=[](Vec3,bool,std::string& e){e="collision host failed";return false;};
    check(motionPlayback.prepare(motionPlan,policies,selection,motionServices,"motion-action",error)&&motionPlayback.begin(error),error);
    check(!motionPlayback.advance(.01,error)&&error=="collision host failed","motion host failure silently ignored");
    MarkerCursor cursor;check(AnimationMarkers::restart(cursor,error),error);std::vector<MarkerOccurrence> occurrences;const auto* aggregate=binding.markers("virtual-action",error);check(aggregate&&aggregate->advance(cursor,317,false,occurrences,error),error);check(occurrences.size()==9,"authored repeated phase markers dropped");check(occurrences[2].marker.name=="end"&&occurrences[3].marker.name=="begin"&&occurrences[2].elapsed_ms==occurrences[3].elapsed_ms,"phase boundary marker order differs");
    if(argc==2) {
        const auto root=std::filesystem::path(argv[1]);AssetCatalog metadata(root/".local-inputs/windows-melee-bindings"),assets(root/".local-inputs/windows-shared-assets");OriginalMeleeBindings original;check(original.load(metadata,"original-melee-bindings.xml",error),error);OriginalSequencePolicies originalPolicies;check(original_sequence_policies(original,originalPolicies,error),error);ActorCustomization customization;customization.skin_id_contains="_default_warrior-mesh-skin";customization.expected_controller_count=4;customization.allow_missing_animation_targets=true;OriginalCombatVisualPlan actual;check(build_original_combat_visual_plan(assets,original,"KnightPlayerBase",customization,"actual-role",actual,error),error);
        const auto* attack=actual.sequence("Attack",0);check(attack,"original attack missing");auto visualConfig=actual.config;visualConfig.clips.clear();for(const auto& phase:attack->phases)if(phase.sourcePath.size()==2&&phase.sourcePath[0]==0)visualConfig.clips.emplace_back(phase.clipName,phase.resolvedPath);CharacterVisual visual;check(visual.load(assets,visualConfig,error),error);
        std::string actualCurrent;auto actualBase=combat_visual_binding(visual);OriginalAttackSequenceServices actualServices{actualBase,[&](const std::string& name,std::string& e){actualCurrent=name;return visual.restart(name,false,e);}};OriginalAttackSelection actualSelection;actualSelection.state="Attack";actualSelection.group_path={0};OriginalAttackSequence actualPlayback;check(actualPlayback.prepare(actual,originalPolicies,actualSelection,actualServices,"actual-action",error),error);check(actualPlayback.phases().size()==3,"original selected group is not pre/strike/recovery");check(actualPlayback.begin(error),error);
        const auto hit=std::find_if(actualPlayback.scheduled_markers().begin(),actualPlayback.scheduled_markers().end(),[&](const auto& m){return m.phase==1&&m.source.name=="attack_mainhand"&&m.wall_seconds<actualPlayback.phases()[1].wall_start_seconds+actualPlayback.phases()[1].wall_duration_seconds;});check(hit!=actualPlayback.scheduled_markers().end(),"original strike markers absent");check(actualPlayback.advance(hit->virtual_ms/1000.0,error),error);check(actualCurrent==actualPlayback.phases()[1].source.clipName,"marker preceded actual strike pose");const auto sourceOffset=(hit->source.time_ms-actualPlayback.phases()[1].start_ms)/1000.0;check(visual.animation_elapsed_seconds()+.001>=sourceOffset,"visual source clock trails authored marker");check(actualPlayback.advance(10,error),error);check(actualPlayback.finished(),"original recovery did not finish");
        std::cout<<"original phases="<<actualPlayback.phases().size()<<" strikeMarkerWall="<<hit->wall_seconds<<" virtualMs="<<hit->virtual_ms<<"\n";
    }
    std::cout<<"PASS explicit group, source rates, authored marker chronology, subframe transitions, repeated action, unsupported-policy rejection\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 1;}}

