#include "playable_actor_bodies.hpp"
#include "original_actor_properties.hpp"
#include "playable_actor_world.hpp"
#include <cstring>
#include <iostream>
#include <stdexcept>
using namespace dh::foundation;
void check(bool value,const std::string& error){if(!value)throw std::runtime_error(error);}
struct Fields { ActorState actor; std::array<float,3> destination{};std::uintptr_t attached=0,visual=0; };
struct ContactDelivery {
 std::vector<dh2::character::AIEventRequest40> calls;
 static std::int32_t invoke(void* p,dh2::character::AIEventState64*,const dh2::character::AIEventRequest40* request,std::uint32_t*) {static_cast<ContactDelivery*>(p)->calls.push_back(*request);return 0;}
};
struct SourceObstacles {std::array<dh2::navigation::ObstacleEntry,8> entries{};std::array<unsigned,8> floors{};dh2::navigation::ObstacleRegistry registry{entries.data(),0,8,floors.data(),0,8};};
int main(int argc,char**argv){try{
 check(argc==2,"Original shared assets root required");AssetCatalog assets(argv[1]);std::string error;auto database=std::make_shared<OriginalPropertyDatabase>();check(load_original_property_tables(assets,"original-cache/data/pydata/",*database,error),error);auto ai=std::make_shared<dh2::data::AiTables>();check(load_original_ai_tables(assets,"original-cache/data/pydata/",*ai,error),error);
 auto world=std::make_shared<dh2::physical::NativeWorld>();const float bounds[]{-1000,-1000,1000,1000};world->load(bounds);PlayableActorBodies pool;
 std::vector<std::shared_ptr<Fields>> actors;std::vector<std::shared_ptr<OriginalCombatProperties>> properties;std::vector<OriginalActorBodyPlan> cachedPlans;unsigned filterReached=0,contactReached=0;
 for(const std::string row:{"KnightPlayerBase","Swamp_LizadMan_Type1"}) {
  auto fields=std::make_shared<Fields>();fields->actor.id=100+actors.size();fields->actor.transform.position={1090.75f,-212.202f,258};fields->actor.health=17;fields->actor.target_id=987;fields->actor.action=CharacterAction::attacking;
  OriginalActorProperties resolved;check(resolve_original_actor_properties(database->characters,database->classes,row,{256,true},resolved,error),error);auto data=std::make_shared<OriginalCombatProperties>();data->sheets=std::move(resolved.sheets);const auto sourceSheets=data->sheets;
  OriginalActorBodyPlanInput q;q.properties=&data->sheets;q.ai=ai.get();q.owner_identity=fields->actor.id;q.position={fields->actor.transform.position[0],fields->actor.transform.position[1],fields->actor.transform.position[2]};q.source_name=row;q.visual.model_path=row=="KnightPlayerBase"?"models/prince_modular.bdae":"original-cache/data/3d/characters/lizardman/lizardman.bdae";q.visual.use_authored_modular_defaults=true;OriginalActorBodyPlan plan;check(make_original_actor_body_plan(assets,q,plan,error),error);
  OriginalActorPhysicalBindings b;b.actor_lease=fields;b.world_lease=world;b.data_lease=data;b.world=world.get();b.ai=ai.get();b.destination1a8=fields->destination.data();b.attached2e0=&fields->attached;b.visual2d8=&fields->visual;
  b.static84=[](auto& out,auto&){out=0;return true;};b.is_player=[row](auto type,auto& out,auto&){out=original_actor_source_is_player(type,row);return true;};b.debug_switch=[](const char*,bool& out,std::string&){out=false;return true;};
  b.contact=[&](auto,void*,unsigned,auto& e){++contactReached;e="Gameplay contact provider deliberately unbound in this fixture";return false;};
  check(!pool.bind(fields->actor,*data,plan,b,error)&&pool.size()==actors.size(),"Missing collision filter silently accepted or published partial body");
  b.filter=[&](void*,const auto&,const auto&,bool&,auto& e){++filterReached;e="Gameplay filter deliberately unbound in this fixture";return false;};
  check(pool.bind(fields->actor,*data,plan,b,error),error);check(pool.navigation(fields->actor.id)&&pool.navigation(fields->actor.id)->user==0,"Real fresh PFObject user0 callback replaced by fixture success");check(pool.physical(fields->actor.id)->native().body,"Actual native body pool entry absent");
  OriginalTriggerActorBorrow actor;check(pool.actor_borrow(fields->actor.id,actor,error),error);check(actor.position160==fields->actor.transform.position.data(),"Actor position authority copied");OriginalTriggerPhysicalBorrow physical;check(pool.physical_borrow(*actor.physical2dc,physical,error),error);check(physical.native==&pool.physical(fields->actor.id)->native(),"Body query returned different physical receiver");
  OriginalActorSubobjectsBorrow motion;check(pool.subobjects_borrow(fields->actor.id,motion,error),error);
  check(motion.position160==fields->actor.transform.position.data()&&motion.destination1a8==fields->destination.data()
    &&motion.physical2dc==actor.physical2dc&&motion.native==physical.native
    &&motion.absolute12c==actor.absolute12c&&motion.attached2e0==&fields->attached&&motion.visual2d8==&fields->visual,
    "Subobjects borrow manufactured another actor/body/slot authority");
  auto sameNative=motion.native;check(pool.remove_physical(fields->actor.id,error),error);
  check(pool.subobjects_borrow(fields->actor.id,motion,error)&&!motion.native&&!*motion.physical2dc,"Removed source physical slot borrowed a present native body");
  check(pool.initialize_physical(fields->actor.id,error)&&pool.subobjects_borrow(fields->actor.id,motion,error)&&motion.native==sameNative,"Physical reinitialization replaced the owned native receiver");
  const auto hp=fields->actor.health;const auto target=fields->actor.target_id;const auto action=fields->actor.action;check(pool.set_position(fields->actor.id,{250,375,500},true,error),error);check(fields->actor.transform.position==std::array<float,3>{250,375,500}&&fields->destination==fields->actor.transform.position,"Source current/destination not same actor fields");check(fields->actor.health==hp&&fields->actor.target_id==target&&fields->actor.action==action&&!std::memcmp(&sourceSheets,&data->sheets,sizeof(sourceSheets)),"Body bridge changed gameplay/property authority");
  if(actors.empty()){check(pool.set_pinned(fields->actor.id,false,error),error);check(physical.native->pinned==0&&physical.native->body->GetMass()>0,"Original source Unpin did not restore shape mass");check(pool.set_pinned(fields->actor.id,true,error),error);check(physical.native->pinned==1&&physical.native->body->GetMass()==0,"Original source Pin did not zero native mass");check(fields->actor.action==action&&fields->actor.target_id==target,"Pin bridge invented a state/target transition");}
  dh2::physical::NativeBodyObservation observed{};check(!dh2_native_body_observe(&observed,physical.native)&&observed.position[0]==2.5f&&observed.position[1]==3.75f,"Admitted source SetPosition did not move native body");
  if(actors.empty()) {auto* shape=physical.native->body->GetShapeList();const auto saved=shape->GetFilterData();check(pool.set_physical_filter_enabled(fields->actor.id,false,error),error);auto disabled=shape->GetFilterData();check(disabled.groupIndex==0&&disabled.categoryBits==0&&disabled.maskBits==0,"Original disableFilter words not applied");check(pool.set_physical_filter_enabled(fields->actor.id,true,error),error);auto enabled=shape->GetFilterData();check(enabled.groupIndex==saved.groupIndex&&enabled.categoryBits==saved.categoryBits&&enabled.maskBits==saved.maskBits,"Original saved filter not restored");}
  if(actors.empty()) {check(pool.remove_physical(fields->actor.id,error),error);check(!*actor.physical2dc&&pool.physical(fields->actor.id)&&pool.navigation(fields->actor.id)->user==0,"Source physical removal destroyed actor/AABB/PF authority");check(pool.actor_borrow(fields->actor.id,actor,error)&&actor.absolute12c[0]==plan.bounds.relative_box[0]+250,error);check(!pool.set_physical_filter_enabled(fields->actor.id,false,error),"Absent actual physical filter receiver accepted");check(pool.initialize_physical(fields->actor.id,error),error);check(*actor.physical2dc&&pool.physical(fields->actor.id)->native().body,"Source physical reinitialization absent");}
  check(!pool.bind(fields->actor,*data,plan,b,error),"Duplicate body identity accepted");actors.push_back(fields);properties.push_back(data);cachedPlans.push_back(plan);
 }
 bool rejected=false;try{world->ShouldCollide(pool.physical(100)->native().body->GetShapeList(),pool.physical(101)->native().body->GetShapeList());}catch(const std::runtime_error&){rejected=true;}check(rejected&&filterReached>0,"Reached unbound gameplay filter reported successful placeholder");
 b2ContactPoint contact{};contact.shape1=pool.physical(100)->native().body->GetShapeList();contact.shape2=pool.physical(101)->native().body->GetShapeList();rejected=false;try{world->Add(&contact);}catch(const std::runtime_error&){rejected=true;}check(rejected&&contactReached>0,"Reached unbound gameplay contact reported successful placeholder");
 OriginalTriggerActorBorrow retained;check(pool.actor_borrow(100,retained,error),error);check(pool.clear(error),error);check(pool.size()==0&&*retained.physical2dc==0,"Release did not detach actual physical slot before registry replacement");OriginalTriggerPhysicalBorrow absent;check(!pool.physical_borrow(123,absent,error),"Released physical query accepted");
 // A restore replaces admitted source position only after old bodies detach;
 // rebuild uses the same immutable property authority and a fresh source plan.
 auto fields=actors.front();fields->actor.transform.position={50000,40000,255};auto restored=cachedPlans.front();check(OriginalActorBounds::update_absolute(restored.bounds,{50000,40000,255},error),error);auto rebased=restored;check(PlayableActorBodies::rebase_plan(rebased,fields->actor.id,fields->actor.transform.position,error),error);check(rebased.radius_game_units!=restored.radius_game_units,"Fixture did not exercise source absolute-bound cancellation rounding");OriginalActorPhysicalBindings b;b.actor_lease=fields;b.world_lease=world;b.data_lease=properties.front();b.world=world.get();b.ai=ai.get();b.destination1a8=fields->destination.data();b.attached2e0=&fields->attached;b.visual2d8=&fields->visual;b.static84=[](auto& out,auto&){out=0;return true;};b.is_player=[](auto type,auto& out,auto&){out=original_actor_source_is_player(type,"KnightPlayerBase");return true;};b.debug_switch=[](const char*,bool& out,std::string&){out=false;return true;};b.filter=[](void*,const auto&,const auto&,bool&,auto& e){e="Gameplay filter not admitted";return false;};b.contact=[](auto,void*,unsigned,auto& e){e="Gameplay contact not admitted";return false;};check(pool.bind(fields->actor,*properties.front(),restored,b,error),error);check(pool.navigation(100)->user==0&&fields->actor.transform.position==std::array<float,3>{50000,40000,255},"Restore body rebuild changed admitted authority or reused old PF runtime");check(pool.physical(100)->native().radius*100.f==rebased.radius_game_units,"Rebuilt body differs from exact current source radius");std::cout<<"Radius rebase old="<<restored.radius_game_units<<" current="<<rebased.radius_game_units<<"\n";check(pool.clear(error),error);auto wrong=restored;wrong.group_index^=1;check(!pool.bind(fields->actor,*properties.front(),wrong,b,error)&&pool.size()==0,"Unrelated source group mismatch accepted");wrong=restored;wrong.character_type+=1;check(!pool.bind(fields->actor,*properties.front(),wrong,b,error),"Unrelated source type mismatch accepted");
 // Real authored floor and SAME PF/native owner, with an explicitly unoptimized
 // source child-pose fixture. No campaign geometry-admission or Step claim.
 const auto floorBytes=assets.read("original-cache/data/3d/modules/swamp/swamp.bdae");dh2::resources::BresView floorView{};check(dh2_bres_open(&floorView,floorBytes.data(),floorBytes.size())==dh2::resources::BresError::ok,"Original floor BRES missing");dh2::scene::Scene floorScene;check(dh2::scene::load(floorView,floorScene,error),error);unsigned floorInstance=UINT32_MAX;for(unsigned i=0;i<floorScene.instances.size();++i)if(floorScene.graph[floorScene.instances[i].node_index].name.find("floor")!=std::string::npos){floorInstance=i;break;}check(floorInstance!=UINT32_MAX,"Actual source floor instance absent");auto floorWorld=std::make_shared<dh2::floors::World>();OriginalSourceFloorBinding floorBinding;floorBinding.instance=floorInstance;floorBinding.room=0;floorBinding.mesh_local_quaternion={0,0,0,1};floorBinding.mesh_local_scale={1,1,1};check(append_original_module_floors(floorView,floorScene,{floorBinding},*floorWorld,error),error);check(dh2::floors::build_graph(*floorWorld,error)&&dh2::floors::post_load(*floorWorld,error),error);std::array<float,3> floorPoint{};bool foundFloor=false;for(const auto& triangle:floorWorld->records.front()->triangles){for(unsigned k=0;k<3;++k)floorPoint[k]=(triangle.points[0][k]+triangle.points[1][k]+triangle.points[2][k])/3.f;float height=floorPoint[2];if(dh2::floors::height(*floorWorld,floorPoint.data(),height)){floorPoint[2]=height;foundFloor=true;break;}}check(foundFloor,"Actual source floor selector has no diagnostic point");fields->actor.transform.position=floorPoint;auto groundPlan=cachedPlans.front();check(PlayableActorBodies::rebase_plan(groundPlan,fields->actor.id,floorPoint,error),error);check(pool.bind(fields->actor,*properties.front(),groundPlan,b,error),error);const auto* solePF=pool.navigation(100);check(solePF&&solePF->user==0,"Ground body did not retain constructor PFObject");auto obstacles=std::make_shared<SourceObstacles>();check(pool.initialize_navigation(100,{floorWorld,obstacles,floorWorld.get(),&obstacles->registry},error),error);check(pool.navigation(100)==solePF&&solePF->user==100&&solePF->radius==pool.physical(100)->native().radius*100.f&&obstacles->registry.count==1,"Late PF/native radius/obstacle publication differs");
 auto elevated=floorPoint;elevated[2]+=10;check(pool.set_position(100,elevated,false,error),error);OriginalActorNavigationMoveResult ground;check(pool.move_grounded(100,{elevated[0],elevated[1],elevated[2]},{0,0,0},ground,error),error);check(!ground.direction_checked&&ground.position_valid&&ground.grounded&&fields->actor.transform.position[2]==solePF->motion.position[2],"Idle source position validation did not ground SAME owner/PF");check(ground.position.z!=elevated[2],"Idle source query retained nonfloor owner Z");OriginalTriggerActorBorrow groundedBorrow;check(pool.actor_borrow(100,groundedBorrow,error),error);for(unsigned k=0;k<6;++k)check(groundedBorrow.absolute12c[k]==groundPlan.bounds.relative_box[k]+fields->actor.transform.position[k%3],"Admitted floor motion did not translate SAME source AABB");
 const auto beforeMotion=fields->actor.transform.position;auto untouched=ground;floorWorld->source_motion_policy_v95.maximum_height_delta=-1;check(!pool.move_grounded(100,{beforeMotion[0],beforeMotion[1],beforeMotion[2]},{0,0,0},ground,error)&&ground.kind==untouched.kind&&fields->actor.transform.position==beforeMotion,"Malformed SAME motion policy was successful fallback or changed owner/output");floorWorld->source_motion_policy_v95.maximum_height_delta=100;check(pool.move_grounded(100,{beforeMotion[0],beforeMotion[1],beforeMotion[2]},{999999,999999,0},ground,error),error);check(!ground.direction_checked&&!ground.position_valid&&ground.grounded&&fields->actor.transform.position==beforeMotion&&fields->actor.transform.position[0]==ground.position.x&&fields->actor.transform.position[1]==ground.position.y,"Source root position rejection or heading separation differs");
 auto hostHeading=std::make_shared<dh2::navigation::HeadingState>();const float intent[]{1,0,0};check(!dh2_nav_set_heading(hostHeading.get(),intent,1),"Source host heading init failed");OriginalManualHeadingBindings headingBindings;headingBindings.controller_lease=hostHeading;headingBindings.read_heading=[hostHeading](auto& out,auto&){out=*hostHeading;return true;};headingBindings.publish_heading=[hostHeading](const auto& out,auto&){*hostHeading=out;return true;};headingBindings.source_policy=[](auto& flags,auto& boundary,auto&){flags=0x23c1;boundary=1;return true;}; // Explicit Move-focus field fixture, not a state-ID-derived runtime policy.
 headingBindings.skip_boundary=[](auto& skip,auto&){skip=0;return true;};OriginalManualHeadingResult headed;check(pool.update_manual_heading(100,headingBindings,headed,error),error);check(headed.path_policy_enabled&&headed.boundary_checked&&solePF->motion.position[0]==fields->actor.transform.position[0],"Pool manual-heading bridge used a different actor/PF position");
 auto teleported=beforeMotion;teleported[2]+=300;check(pool.set_position(100,teleported,false,error),error);check(pool.move_grounded(100,{teleported[0],teleported[1],teleported[2]},{999999,999999,0},ground,error),error);check(!ground.position_valid&&ground.kind==3&&ground.grounded&&fields->actor.transform.position==beforeMotion&&ground.position.z!=teleported[2],"False source kind3 clamped point was discarded instead of published");
 check(pool.remove_physical(100,error),error);check(obstacles->registry.count==0&&pool.navigation(100)==solePF&&solePF->user==100,"Physical removal did not run original obstacle detach on SAME PF");check(pool.initialize_physical(100,error),error);check(obstacles->registry.count==1&&solePF->radius==pool.physical(100)->native().radius*100.f,"Source native reinitialization did not reattach actual PF obstacle/radius");check(pool.clear(error),error);check(obstacles->registry.count==0,"Pool release left source obstacle entries across owner replacement");
 // Typed contact-delivery fixture exercises the recovered dispatcher; this is
 // an explicit observer service, not a live AIS/FSM or world-Step claim.
 ContactDelivery delivery;std::array<std::uintptr_t,102> aiMethods{};aiMethods[0xbc/4]=0x3d0decu;aiMethods[0xc0/4]=0x3d0e10u;aiMethods[0xc4/4]=0x3d0e34u;
 dh2::character::AIEventOwner48 aiOwner{fields->actor.id,1,2,reinterpret_cast<std::uintptr_t>(&properties.front()->sheets),0,0,0,0};dh2::character::AIEventState64 state{};state.ai=3;state.owner=&aiOwner;state.ai_virtuals=aiMethods.data();std::vector<std::string> order;
 OriginalActorContactBindings contactBindings;contactBindings.runtime_lease=fields;contactBindings.peer_owner=[&](void*,auto& id,auto&){order.push_back("peer");id=101;return true;};contactBindings.handle_character=[&](auto id,auto& out,auto&){order.push_back("handle");check(id==fields->actor.id,"Contact owner identity changed");out=id;return true;};contactBindings.debug_load=[&](auto&){order.push_back("load");return true;};contactBindings.debug_switch=[&](const char* key,bool& out,auto&){order.push_back("debug");check(std::strcmp(key,"isTracingPlayersCollision")==0,"Wrong source contact debug switch");out=false;return true;};contactBindings.ai_events=[&](auto id,auto*& out,auto& services,auto&){order.push_back("ai");check(id==fields->actor.id,"Contact borrowed another AI owner");out=&state;services={&delivery,ContactDelivery::invoke,3,0};return true;};
 auto contactCallback=original_actor_contact_callback(fields->actor.id,contactBindings);check(contactCallback(dh2::physical::ContactEvent::add,nullptr,1,error),error);check(order==std::vector<std::string>({"peer","load","debug","handle","ai"}),"Original begin Debug/handle prefix order differs");check(delivery.calls.back().event==0x37&&delivery.calls.back().operation==0xbc&&delivery.calls.back().payload==101&&delivery.calls.back().argument==1,"Source begin event/persist/peer routing changed");
 order.clear();check(contactCallback(dh2::physical::ContactEvent::persist,nullptr,0,error),error);check(order==std::vector<std::string>({"peer","handle","load","debug","ai"}),"Original persist handle/Debug prefix order differs");check(delivery.calls.back().event==0x3a&&delivery.calls.back().operation==0xc0&&delivery.calls.back().argument==0,"Source persist event routing changed");aiOwner.locked=1;check(contactCallback(dh2::physical::ContactEvent::remove,nullptr,1,error),error);check(delivery.calls.back().service==dh2::character::ai_event_state_event&&delivery.calls.back().event==0x3b,"Original controller gate did not use SAME FSM service");aiOwner.locked=0;
 contactBindings.ai_events={};contactCallback=original_actor_contact_callback(fields->actor.id,contactBindings);check(!contactCallback(dh2::physical::ContactEvent::add,nullptr,1,error),"Unbound source Character/AIS contact dispatcher silently succeeded");check(contactCallback(dh2::physical::ContactEvent::result,nullptr,1,error),"Proved empty Result body rejected");
 std::cout<<"PASS genuine player/NPC native bodies, source fresh PF user0 callback, same actor/property authority, native SetPosition, exact contact prefix/event gates, explicit filter/contact failures and release lifetime\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 1;}}
