#include "../retained_sequence_playback.hpp"
#include "../asset_catalog.hpp"
#include <iostream>
#include <cmath>
#include <stdexcept>
using namespace dh::foundation;
void check(bool yes,const std::string& error){if(!yes)throw std::runtime_error(error);}
void equal(const RetainedAnimationFrame&a,const RetainedAnimationFrame&b){check(a.events.size()==b.events.size(),"frame event count differs");for(size_t i=0;i<a.events.size();++i)check(a.events[i].name==b.events[i].name&&a.events[i].clip_id==b.events[i].clip_id&&a.events[i].lag_ms==b.events[i].lag_ms&&a.events[i].slot==b.events[i].slot&&a.events[i].generation==b.events[i].generation,"frame event order/lag/identity differs");check(a.move_go==b.move_go&&std::abs(a.authored_motion.x-b.authored_motion.x)<.00001f&&std::abs(a.authored_motion.y-b.authored_motion.y)<.00001f&&std::abs(a.authored_motion.z-b.authored_motion.z)<.00001f,"source motion differs");}
int main(int argc,char**argv){try{
 check(argc==2,"Expected repository root");const auto root=std::filesystem::path(argv[1]);AssetCatalog metadata(root/".local-inputs/windows-melee-bindings"),assets(root/".local-inputs/windows-shared-assets");OriginalMeleeBindings data;std::string error;check(data.load(metadata,"original-melee-bindings.xml",error),error);OriginalSequencePolicies policies;check(original_sequence_policies(data,policies,error),error);
 for(const auto& actor:std::vector<std::pair<std::string,std::string>>{{"KnightPlayerBase","Attack"},{"Swamp_LizadMan_Type1","Spawn"}}){
  ActorCustomization custom;custom.allow_missing_animation_targets=true;if(actor.first=="KnightPlayerBase"){custom.skin_id_contains="_default_warrior-mesh-skin";custom.expected_controller_count=4;}
  OriginalCombatVisualPlan plan;check(build_original_combat_visual_plan(assets,data,actor.first,custom,"source-test",plan,error),error);const auto* selected=plan.sequence(actor.second,0);check(selected,"Missing actual selected state");OriginalAttackSelection selection;selection.state=actor.second;if(actor.first=="KnightPlayerBase")selection.group_path={0};
  auto config=plan.config;config.motion_node_id="auto";config.consume_root_motion=true;config.clips.clear();for(const auto& phase:selected->phases)if(selection.group_path.empty()||phase.sourcePath[0]==0)config.clips.emplace_back(phase.clipName,phase.resolvedPath);const auto* idle=plan.phase("Idle",0,{0});check(idle&&idle->has_visual(),"Explicit caller Idle unavailable");config.clips.emplace_back(idle->clipName,idle->resolvedPath);const auto* injured=plan.phase("Injured",0,{0});if(injured&&injured->has_visual())config.clips.emplace_back(injured->clipName,injured->resolvedPath);const auto* walk=plan.phase("Walk",0,{0});if(walk&&walk->has_visual())config.clips.emplace_back(walk->clipName,walk->resolvedPath);
  CharacterVisual visual,referenceVisual;check(visual.load(assets,config,error),error);check(referenceVisual.load(assets,config,error),error);
  RetainedSequencePlayback sequence(visual,complete_pose_root_sampler(visual));RetainedAnimationOwner reference(referenceVisual,complete_pose_root_sampler(referenceVisual));
  std::vector<RetainedAnimationFrame> frames;std::vector<size_t> framePhases;unsigned closes=0;dh2::timeline::Completion closed{};bool callerIdle=false;
  RetainedSequenceServices services;services.frame=[&](size_t phase,const RetainedAnimationFrame&frame,std::string&){frames.push_back(frame);framePhases.push_back(phase);return true;};services.closed=[&](const dh2::timeline::Completion& completion,std::string&e){++closes;closed=completion;RetainedAnimationFrame seeded;if(!sequence.seed(assets,idle->clipName,idle->resolvedPath,true,static_cast<float>(idle->speed),static_cast<int>(idle->blendOut),idle->moveGO!=0,seeded,e))return false;callerIdle=true;return true;};
  check(sequence.prepare(assets,plan,policies,selection,services,"source-action",error),error);check(sequence.phases().size()==(actor.first=="KnightPlayerBase"?3:1),"Actual selected phase count differs");
  for(const auto& phase:sequence.phases()){const auto bytes=assets.read(phase.source.resolvedPath);check(reference.bind_events(phase.source.clipName,bytes.data(),bytes.size(),error),error);}auto idleBytes=assets.read(idle->resolvedPath);check(reference.bind_events(idle->clipName,idleBytes.data(),idleBytes.size(),error),error);
  RetainedAnimationFrame expected,seeded;check(sequence.seed(assets,idle->clipName,idle->resolvedPath,true,static_cast<float>(idle->speed),static_cast<int>(idle->blendOut),idle->moveGO!=0,seeded,error),error);check(reference.select(idle->clipName,true,static_cast<float>(idle->speed),static_cast<int>(idle->blendOut),idle->moveGO!=0,expected,error),error);equal(seeded,expected);
  auto enterReference=[&](size_t index,int extra){const auto&p=sequence.phases()[index];check(reference.select(p.source.clipName,false,static_cast<float>(p.rate),static_cast<int>(p.source.blendOut),p.source.moveGO!=0,expected,error,extra),error);};
  check(sequence.begin(error),error);enterReference(0,0);check(frames.size()==1,"Initial phase delivery missing");equal(frames.back(),expected);check(sequence.animation()->pose().slots()[sequence.animation()->pose().current_slot()].timeline.current_ms==sequence.phases()[0].start_ms,"Initial phase offset incorrect");
  unsigned hitCount=0,spawnEvents=0;double wall=0;std::size_t referencePhase=0;bool referenceDone=false;std::uint32_t hitWall=0;int hitLag=0;unsigned transitions=0;
  for(unsigned step=0;step<2000&&sequence.active();++step){const double delta=step%5==4?.037:.016;wall+=delta;frames.clear();check(reference.advance(delta,expected,error),error);const auto completion=reference.take_completion();check(sequence.advance(delta,error),error);check(!frames.empty(),"Wall frame not delivered");equal(frames[0],expected);
   for(const auto& event:frames[0].events){if(event.name=="attack_mainhand"){++hitCount;hitWall=event.wall_timestamp_ms;hitLag=event.lag_ms;}if(event.clip_id==sequence.phases()[0].source.clipName&&actor.second=="Spawn"){++spawnEvents;std::cout<<"spawn marker "<<event.name<<" lag="<<event.lag_ms<<" wall="<<event.wall_timestamp_ms<<'\n';}}
   if(completion.pending){++transitions;if(referencePhase+1<sequence.phases().size()){++referencePhase;enterReference(referencePhase,completion.extra_ms);check(frames.size()==2,"Next phase not delivered at completion frame");equal(frames[1],expected);const auto&current=sequence.animation()->pose().slots()[sequence.animation()->pose().current_slot()];check(current.timeline.current_ms==sequence.phases()[referencePhase].start_ms,"Different resource incorrectly consumed discarded overshoot");}else{referenceDone=true;check(closed.pending==completion.pending&&closed.extra_ms==completion.extra_ms,"Closed completion remainder differs");}}
   else check(frames.size()==1,"Transition occurred without genuine completion");
  }
  check(referenceDone&&sequence.finished()&&callerIdle&&closes==1,"Genuine final completion did not invoke caller Idle exactly once");check(transitions==sequence.phases().size(),"Completion phase count differs");check(!sequence.advance(.01,error)&&closes==1,"Closed sequence delivered twice");if(actor.second=="Attack")check(hitCount==1,"Actual Prince strike hit missing or duplicated");
  std::cout<<actor.first<<" phases="<<sequence.phases().size()<<" completionWall="<<wall<<" strikeWallMs="<<hitWall<<" strikeLag="<<hitLag<<" sourceFrameComparison=pass\n";
  const auto idleSlot=sequence.animation()->pose().current_slot();const auto idlePrior=sequence.animation()->pose().slots()[idleSlot].timeline.current_ms;check(sequence.advance_seeded(.123,error)&&sequence.advance_seeded(.123,error),error);check(framePhases.back()==SIZE_MAX&&sequence.animation()->pose().slots()[idleSlot].timeline.current_ms!=idlePrior,"Seeded Idle clock did not advance through retained owner");check(sequence.advance_seeded(2,error)&&sequence.finished()&&closes==1,"Seeded loop reclosed finite action");check(sequence.advance_seeded(0,error)&&frames.back().completion.pending==0,"Seeded completion latch not consumed");
  if(injured&&injured->has_visual()){
   check(sequence.begin(error)&&sequence.active(),error);check(sequence.seed(assets,injured->clipName,injured->resolvedPath,false,static_cast<float>(injured->speed),static_cast<int>(injured->blendOut),injured->moveGO!=0,seeded,error),error);check(!sequence.active()&&!sequence.finished()&&sequence.seeded(),"Explicit Injured seed did not interrupt finite action");check(sequence.advance_seeded(10,error)&&sequence.advance_seeded(10,error),error);check(sequence.animation()->pose().current_ended()&&closes==1,"Seeded Injured did not end on actual timeline");
  }
  auto bad=selection;bad.state="unknown";check(!sequence.prepare(assets,plan,policies,bad,services,"bad",error),"Invalid source plan accepted");check(sequence.phases().size()==transitions,"Failed prepare changed previous program");
  if(walk&&walk->has_visual()){
   CharacterVisual loopVisual,loopReferenceVisual;check(loopVisual.load(assets,config,error)&&loopReferenceVisual.load(assets,config,error),error);RetainedSequencePlayback looping(loopVisual,complete_pose_root_sampler(loopVisual));RetainedAnimationOwner loopReference(loopReferenceVisual,complete_pose_root_sampler(loopReferenceVisual));std::vector<RetainedAnimationFrame> batches;unsigned loopClosed=0;RetainedSequenceServices loopServices;loopServices.frame=[&](size_t phase,const RetainedAnimationFrame&f,std::string&){check(phase==SIZE_MAX,"Seed repeat fabricated attack phase");batches.push_back(f);return true;};loopServices.closed=[&](const dh2::timeline::Completion&,std::string&){++loopClosed;return true;};check(looping.prepare(assets,plan,policies,selection,loopServices,"loop-validation",error),error);const auto wb=assets.read(walk->resolvedPath);check(loopReference.bind_events(walk->clipName,wb.data(),wb.size(),error),error);
   check(looping.seed_sequence(assets,walk->clipName,walk->resolvedPath,static_cast<float>(walk->speed),static_cast<int>(walk->blendOut),walk->moveGO!=0,-1,seeded,error),error);check(loopReference.select(walk->clipName,false,static_cast<float>(walk->speed),static_cast<int>(walk->blendOut),walk->moveGO!=0,expected,error),error);equal(seeded,expected);unsigned repeated=0;double motionLength=0;
   for(unsigned i=0;i<150;++i){batches.clear();check(loopReference.advance(.05,expected,error),error);const auto c=loopReference.take_completion();check(looping.advance_seeded(.05,error),error);check(!batches.empty(),"Source repeat frame missing");equal(batches[0],expected);motionLength+=std::hypot(batches[0].authored_motion.x,batches[0].authored_motion.y);if(c.pending){++repeated;check(loopReference.select(walk->clipName,false,static_cast<float>(walk->speed),static_cast<int>(walk->blendOut),walk->moveGO!=0,expected,error,c.extra_ms),error);check(batches.size()==2,"Actual completion did not select source repeat");equal(batches[1],expected);}else check(batches.size()==1,"Source repeat selected on approximated duration");check(looping.animation()->pose().slots()[looping.animation()->pose().current_slot()].timeline.loop==0,"Source sequence became raw timeline loop");}
   check(repeated>=2&&loopClosed==0&&motionLength>0,"Infinite source sequence failed repetition/root movement");std::cout<<actor.first<<" sourceWalkRepeats="<<repeated<<" sourceRootXY="<<motionLength<<" rootResetReference=pass\n";
  }
  if(actor.second=="Attack"){
   // Three source phases replay the same ORIGINAL resource. The third incoming
   // physical slot retains that clip identity, so source completion extra jumps
   // its start. The second slot still held Idle and must discard that extra.
   OriginalCombatVisualPlan repeated=plan;OriginalCombatSequencePlan chain;chain.state="caller-replay";chain.id=900000;chain.type=1;const auto strike=sequence.phases()[1].source;
   for(size_t i=0;i<3;++i){auto p=strike;p.sourcePath={i};p.ancestors.clear();p.speed=1;p.blendOut=100;chain.phases.push_back(p);}repeated.sequences={chain};OriginalAttackSelection replaySelection;replaySelection.state=chain.state;RetainedSequencePlayback replay(visual,complete_pose_root_sampler(visual));RetainedSequenceServices replayServices;replayServices.frame=[](size_t,const RetainedAnimationFrame&,std::string&){return true;};replayServices.closed=[](const dh2::timeline::Completion&,std::string&){return true;};check(replay.prepare(assets,repeated,policies,replaySelection,replayServices,"replay-action",error),error);check(replay.seed(assets,idle->clipName,idle->resolvedPath,true,1,100,false,seeded,error)&&replay.begin(error),error);
   while(replay.phase_index()==0)check(replay.advance(.25,error),error);auto&second=replay.animation()->pose().slots()[replay.animation()->pose().current_slot()];check(second.timeline.current_ms==replay.phases()[1].start_ms,"Different slot ID did not discard overshoot");
   while(replay.phase_index()==1)check(replay.advance(.25,error),error);auto&third=replay.animation()->pose().slots()[replay.animation()->pose().current_slot()];check(third.timeline.current_ms>replay.phases()[2].start_ms,"Same physical slot replay did not consume source extra");std::cout<<"same-resource thirdStart="<<third.timeline.current_ms<<" authoredStart="<<replay.phases()[2].start_ms<<'\n';replay.cancel();
   bool reentered=false;replayServices.frame=[&](size_t,const RetainedAnimationFrame&frame,std::string&e){if(frame.completion.pending&&!reentered){reentered=true;return replay.begin(e);}return true;};check(replay.prepare(assets,repeated,policies,replaySelection,replayServices,"replay-action",error)&&replay.begin(error),error);for(unsigned i=0;i<10&&!reentered;++i)check(replay.advance(.25,error),error);check(reentered&&replay.phase_index()==0&&replay.completed_phases()==0,"Reentry consumed stale completion");check(replay.advance(0,error)&&replay.phase_index()==0&&replay.completed_phases()==0,"Old latch closed restarted action");replay.cancel();
   repeated.sequences[0].type=2;replaySelection.choices[{}]=1;check(replay.prepare(assets,repeated,policies,replaySelection,replayServices,"explicit-choice",error),error);check(replay.phases().size()==1&&replay.phases()[0].source.sourcePath==std::vector<size_t>{1},"Source type2 explicit choice was not retained");auto missingChoice=replaySelection;missingChoice.choices.clear();check(!replay.prepare(assets,repeated,policies,missingChoice,replayServices,"missing-choice",error)&&replay.phases().size()==1,"Missing type2 choice guessed or changed program");check(replay.begin(error),error);for(unsigned i=0;i<20&&replay.active();++i)check(replay.advance(.1,error),error);check(replay.finished()&&replay.completed_phases()==1,"Explicit type2 selection did not complete genuine single phase");
   RetainedSequencePlayback hooked(visual,complete_pose_root_sampler(visual));RetainedSequenceServices hookedServices;
   std::vector<RetainedSequenceBoundary> boundaries;unsigned hookedCloses=0;
   hookedServices.frame=[](size_t,const RetainedAnimationFrame&,std::string&){return true;};
   hookedServices.closed=[&](const auto&,std::string&){++hookedCloses;return true;};
   hookedServices.boundary=[&](const RetainedSequenceBoundary& boundary,RetainedSequenceCursorDecision& decision,std::string&){
    boundaries.push_back(boundary);if(!boundary.beginning&&boundary.depth==1&&boundary.step==1)decision.skipNext=true;return true;
   };
   check(hooked.prepare(assets,plan,policies,selection,hookedServices,"scoped-source-hooks",error)&&hooked.begin(error),error);
   for(unsigned i=0;i<200&&hooked.active();++i)check(hooked.advance(.016,error),error);
   check(hooked.finished()&&hookedCloses==1&&hooked.completed_phases()==2,"Source scoped group did not honor SkipNext or escaped scope");
   check(boundaries.size()>=5&&boundaries[0].beginning&&boundaries[0].depth==0&&boundaries[0].count==3&&
         boundaries[1].beginning&&boundaries[1].depth==1&&boundaries[1].count==3,"Source hierarchy hooks lost actual root/redirect count");
   bool boundaryReentered=false;hookedServices.boundary=[&](const RetainedSequenceBoundary& boundary,RetainedSequenceCursorDecision&,std::string&e){
    if(!boundary.beginning&&!boundaryReentered){boundaryReentered=true;return hooked.begin(e);}return true;
   };
   check(hooked.prepare(assets,plan,policies,selection,hookedServices,"hierarchy-reentry",error)&&hooked.begin(error),error);
   for(unsigned i=0;i<100&&!boundaryReentered;++i)check(hooked.advance(.016,error),error);
   check(boundaryReentered&&hooked.phase_index()==0&&hooked.completed_phases()==0,"Source boundary reentry consumed stale completion or advanced old cursor");hooked.cancel();
   std::cout<<"source hierarchy hooks: scoped SkipNext, actual counts, synchronous reentry=pass\n";
  }
 }
 std::cout<<"retained sequence tests passed: actual source completion cadence, serialized events/lag, BlendOut/rate/MoveGO, caller Idle closure\n";
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}



