#include "../source_module_floors.hpp"
#include "../source_root_scopes.hpp"
#include "../source_world_objects.hpp"
#include "../collision_scene.hpp"
#include "../original_actor_navigation.hpp"
#include "../../engine-math/math.hpp"
#include <filesystem>
#include <iostream>
#include <stdexcept>
#include <fstream>
#include <functional>
#include "../content_paths.hpp"
using namespace dh::foundation;
void check(bool x,const std::string&e){if(!x)throw std::runtime_error(e);}
int main(int argc,char**argv){try{
 check(argc==2,"Repository root required");AssetCatalog assets(std::filesystem::path(argv[1])/"port/windows-foundation/assets");const std::string uri="original-cache/data/scene/001_swamp.mlx";std::vector<ActorDefinition>definitions;std::string error;check(load_actor_definitions(assets,uri,definitions,error),error);SourceWorldObjects objects;SourceRootScopes scopes;check(objects.load(definitions,error)&&scopes.load(assets,uri,definitions,error)&&scopes.bind(objects,error),error);
 auto world=std::make_shared<dh2::floors::World>();SourceModuleFloors floors(world);std::shared_ptr<SourceModuleFloorRoom> room;SourceModuleFloorRequest unknown;check(!floors.load(assets,unknown,room,error)&&floors.rooms().empty(),"Missing genuine module receipt guessed a room");unsigned nonidentity=0,hidden=0;
 for(const auto&trace:scopes.modules().entries()){
  SourceModuleFloorRequest q;q.trace=trace;q.pose_phase=SourceModulePosePhase::constructor_degrees;q.admitted=true; // Explicit test admission; source campaign gates remain host provider.
  for(const auto&record:scopes.module_records())if(record->receiver->base().identity()==trace.receiver.identity)q.record=record;check(bool(q.record),"Actual source constructor record not associated with same trace");
  const auto before=floors.rooms().size();check(floors.load(assets,q,room,error),error);check(room->id==before&&room->module_id==q.record->receiver->module_id()&&room->source_room1c==q.record->receiver->base().room64(),"PF index/module ID/inherited room association differs");check(room->source_room1c==-1,"Actual root inherited room expected-1 independent of positive module IDs");check(room->completed,"Actual room floor prefix incomplete");std::cout<<"room="<<room->id<<" modulePos="<<trace.position[0]<<","<<trace.position[1]<<","<<trace.position[2]<<" xrefRootLocal="<<room->factory.scene.graph.front().translation[0]<<","<<room->factory.scene.graph.front().translation[1]<<","<<room->factory.scene.graph.front().translation[2]<<" floors="<<room->floors.size()<<"\n";for(auto fid:room->floors){const auto&b=world->records.at(fid)->world;std::cout<<"floor="<<fid<<" bounds="<<b.minimum[0]<<","<<b.minimum[1]<<","<<b.minimum[2]<<".."<<b.maximum[0]<<","<<b.maximum[1]<<","<<b.maximum[2]<<"\n";}
  for(const auto&mesh:room->meshes){const auto&instance=room->factory.scene.instances.at(mesh.instance);dh2::math::Matrix4f cached{};std::copy(instance.world.begin(),instance.world.end(),cached.m);cached.identity_hint=0;dh2::math::Quaternion expected{};dh2_quat_from_matrix(&expected,&cached);check(mesh.mesh_local_quaternion==std::array<float,4>{expected.x,expected.y,expected.z,expected.w},"Actual optimized child quaternion differs from source cached world");check(mesh.mesh_local_scale==std::array<float,3>{1,1,1},"Source mesh ctor scale changed during OptimizeStatic");check(world->records.at(mesh.floor)->room==room->id&&mesh.source_cached_world==instance.world,"Floor uses wrong actual PF room or reapplied cache");if(expected.x!=0||expected.y!=0||expected.z!=0||expected.w!=1)++nonidentity;if(!room->factory.instance_visibility.at(mesh.instance))++hidden;}
  check(!floors.load(assets,q,room,error)&&floors.rooms().size()==before+1,"Same Module floor factory replay accepted");
 }
 check(floors.rooms().size()==scopes.count()&&!world->records.empty(),"Actual source rooms/floors missing");check(floors.post_load(error),error);check(world->sewn&&world->collision_world.room_count==floors.rooms().size()&&world->collision_world.floor_count==world->records.size(),"Actual PF postload collision grouping missing");CollisionScene preview;check(load_collision_level(assets,uri,preview,error),error);
 const std::array<std::array<float,3>,3> probes{{{1090.75f,-212.202f,258},{-6752.641f,938.285f,250},{-3500,250,255}}};
 for(const auto&point:probes){dh2::navigation::HeightHit hit{};hit.height=point[2];hit.normal[2]=1;check(dh2_nav_world_height(&hit,&world->collision_world,point.data(),0)==1,"Actual source first-hit PF height missing at playable probe");check(std::abs(hit.height-255.f)<.001f,"Actual source floor-height fixture changed");FloorHit visible;check(preview.floor(point[0],point[1],point[2],visible),"Assembled source helper collision floor missing");check(std::abs(visible.point.z-hit.height)<.001f,"Source PF and assembled helper collision transforms disagree");std::cout<<"sourcePoint="<<point[0]<<","<<point[1]<<","<<point[2]<<" sourceHeight="<<hit.height<<" PFRoom="<<hit.room<<" PFFloor="<<hit.floor<<" type="<<world->collision_floors.at(hit.floor).traits.type<<" previewHeight="<<visible.point.z<<"\n";}
 const auto&spawn=probes.front();dh2::navigation::NavigationObject object{};std::array<float,6>relative{-100,-50,-10,100,50,10},absolute{};for(unsigned k=0;k<6;++k)absolute[k]=relative[k]+spawn[k%3];std::array<dh2::navigation::ObstacleEntry,16>entries{};std::array<unsigned,16>keys{};dh2::navigation::ObstacleRegistry obstacles{entries.data(),0,16,keys.data(),0,16};OriginalActorNavigationBindings binding;binding.actor_lease=world;binding.world_lease=world;binding.identity=100;binding.position160=spawn.data();binding.relative144=relative.data();binding.absolute12c=absolute.data();binding.object=&object;binding.obstacles=&obstacles;binding.floors=world.get();binding.static84=[](std::uint8_t&out,std::string&){out=0;return true;};OriginalActorNavigation navigation(binding);check(navigation.construct_defaults(error)&&navigation.initialize_pf(error),error);check(object.motion.floor!=UINT32_MAX&&std::abs(object.motion.position[2]-255.f)<.001f,"Source actor PF initialization did not use actual floor world");float next[]{spawn[0]+10,spawn[1],spawn[2]};dh2::navigation::ObjectPositionRequest move{&world->collision_world,&obstacles,&object,100,next,&world->source_motion_policy_v95};dh2::navigation::PositionResult moved{};check(dh2_nav_validate_object_position(&moved,&move)==0&&moved.valid&&std::abs(next[2]-255.f)<.001f,"Actual source navigation motion validation failed positive step");
 // Mutate ONLY a new test BRES copy's actual SNode visibility word. The
 // source factory still constructs the hidden floor mesh; PF must include it.
 const auto&first_room=floors.rooms().front();check(!first_room->meshes.empty(),"Source floor fixture absent");const auto&target_id=first_room->factory.scene.graph.at(first_room->factory.scene.instances.at(first_room->meshes.front().instance).node_index).id;auto hidden_bytes=first_room->bytes;
 auto word=[&](std::size_t p){check(p+4<=hidden_bytes.size(),"Fixture source word out of range");return std::uint32_t(hidden_bytes[p])|(std::uint32_t(hidden_bytes[p+1])<<8)|(std::uint32_t(hidden_bytes[p+2])<<16)|(std::uint32_t(hidden_bytes[p+3])<<24);};
 std::function<bool(std::size_t)> hide=[&](std::size_t node){const auto string=word(node);check(string<hidden_bytes.size(),"Fixture source node id missing");if(target_id==reinterpret_cast<const char*>(hidden_bytes.data()+string)){for(unsigned k=0;k<4;++k)hidden_bytes.at(node+52+k)=0;return true;}const auto count=word(node+56),children=word(node+60);for(unsigned i=0;i<count;++i)if(hide(children+80*i))return true;return false;};
 const auto visual=word(first_room->bres.root_offset+156);const auto top_count=word(visual+8),top_nodes=word(visual+12);bool hidden_written=false;for(unsigned i=0;i<top_count&&!hidden_written;++i)hidden_written=hide(top_nodes+80*i);check(hidden_written,"Actual source visibility fixture node not found");
 const auto fixture_root=std::filesystem::path(argv[1])/".local-inputs/windows-source-floor-fixture";const auto fixture_model=normalize_content_uri(*first_room->module->receiver->base().string(0x290));const auto fixture_path=fixture_root/fixture_model;std::filesystem::create_directories(fixture_path.parent_path());{std::ofstream file(fixture_path,std::ios::binary);file.write(reinterpret_cast<const char*>(hidden_bytes.data()),hidden_bytes.size());check(bool(file),"New fixture source asset write failed");}AssetCatalog fixture_assets(fixture_root);
 SourceRootScopes rotated_scopes;check(rotated_scopes.load(assets,uri,definitions,error),error);const auto&actual_trace=rotated_scopes.modules().entries().front();SourceModuleFloorRequest rotated;rotated.trace=actual_trace;rotated.pose_phase=SourceModulePosePhase::constructor_degrees;rotated.admitted=true;for(const auto&record:rotated_scopes.module_records())if(record->receiver->base().identity()==actual_trace.receiver.identity)rotated.record=record;check(bool(rotated.record),"Actual rotated fixture constructor receipt absent");rotated.record->receiver->base().vector3(0x16c)[2]=45.f; // Explicit source-field override fixture, not original authored rotation.
 auto rotated_world=std::make_shared<dh2::floors::World>();SourceModuleFloors rotated_floors(rotated_world);std::shared_ptr<SourceModuleFloorRoom>rotated_room;check(rotated_floors.load(fixture_assets,rotated,rotated_room,error),error);unsigned fixture_hidden=0,fixture_nonidentity=0;for(const auto&mesh:rotated_room->meshes){if(!rotated_room->factory.instance_visibility.at(mesh.instance))++fixture_hidden;if(mesh.mesh_local_quaternion[2]!=0)++fixture_nonidentity;dh2::math::Matrix4f actual{};std::copy(mesh.source_cached_world.begin(),mesh.source_cached_world.end(),actual.m);actual.identity_hint=0;dh2::math::Quaternion expected{};dh2_quat_from_matrix(&expected,&actual);check(mesh.mesh_local_quaternion==std::array<float,4>{expected.x,expected.y,expected.z,expected.w},"Rotated source OptimizeStatic quaternion mismatch");}
 check(fixture_hidden==1&&fixture_nonidentity>0&&rotated_room->floors.size()==first_room->floors.size(),"Hidden original factory floor or nonidentity source quaternion omitted");
 std::cout<<"PASS actualRootConstructors="<<scopes.count()<<" actualPFRooms="<<floors.rooms().size()<<" originalFloorRecords="<<world->records.size()<<" nonidentitySourceChildQuaternions="<<nonidentity<<" hiddenFloorsIncluded="<<hidden<<" actualPFValidatedMove="<<moved.valid<<" moveZ="<<next[2]<<" positiveHiddenFixture="<<fixture_hidden<<" positiveNonidentityFixture="<<fixture_nonidentity<<" admissionExplicitFixture=true noMapBranches=true\n";
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}




