#include "../../level-world/character_player_skills_v6.hpp"
#define CharacterPlayerSkillsV3 CharacterPlayerSkillsV6
// Snapshot; both AS fixtures replaced with actual retained AS objects.
// Reuse source-cache/test loaders without modifying the frozen V3 test.
#define main frozen_player_skills_audit_main
#include "../../level-world/tests/character_player_skills_v3.cpp"
#undef main
#include "../character_menu_queries_owner_v1.hpp"
#include "../character_menu_inventory_order_v1.hpp"
#include "../character_menu_inventory_mutation_v1.hpp"
#include <filesystem>
#include <cctype>
#include "character_menu_connected_as_host_v29.hpp"
#include "../../level-world/character_menu_faery_connection_v8.hpp"
#include "../../level-loader/native_gslevel_runtime_v27.hpp"
using namespace dh2::ui;using namespace dh2::player;
namespace {
struct MenuPlatform {
 std::string root,assets;TextFiles text;DebugSwitches* debug{};DebugFileServices24 files{};
 CharacterGameDesign::Borrow design;std::uintptr_t identity{};unsigned world_calls{},stores{};
 static skinning::VisualAssetResultV6 asset(void* p,const char* path,Raw& out,std::string&){auto& c=*static_cast<MenuPlatform*>(p);std::string uri=path,full;if(uri.find("data/pydata/loot_table_")==0)full=c.root+"/.local-inputs/items-discovery/"+uri.substr(12);else if(uri.find("data/pydata/item_powers_")==0)full=c.root+"/.local-inputs/player-item-effects-v5/power-cache/"+uri.substr(12);else if(uri.find("data/3d/characters/prince/weapons/")==0){auto name=uri.substr(uri.find_last_of('/')+1);for(auto& x:name)x=char(std::tolower(static_cast<unsigned char>(x)));full=c.root+"/.local-inputs/visual-skin-owner-v6/weapons/"+name;}else full=c.assets+"/original-cache/"+uri;if(!std::filesystem::exists(full))return skinning::VisualAssetResultV6::missing;out=file(full);return skinning::VisualAssetResultV6::found;}
 static bool world(void* p,EquipmentWorldQueryV1 q,std::uintptr_t subject,std::uintptr_t& id,std::int32_t& scalar,std::string&){auto& c=*static_cast<MenuPlatform*>(p);check(subject==c.identity);++c.world_calls;id=0;scalar=0;if(q==EquipmentWorldQueryV1::current_player)id=subject;if(q==EquipmentWorldQueryV1::player_count)scalar=1;return true;}
 static bool constant(void* p,const char* group,const char* key,std::uint32_t& out,std::string&){auto& c=*static_cast<MenuPlatform*>(p);if(!std::strcmp(group,"StrID"))return TextFiles::constant(&c.text,group,key,out,c.error);std::int32_t v;auto* bindings=c.design.design();if(!bindings->lookup||bindings->lookup(bindings->context,0,group,key,&v))return false;std::memcpy(&out,&v,4);return true;}
 static bool text_open(void* p,const char* name,bool& found,Raw& out,std::uintptr_t& lease,std::string& e){return TextFiles::open(&static_cast<MenuPlatform*>(p)->text,name,found,out,lease,e);}
 static bool text_close(void* p,std::uintptr_t lease,std::string& e){return TextFiles::close(&static_cast<MenuPlatform*>(p)->text,lease,e);}
 static bool text_debug(void* p,const char* key,std::string&){auto& c=*static_cast<MenuPlatform*>(p);std::uint32_t v;return dh2_character_debug_get(&v,c.debug,key,&c.files)==1;}
 std::string error;
};
Raw section(const std::string& text){Raw out(4);auto n=std::uint32_t(text.size()+1);std::memcpy(out.data(),&n,4);out.insert(out.end(),text.begin(),text.end());out.push_back(0);return out;}


void inventory_order_gold(const std::string& root){
 auto slots=file(root+"/port/engine-ui/reference/character-menu-native-v1/inventory-slot-gold-v1.bin");std::uint32_t count;std::memcpy(&count,slots.data(),4);check(count==810&&slots.size()==4+count*20);
 for(unsigned j=0;j<count;++j){std::int32_t row[5];std::memcpy(row,slots.data()+4+j*20,20);data::ItemInstanceV1 item;data::ItemRecord164 metadata{};data::PropertySheet props{};metadata.words[22]=row[0];metadata.words[26]=row[1];props[202]=row[2];check(character_menu_slot_candidate_v1(item,metadata,props,std::uint32_t(row[3]))==bool(row[4]),"Original slot eligibility mismatch");}
 auto values=file(root+"/port/engine-ui/reference/character-menu-native-v1/inventory-order-gold-v1.bin");std::memcpy(&count,values.data(),4);check(count==450&&values.size()==4+count*32);
 for(unsigned j=0;j<count;++j){std::int32_t row[8];std::memcpy(row,values.data()+4+j*32,32);data::ItemInstanceV1 a,b;data::ItemRecord164 ar{},br{};a.value=row[1];b.value=row[2];a.powers.resize(row[3]);b.powers.resize(row[4]);const char* names[]{"Alpha","Zulu"};a.name=names[row[5]];b.name=names[row[6]];for(unsigned k=8;k<17;++k){float av=float(k-6),bv=float(17-k);std::memcpy(&ar.words[k],&av,4);std::memcpy(&br.words[k],&bv,4);}check(character_menu_item_value_less_v1(a,ar,b,br,row[0])==bool(row[7]),"Original class/value comparator mismatch");}
 auto equipment=file(root+"/port/engine-ui/reference/character-menu-native-v1/inventory-equipment-order-gold-v1.bin");std::memcpy(&count,equipment.data(),4);check(count==360&&equipment.size()==4+count*32);
 for(unsigned j=0;j<count;++j){std::int32_t row[8];std::memcpy(row,equipment.data()+4+j*32,32);data::ItemInstanceV1 a,b;data::ItemRecord164 ar{},br{};const char* names[]{"Alpha","Zulu"};a.name=names[row[5]];b.name=names[row[6]];check(character_menu_item_equipment_less_v1(a,ar,b,br,0,row[0],row[1],row[2],row[3],row[4])==bool(row[7]),"Original equipment-priority comparator mismatch");}
}
}
int main(int argc,char** argv){try{
 check(argc==3,"Usage: menu-composite workspace original-cache.zip");const std::string root=argv[1],assets=root+"/port/android-native/app/src/main/assets",cache=root+"/.local-inputs/character-skill-session-v2/cache";Inputs raw((root+"/port/level-world/reference/character-game-design/real-cache-inputs.bin").c_str());CharacterGameDesign design;std::string error;check(design.initialize(raw.input,error),error);auto d=design.borrow();data::SkillTables skills;data::FaeryTables faeries;auto load=[&](auto& owner,const std::string& base){auto a=file(base+"_pyarray.bin"),b=file(base+"_pyarraynames.bin"),c=file(base+"_pystructnames.bin");check(owner.load(bytes(a),bytes(b),bytes(c),error),error);};load(skills,assets+"/data/skills");load(faeries,cache+"/data/pydata/faeries");auto sb=skills.borrow();auto cache_owner=script_assets(argv[2],skills.borrow());auto full_cache=cache_owner.borrow();check(full_cache.files().size()==219);
 inventory_order_gold(root);Debug debug_files;DebugFileServices24 files{&debug_files,Debug::open,Debug::close};auto* debug=dh2_character_debug_create();check(debug);std::unique_ptr<DebugSwitches,decltype(&dh2_character_debug_destroy)> debug_owner(debug,dh2_character_debug_destroy);auto* modules=dh2_fx_debug_modules_create(debug,&files);check(modules);std::unique_ptr<fx::DebugModules,decltype(&dh2_fx_debug_modules_destroy)> module_owner(modules,dh2_fx_debug_modules_destroy);fx::PreloadServices16 debug_services{modules,dh2_fx_debug_preload_service};Vitals vitals{&debug_services};sk::PlayerSkillInitServicesV3 init{&vitals,Vitals::invoke};
 skinning::VisualSkinResourcesV6 resources;check(resources.load(file(assets+"/models/prince_modular.bdae"),error),error);unsigned classes=0,stat_members=0,item_members=0,skill_members=0,training=0,actions=0,guards=0;
 for(const auto& name:{std::string("KnightPlayerBase"),std::string("MagePlayerBase"),std::string("RoguePlayerBase")}){
  auto at=std::find(d.characters()->names.begin(),d.characters()->names.end(),name);check(at!=d.characters()->names.end());const auto actor_index=std::int32_t(at-d.characters()->names.begin());auto unit=std::make_unique<Unit>();auto identity=std::uintptr_t(0xabcdef0200000000ULL+classes+1);unit->fsm_state.current=3;unit->fsm={&unit->fsm_state,identity,1,0};unit->event_owner={identity,identity+1,reinterpret_cast<std::uintptr_t>(&unit->fsm_state),identity+2,0,0,0,0};unit->ai_keys[0x90/4]=0x3d0ca0;unit->ais_keys[0x90/4]=0x3dcc80;unit->events={identity+3,&unit->event_owner,unit->ai_keys.data(),0,unit->ais_keys.data(),0,0,0,0,0,0};
  auto temp=std::make_shared<data::PropertySheet>();CharacterScriptSessionInputV3 in;in.identity=identity;in.name="Player";in.source_is_character=1;in.properties=std::make_shared<data::PropertyState>();in.combat=std::make_shared<data::CombatActorState>();in.temporary=temp;data::reset_properties(*d.rules(),*in.properties,&d.characters()->rows[actor_index]);check(data::recalc_properties_with_class(*d.classes(),*d.rules(),*in.properties,error),error);unit->saved=std::make_shared<data::PlayerSavegameV1>();unit->saved->set_character(identity);const auto list=in.properties->resolved[28]>=0&&std::size_t(in.properties->resolved[28])<sb.lists().size()?std::size_t(in.properties->resolved[28]):3;check(unit->saved->initialize_skills(sb.lists()[list],error),error);unit->saved->initialize_faeries();auto class_blob=section(name);std::size_t used;check(unit->saved->load_class(bytes(class_blob),d.characters()->names,used,error)&&unit->saved->class_id()==actor_index,error);auto player_name=section(name+" Audit");check(unit->saved->load_name(bytes(player_name),used,error),error);in.savegame=unit->saved;unit->scripts=full_cache;in.common=full_cache.common();in.cached_file_context=unit.get();in.cached_file=Unit::cached;
  auto player_init=init;player_init.gameplay.ai=&unit->events;unit->skill_owner={identity,0,0};player_init.gameplay.skill_owner=&unit->skill_owner;player_init.gameplay.difficulty_context=unit.get();player_init.gameplay.difficulty=Unit::selected;unit->player=sk::CharacterPlayerSkillsV3::create(design.borrow(),in,skills.borrow(),faeries.borrow(),debug_services,unit->fsm,player_init,error);check(bool(unit->player),error);
  MenuPlatform platform;platform.root=root;platform.assets=assets;platform.identity=identity;platform.debug=debug;platform.files=files;platform.design=design.borrow();platform.text.assets=assets;auto constants=file(assets+"/original-cache/data/pydata/common_text_pycst.bin");dh2_script_constants_reload receipt{};check(!dh2_script_constants_load(platform.text.constants,constants.data(),constants.size(),&receipt));HudTextEnvironmentV1 env{{&platform,MenuPlatform::text_open,MenuPlatform::text_close,MenuPlatform::text_debug,MenuPlatform::constant,nullptr,nullptr}};
  auto scene=resources.borrow().factory_scene();data::LootRandom8V2 random{1,0};PlayerEquipmentRenderInputsV1 gear_input;gear_input.design=design.borrow();gear_input.properties=in.properties;gear_input.random=&random;gear_input.character=identity;gear_input.potion_capacity=12;gear_input.language_pack=0;gear_input.resources=resources.borrow();gear_input.live_scene=&scene;gear_input.assets={&platform,MenuPlatform::asset};gear_input.debug=debug;gear_input.debug_files=files;gear_input.text_environment=env;gear_input.world={&platform,MenuPlatform::world};PlayerEquipmentRenderOwnerV1 gear(std::move(gear_input));check(gear.initialize(error),error);check(unit->player->initialize(1)==1,unit->player->error());check(gear.inventory()->properties()==unit->player->session().properties());
  HudTextV1 text_owner;auto a=file(assets+"/original-cache/data/pydata/common_text_pyarray.bin"),b=file(assets+"/original-cache/data/pydata/common_text_pyarraynames.bin"),c=file(assets+"/original-cache/data/pydata/common_text_pystructnames.bin");check(text_owner.load({a.data(),a.size()},{b.data(),b.size()},{c.data(),c.size()},error)&&text_owner.switch_pack(0,false,error),error);
  auto retained=std::make_shared<int>(1);CharacterMenuActionsGraphV1 ag;ag.owner=retained;ag.equipment=&gear;ag.skills=unit->player.get();ag.save=unit->saved.get();ag.skill_tables=skills.borrow();auto list_index=std::int32_t(list);ag.skill_list_index=&list_index;ag.save_binding=[&](auto& save,auto& player,auto&){return &save==in.savegame.get()&&player.identity()==unit->player.get();};ag.stats={in.properties.get(),gear.property_view(),d.characters(),d.class_rows()->data(),std::uint32_t(d.class_rows()->size()),actor_index};ag.stats.debug_load=[&](auto&){return dh2_character_debug_load(debug,&files)==1;};ag.stats.debug_query=[&](const char* key,bool& out,auto&){std::uint32_t value;if(dh2_character_debug_get(&value,debug,key,&files)!=1)return false;out=value!=0;return true;};
  // GearV1 constructs a non-const V4 owner. This narrow source-field provider
  // verifies the exact owned pointer and removes only its read-view const.
  auto* mutable_inventory=const_cast<data::FreshInventoryOwnedV4*>(gear.inventory());ag.potion_capacity_store=[&](std::uint8_t value,auto&){check(gear.inventory()==mutable_inventory&&mutable_inventory->properties()==in.properties);mutable_inventory->project_potion_capacity(std::int8_t(value));++platform.stores;return true;};std::vector<std::string> hud;ag.swap_hud=[&](const char* callback,auto&){hud.push_back(callback);return true;};CharacterMenuActionsOwnerV1 action_owner(ag);
  CharacterMenuQueriesGraphV1 qg;qg.owner=retained;qg.actions=&action_owner;qg.characters=d.characters();qg.text=&text_owner;qg.text_environment=env;qg.temporary=temp;qg.temporary_binding=[&](auto& player,const auto& sheet,auto&){return player.identity()==unit->player.get()&&sheet==in.temporary;};qg.player=[&](auto index,bool remote,auto& id,auto&){check(!remote);id=index==0?identity:0;return true;};qg.difficulty=[&](auto& tier,auto&){tier=unit->difficulty;return true;};qg.item_equippable=[&](const auto& item,bool& out,auto& e){auto* row=data::item(gear.inventory()->table(),item.id);return row&&character_menu_item_equippable_v1(row->record,in.properties->resolved,unit->saved->class_id(),*d.characters(),false,false,out,e);};character::PlayerFaeryAssociationV8 association(identity);
  auto source_globals=std::make_shared<loader::NativeGSLevelGlobalsV27>();
  unsigned visual_calls{},level_reads{};
  character::CharacterMenuFaeryServicesV8 faery;
  faery.owner=retained;faery.difficulty=[&](auto& tier,auto&){tier=unit->difficulty;return true;};
  faery.faery_character=[&](auto id,auto& actor,auto&){check(id==association.character);actor=association.faery420;return true;};
  faery.model_name=[&](auto,const char*&,auto& e){++visual_calls;e="declared missing positive faery visual owner";return false;};
  faery.current_level=[&](auto& id,auto& e){++level_reads;loader::CanonicalCurrentLevelBorrowV1 actual;
   if(!loader::borrow_current_canonical_level_v1(source_globals->borrow(source_globals),actual,e))return false;
   id=actual.identity();return true;
  };
  check(character::bind_character_menu_faery_v8(action_owner,qg,*unit->player,std::move(faery),error),error);
  CharacterMenuQueriesOwnerV1 queries(qg);ConnectedMenuASHostV2 as(queries,retained,assets+"/original-cache/data/menus");
  for(unsigned chosen=0;chosen<5;++chosen){
   auto choose=as.call({CharacterMenuValueV1::numeric(chosen),CharacterMenuValueV1::numeric(0)});
   check(as.dispatch("NativeHUDSetActiveFaery",choose,error),error);
   check(unit->saved->current_faery(unit->difficulty)==int(chosen)&&association.faery420==0&&visual_calls==0&&source_globals->s_level==nullptr,"same Save/update/null source association and GS branch");
  }
  check(level_reads==5,"source current-Level query count with genuine NULL");
  association.faery420=identity+0x700; // Explicit positive visual failure fixture.
  auto failed_choose=as.call({CharacterMenuValueV1::numeric(0),CharacterMenuValueV1::numeric(0)});
  check(!as.dispatch("NativeHUDSetActiveFaery",failed_choose,error)&&error.find("missing positive faery visual")!=std::string::npos,"required positive faery receiver failure");
  check(unit->saved->current_faery(unit->difficulty)==0&&visual_calls==1&&level_reads==5,"source store/update prefix retained before failed visual and outer Level tail");
  association.faery420=0;error.clear();
  auto stats=as.call({CharacterMenuValueV1::reference(as.object),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeGetPlayerStats",stats,error),error);check(as.members.size()==69&&as.member("Name").text==unit->saved->name()&&as.member("Level").number==(in.properties->resolved[19]>>8));stat_members+=69;
  for(auto pair:std::vector<std::pair<const char*,const char*>>{{"NativeInvGetHasOffHandWeapon","HasOffHandWeapon"},{"NativeInvGetHasTwoHandedWeapon","IsWeaponTwoHanded"}}){auto present=as.call({CharacterMenuValueV1::numeric(0)});check(as.dispatch(pair.first,present,error),error);check(present.result.kind==1&&present.result.boolean==as.member(pair.second).boolean);auto absent=as.call({CharacterMenuValueV1::numeric(9)});check(as.dispatch(pair.first,absent,error)&&absent.result.kind==1&&!absent.result.boolean);++guards;}
  as.members.clear();CharacterMenuFontPaletteV1 palette;auto font_rows=file(root+"/.local-inputs/character-menu-native-v1-fonts/fonts_pyarray.bin"),font_schema=file(root+"/.local-inputs/character-menu-native-v1-fonts/fonts_pystructnames.bin");check(palette.load({font_rows.data(),font_rows.size()},{font_schema.data(),font_schema.size()},error),error);auto palette_graph=qg;palette_graph.font_palette=&palette;CharacterMenuQueriesOwnerV1 inventory_queries(palette_graph);auto equipped_item=as.call({CharacterMenuValueV1::numeric(1),CharacterMenuValueV1::reference(as.object),CharacterMenuValueV1::numeric(0)});check(as.dispatch(inventory_queries,"NativeInvGetEquipedItem",equipped_item,error),error);check(equipped_item.result.kind==1&&equipped_item.result.boolean&&as.members.size()==3&&as.member("ItemName").text.find("<font color='#")==0);item_members+=3;as.members.clear();
  for(unsigned slot=0;slot<=9;++slot){ConnectedMenuListHostV2 list_host(as);auto call=list_host.call(slot);check(as.dispatch(inventory_queries,"NativeInvGetItemsListForSlot",call,error),error);list_host.observe();check(call.result.kind==5&&call.result.object==list_host.array&&list_host.elements[0].number==99);for(std::size_t j=1;j<list_host.elements.size();++j){auto& row=list_host.rows.at(list_host.elements[j].object);check(row.size()==6);const char* keys[]{"ItemName","ItemIndex","ItemEquippable","ItemEquipped","ItemEquippedOtherHand","ItemQuantity"};for(unsigned k=0;k<6;++k)check(row[k].first==keys[k]);auto index=std::uint32_t(row[1].second.number);check(index<gear.inventory()->items().size()&&row[0].second.text.find(gear.inventory()->items()[index]->item->name)!=std::string::npos);check(row[5].second.text==(slot==9?std::to_string(gear.inventory()->items()[index]->item->signed_quantity()):" "));item_members+=6;}}
  auto automatic=as.call({CharacterMenuValueV1::numeric(1),CharacterMenuValueV1::numeric(0)});check(as.dispatch(inventory_queries,"NativeInvAutoEquipSlot",automatic,error),error);auto automatic_all=as.call({CharacterMenuValueV1::numeric(-1),CharacterMenuValueV1::numeric(0)});check(as.dispatch(inventory_queries,"NativeInvAutoEquipSlot",automatic_all,error),error);check(gear.inventory()->equipment()[gear.inventory()->current_equipment()][1]);actions+=2;
  auto missing_requirements=palette_graph;missing_requirements.item_equippable={};CharacterMenuQueriesOwnerV1 missing_slot(missing_requirements);check(!as.dispatch(missing_slot,"NativeInvAutoEquipSlot",automatic,error)&&!gear.inventory()->equipment()[gear.inventory()->current_equipment()][1]);++guards;check(as.dispatch(inventory_queries,"NativeInvAutoEquipSlot",automatic,error),error);
  auto unlocked=as.call({CharacterMenuValueV1::numeric(0),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeHUDGetIsFaeryUnlocked",unlocked,error)&&unlocked.result.kind==1&&!unlocked.result.boolean,error);check(unit->saved->set_faery_state(0,1,unit->difficulty,error));check(as.dispatch("NativeHUDGetIsFaeryUnlocked",unlocked,error)&&unlocked.result.boolean,error);
  for(unsigned j=0;j<gear.inventory()->items().size();++j){check(gear.inventory()->items()[j]->item->powers.empty());auto item=as.call({CharacterMenuValueV1::numeric(j),CharacterMenuValueV1::reference(as.object),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeInvGetItemDetails",item,error),error);check(as.members.size()==14&&as.member("ItemValue").number==gear.inventory()->items()[j]->item->value&&as.member("ItemStatsDesc").text==gear.inventory()->items()[j]->item->description);item_members+=14;as.members.clear();}
  auto passive=classes==0?"prince_warrior_hardiness":classes==1?"prince_mage_staffmaster":"prince_rogue_acrobat";auto& rows=unit->player->state().skills;auto selected=std::find_if(rows.items,rows.items+rows.count,[&](auto* row){return row&&!std::strcmp(row->script,passive);});check(selected!=rows.items+rows.count,"Actual passive row");auto skill_index=std::uint32_t(selected-rows.items);const auto& training_row=sb.skills()[sb.lists()[list][skill_index]];
  // Source-native progression input reaches the actual authored availability
  // boundary; neither a skill row nor menu display value is synthesized.
  check(!dh2_property_set_int(&unit->player->session().property_view(),19,std::max(1,std::int32_t(training_row.scalar.words[8]))));check(!dh2_property_set_int(&unit->player->session().property_view(),157,3));std::int32_t refreshed_points;check(!dh2_property_resolve(&unit->player->session().property_view(),157,&refreshed_points));auto saved_points=in.properties->saved[157];auto train=as.call({CharacterMenuValueV1::numeric(skill_index),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeSkillsTrainSkill",train,error),error);check(unit->saved->skill_level(skill_index)==1&&in.properties->saved[157]==saved_points-256&&train.result.number==(in.properties->resolved[157]>>8)&&platform.stores==1,"Training level="+std::to_string(unit->saved->skill_level(skill_index))+" points="+std::to_string(train.result.number)+" stores="+std::to_string(platform.stores));++training;
  auto detail=as.call({CharacterMenuValueV1::numeric(skill_index),CharacterMenuValueV1::reference(as.object),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeGetSkillDetails",detail,error),error);check(as.members.size()==9&&as.member("SkillLevel").number==1&&!as.member("SkillName").text.empty()&&!as.member("SkillCurrLevel").text.empty());skill_members+=9;as.members.clear();
  auto available=std::find_if(sb.lists()[list].begin(),sb.lists()[list].end(),[&](auto id){auto& s=sb.skills()[id];return s.scalar.words[18]!=UINT32_MAX&&std::int32_t(s.scalar.words[8])<=(in.properties->resolved[19]>>8);});check(available!=sb.lists()[list].end());auto active=std::uint32_t(available-sb.lists()[list].begin());check(unit->saved->set_skill_level(active,1,error));auto equip_skill=as.call({CharacterMenuValueV1::numeric(0),CharacterMenuValueV1::numeric(active),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeEquipSkill",equip_skill,error)&&unit->saved->skill_in_slot(0)==std::int32_t(active),error);++actions;
  auto equipped=as.call({CharacterMenuValueV1::reference(as.array),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeSkillGetEquipedSkillsIDs",equipped,error),error);check(as.elements.size()==4&&as.elements[0].number==99&&as.elements[1].number==active&&equipped.result.boolean);++actions;
  check(!dh2_property_set_int(&unit->player->session().property_view(),148,1));auto before=in.properties->saved[149];auto stat=as.call({CharacterMenuValueV1::numeric(0),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeStatsAssignPoint",stat,error),error);check(in.properties->saved[149]==before+256);++actions;
  const auto* main_cell=gear.inventory()->equipment()[gear.inventory()->current_equipment()][1];check(main_cell);auto cell=std::find_if(gear.inventory()->items().begin(),gear.inventory()->items().end(),[&](auto& p){return p.get()==main_cell;});check(cell!=gear.inventory()->items().end());auto index=std::uint32_t(cell-gear.inventory()->items().begin());auto unequip=as.call({CharacterMenuValueV1::numeric(1),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeInvUnequipItem",unequip,error),error);auto equip=as.call({CharacterMenuValueV1::numeric(1),CharacterMenuValueV1::numeric(index),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeInvEquipItem",equip,error),error);actions+=2;
  auto swap=as.call({CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeSwapEquipment",swap,error)&&as.dispatch("NativeSwapEquipment",swap,error),error);check(hud==std::vector<std::string>{"DisplayRightHud","FillActionIcon","DisplayRightHud","FillActionIcon"});actions+=2;
  auto bad=qg;bad.temporary_binding={};CharacterMenuQueriesOwnerV1 missing(bad);check(!as.dispatch(missing,"NativeGetSkillDetails",detail,error));++guards;auto absent=as.call({CharacterMenuValueV1::reference(as.object),CharacterMenuValueV1::numeric(9)});check(as.dispatch("NativeGetPlayerStats",absent,error)&&as.members.empty());++guards;
  check(gear.inventory()==mutable_inventory&&gear.properties()==unit->player->session().properties()&&platform.text.opens==platform.text.closes);
  data::CharacterMenuInventoryMutationV1 mutation(*mutable_inventory);
  struct RemovalProbe {data::CharacterMenuInventoryMutationV1* mutation;unsigned calls{};bool rejected{};};
  RemovalProbe probe{&mutation};data::OwnedInventoryServicesV4 removal_services;
  removal_services.context=&probe;removal_services.observe_storage=[](void* context,auto& owner,const auto& request){auto& p=*static_cast<RemovalProbe*>(context);check(&owner==&p.mutation->inventory());check(request.operation==data::OwnedInventoryOperationV4::destroy_item&&request.source_caller==0x3fe558);++p.calls;std::string nested;data::OwnedInventoryServicesV4 none;p.rejected=!p.mutation->remove(0,none,nested)&&nested.find("reentry")!=std::string::npos;};
  auto removal_count=mutable_inventory->items().size();auto* removed=mutable_inventory->items()[index]->item.get();check(removed->signed_quantity()==1);
  check(mutation.remove(index,removal_services,error),error);check(probe.calls==1&&probe.rejected&&mutable_inventory->items().size()+1==removal_count);
  for(const auto& set:mutable_inventory->equipment())for(auto* entry:set)check(entry!=main_cell);check(mutable_inventory->potion()!=removed);
  ++classes;
 }
 std::cout<<"{\"validation\":\"PASS\",\"same_graph_classes\":"<<classes<<",\"stat_members\":"<<stat_members<<",\"actual_item_members\":"<<item_members<<",\"actual_skill_members\":"<<skill_members<<",\"whole_training_transactions\":"<<training<<",\"same_graph_actions\":"<<actions<<",\"required_provider_guards\":"<<guards<<",\"complete_original_scripts\":219,\"real_retained_AS_transport\":true,\"actual_AS_inventory_lists\":true,\"authored_character_menu_flow\":false,\"startup_GPU_offline_world_and_positive_faery_visual_boundary_fixtures\":true}\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}

#undef CharacterPlayerSkillsV3
