// Snapshot of character_menu_composite_v1.cpp; replaces only the AS fixture.
// Reuse source-cache/test loaders without modifying the frozen V3 test.
#define main frozen_player_skills_audit_main
#include "../../level-world/tests/character_player_skills_v3.cpp"
#undef main
#include "../character_menu_queries_owner_v1.hpp"
#include <filesystem>
#include <cctype>
#include "character_menu_connected_as_host_v1.hpp"
using namespace dh2::ui;using namespace dh2::player;
namespace {
struct MenuPlatform {
 std::string root,assets;TextFiles text;DebugSwitches* debug{};DebugFileServices24 files{};
 CharacterGameDesign::Borrow design;std::uintptr_t identity{};unsigned world_calls{},stores{};
 static skinning::VisualAssetResultV6 asset(void* p,const char* path,Raw& out,std::string&){auto& c=*static_cast<MenuPlatform*>(p);std::string uri=path,full;if(uri.find("data/pydata/loot_table_")==0)full=c.root+"/.local-inputs/items-discovery/"+uri.substr(12);else if(uri.find("data/pydata/item_powers_")==0)full=c.root+"/.local-inputs/player-item-effects-v5/power-cache/"+uri.substr(12);else if(uri.find("data/3d/characters/prince/weapons/")==0){auto name=uri.substr(uri.find_last_of('/')+1);for(auto& x:name)x=char(std::tolower(static_cast<unsigned char>(x)));full=c.root+"/.local-inputs/visual-skin-owner-v6/weapons/"+name;}else full=c.assets+"/original-cache/"+uri;if(!std::filesystem::exists(full))return skinning::VisualAssetResultV6::missing;out=file(full);return skinning::VisualAssetResultV6::found;}
 static bool world(void* p,EquipmentWorldQueryV1 q,std::uintptr_t subject,std::uintptr_t& id,std::int32_t& scalar,std::string&){auto& c=*static_cast<MenuPlatform*>(p);check(subject==c.identity);++c.world_calls;id=0;scalar=0;if(q==EquipmentWorldQueryV1::current_player)id=subject;if(q==EquipmentWorldQueryV1::player_count)scalar=1;return true;}
 static bool constant(void* p,const char* group,const char* key,std::uint32_t& out,std::string&){auto& c=*static_cast<MenuPlatform*>(p);if(!std::strcmp(group,"StrID"))return TextFiles::constant(&c.text,group,key,out,c.error);std::int32_t v;auto* bindings=c.design.design();if(!bindings->lookup||bindings->lookup(bindings->context,0,group,key,&v))return false;std::memcpy(&out,&v,4);return true;}
 static bool text_open(void* p,const char* name,bool& found,Raw& out,std::uintptr_t& lease,std::string& e){return TextFiles::open(&static_cast<MenuPlatform*>(p)->text,name,found,out,lease,e);}
 static bool text_close(void* p,std::uintptr_t lease,std::string& e){return TextFiles::close(&static_cast<MenuPlatform*>(p)->text,lease,e);}
 static bool text_debug(void* p,const char* key,std::string&){auto& c=*static_cast<MenuPlatform*>(p);std::uint32_t v;return dh2_character_debug_get(&v,c.debug,key,&c.files)==1;}
 std::string error;
};
Raw section(const std::string& text){Raw out(4);auto n=std::uint32_t(text.size()+1);std::memcpy(out.data(),&n,4);out.insert(out.end(),text.begin(),text.end());out.push_back(0);return out;}

}
int main(int argc,char** argv){try{
 check(argc==3,"Usage: menu-composite workspace original-cache.zip");const std::string root=argv[1],assets=root+"/port/android-native/app/src/main/assets",cache=root+"/.local-inputs/character-skill-session-v2/cache";Inputs raw((root+"/port/level-world/reference/character-game-design/real-cache-inputs.bin").c_str());CharacterGameDesign design;std::string error;check(design.initialize(raw.input,error),error);auto d=design.borrow();data::SkillTables skills;data::FaeryTables faeries;auto load=[&](auto& owner,const std::string& base){auto a=file(base+"_pyarray.bin"),b=file(base+"_pyarraynames.bin"),c=file(base+"_pystructnames.bin");check(owner.load(bytes(a),bytes(b),bytes(c),error),error);};load(skills,assets+"/data/skills");load(faeries,cache+"/data/pydata/faeries");auto sb=skills.borrow();auto cache_owner=script_assets(argv[2],skills.borrow());auto full_cache=cache_owner.borrow();check(full_cache.files().size()==219);
 Debug debug_files;DebugFileServices24 files{&debug_files,Debug::open,Debug::close};auto* debug=dh2_character_debug_create();check(debug);std::unique_ptr<DebugSwitches,decltype(&dh2_character_debug_destroy)> debug_owner(debug,dh2_character_debug_destroy);auto* modules=dh2_fx_debug_modules_create(debug,&files);check(modules);std::unique_ptr<fx::DebugModules,decltype(&dh2_fx_debug_modules_destroy)> module_owner(modules,dh2_fx_debug_modules_destroy);fx::PreloadServices16 debug_services{modules,dh2_fx_debug_preload_service};Vitals vitals{&debug_services};sk::PlayerSkillInitServicesV3 init{&vitals,Vitals::invoke};
 skinning::VisualSkinResourcesV6 resources;check(resources.load(file(assets+"/models/prince_modular.bdae"),error),error);unsigned classes=0,stat_members=0,item_members=0,skill_members=0,training=0,actions=0,guards=0;
 for(const auto& name:{std::string("KnightPlayerBase"),std::string("MagePlayerBase"),std::string("RoguePlayerBase")}){
  auto at=std::find(d.characters()->names.begin(),d.characters()->names.end(),name);check(at!=d.characters()->names.end());const auto actor_index=std::int32_t(at-d.characters()->names.begin());auto unit=std::make_unique<Unit>();auto identity=std::uintptr_t(0xabcdef0200000000ULL+classes+1);unit->fsm_state.current=3;unit->fsm={&unit->fsm_state,identity,1,0};unit->event_owner={identity,identity+1,reinterpret_cast<std::uintptr_t>(&unit->fsm_state),identity+2,0,0,0,0};unit->ai_keys[0x90/4]=0x3d0ca0;unit->ais_keys[0x90/4]=0x3dcc80;unit->events={identity+3,&unit->event_owner,unit->ai_keys.data(),0,unit->ais_keys.data(),0,0,0,0,0,0};
  auto temp=std::make_shared<data::PropertySheet>();CharacterScriptSessionInputV3 in;in.identity=identity;in.name="Player";in.source_is_character=1;in.properties=std::make_shared<data::PropertyState>();in.combat=std::make_shared<data::CombatActorState>();in.temporary=temp;data::reset_properties(*d.rules(),*in.properties,&d.characters()->rows[actor_index]);check(data::recalc_properties_with_class(*d.classes(),*d.rules(),*in.properties,error),error);unit->saved=std::make_shared<data::PlayerSavegameV1>();unit->saved->set_character(identity);const auto list=in.properties->resolved[28]>=0&&std::size_t(in.properties->resolved[28])<sb.lists().size()?std::size_t(in.properties->resolved[28]):3;check(unit->saved->initialize_skills(sb.lists()[list],error),error);unit->saved->initialize_faeries();auto class_blob=section(name);std::size_t used;check(unit->saved->load_class(bytes(class_blob),d.characters()->names,used,error)&&unit->saved->class_id()==actor_index,error);auto player_name=section(name+" Audit");check(unit->saved->load_name(bytes(player_name),used,error),error);in.savegame=unit->saved;unit->scripts=full_cache;in.common=full_cache.common();in.cached_file_context=unit.get();in.cached_file=Unit::cached;
  auto player_init=init;player_init.gameplay.ai=&unit->events;unit->skill_owner={identity,0,0};player_init.gameplay.skill_owner=&unit->skill_owner;player_init.gameplay.difficulty_context=unit.get();player_init.gameplay.difficulty=Unit::selected;unit->player=sk::CharacterPlayerSkillsV3::create(design.borrow(),in,skills.borrow(),faeries.borrow(),debug_services,unit->fsm,player_init,error);check(bool(unit->player),error);
  MenuPlatform platform;platform.root=root;platform.assets=assets;platform.identity=identity;platform.debug=debug;platform.files=files;platform.design=design.borrow();platform.text.assets=assets;auto constants=file(assets+"/original-cache/data/pydata/common_text_pycst.bin");dh2_script_constants_reload receipt{};check(!dh2_script_constants_load(platform.text.constants,constants.data(),constants.size(),&receipt));HudTextEnvironmentV1 env{{&platform,MenuPlatform::text_open,MenuPlatform::text_close,MenuPlatform::text_debug,MenuPlatform::constant,nullptr,nullptr}};
  auto scene=resources.borrow().factory_scene();data::LootRandom8V2 random{1,0};PlayerEquipmentRenderInputsV1 gear_input;gear_input.design=design.borrow();gear_input.properties=in.properties;gear_input.random=&random;gear_input.character=identity;gear_input.potion_capacity=12;gear_input.language_pack=0;gear_input.resources=resources.borrow();gear_input.live_scene=&scene;gear_input.assets={&platform,MenuPlatform::asset};gear_input.debug=debug;gear_input.debug_files=files;gear_input.text_environment=env;gear_input.world={&platform,MenuPlatform::world};PlayerEquipmentRenderOwnerV1 gear(std::move(gear_input));check(gear.initialize(error),error);check(unit->player->initialize(1)==1,unit->player->error());check(gear.inventory()->properties()==unit->player->session().properties());
  HudTextV1 text_owner;auto a=file(assets+"/original-cache/data/pydata/common_text_pyarray.bin"),b=file(assets+"/original-cache/data/pydata/common_text_pyarraynames.bin"),c=file(assets+"/original-cache/data/pydata/common_text_pystructnames.bin");check(text_owner.load({a.data(),a.size()},{b.data(),b.size()},{c.data(),c.size()},error)&&text_owner.switch_pack(0,false,error),error);
  auto retained=std::make_shared<int>(1);CharacterMenuActionsGraphV1 ag;ag.owner=retained;ag.equipment=&gear;ag.skills=unit->player.get();ag.save=unit->saved.get();ag.skill_tables=skills.borrow();auto list_index=std::int32_t(list);ag.skill_list_index=&list_index;ag.save_binding=[&](auto& save,auto& player,auto&){return &save==in.savegame.get()&&player.identity()==unit->player.get();};ag.stats={in.properties.get(),gear.property_view(),d.characters(),d.class_rows()->data(),std::uint32_t(d.class_rows()->size()),actor_index};ag.stats.debug_load=[&](auto&){return dh2_character_debug_load(debug,&files)==1;};ag.stats.debug_query=[&](const char* key,bool& out,auto&){std::uint32_t value;if(dh2_character_debug_get(&value,debug,key,&files)!=1)return false;out=value!=0;return true;};
  // GearV1 constructs a non-const V4 owner. This narrow source-field provider
  // verifies the exact owned pointer and removes only its read-view const.
  auto* mutable_inventory=const_cast<data::FreshInventoryOwnedV4*>(gear.inventory());ag.potion_capacity_store=[&](std::uint8_t value,auto&){check(gear.inventory()==mutable_inventory&&mutable_inventory->properties()==in.properties);mutable_inventory->project_potion_capacity(std::int8_t(value));++platform.stores;return true;};std::vector<std::string> hud;ag.swap_hud=[&](const char* callback,auto&){hud.push_back(callback);return true;};CharacterMenuActionsOwnerV1 action_owner(ag);
  CharacterMenuQueriesGraphV1 qg;qg.owner=retained;qg.actions=&action_owner;qg.characters=d.characters();qg.text=&text_owner;qg.text_environment=env;qg.temporary=temp;qg.temporary_binding=[&](auto& player,const auto& sheet,auto&){return player.identity()==unit->player.get()&&sheet==in.temporary;};qg.player=[&](auto index,bool remote,auto& id,auto&){check(!remote);id=index==0?identity:0;return true;};qg.difficulty=[&](auto& tier,auto&){tier=unit->difficulty;return true;};qg.item_equippable=[&](const auto& item,bool& out,auto& e){auto* row=data::item(gear.inventory()->table(),item.id);return row&&character_menu_item_equippable_v1(row->record,in.properties->resolved,unit->saved->class_id(),*d.characters(),false,false,out,e);};CharacterMenuQueriesOwnerV1 queries(qg);ConnectedMenuASHostV1 as(queries,retained,assets+"/original-cache/data/menus");
  auto stats=as.call({CharacterMenuValueV1::reference(as.object),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeGetPlayerStats",stats,error),error);check(as.members.size()==69&&as.member("Name").text==unit->saved->name()&&as.member("Level").number==(in.properties->resolved[19]>>8));stat_members+=69;
  for(auto pair:std::vector<std::pair<const char*,const char*>>{{"NativeInvGetHasOffHandWeapon","HasOffHandWeapon"},{"NativeInvGetHasTwoHandedWeapon","IsWeaponTwoHanded"}}){auto present=as.call({CharacterMenuValueV1::numeric(0)});check(as.dispatch(pair.first,present,error),error);check(present.result.kind==1&&present.result.boolean==as.member(pair.second).boolean);auto absent=as.call({CharacterMenuValueV1::numeric(9)});check(as.dispatch(pair.first,absent,error)&&absent.result.kind==1&&!absent.result.boolean);++guards;}
  as.members.clear();CharacterMenuFontPaletteV1 palette;auto font_rows=file(root+"/.local-inputs/character-menu-native-v1-fonts/fonts_pyarray.bin"),font_schema=file(root+"/.local-inputs/character-menu-native-v1-fonts/fonts_pystructnames.bin");check(palette.load({font_rows.data(),font_rows.size()},{font_schema.data(),font_schema.size()},error),error);auto palette_graph=qg;palette_graph.font_palette=&palette;CharacterMenuQueriesOwnerV1 inventory_queries(palette_graph);auto equipped_item=as.call({CharacterMenuValueV1::numeric(1),CharacterMenuValueV1::reference(as.object),CharacterMenuValueV1::numeric(0)});check(as.dispatch(inventory_queries,"NativeInvGetEquipedItem",equipped_item,error),error);check(equipped_item.result.kind==1&&equipped_item.result.boolean&&as.members.size()==3&&as.member("ItemName").text.find("<font color='#")==0);item_members+=3;as.members.clear();
  for(unsigned j=0;j<gear.inventory()->items().size();++j){check(gear.inventory()->items()[j]->item->powers.empty());auto item=as.call({CharacterMenuValueV1::numeric(j),CharacterMenuValueV1::reference(as.object),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeInvGetItemDetails",item,error),error);check(as.members.size()==14&&as.member("ItemValue").number==gear.inventory()->items()[j]->item->value&&as.member("ItemStatsDesc").text==gear.inventory()->items()[j]->item->description);item_members+=14;as.members.clear();}
  auto passive=classes==0?"prince_warrior_hardiness":classes==1?"prince_mage_staffmaster":"prince_rogue_acrobat";auto& rows=unit->player->state().skills;auto selected=std::find_if(rows.items,rows.items+rows.count,[&](auto* row){return row&&!std::strcmp(row->script,passive);});check(selected!=rows.items+rows.count,"Actual passive row");auto skill_index=std::uint32_t(selected-rows.items);const auto& training_row=sb.skills()[sb.lists()[list][skill_index]];
  // Source-native progression input reaches the actual authored availability
  // boundary; neither a skill row nor menu display value is synthesized.
  check(!dh2_property_set_int(&unit->player->session().property_view(),19,std::max(1,std::int32_t(training_row.scalar.words[8]))));check(!dh2_property_set_int(&unit->player->session().property_view(),157,3));std::int32_t refreshed_points;check(!dh2_property_resolve(&unit->player->session().property_view(),157,&refreshed_points));auto saved_points=in.properties->saved[157];auto train=as.call({CharacterMenuValueV1::numeric(skill_index),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeSkillsTrainSkill",train,error),error);check(unit->saved->skill_level(skill_index)==1&&in.properties->saved[157]==saved_points-256&&train.result.number==(in.properties->resolved[157]>>8)&&platform.stores==1,"Training level="+std::to_string(unit->saved->skill_level(skill_index))+" points="+std::to_string(train.result.number)+" stores="+std::to_string(platform.stores));++training;
  auto detail=as.call({CharacterMenuValueV1::numeric(skill_index),CharacterMenuValueV1::reference(as.object),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeGetSkillDetails",detail,error),error);check(as.members.size()==9&&as.member("SkillLevel").number==1&&!as.member("SkillName").text.empty()&&!as.member("SkillCurrLevel").text.empty());skill_members+=9;as.members.clear();
  auto available=std::find_if(sb.lists()[list].begin(),sb.lists()[list].end(),[&](auto id){auto& s=sb.skills()[id];return s.scalar.words[18]!=UINT32_MAX&&std::int32_t(s.scalar.words[8])<=(in.properties->resolved[19]>>8);});check(available!=sb.lists()[list].end());auto active=std::uint32_t(available-sb.lists()[list].begin());check(unit->saved->set_skill_level(active,1,error));auto equip_skill=as.call({CharacterMenuValueV1::numeric(0),CharacterMenuValueV1::numeric(active),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeEquipSkill",equip_skill,error)&&unit->saved->skill_in_slot(0)==std::int32_t(active),error);++actions;
  auto equipped=as.call({CharacterMenuValueV1::reference(as.array),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeSkillGetEquipedSkillsIDs",equipped,error),error);check(as.elements.size()==4&&as.elements[0].number==99&&as.elements[1].number==active&&equipped.result.boolean);++actions;
  check(!dh2_property_set_int(&unit->player->session().property_view(),148,1));auto before=in.properties->saved[149];auto stat=as.call({CharacterMenuValueV1::numeric(0),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeStatsAssignPoint",stat,error),error);check(in.properties->saved[149]==before+256);++actions;
  const auto* main_cell=gear.inventory()->equipment()[gear.inventory()->current_equipment()][1];check(main_cell);auto cell=std::find_if(gear.inventory()->items().begin(),gear.inventory()->items().end(),[&](auto& p){return p.get()==main_cell;});check(cell!=gear.inventory()->items().end());auto index=std::uint32_t(cell-gear.inventory()->items().begin());auto unequip=as.call({CharacterMenuValueV1::numeric(1),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeInvUnequipItem",unequip,error),error);auto equip=as.call({CharacterMenuValueV1::numeric(1),CharacterMenuValueV1::numeric(index),CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeInvEquipItem",equip,error),error);actions+=2;
  auto swap=as.call({CharacterMenuValueV1::numeric(0)});check(as.dispatch("NativeSwapEquipment",swap,error)&&as.dispatch("NativeSwapEquipment",swap,error),error);check(hud==std::vector<std::string>{"DisplayRightHud","FillActionIcon","DisplayRightHud","FillActionIcon"});actions+=2;
  auto bad=qg;bad.temporary_binding={};CharacterMenuQueriesOwnerV1 missing(bad);check(!missing.dispatch("NativeGetSkillDetails",detail,error));++guards;auto absent=as.call({CharacterMenuValueV1::reference(as.object),CharacterMenuValueV1::numeric(9)});check(as.dispatch("NativeGetPlayerStats",absent,error)&&as.members.empty());++guards;
  check(gear.inventory()==mutable_inventory&&gear.properties()==unit->player->session().properties()&&platform.text.opens==platform.text.closes);++classes;
 }
 std::cout<<"{\"validation\":\"PASS\",\"same_graph_classes\":"<<classes<<",\"stat_members\":"<<stat_members<<",\"actual_item_members\":"<<item_members<<",\"actual_skill_members\":"<<skill_members<<",\"whole_training_transactions\":"<<training<<",\"same_graph_actions\":"<<actions<<",\"required_provider_guards\":"<<guards<<",\"complete_original_scripts\":219,\"real_retained_AS_transport\":true,\"authored_character_menu_flow\":false,\"startup_GPU_and_offline_world_boundary_fixtures\":true}\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
