"""Actual retained HUD core connection with audit-only scoped clip visitor.
Frozen facade/vendor remain untouched. The private visitor adds no scheduling,
tag, draw or lifetime policy; production facade wiring remains parent-owned.
"""
import argparse,hashlib,json,struct,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument('--core-library',default='/home/adampalace/dh2-gameswf-asan/libgameswf_core.a');p.add_argument('--build-dir',default='/home/adampalace/dh2-hud-core-audit');p.add_argument('--output',type=Path,default=ROOT/'port/engine-ui/reports/hud-sprite-core-owner-host-audit.json');a=p.parse_args();scratch=ROOT/'.local-inputs/hud-sprite-timeline/core-audit';scratch.mkdir(parents=True,exist_ok=True);ui=ROOT/'port/engine-ui';paths=[ui/'swf_movie.hpp',ui/'swf_movie.cpp',ui/'swf_viewport_connection.hpp',ui/'swf_viewport_connection.cpp',ui/'viewport.hpp',ui/'viewport.cpp',ui/'hud_player_values.hpp',ui/'hud_player_values.cpp',ui/'hud_sprite_timeline.hpp',ui/'hud_sprite_timeline.cpp',ui/'hud_sprite_core.hpp',ui/'hud_sprite_core.cpp',ui/'hud_advance_owner.hpp',ui/'hud_advance_owner.cpp',ui/'tests/hud_sprite_core.cpp'];before={str(x.relative_to(ROOT)).replace('\\','/'):sha(x) for x in paths}
 header=(ui/'swf_movie.hpp').read_text().replace('namespace gameswf { struct font;','namespace gameswf { struct character; struct font;');decl=' bool audit_visit_clip(const char*,void*,int(*)(void*,gameswf::character*,std::string&),std::string&);\n';header=header.replace(' const std::vector<std::string>& diagnostics() const;',decl+' const std::vector<std::string>& diagnostics() const;');(scratch/'swf_movie.hpp').write_text(header)
 addition='\nnamespace dh2::ui { bool SwfMovie::audit_visit_clip(const char* path,void*ctx,int(*visit)(void*,gameswf::character*,std::string&),std::string&e){Impl::Scope scope(impl_.get());if(!scope.entered){e="SWF core busy";return false;}auto*c=impl_->find(path);if(!c||!visit){e="Audit clip missing";return false;}if(visit(ctx,c,e)<0)return false;return impl_->finish(e);} }\n';(scratch/'swf_movie.cpp').write_text((ui/'swf_movie.cpp').read_text()+addition)
 tree=ROOT/'.local-inputs/ui-layout-discovery/dqhud_droid-tree.json';rows=json.loads(tree.read_text());records=[]
 for cid,count in ((90,100),(147,100),(152,101)):
  clip=next(x for x in rows if x.get('id')==cid);placements={x['frame']:x['matrix_twips'] for x in clip['children'] if x['tag']==26 and x.get('placement_depth')==3 and 'matrix_twips'in x}
  for frame in list(range(count))+list(range(count-1,-1,-1)):
   m=placements[frame];records.append(struct.pack('<2I6f',cid,frame,m[0],m[2],m[4],m[1],m[3],m[5]))
 samples=scratch/'authored-matrices.bin';samples.write_bytes(struct.pack('<2I',0x31505348,len(records))+b''.join(records))
 def wslpath(x):return '/mnt/c/'+str(x)[3:].replace('\\','/')
 def run(args):
  q=subprocess.run(args,capture_output=True,text=True);assert q.returncode==0,(q.args,q.stdout,q.stderr);return q.stdout.strip()
 core_before=run(['wsl','-e','sha256sum',a.core_library]).split()[0];run(['wsl','-e','mkdir','-p',a.build_dir]);exe=a.build_dir+'/hud_sprite_core_audit';repo=wslpath(ROOT);work=wslpath(scratch);command=['wsl','-e','g++','-std=c++17','-O1','-g','-fPIC','-fpermissive','-fsanitize=address,undefined','-fno-sanitize=vptr','-fno-omit-frame-pointer','-I'+work,'-I'+repo+'/port/engine-ui','-isystem',repo+'/port/engine-ui/vendor/gameswf1714','-DTU_CONFIG_LINK_TO_JPEGLIB=0','-DTU_CONFIG_LINK_TO_LIBPNG=0','-DTU_CONFIG_LINK_TO_FREETYPE=0','-DTU_CONFIG_LINK_TO_THREAD=0',work+'/swf_movie.cpp',repo+'/port/engine-ui/swf_viewport_connection.cpp',repo+'/port/engine-ui/viewport.cpp',repo+'/port/engine-ui/hud_player_values.cpp',repo+'/port/engine-ui/hud_sprite_timeline.cpp',repo+'/port/engine-ui/hud_sprite_core.cpp',repo+'/port/engine-ui/hud_advance_owner.cpp',repo+'/port/engine-ui/tests/hud_sprite_core.cpp',a.core_library,'-lz','-ldl','-o',exe];run(command);result=json.loads(run(['wsl','-e','env','ASAN_OPTIONS=detect_leaks=1:halt_on_error=1','UBSAN_OPTIONS=halt_on_error=1',exe,repo+'/.local-inputs/ui-layout-discovery',wslpath(samples)]));assert before=={str(x.relative_to(ROOT)).replace('\\','/'):sha(x) for x in paths};assert core_before==run(['wsl','-e','sha256sum',a.core_library]).split()[0]
 report=dict(validation='PASS',**{k:v for k,v in result.items() if k!='validation'},source_sha256=before,core_library_sha256=core_before,executable_sha256=run(['wsl','-e','sha256sum',exe]).split()[0],private_scoped_visitor_header_sha256=sha(scratch/'swf_movie.hpp'),private_scoped_visitor_cpp_sha256=sha(scratch/'swf_movie.cpp'),asset_sha256={p.name:sha(p) for p in (ROOT/'.local-inputs/ui-layout-discovery/dqshared_droid.swf',ROOT/'.local-inputs/ui-layout-discovery/dqhud_droid.swf')},authored_matrix_samples_sha256=sha(samples),matrix_inventory_sha256=sha(tree),sanitizers=['address','undefined(excluding upstream vptr)','leak'],sanitizer_findings=0,limits={'texture_images_localization_stencil_are_fixtures':True,'notify_owner_uses_actual_core_weak_parent_projection':True,'needs_advance_storage_owned_sidecar':True,'full_original_tag_or_AS_parity':False,'live_GL':False,'production_facade_wired':False},scope=__doc__);a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
if __name__=='__main__':main()
