import argparse,hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument('--core-library',default='/home/adampalace/dh2-gameswf-asan/libgameswf_core.a');a=p.parse_args();repo='/mnt/c/'+str(ROOT)[3:].replace('\\','/');build='/home/adampalace/dh2-hud-infos-audit';ui=ROOT/'port/engine-ui';paths=[ui/x for x in ('hud_player_infos.hpp','hud_player_infos.cpp','hud_player_infos_core.hpp','hud_player_infos_core.cpp','tests/hud_player_infos.cpp','tests/hud_player_infos_core.cpp')]+[ROOT/'port/script-runtime'/x for x in ('script_constants.hpp','script_constants.cpp')];before={str(x.relative_to(ROOT)).replace('\\','/'):sha(x) for x in paths};gold=ui/'reference/hud-player-infos/info-gold.bin';constants=ROOT/'port/android-native/app/src/main/assets/data/design_pycst.bin'
 def run(args):
  q=subprocess.run(args,capture_output=True,text=True);assert q.returncode==0,(q.args,q.stdout,q.stderr);return q.stdout.strip()
 core_before=run(['wsl','-e','sha256sum',a.core_library]).split()[0];run(['wsl','-e','mkdir','-p',build]);common=['wsl','-e','g++','-std=c++17','-O1','-g','-fsanitize=address,undefined','-fno-omit-frame-pointer','-I'+repo+'/port/engine-ui'];exe=build+'/hud_player_infos_audit';run(common+[repo+'/port/engine-ui/hud_player_infos.cpp',repo+'/port/engine-ui/tests/hud_player_infos.cpp','-o',exe]);env=['wsl','-e','env','ASAN_OPTIONS=detect_leaks=1:halt_on_error=1','UBSAN_OPTIONS=halt_on_error=1'];raw=json.loads(run(env+[exe,repo+'/port/engine-ui/reference/hud-player-infos/info-gold.bin']));asexe=build+'/hud_player_infos_core_audit';run(common+['-fno-sanitize=vptr','-fpermissive','-isystem',repo+'/port/engine-ui/vendor/gameswf1714','-I'+repo+'/port/script-runtime','-DTU_CONFIG_LINK_TO_JPEGLIB=0','-DTU_CONFIG_LINK_TO_LIBPNG=0','-DTU_CONFIG_LINK_TO_FREETYPE=0','-DTU_CONFIG_LINK_TO_THREAD=0',repo+'/port/engine-ui/hud_player_infos.cpp',repo+'/port/engine-ui/hud_player_infos_core.cpp',repo+'/port/script-runtime/script_constants.cpp',repo+'/port/engine-ui/tests/hud_player_infos_core.cpp',a.core_library,'-lz','-ldl','-o',asexe]);core=json.loads(run(env+[asexe,repo+'/port/android-native/app/src/main/assets/data/design_pycst.bin']));assert before=={str(x.relative_to(ROOT)).replace('\\','/'):sha(x) for x in paths};assert core_before==run(['wsl','-e','sha256sum',a.core_library]).split()[0];report=dict(validation='PASS',original_gold_replay=raw,actual_AS_adapter=core,source_sha256=before,gold_sha256=sha(gold),constants_stream_sha256=sha(constants),core_library_sha256=core_before,executable_sha256=run(['wsl','-e','sha256sum',exe]).split()[0],adapter_executable_sha256=run(['wsl','-e','sha256sum',asexe]).split()[0],sanitizer_findings=0,sanitizers=['address','undefined(adapter excludes upstream vptr)','leak'],limits={'skill_potion_player_property_saved_option_services_are_fixtures':True,'low_health_constant_is_actual_owned_cache':True,'original_AS_coercion_and_generic_object_setter_parity':False,'live_HUD':False});out=ui/'reports/hud-player-infos-host-audit.json';out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
if __name__=='__main__':main()
