"""Actual isolated localization DSO, genuine native constants/Debug dependencies."""
import argparse,json,shlex,subprocess
from pathlib import Path
from localization_differential import ROOT,REPO,sha
def linux(p):return '/mnt/'+p.drive[0].lower()+p.as_posix()[2:]
def main():
 p=argparse.ArgumentParser();p.add_argument('--build',default='/home/adampalace/dh2-world-build');a=p.parse_args();folder=REPO/'.local-inputs/localization-discovery/host';deps=folder/'dependencies';deps.mkdir(parents=True,exist_ok=True);commands=[]
 def run(argv):
  result=subprocess.run(['wsl','--','bash','-lc',shlex.join(argv)],capture_output=True,text=True);commands.append({'args':argv,'returncode':result.returncode,'stdout':result.stdout,'stderr':result.stderr});assert result.returncode==0,(result.returncode,result.stdout,result.stderr);return result.stdout
 paths=run(['find',a.build,'-type','f','-name','*.so']).splitlines();before={x:run(['sha256sum',x]).split()[0]for x in paths};assert len({Path(x).name for x in paths})==len(paths)
 for x in paths:run(['cp',x,linux(deps/Path(x).name)])
 assert before=={x:run(['sha256sum',x]).split()[0]for x in paths};copied={str((deps/Path(x).name).relative_to(REPO)):sha(deps/Path(x).name)for x in paths};assert list(copied.values())==list(before.values())
 flags=['-std=c++17','-O1','-g','-fsanitize=address,undefined','-fno-omit-frame-pointer','-fno-fast-math','-ffp-contract=off','-Wall','-Wextra','-Werror','-Wno-misleading-indentation'];lib=folder/'libdh2_localization_audit.so';exe=folder/'localization_audit';connection=folder/'localization_connection_audit';cpp=ROOT/'localization.cpp';sources=[cpp,ROOT/'localization.hpp',ROOT/'tests/localization.cpp',ROOT/'tests/localization_connection.cpp',Path(__file__)];bindings={x.relative_to(REPO).as_posix():sha(x)for x in sources}
 run(['g++',*flags,'-shared','-fPIC',linux(cpp),'-o',linux(lib)])
 for test,output,extra in [(ROOT/'tests/localization.cpp',exe,[]),(ROOT/'tests/localization_connection.cpp',connection,['-L'+linux(deps),'-ldh2_level_world','-ldh2_script_runtime','-Wl,-rpath,'+linux(deps)])]:run(['g++',*flags,linux(test),'-L'+linux(folder),'-ldh2_localization_audit','-Wl,-rpath,'+linux(folder),*extra,'-o',linux(output)])
 env=['env','ASAN_OPTIONS=detect_leaks=1:halt_on_error=1','UBSAN_OPTIONS=halt_on_error=1','LD_LIBRARY_PATH='+linux(deps)+':'+linux(folder)];gold=ROOT/'reference/localization/localization-fixtures.bin';ownedgold=ROOT/'reference/localization/localization-connection-fixtures.bin';assets=REPO/'port/android-native/app/src/main/assets/original-cache/data';fonts=REPO/'port/android-native/app/src/main/assets/data/fonts_pycst.bin'
 results=[json.loads(run([*env,linux(exe),linux(gold)])),json.loads(run([*env,linux(connection),linux(ownedgold),linux(assets),linux(fonts),linux(folder)]))];assert all(x['validation']=='PASS'for x in results);assert bindings=={x.relative_to(REPO).as_posix():sha(x)for x in sources};linkage=run([*env,'ldd',linux(connection)]);assert 'not found'not in linkage and 'libasan.so'in linkage and 'libubsan.so'in linkage
 report={'validation':'PASS','kernel_audit':results[0],'owned_connection_audit':results[1],'source_sha256':bindings,'library_sha256':sha(lib),'executables_sha256':{x.name:sha(x)for x in [exe,connection]},'private_original_dependency_bindings':before,'private_dependency_sha256':copied,'gold_sha256':sha(gold),'connection_gold_sha256':sha(ownedgold),'original_instruction_report_sha256':sha(ROOT/'reports/localization-arm64-differential.json'),'original_connection_report_sha256':sha(ROOT/'reference/localization/connection-probe.json'),'actual_isolated_localization_library_executed':True,'actual_constants_and_DebugSwitches_native_libraries_executed':True,'dependencies_rebuilt':False,'sanitizers':['AddressSanitizer','UndefinedBehaviorSanitizer'],'sanitizer_findings':0,'commands':commands,'scope':'Owned333exact text files and genuine native common_text/fonts constants + missing-file DebugSwitches. Original source full HUD wrapper gold and callback ordering; explicit AS conversion/publication, player receiver/name and resource file provider. Original global language/player Application owner and varargs formatted text outside this domain.'};dest=ROOT/'reports/localization-host-audit.json';dest.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'validation':'PASS','kernel':results[0],'connection':results[1],'report':str(dest)}))
if __name__=='__main__':main()
