#include "character_world_physical_character_v1.hpp"
namespace dh2::character {
bool CharacterWorldPhysicalCharacterV1::coherent(std::string& e){if(borrow_.machine.character!=borrow_.identity||borrow_.world.state_borrow(borrow_.identity)!=borrow_.machine.state){e="Required same registered Character physical FSM";return false;}return true;}
bool CharacterWorldPhysicalCharacterV1::character(std::uintptr_t& value,std::string& e){target_providers::Handle16* shared{};target_providers::Registry24* registry{};if(borrow_.world.handle_borrow(borrow_.identity,&shared,&registry)){e=borrow_.world.error();return false;}target_providers::Handle16 local{};auto q=borrow_.world.targets().query_services();if(dh2_target_handle_character(&value,&local,shared,registry,&q)){e="Required source physical Character handle conversion";return false;}return true;}
bool CharacterWorldPhysicalCharacterV1::debug(std::string& e){std::uint32_t tracing{};if(dh2_character_debug_load(&borrow_.debug,&borrow_.files)!=1||dh2_character_debug_get(&tracing,&borrow_.debug,"isTracingPlayersCollision",&borrow_.files)!=1){e="Required source POCharacter collision Debug";return false;}if(tracing){auto q=borrow_.world.targets().query_services();target_providers::Request24 r{target_providers::virtual_player,0,borrow_.identity,0};std::uintptr_t out{};if(q.invoke(q.context,&r,&out)){e="Required collision trace IsPlayer query";return false;}}return true;}
bool CharacterWorldPhysicalCharacterV1::filter(std::uint16_t category,bool& allowed,std::string& e){e.clear();allowed=false;if(!coherent(e))return false;std::uintptr_t owner{};if(!character(owner,e))return false;if(owner){std::int32_t current{};if(dh2_character_native_fsm_get_integer(&current,&borrow_.machine,0)!=1){e="Required same physical Character current-state getter";return false;}if(current==0||(current==10&&!(category&3)))return true;}allowed=true;return true;}
bool CharacterWorldPhysicalCharacterV1::event(physical::ContactEvent event,std::uintptr_t peer,unsigned persist,std::string& e){e.clear();if(!coherent(e))return false;if(event==physical::ContactEvent::result||!peer)return true;std::uintptr_t owner{};if(event==physical::ContactEvent::persist){if(!character(owner,e)||!debug(e))return false;}else if(!debug(e)||!character(owner,e))return false;if(!owner)return true;const auto id=event==physical::ContactEvent::add?0x37u:event==physical::ContactEvent::persist?0x39u:0x3bu;if(!borrow_.raise_event||borrow_.raise_event(borrow_.context,owner,id+(persist?0:1),peer,e)){if(e.empty())e="Required actual same Character AI/FSM RaiseEvent collision receiver";return false;}return true;}
WorldPhysicalCharacterServicesV1 CharacterWorldPhysicalCharacterV1::services()noexcept{return {this,[](void* p,std::uint16_t c,bool& v,std::string& e){return static_cast<CharacterWorldPhysicalCharacterV1*>(p)->filter(c,v,e)?0:-1;},[](void* p,physical::ContactEvent c,std::uintptr_t id,unsigned flag,std::string& e){return static_cast<CharacterWorldPhysicalCharacterV1*>(p)->event(c,id,flag,e)?0:-1;}};}
}
