#include "gameplay_skybox_v24.hpp"
#include <cstring>
#include <algorithm>
namespace {
std::uint32_t word(const std::uint8_t*p){return p[0]|std::uint32_t(p[1])<<8|std::uint32_t(p[2])<<16|std::uint32_t(p[3])<<24;}
bool text(const dh2::resources::BresView&v,std::uint32_t p,std::string&out,std::string&e){if(!p||p>=v.size){e="Required actual skybox serialized string";return false;}const auto*end=static_cast<const std::uint8_t*>(std::memchr(v.bytes+p,0,v.size-p));if(!end){e="Unterminated actual skybox string";return false;}out.assign(reinterpret_cast<const char*>(v.bytes+p),end-(v.bytes+p));return true;}
bool diffuse_uri(const dh2::resources::BresView&v,std::uint32_t material,std::string&out,std::string&e){
 const auto*p=dh2_bres_library_item(&v,dh2::resources::Library::material,material);if(!p){e="Actual skybox material absent";return false;}const auto count=word(p+16),base=word(p+20);if(std::uint64_t(base)+std::uint64_t(count)*24>v.size){e="Skybox material parameters outside BRES";return false;}
 for(unsigned i=0;i<count;++i){const auto*q=v.bytes+base+i*24;std::string name;if(!text(v,word(q),name,e))return false;if(name!="Diffuse"&&name!="diffuse-sampler")continue;
  if(word(q+8)!=11||word(q+12)!=1){e="Required actual scalar skybox texture sampler";return false;}const auto sizes=word(q+16),data=word(q+20);if(sizes+4ull>v.size||data+4ull>v.size||word(v.bytes+sizes)!=1){e="Invalid skybox sampler vector";return false;}const auto pointer=word(v.bytes+data);if(pointer+4ull>v.size){e="Invalid skybox sampler pointer";return false;}const auto image=word(v.bytes+pointer);const auto*img=dh2_bres_library_item(&v,dh2::resources::Library::image,image);if(!img){e="Skybox actual texture image index absent";return false;}return text(v,word(img+8),out,e);
 }e="Required reached skybox COMMON diffuse sampler producer";return false;
}
}
extern "C" void dh2_skybox_transform_v24(float*m,const float*eye,const float*near){m[12]=eye[0];m[13]=eye[1];m[14]=eye[2];const float scale=*near+*near;m[0]=m[5]=m[10]=scale;}
extern "C" void dh2_skybox_clear_depth_write_v24(std::uint32_t*flags,std::uint8_t*dirty){const auto old=*flags;*flags=old&~0x100000u;if(old&0x100000u)*dirty=1;}
namespace dh2::camera {
struct SkyboxNodeV24::ParentLease {std::shared_ptr<SkyboxNodeV24> node;~ParentLease(){if(node){std::string error;node->drop(error);}}};
SkyboxNodeV24::SkyboxNodeV24(std::shared_ptr<SkyboxResourceV24>r,std::vector<SkyboxMaterialRendererBorrowV24>m,std::shared_ptr<world::GameObjectSceneRootRegistryV1>roots):resource_(std::move(r)),materials_(std::move(m)),roots_(roots){}
bool SkyboxNodeV24::construct_tail(std::string&e){if(!resource_||resource_->buffers.empty()){e="Required actual skybox CMeshSceneNode mesh/material0";return false;}const auto index=resource_->buffers[0].material;if(index>=materials_.size()||!materials_[index].owner||!materials_[index].flags4||!materials_[index].dirty30){e="Required SAME original skybox material RenderPass flags/dirty owner";return false;}dh2_skybox_clear_depth_write_v24(materials_[index].flags4,materials_[index].dirty30);return true;}
bool SkyboxNodeV24::grab(std::string&e){if(!alive_||!references_){e="Released actual skybox reference";return false;}++references_;return true;}
bool SkyboxNodeV24::drop(std::string&e){if(!alive_||!references_){e="Required live source skybox drop";return false;}--references_;if(!references_){if(parentec_){e="Skybox source drop reached registered parent at zero";return false;}alive_=false;materials_.clear();resource_.reset();}return true;}
bool SkyboxNodeV24::attach(std::string&e){auto roots=roots_.lock();if(!alive_||!roots){e="Required actual skybox SAME SceneManager root";return false;}if(parentec_){e="Skybox already has a source parent";return false;}if(!grab(e))return false;auto parent=std::make_shared<ParentLease>();parent->node=shared_from_this();world::GameObjectSceneRootBorrowV1 b;b.owner=parent;b.identity=identity();b.flags11c=&flags11c_;b.parentec=&parentec_;std::weak_ptr<SkyboxNodeV24> weak=shared_from_this();
 b.notify_visibility=[weak](bool visible,std::string&error){auto node=weak.lock();if(!node){error="Released skybox visibility receiver";return false;}node->parent121_=visible;if(node->local120_&&node->parent121_)node->flags11c_|=1;else node->flags11c_&=~1u;return true;};
 b.remove_animators=[weak](std::string&error){auto node=weak.lock();if(!node){error="Released skybox animator receiver";return false;}return true;}; // actual wrapper C1 owns an empty animator list
 b.modular_receivers_v114=[weak](auto&,std::string& e){if(weak.expired()){e="Retired actual skybox type search";return false;}e.clear();return true;}; //actual Skybox node owns mesh buffers, no CModularSkinnedMeshSceneNode children
 b.scene_manager_changed=[weak](std::uintptr_t manager,std::string&error){auto node=weak.lock();if(!node){error="Released skybox manager receiver";return false;}node->manager110_=manager;return true;};
 return roots->add_child(std::move(b),e);
}
bool SkyboxNodeV24::detach(std::string&e){if(!parentec_)return true;auto roots=roots_.lock();if(!roots){e="Required SAME skybox parent removal owner";return false;}return roots->release_visual_root(identity(),e);}
bool SkyboxNodeV24::register_buffers(bool driver,const std::function<bool(const SkyboxQueueEntryV24&,std::string&)>&queue,std::string&e){if(!alive_){e="Released source skybox register receiver";return false;}if(!resource_||!driver)return true;if(!queue){e="Required real SceneManager skybox render queue";return false;}for(unsigned i=0;i<resource_->buffers.size();++i){SkyboxQueueEntryV24 entry;entry.node=shared_from_this();entry.buffer_parameter=i+1;entry.material=resource_->buffers[i].material;if(!queue(entry,e))return false;}return true;}
bool SkyboxNodeV24::render(std::uint32_t parameter,const SkyboxRenderServicesV24&s,std::string&e){if(!alive_){e="Released source skybox render receiver";return false;}if(!enabled138_||!resource_||!s.actual_driver_present||!s.actual_active_camera_present)return true;if(!s.active_camera_position||!s.active_camera_near||!s.set_world_transform){e="Required actual active camera/driver world-transform services";return false;}std::array<float,3> eye;float near;if(!s.active_camera_position(eye,e))return false;transform_[12]=eye[0];transform_[13]=eye[1];transform_[14]=eye[2];if(!s.active_camera_near(near,e))return false;dh2_skybox_transform_v24(transform_.data(),eye.data(),&near);if(!s.set_world_transform(transform_,e))return false;if(!parameter||parameter-1>=resource_->buffers.size())return true;const auto&buffer=resource_->buffers[parameter-1];if(!s.set_material||!s.set_shadow_cascade||!s.draw_buffer){e="Required original skybox material/cascade/drawMeshBuffer backend";return false;}if(!s.set_material(*resource_,buffer,e)||!s.set_shadow_cascade(0,e)||!s.draw_buffer(*resource_,buffer,e))return false;return true;}
bool GameplaySkyboxV24::prepare(const std::string&file,std::shared_ptr<SkyboxResourceV24>&out,bool&found,std::string&e){found=false;if(!services_.actual_resource_owner||!services_.read){e="Required actual skybox file/database resource owner";return false;}auto r=std::make_shared<SkyboxResourceV24>();r->file=file;if(!services_.read(file,r->bytes,found,e))return false;if(!found)return true;reached_resource_=r;if(dh2_bres_open(&r->bres,r->bytes.data(),r->bytes.size())!=resources::BresError::ok){e="Invalid actual skybox BRES";return false;}if(!scene::load(r->bres,r->scene,e))return false;
 if(r->scene.instances.empty()){found=false;return true;} // only supported visible geometry domain
 r->source_mesh_instance=0;const auto&instance=r->scene.instances[0];if(instance.controller!=-1){e="Required actual non-static skybox mesh constructor";return false;}if(dh2_mesh_open(&r->mesh,&r->bres,instance.geometry)!=assets::Error::ok){e="Required original skybox static CMesh payload";return false;}
 r->textures.resize(r->scene.materials.size());for(unsigned m=0;m<r->scene.materials.size();++m){std::string uri;if(!diffuse_uri(r->bres,m,uri,e))return false;auto texture=std::make_shared<SkyboxTextureV24>();texture->uri=uri;bool exists;if(!services_.read(uri,texture->bytes,exists,e))return false;if(!exists){e="Original skybox texture absent: "+uri;return false;}textures::View v;if(dh2_texture_open(texture->bytes.data(),texture->bytes.size(),&v)!=textures::Error::ok){e="Original skybox texture decoding header unsupported";return false;}texture->width=v.width;texture->height=v.height;const auto count=std::uint64_t(v.width)*v.height*4;if(count>64*1024*1024){e="Skybox texture output exceeds supported limit";return false;}texture->rgba.resize(count);if(dh2_texture_decode(&v,texture->rgba.data(),texture->rgba.size())!=textures::Error::ok){e="Actual skybox texture decode failed";return false;}r->textures[m]=std::move(texture);}
 for(unsigned i=0;i<r->mesh.primitives;++i){SkyboxBufferV24 b;if(dh2_mesh_primitive(&r->mesh,i,&b.primitive)!=assets::Error::ok){e="Invalid actual skybox primitive";return false;}if(i>=instance.materials.size()){e="Required actual mesh buffer material binding";return false;}b.material=instance.materials[i];assets::Attribute pos,uv;if(dh2_mesh_attribute(&r->mesh,b.primitive.attributes[0],&pos)!=assets::Error::ok||pos.components!=3||dh2_mesh_attribute(&r->mesh,b.primitive.attributes[4],&uv)!=assets::Error::ok||uv.components!=2){e="Required actual skybox position/UV attributes";return false;}b.positions.resize(pos.vertices);b.uv.resize(uv.vertices);for(unsigned j=0;j<pos.vertices;++j)if(!dh2_attribute_read(&pos,j,b.positions[j].data())){e="Skybox position read failed";return false;}for(unsigned j=0;j<uv.vertices;++j)if(!dh2_attribute_read(&uv,j,b.uv[j].data())){e="Skybox UV read failed";return false;}b.indices.resize(b.primitive.index_count);for(unsigned j=0;j<b.indices.size();++j)if(!dh2_index_read(&b.primitive,j,&b.indices[j])){e="Skybox index read failed";return false;}r->buffers.push_back(std::move(b));}
 out=std::move(r);return true;
}
bool GameplaySkyboxV24::add(const std::string&file,std::string&e){if(file.empty())return true;std::shared_ptr<SkyboxResourceV24>resource;bool found;if(!prepare(file,resource,found,e))return false;if(!found)return true;if(!services_.same_roots){e="Required SAME actual skybox SceneManager root registry";return false;}if(!services_.material_renderer){e="Required actual original COMMON skybox material renderer constructor";return false;}std::vector<SkyboxMaterialRendererBorrowV24> materials(resource->scene.materials.size());for(unsigned i=0;i<materials.size();++i)if(!services_.material_renderer(resource,i,materials[i],e))return false;
 // LoadScene constructs new mesh/materials before original old438 removal.
 // SkyBox wrapper C1 and its depth-write mutation follow that removal.
 if(skybox438_){if(!skybox438_->detach(e)||!skybox438_->drop(e))return false;skybox438_.reset();}auto node=std::make_shared<SkyboxNodeV24>(resource,std::move(materials),services_.same_roots);if(!node->construct_tail(e))return false;skybox438_=std::move(node);if(!skybox438_->attach(e))return false;reached_resource_.reset();return true;}
bool GameplaySkyboxV24::release(std::string&e){if(skybox438_){if(!skybox438_->detach(e)||!skybox438_->drop(e))return false;skybox438_.reset();}reached_resource_.reset();return true;}
}
