#include "retained_generic_animator_v21.hpp"
namespace dh2::world {
bool RetainedGenericAnimatorV21::list(std::vector<GenericAnimatorCallbackBorrowV21>& out,std::string& e){out.clear();if(!visual_){e="Required same retained generic visual";return false;}std::uintptr_t id{};bool present{};if(!visual_->generic_animator_identity_v21(id,present,e))return false;if(present)out.push_back({visual_,id,&visual_->generic_callbacks_v69()});return true;}
bool RetainedGenericAnimatorV21::initialize(std::string& e){if(initialized_){e="Generic controller callback initialization cannot replay";return false;}std::vector<GenericAnimatorCallbackBorrowV21> actual;if(!list(actual,e))return false;if(!generic_animation_set_callbacks_all_v21(actual,GenericAnimatorCallbackFieldsV21::source_do_nothing(),e))return false;initialized_=true;return true;}
bool RetainedGenericAnimatorV21::set_callbacks(GenericAnimationCallbacksV21 fields,std::string& e){if(!initialized_){e="Required initialized actual generic callback owner";return false;}std::vector<GenericAnimatorCallbackBorrowV21> actual;if(!list(actual,e))return false;return generic_animation_set_callbacks_all_v21(actual,std::move(fields),e);}
bool RetainedGenericAnimatorV21::frame(std::uint32_t ms,std::string& e){if(!initialized_||failed_){e="Required live generic animator callback frame; failed prefix cannot replay";return false;}auto pin=visual_;if(!pin||!pin->update_callbacks_v21(ms,visual_->generic_callbacks_v69(),e)){failed_=true;return false;}return true;}
bool RetainedGenericAnimatorV21::count(std::uint32_t& out,std::string& e){if(!visual_){e="Required same retained generic visual";return false;}auto b=visual_->named_animation(visual_);if(!b.timeline){e="Required actual generic timeline library";return false;}out=static_cast<std::uint32_t>(b.timeline_library_count);return true;}
bool RetainedGenericAnimatorV21::play_index(std::uint32_t index,bool loop,bool& accepted,std::string& e){if(!initialized_||!visual_){e="Required actual retained index controller";return false;}auto b=visual_->named_animation(visual_);return base_index_animation_play_v21(b,index,loop,accepted,e);}
}
