import json,pathlib
p=pathlib.Path('reports/source-backend-callbacks-20261009.json');r=json.loads(p.read_text())
if 'evidence_audit_20261009' in r:
 assert r['evidence_audit_20261009']['logic_evidence']
 assert r['evidence_audit_20261009']['verification_layers']
 print('existing evidence audit valid; retained')
 raise SystemExit(0)
r['evidence_audit_20261009']={
 'scope':'Internal callback infrastructure. Existing recovered source is reused; no footage requirement is invented for registry/lifetime plumbing. Visible consumer invariants are source actor targeting/heading, zone visibility, TalkToNPC interaction, authored FX/audio and Limbus hide/respawn. No direct original gameplay footage was inspected by this worker and no visual equivalence is claimed.',
 'logic_evidence':[
 'source_campaign_character_fsm_v101.cpp:620 Limbus state0 body;995/1058 AI MyTurn;1016 skill target OnAggro;1082 clear;1175 AI enable/disable zoning;1343/1362/1407 FX;1461 selected actual IsCharacter then Character/nonCharacter interaction;1629 attack/monster audio category.',
 'source_campaign_script_actor_v96.cpp:38-97 source target180/visible80/position160 and active controller378 identity before native controller_look_object/LookAt kernel;303-321 visible80 store then source Visual2d8 synchronization with player/AI type3/zoned2ee/inzone2f0 gates.',
 'source_campaign_character_interaction_v114.cpp:29-37 original null id is successful out0 before World scope; positive lookup requires selected ObjectManager lease and IsCharacter virtual, copies entry before call.40-89 Character.Interact state!=13 samples current Level before quest event, constants TalkToNPC then SetInteract, TalkToNPC2fa, AI merchant/cleaner and actual PM/UI gates.',
 'source_campaign_character_zoning_v108.cpp:15-55 actual inherited mutable 2ee/2f0/2f4/2d8 fields, Room/ModuleRoomZone owner or retained generic Room, ObjectManager no-room membership, updating85, visibility and qualified zone event before native enable/disable zoning kernels.',
 'source_campaign_ai_queue_v105.cpp:10-40 selected registered CharAI receiver resolved through actual manager character list; forced/global-blocked/locked controller, dead/player/follower/faerie/zoned/remote fields.43-54 same constructor queue advanced by actual App dt then IsMyTurn; CharacterWorldRuntime target pin alone does not implement queue policy.',
 'source_campaign_script_ai_v118.cpp:69-101 CSLimbus event0x3bffe8, focus0x3c2e58, blur0x3c2be4; Debug trace gate, flags reset/visible false, actual respawn property11/1481/530 and online gate/timer47, reciprocal aggro; blur controller unlock/visible true, initial position1450/rotation145c/revive and AI group.',
 'source_campaign_death_rewards_v84.cpp:394-410 published death_rewards_v84 owner dispatches notify_aggro/clear_aggro; existing World target runtime alone is insufficient.',
 'audio_campaign_bridge_v46.cpp:113-117 original no-clock prefix validates producer/captured manager and runs VoxPlay3D owner gates. submit uses actual event clock scope, category and same bridge World. No fallback playback.'
 ],
 'visual_evidence':'Existing reports/cinematic-live-integration.json reference section reuses reports/fidelity-video-audit-v18.json: movie frames267/273 show moths with HUD hidden/SKIP and274 shows gameplay restored. This supplies a consumer visibility invariant only; it does not prove this callback adapter or source zoning/Limbus/FX timing. Direct reference/runtime comparisons remain feature-owned gaps.',
 'expected_reusable_invariant':'Borrow published same-owner actors/services per reached call, preserve source null/no-op and admission branches, mutate actual source heading/visibility through recovered kernels, retain selected receiver across synchronous virtual mutation. Original consumer behavior remains in reusable native leaves; no parallel gameplay state or generic wrapper is needed.',
 'uncertainties':['No live registered backend call has run.','Seven service entries are forwarding seams, not implemented native bodies. Root must publish concrete original-owner methods; never bind a seam to its same model_renderer symbol, which would recurse.','Original footage for Limbus/zone/aggro/FX timing not inspected in this bounded infrastructure task. Feature visual verification still required.','Full closure still has54 native link gaps.'],
 'focused_test_defined_before_correction':'Actual exported object-as-character: id0 with no registered context -> true,out0,error cleared; positive missing context -> false/typed error; with real manager selected callback erasing its own publication, selected lease remains alive until virtual returns. Also duplicate current registration and World/Level mismatch failures; each reached missing service fails while unreached missing service does not gate registration. Positive real record and visual/LookAt branch tests require initialized root graph.',
 'bug':{'name':'null IsCharacter short-circuit and selected receiver lifetime','implementation_owner':'/root/workforce_dispatcher/source_backend_callbacks_sol','reviewer':'/root/integration_lead','status':'correction pending focused compile/runtime attempt','source':'source_campaign_character_interaction_v114.cpp:29-37'},
 'verification_layers':{'investigation':'recovered callers/native source inspected; no direct new footage inspection','implementation':'8 direct adapters,3 real typed FX/audio paths,7 forwarding service seams','isolated':'strict COFF compilation and symbol audit; runtime probe pending','integrated':'not run','remaining':'root owner publication,54-symbol native closure, real positive/failure/duplicate integration, visible feature verification'}
}
p.write_text(json.dumps(r,indent=2)+'\n')
