#include "../audio_bank_v34.hpp"
#include "../../level-world/vox_audio_bridge_v34.hpp"
#include "../audio_native_envelope_v34.hpp"
#include <fstream>
#include <iostream>
#include <algorithm>
#include <cmath>
#include <cstring>
using namespace dh2::audio;
static unsigned checks;
extern "C" unsigned dh2_audio_ima_v34(const unsigned char*,unsigned char*);
extern "C" unsigned dh2_audio_spatial_v34(const unsigned char*,unsigned char*);
extern "C" unsigned dh2_audio_envelope_v34(const unsigned char*,unsigned char*);
static void check(bool x,const char*message){++checks;if(!x)throw std::runtime_error(message);}
static std::shared_ptr<const std::vector<std::uint8_t>>read(const std::string&path){std::ifstream f(path,std::ios::binary);if(!f)return {};return std::make_shared<const std::vector<std::uint8_t>>(std::istreambuf_iterator<char>(f),std::istreambuf_iterator<char>());}
static bool asset(void*context,const char*uri,std::shared_ptr<const std::vector<std::uint8_t>>&bytes,std::string&error){const std::string path=uri;if(path.rfind("data/sounds/",0)!=0)return false;bytes=read(*static_cast<std::string*>(context)+"/"+path.substr(12));if(!bytes){error="Required exact original asset "+path;return false;}return true;}
static void replay(){
 for(int kind=0;kind<3;++kind){const char*names[]{"ima","spatial","envelope"};auto gold=read(std::string("port/engine-audio/reports/audio-v34-")+names[kind]+"-gold.bin");check(bool(gold),"original instruction gold");std::size_t p=0;auto word=[&](){check(p+4<=gold->size(),"gold extent");unsigned v;std::memcpy(&v,gold->data()+p,4);p+=4;return v;};word();const auto count=word();for(unsigned i=0;i<count;++i){unsigned bytes=kind==1?100:word();unsigned frames=kind==0?word():0;check(p+bytes<=gold->size(),"gold input extent");const auto*input=gold->data()+p;p+=bytes;const unsigned expected=kind==1?16:word();check(p+expected<=gold->size(),"gold output extent");unsigned char out[16384]{};const auto size=kind==0?dh2_audio_ima_v34(input,out):kind==1?dh2_audio_spatial_v34(input,out):dh2_audio_envelope_v34(input,out);check(kind==0?size>=frames:size==expected,"source returned extent");check(std::memcmp(out,gold->data()+p,expected)==0,"original instructions match host arithmetic");p+=expected;}check(p==gold->size(),"complete gold replay");}
}
int main(int argc,char**argv){try{
 replay();
 if(argc!=2)return 1;std::string cache=argv[1],error;unsigned pcm=0,ima=0,native=0;std::ifstream list(cache+"/assets.txt");check(bool(list),"Actual audio asset manifest");std::string name;
 while(std::getline(list,name)){if(!name.empty()&&name.back()=='\r')name.pop_back();auto bytes=read(cache+"/"+name);AudioSampleV34 sample;const bool opened=audio_sample_open_v34(bytes,sample,error);check(opened,(name+": "+error).c_str());if(sample.native)++native;else if(sample.format==17)++ima;else ++pcm;
  for(unsigned segment=0;segment<sample.segments.size();++segment){AudioSampleCursorV34 cursor;check(cursor.bind(&sample,segment),"retained source cursor");const auto frames=cursor.frames();check(frames>0,"positive authored source duration");
   for(std::uint64_t i:{std::uint64_t(0),std::uint64_t(1),std::uint64_t(frames/2),std::uint64_t(frames-1)}){float l,r;check(cursor.frame(i,l,r),"real first/middle/final sample");check(std::isfinite(l)&&std::isfinite(r)&&std::abs(l)<=1&&std::abs(r)<=1,"PCM normalized sample domain");float l2,r2;check(cursor.frame(i,l2,r2)&&l2==l&&r2==r,"same cursor/cache sample identity");}
   float l,r;check(!cursor.frame(frames,l,r),"source segment extent guard");
  }
 }
 check(pcm==228&&ima==16&&native==17,"Actual complete 261-stream cache census");
 AudioCatalogV34 catalog;auto xml=read(cache+"/sounds.xml");const bool catalog_ok=catalog.load_xml(*xml,error);check(catalog_ok,error.c_str());check(catalog.sounds().size()==578&&catalog.events().size()==63&&catalog.groups().size()==12&&catalog.banks().size()==7,"Original XML topology");check(catalog.sound_uid("SlamSkill")==101&&catalog.sound(101)->filename=="sfx_skill_warrior_headsplitter.wav","Exact XML source SlamSkill UID/file");
 auto event_gold=read("port/engine-audio/reports/audio-v34-event-gold.bin");check(bool(event_gold),"original event gold");std::size_t ep=8;auto ew=[&](){unsigned v;check(ep+4<=event_gold->size(),"event gold extent");std::memcpy(&v,event_gold->data()+ep,4);ep+=4;return v;};
 for(unsigned sequence=0;sequence<8;++sequence){const unsigned kind=ew(),limit=ew(),count=ew();std::string fixture(xml->begin(),xml->end());auto first=fixture.find("<events"),last=fixture.find("</events>",first);check(first!=std::string::npos&&last!=std::string::npos,"fixture original event topology");fixture.replace(first,last+9-first,"<events size=\"1\"><event uid=\"0\" type=\""+std::string(kind?"playlist":"random")+"\" params=\""+std::to_string(limit)+"\" label=\"fixture\" value=\"39,40,41\"/></events>");AudioCatalogV34 events;check(events.load_xml({fixture.begin(),fixture.end()},error),error.c_str());for(unsigned i=0;i<count;++i){struct Draw{int values[2];unsigned index{};}draw{{int(ew()),int(ew())}};const auto expected=ew();AudioRandomV34 random{&draw,[](void*p,int&value){auto&d=*static_cast<Draw*>(p);if(d.index>=2)return false;value=d.values[d.index++];return true;}};int uid;check(events.select_event(0,random,uid,error)&&uid==int(expected),"original ordered event replay");check(draw.index==(kind?1u:2u),"same original RNG prefix");}}check(ep==event_gold->size(),"all eight event sequences");
 auto mixer=std::make_unique<AudioMixerV34>();AudioSampleBankV34 bank(catalog,*mixer,{&cache,asset});check(bank.initialize_banks(),bank.error().c_str());check(mixer->set_rate(32000),"fixture device rate");
 const int menu=catalog.sound_uid("MenuSelect");check(menu>=0,"original UI label");AudioCommandV34 command;command.start_frame=16;command.left=command.right=0.5f;std::uint64_t token;
 check(bank.play_uid(menu,command,token)&&token,"exact original sound queued");auto sample=bank.load(menu);AudioSampleCursorV34 source;check(source.bind(sample.get(),0),"same sample");std::vector<float>buffer(64);mixer->render(buffer.data(),32);for(unsigned i=0;i<16;++i)check(buffer[2*i]==0&&buffer[2*i+1]==0,"sample-accurate authored frame boundary");for(unsigned i=16;i<32;++i){float l,r;check(source.frame(i-16,l,r),"source PCM frame");check(buffer[2*i]==l*.5f&&buffer[2*i+1]==r*.5f,"same positive decoded transport output");}
 command={};command.kind=AudioCommandKindV34::pause_all;check(mixer->post(command),"pause queue");mixer->render(buffer.data(),32);for(float x:buffer)check(x==0,"pause silence");command.kind=AudioCommandKindV34::resume_all;check(mixer->post(command),"resume queue");mixer->render(buffer.data(),32);for(unsigned i=0;i<32;++i){float l,r;check(source.frame(i+16,l,r),"retained PCM after pause");check(buffer[2*i]==l*.5f&&buffer[2*i+1]==r*.5f,"same cursor after resume");}
 command={};command.kind=AudioCommandKindV34::stop;command.token=token;check(mixer->post(command),"stop queue");mixer->render(buffer.data(),32);bank.pump_receipts();check(!bank.pinned_samples(),"terminal receipt releases sole voice pin on producer");
 AudioReceiptV34 receipt;unsigned started=0,stopped=0;while(bank.take_receipt(receipt)){started+=receipt.kind==AudioReceiptKindV34::started;stopped+=receipt.kind==AudioReceiptKindV34::stopped;}check(started==1&&stopped==1,"actual voice lifecycle receipts");
 check(!bank.load(catalog.sound_uid("DropGold")),"genuine exact XML missing asset remains required");check(bank.error().find("sfx_drop_gold.wav")!=std::string::npos,"missing filename provenance");
 // All native playlists start from authored state zero; no default state is
 // supplied by production. This test supplies explicit fixture state zero.
 std::ifstream native_list(cache+"/assets.txt");while(std::getline(native_list,name)){if(!name.empty()&&name.back()=='\r')name.pop_back();if(name.size()<4||name.substr(name.size()-4)!=".vxn")continue;int uid=-1;for(const auto&s:catalog.sounds())if(s.filename==name){uid=s.uid;break;}check(uid>=0,"native exact XML file identity");auto native_sample=bank.load(uid);check(bool(native_sample),bank.error().c_str());command={};command.native_state=0;check(bank.play_uid(uid,command,token),bank.error().c_str());mixer->render(buffer.data(),32);bank.pump_receipts();check(bank.pinned_samples()==1,"native startup sample pinned");AudioSampleCursorV34 native_source;check(native_source.bind(native_sample.get(),0),"native source segment zero");for(unsigned i=0;i<32;++i){float l,r;check(native_source.frame(i,l,r),"native startup source frame");check(buffer[i*2]==l&&buffer[i*2+1]==r,"native authored playlist startup waveform");}
  if(native_sample->states.size()==2){command={};command.kind=AudioCommandKindV34::native_state;command.token=token;command.native_state=1;check(mixer->post(command),"phase synced combat state queued");mixer->render(buffer.data(),32);AudioSampleCursorV34 combat_source;check(combat_source.bind(native_sample.get(),1),"native target segment");const int fade_length=int(native_sample->rate*2);AudioNativeEnvelopeV34 incoming{0,fade_length,1073741824/fade_length,0,false},outgoing{0,fade_length,-(1073741824/fade_length),1073741824,false};for(unsigned i=0;i<32;++i){float al,ar,bl,br;check(native_source.frame(32+i,al,ar)&&combat_source.frame(32+i,bl,br),"phase transposed source samples");const std::int16_t a[]{std::int16_t(al*32768),std::int16_t(ar*32768)},b[]{std::int16_t(bl*32768),std::int16_t(br*32768)};std::int32_t blended[2]{};check(audio_native_envelope_mix_v34(a,1,2,blended,outgoing)&&audio_native_envelope_mix_v34(b,1,2,blended,incoming),"source transition envelopes");check(buffer[2*i]==float(std::clamp(blended[0],-32768,32767))/32768.f&&buffer[2*i+1]==float(std::clamp(blended[1],-32768,32767))/32768.f,"integrated original Q30 transition output");}command.native_state=0;check(mixer->post(command),"rapid reverse explicitly required");mixer->render(buffer.data(),32);bank.pump_receipts();check(bank.pinned_samples()==1,"unsupported native control never releases active pin");bool required=false;while(bank.take_receipt(receipt))required|=receipt.kind==AudioReceiptKindV34::control_required;check(required,"third dying segment remains explicit");}
  else{check(name=="m_title.vxn","only original title has one state");command={};command.kind=AudioCommandKindV34::gains;command.token=token;command.pitch=8;check(mixer->post(command),"accelerated bounded title fixture");const auto intro=native_source.frames();check(intro>32,"title authored intro duration");unsigned advance=(intro-32+7)/8;float scratch[1024]{};while(advance){const auto n=std::min(advance,512u);mixer->render(scratch,n);advance-=n;}mixer->render(buffer.data(),1);AudioSampleCursorV34 loop_source;check(loop_source.bind(native_sample.get(),1),"title loop source cursor");const auto overflow=32+((intro-32+7)/8)*8-intro;float l,r;check(loop_source.frame(overflow,l,r),"actual title intro to loop frame");check(buffer[0]==l&&buffer[1]==r&&mixer->active_voices()==1,"title once intro continues into authored infinite loop");}
  command={};command.kind=AudioCommandKindV34::stop;command.token=token;check(mixer->post(command),"native stop");mixer->render(buffer.data(),32);bank.pump_receipts();check(bank.pinned_samples()==0,"native stopped pin released");while(bank.take_receipt(receipt)){}
 }
 std::uint8_t legacy[12]{1,0,0,0,255,255,255,255,2,0,0,0};std::vector<AudioSoundAutoGenV34>rows;check(!audio_sound_autogen_rows_v34(legacy,sizeof legacy,rows,error),"legacy Sound/type row not accepted as source event shape");
 AudioRandomV34 random{nullptr,[](void*,int&v){static int value=1;v=value++;return true;}};int selected;const int event=catalog.event_uid("env_fs_walk_stone");check(event>=0,"source footsteps event label");for(unsigned i=0;i<20;++i){check(catalog.select_event(event,random,selected,error),error.c_str());check(selected==72||selected==74,"actual event excludes non-authored footstep filenames");}
 // Driver callback control beyond actual bank limits must follow source theft.
 auto small=std::make_unique<AudioMixerV34>();AudioBankV34 limit{1,-128,1,2};check(small->configure_banks(&limit,1),"source low/equal-priority bank");AudioCommandV34 voice;voice.sample=sample.get();voice.bank=1;voice.priority=2;voice.token=1;voice.loop=true;check(small->post(voice),"first voice");small->render(buffer.data(),1);voice.token=2;voice.priority=1;check(small->post(voice),"lower priority request");small->render(buffer.data(),1);voice.token=3;voice.priority=2;check(small->post(voice),"equal priority request");small->render(buffer.data(),1);unsigned stolen=0,rejected=0;while(small->receipt(receipt)){stolen+=receipt.kind==AudioReceiptKindV34::stolen;rejected+=receipt.kind==AudioReceiptKindV34::rejected;}check(stolen==1&&rejected==1,"source bank lower refused equal oldest stolen");
 // Borrowed fixture gates, not a change to the production World phase.
 struct Gates{int phase{},commands{};bool ready{true};}gates;
 dh2::sound::VoxAudioAuthoritiesV34 authorities;authorities.context=&gates;authorities.gates={&gates,[](void*p,const dh2::sound::VoxPlay3DRequestV2&q,dh2::sound::VoxPlay3DResponseV2&r){using O=dh2::sound::VoxPlay3DOperationV2;auto&g=*static_cast<Gates*>(p);r={};if(q.operation==O::current_level){r.identity=456;r.value=g.phase;}return 0;}};
 authorities.output_ready=[](void*p,std::string&){return static_cast<Gates*>(p)->ready;};authorities.event_frame=[](void*,std::uint64_t&frame,std::string&){frame=10000;return true;};authorities.source_command=[](void*p,const dh2::character::CombatSoundPlayV1&,const AudioSoundV34&,const AudioGroupV34&,AudioCommandV34&c,std::string&){++static_cast<Gates*>(p)->commands;c.left=.25f;c.right=.75f;return true;};
 dh2::sound::VoxAudioBridgeV34 bridge(catalog,bank,123,authorities);check(bridge.bind_source_autogen({{menu,0}},error),"explicit source UID/event bindings");dh2::sound::VoxPlay3DOwnerV2 owner(bridge.services());dh2::character::CombatSoundPlayV1 play;play.manager=123;play.sound_id=0;
 check(owner.play(play)==0&&owner.phase()==2&&gates.commands==0&&bank.pinned_samples()==0,"genuine phase zero remains source early return");gates.phase=38;check(owner.play(play)==0&&gates.commands==1&&bank.pinned_samples()==1,"explicit positive source fixture reaches exact original file transport");command={};command.kind=AudioCommandKindV34::stop_all;check(mixer->post(command),"cancel future source timestamp immediately");mixer->render(buffer.data(),32);bank.pump_receipts();check(bank.pinned_samples()==0&&mixer->active_voices()==0,"future play cannot block same-source cancellation");while(bank.take_receipt(receipt)){}gates.ready=false;check(owner.play(play)==-2&&gates.commands==1&&bank.pinned_samples()==0,"actual unavailable driver remains required");
 unsigned draws=0;authorities.random={&draws,[](void*p,int&value){value=int(++*static_cast<unsigned*>(p));return true;}};dh2::sound::VoxAudioBridgeV34 event_bridge(catalog,bank,123,authorities);check(event_bridge.bind_source_autogen({{event,1}},error),"source event binding");dh2::sound::VoxPlay3DOwnerV2 event_owner(event_bridge.services());check(event_owner.play(play)==-2&&draws==2&&gates.commands==1,"driver-unavailable branch retains exact source event RNG prefix");
 std::cout<<"PASS "<<checks<<" checks; PCM="<<pcm<<" IMA="<<ima<<" VoxN="<<native<<"; positive CPU output=true; Android audible=false\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}

