#!/usr/bin/env bash
# P16 LEVELS: builds LEVEL-COVERAGE.md and LEVEL-COVERAGE.json from
#   1. the inventory produced by level_inventory.exe (inventory.md + inventory.json),
#   2. the quiet batch run (summary.json, per-level logs and PPM captures).
# Usage: make_level_coverage.sh INVENTORY_MD RUN_DIR OUT_DIR
# Brightness is the mean gray level of the 1x1 area-scaled capture (ffmpeg); 0-2 means a blank view.
set -euo pipefail
INV_MD="$1"; RUN_DIR="$2"; OUT_DIR="$3"
FF="${FFMPEG:-/c/Users/adamc/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.1.2-full_build/bin/ffmpeg.exe}"
MD="$OUT_DIR/LEVEL-COVERAGE.md"
JS="$OUT_DIR/LEVEL-COVERAGE.json"
TSV="$(mktemp)"
trap 'rm -f "$TSV"' EXIT

# exit code per job name from the runner summary (objects: "name", "exitCode")
exit_of() {
  awk -v n="$1" '
    /"name":/ { gsub(/[",]/, "", $2); cur=$2 }
    /"exitCode":/ { if (cur==n) { gsub(/,/, "", $2); print $2; exit } }' "$RUN_DIR/summary.json"
}

{
  echo "# id|act|file|table|kind|geom|tri|modules|decls|classes|pkg|android|missing|unresolved|bmin|bmax|spawn"
  awk -F'|' 'NR>2 { for (i=2;i<=NF;i++) gsub(/^ +| +$/, "", $i); gsub(/`/, "", $4); print $2"|"$3"|"$4"|"$5"|"$6"|"$7"|"$8"|"$9"|"$10"|"$11"|"$12"|"$13"|"$14"|"$15"|"$16"|"$17"|"$18 }' "$INV_MD"
} > "$TSV.rows"

jq_free_escape() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

{
  echo "# Level coverage (Preview 16, generality gate)"
  echo
  echo "Generated by \`make_level_coverage.sh\` from \`level_inventory.exe\` and the quiet batch in \`$RUN_DIR\`."
  echo "Act numbers are inferred from file-id bands (not stored in the level data): unverified."
  echo
  echo "## Status legend"
  echo
  echo "- **loads+renders**: fixed map loads (geometry, population), quiet run exits 0 and the default-camera capture is not blank."
  echo "- **loads, blank view**: fixed map loads and runs, but the capture from the authored EntryPoint is blank (geometry or camera outside view)."
  echo "- **blocked: X**: the EXE stops with a named error before a frame is drawn."
  echo "- **not run: procedural**: \`.rule.xml\` levels have no path in the Windows EXE; the canonical port (port/level-loader/procedural_*_v1) has the reader and layout generator, not yet wired (gap 7)."
  echo
  echo "Run settings for fixed maps: \`--start-mode swamp\` with a generic KnightPlayerBase (no Swamp combat rows), \`--profiles actor-profiles-v2.xml\`, \`--original-camera\`, \`--position\` = the first authored EntryPoint (SpawnPoint) of the level, 30 frames, \`--fixed-step 0.0333\`, quiet hidden desktop (\`quiet_run.ps1\`). The first EntryPoint is a coverage heuristic, not the original entry rule."
  echo
  echo "## Fixed maps (.mlx)"
  echo
  echo "| id | act (inferred) | level file | level table name | run | geometry | triangles | module placements | declarations (authored) | authored classes | assets in package | assets in Android | missing in both | unresolved refs | spawn (first EntryPoint) | status | unsupported classes logged | mean gray |"
  echo "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"
} > "$MD"

json_rows=()
while IFS='|' read -r id act file table kind geom tri modules decls classes pkg android missing unresolved bmin bmax spawn; do
  [ "$kind" = "fixed .mlx" ] || continue
  name="${file}"; stem="${name%.mlx}"
  log="$RUN_DIR/$stem.log"; ppm="$RUN_DIR/$stem.ppm"
  rc="$(exit_of "$stem" || true)"; [ -n "$rc" ] || rc="n/a"
  err=""; [ -f "$log" ] && err="$(grep -h 'Foundation error' "$log" | head -1 | sed 's/^Foundation error: //' || true)"
  unsup="$(grep -h '^Unsupported class' "$log" 2>/dev/null | sed 's/^Unsupported class \([A-Za-z]*\) status=\([a-z_]*\) declarations=\([0-9]*\).*/\1(\2,\3)/' | paste -sd ',' - || true)"
  lum="-"; [ -f "$ppm" ] && lum="$("$FF" -loglevel error -i "$ppm" -vf "scale=1:1:flags=area" -f rawvideo -pix_fmt gray - 2>/dev/null | od -An -tu1 | tr -d ' ' || true)"
  if [ -n "$err" ]; then status="blocked: $err"
  elif [ "$rc" = "0" ] && [ -f "$ppm" ] && [ -n "$lum" ] && [ "$lum" -gt 2 ] 2>/dev/null; then status="loads+renders"
  elif [ "$rc" = "0" ] && [ -f "$ppm" ]; then status="loads, blank view"
  else status="not run (exit $rc)"; fi
  pop="$(grep -h '^Population visuals' "$log" 2>/dev/null | head -1 | sed 's/Population visuals=//' || true)"
  printf '| %s | %s | `%s` | %s | exit %s | %s | %s | %s | %s (%s) | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n' \
    "$id" "$act" "$name" "${table:--}" "$rc" "$geom" "$tri" "$modules" "$decls" "${pop:--}" "$classes" "$pkg" "$android" "$missing" "$unresolved" "$spawn" "$status" "${unsup:--}" "$lum" >> "$MD"
  json_rows+=("{\"id\":\"$(jq_free_escape "$id")\",\"file\":\"$(jq_free_escape "$name")\",\"act_inferred\":\"$(jq_free_escape "$act")\",\"table_name\":\"$(jq_free_escape "$table")\",\"exit\":\"$rc\",\"geometry\":\"$geom\",\"triangles\":\"$tri\",\"module_placements\":\"$modules\",\"declarations\":\"$decls\",\"classes\":\"$(jq_free_escape "$classes")\",\"assets_package\":\"$pkg\",\"assets_android\":\"$android\",\"missing_both\":\"$missing\",\"unresolved\":\"$unresolved\",\"spawn\":\"$(jq_free_escape "$spawn")\",\"status\":\"$(jq_free_escape "$status")\",\"unsupported_classes\":\"$(jq_free_escape "${unsup:-}")\",\"mean_gray\":\"$lum\"}")
done < <(awk -F'|' 'NR>1' "$TSV.rows")

{
  echo
  echo "## Procedural levels (.rule.xml): not run"
  echo
  echo "| id | act (inferred) | file | level table name | rule tags (from XML) |"
  echo "|---|---|---|---|---|"
  while IFS='|' read -r id act file table kind geom tri modules decls classes pkg android missing unresolved bmin bmax spawn; do
    [ "$kind" = "procedural .rule.xml" ] || continue
    printf '| %s | %s | `%s` | %s | %s |\n' "$id" "$act" "$file" "${table:--}" "$classes"
  done < <(awk -F'|' 'NR>1' "$TSV.rows")
} >> "$MD"

# JSON: inventory (tool output) plus the per-level run record.
{
  echo "{"
  echo "\"generator\":\"coordination/claude-preview16/level-coverage/make_level_coverage.sh\","
  echo "\"fixed_maps\":["
  first=1; for r in "${json_rows[@]}"; do [ $first = 1 ] || echo ","; first=0; printf '%s' "$r"; done
  echo
  echo "],"
  echo "\"inventory_file\":\"coordination/claude-preview16/level-coverage/inventory.json\""
  echo "}"
} > "$JS"
rm -f "$TSV.rows"
cat "$(dirname "$0")/static-sections.md" >> "$MD"
echo "wrote $MD and $JS"
