#include "../general_fx_texture_image_v2.hpp"
#include "../texture_binding_owner_v1.hpp"
#include "../texture_mipmap_v1.hpp"
#include "../texture_unbind_v1.hpp"
#include <EGL/egl.h>
#include <GLES2/gl2.h>
#include <fstream>
#include <iostream>
#include <algorithm>
#include <cstring>
using namespace dh2::textures;
static unsigned checks,images,uploads,generations;
static void check(bool x,const char* what){++checks;if(!x)throw std::runtime_error(what);}
int main(int argc,char** argv){try{if(argc!=2)return 1;const std::string dir=argv[1];EGLDisplay display=eglGetDisplay(EGL_DEFAULT_DISPLAY);check(eglInitialize(display,nullptr,nullptr),"EGL");const EGLint cfgattrs[]{EGL_SURFACE_TYPE,EGL_PBUFFER_BIT,EGL_RENDERABLE_TYPE,EGL_OPENGL_ES2_BIT,EGL_RED_SIZE,8,EGL_GREEN_SIZE,8,EGL_BLUE_SIZE,8,EGL_ALPHA_SIZE,8,EGL_NONE};EGLConfig cfg;EGLint n;check(eglChooseConfig(display,cfgattrs,&cfg,1,&n)&&n==1,"GLES config");const EGLint dims[]{EGL_WIDTH,8,EGL_HEIGHT,8,EGL_NONE},version[]{EGL_CONTEXT_CLIENT_VERSION,2,EGL_NONE};
 for(unsigned cycle=0;cycle<2;++cycle){auto surface=eglCreatePbufferSurface(display,cfg,dims);auto context=eglCreateContext(display,cfg,EGL_NO_CONTEXT,version);check(eglMakeCurrent(display,surface,surface,context),"Actual context");const auto* ext=reinterpret_cast<const char*>(glGetString(GL_EXTENSIONS));check(ext,"Extensions");Gles2TextureSamplerFeaturesV1 features;std::string error;check(texture_gles2_sampler_features_v1(ext,[](auto pname,float& out,std::string&){glGetFloatv(pname,&out);return glGetError()==GL_NO_ERROR;},features,error),error.c_str());
  std::ifstream list(dir+"/images.txt");check(bool(list),"Actual image manifest");std::string name;while(std::getline(list,name)){if(!name.empty()&&name.back()=='\r')name.pop_back();std::ifstream f(dir+"/"+name,std::ios::binary);check(bool(f),"Actual image");auto raw=std::make_shared<const std::vector<std::uint8_t>>(std::istreambuf_iterator<char>(f),std::istreambuf_iterator<char>());View view{};check(dh2_texture_open(raw->data(),raw->size(),&view)==Error::ok,"Existing actual View/Open");Description source{};check(dh2_pvr_describe(raw->data(),raw->size(),&source)&&source.kind==0&&!source.mipmapped,"Actual census nonmipped PVR");std::vector<std::uint8_t> expected(std::size_t(view.width)*view.height*4);check(dh2_texture_decode(&view,expected.data(),expected.size())==Error::ok,"Existing actual decoder");if(cycle==0)++images;
   for(std::uint32_t options:{0u,0x10u}){GeneralFxTextureImageOwnerV2 image;check(image.initialize(raw,features,{},&options,[](auto from,auto to,std::string&){return from!=to&&to==14;},error),error.c_str());check(image.descriptor().width==view.width&&image.descriptor().height==view.height&&image.descriptor().format==14,"Actual dimensions/decoded format");check(image.source_format()==source.engine_format&&image.rgba()==expected,"Source format/pixel identity");check(image.descriptor().mipmapped==bool(options&0x10),"Source driver mip request");
    TextureBindingOwnerV1 grid;TextureGlCacheFieldsV1 cache{};GLint actual_units;glGetIntegerv(GL_MAX_TEXTURE_IMAGE_UNITS,&actual_units);std::uint32_t units=std::min(unsigned(actual_units),8u);TextureBindingDriverBorrowV1 driver{&units,&cache.active_unit268};GLuint texture{};auto& owner=image.parameters();auto& fields=owner.fields();TextureBindingReceiverV1 receiver{&image,&fields.flags3f,&fields.dirty40,&texture};TextureBindingServicesV1 binding;binding.active_texture=[](auto unit,std::string&){glActiveTexture(unit);return true;};binding.bind_texture=[](auto target,auto value,std::string&){glBindTexture(target,value);return true;};binding.update=texture_clean_update_false_v1;
    TextureInitialBindServicesV1 initial;initial.active_texture=binding.active_texture;initial.bind_texture=binding.bind_texture;initial.generate_texture=[](auto& value,std::string&){glGenTextures(1,&value);return true;};check(grid.initial_bind_impl_prefix(receiver,fields,texture,driver,initial,error),error.c_str());TextureParameterServicesV1 parameters;parameters.integer=[](auto target,auto pname,auto value,std::string&){glTexParameteri(target,pname,value);return true;};parameters.scalar=[](auto target,auto pname,float value,std::string&){glTexParameterf(target,pname,value);return true;};parameters.format_flags=general_fx_texture_format_flags_v2;check(owner.update(image.driver(),parameters,error),error.c_str());
    TextureUpload2dBorrowV1 payload;check(image.upload_borrow(&cache.unpack_alignment26c,payload,error),error.c_str());TextureUpload2dServicesV1 upload;upload.image=[&](auto target,auto mip,auto w,auto h,auto internal,const std::uint8_t* bytes,std::size_t size,bool compressed,auto format,auto type,std::string&){check(!compressed&&mip==0&&w==view.width&&h==view.height&&size==expected.size(),"Genuine base upload");check(!std::memcmp(bytes,expected.data(),size),"Actual upload pixel bytes");glTexImage2D(target,mip,internal,w,h,0,format,type,bytes);++uploads;return true;};upload.gl_error=[](auto& value,std::string&){value=glGetError();return true;};upload.pixel_store=[](auto pname,auto value,std::string&){glPixelStorei(pname,value);return true;};upload.generate_mipmaps=[&](std::string& e){TextureMipmapServicesV1 mip;mip.bind=[&](auto unit,const void* identity,auto kind,std::string& why){check(identity==&image,"Same generation receiver");return grid.set_texture(unit,receiver,kind,driver,binding,why);};mip.active_texture=binding.active_texture;mip.generate=[](auto target,std::string&){glGenerateMipmap(target);++generations;return true;};mip.integer=parameters.integer;return owner.generate_mipmaps(&image,{&units,&cache.active_unit268},mip,e);};check(owner.upload(payload,upload,error)&&owner.ready(),error.c_str());check(glGetError()==GL_NO_ERROR,"Actual GLES upload/mips");GLint min,mag,wraps,wrapt;glGetTexParameteriv(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,&min);glGetTexParameteriv(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,&mag);glGetTexParameteriv(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,&wraps);glGetTexParameteriv(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,&wrapt);check(min==(options?GL_LINEAR_MIPMAP_NEAREST:GL_LINEAR)&&mag==GL_LINEAR&&wraps==GL_REPEAT&&wrapt==GL_REPEAT,"Original sampler policy");GLuint framebuffer;glGenFramebuffers(1,&framebuffer);glBindFramebuffer(GL_FRAMEBUFFER,framebuffer);glFramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,texture,0);check(glCheckFramebufferStatus(GL_FRAMEBUFFER)==GL_FRAMEBUFFER_COMPLETE,"Genuine uploaded RGBA FBO");std::uint8_t pixel[4];glReadPixels(0,0,1,1,GL_RGBA,GL_UNSIGNED_BYTE,pixel);check(!std::memcmp(pixel,expected.data(),4),"Actual GPU first pixel");glBindFramebuffer(GL_FRAMEBUFFER,0);glDeleteFramebuffers(1,&framebuffer);TextureUnbindServicesV1 cleanup;cleanup.delete_texture=[](auto value,std::string&){glDeleteTextures(1,&value);return true;};check(texture_unbind_2d_v1(grid,receiver,fields,texture,driver,binding,payload.pending_bits,payload.pending_word_count,cleanup,false,error),error.c_str());check(glGetError()==GL_NO_ERROR,"Clean actual destruction");
   }
  }eglMakeCurrent(display,EGL_NO_SURFACE,EGL_NO_SURFACE,EGL_NO_CONTEXT);eglDestroyContext(display,context);eglDestroySurface(display,surface);
 }eglTerminate(display);check(images==41&&uploads==164&&generations==82,"Full image/options/context census");std::cout<<"PASS "<<checks<<" checks; actual_image_names "<<images<<"; uploads "<<uploads<<"; real_mip_generations "<<generations<<"; contexts2; live_actor=false\n";return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
