#pragma once

// Original dqhud_droid HUD panels (PC HUD action button, cutscene SKIP, caption box, quest banners).
// The batch data is generated by features/hud_panels/export_hud_panels_v1.py from the exact SWF display lists;
// batches are in the original 480x320 stage and need no fit. Bitmap batches sample MenusGraphics_droid (atlas
// bitmap 1); solid batches tint the white texel with rgba.

#include "../generic_skills/pc_gameplay_hud_button_art_v1.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <vector>

namespace dh::foundation::hud_panels {

using generic_skills::PcGameplayHudArtBatchV1;

// One dynamic text field of an original panel, in stage px. container is the authored placement that holds the
// field (TextBox, NameBox, dialogBox...), name is the field's own placement (Title, Desc, TitleReal, RewardTitle).
// align: 0 left, 2 centre (EditText layout).
struct HudPanelTextSlotV1 {
    const char* container;
    const char* name;
    std::array<float, 4> rect; // x0, y0, x1, y1
    std::array<std::uint8_t, 4> rgba;
    float height;
    int align;
};

// Action button btn_interact (PC HUD controls row). The idle ring and the pressed ring are separate batch sets;
// the icon batches are indexed by the authored btimg frame (0 Chest, 1 Item, 2 Lever, 3 Character, 4 Revive,
// 5 Attack, 6 Shrine, 7 Inspect), which is the icon value the context button publishes.
const std::vector<PcGameplayHudArtBatchV1>& action_base_v1() noexcept;
const std::vector<PcGameplayHudArtBatchV1>& action_pressed_v1() noexcept;
const std::vector<PcGameplayHudArtBatchV1>& action_icon_v1(std::size_t btimg_frame) noexcept;
std::size_t action_icon_count_v1() noexcept;

// Cutscene SKIP control (menu_skipcutscene -> btn_MENU_SKIP idle): the X icon and its plate, and the SKIP text slot.
const std::vector<PcGameplayHudArtBatchV1>& skip_batches_v1() noexcept;
const std::vector<HudPanelTextSlotV1>& skip_texts_v1() noexcept;

// Caption box (DialogBox ChestTuto variant: name plate and text band, both bitmap-filled).
const std::vector<PcGameplayHudArtBatchV1>& caption_batches_v1() noexcept;
const std::vector<HudPanelTextSlotV1>& caption_texts_v1() noexcept;

// Quest banners (DialogBox QuestMsgDialog and QuestCompletedMsgDialog variants, rest poses).
const std::vector<PcGameplayHudArtBatchV1>& quest_new_batches_v1() noexcept;
const std::vector<HudPanelTextSlotV1>& quest_new_texts_v1() noexcept;
const std::vector<PcGameplayHudArtBatchV1>& quest_done_batches_v1() noexcept;
const std::vector<HudPanelTextSlotV1>& quest_done_texts_v1() noexcept;

// Original SKIP label (MENU_SKIP in the source label table; the SWF text field is set by ActionScript at run time).
inline constexpr const char* kSkipLabelV1 = "SKIP";

} // namespace dh::foundation::hud_panels
