// Reuse frozen genuine localization/Debug adapters; the historical test and
// its receipt stay unchanged. This new test replaces its null Visual branch.
#define main frozen_v5_cache_fixture_main
#include "../../game-data/tests/player_gear_cache_v5.cpp"
#undef main
#include "../visual_skin_owner_v6.hpp"
#include <filesystem>
#include <cctype>
using namespace dh2::skinning;
struct WeaponFiles {std::string directory;unsigned reads{};};
static VisualAssetResultV6 read_weapon(void* raw,const char* name,Raw& bytes,std::string&){auto& p=*static_cast<WeaponFiles*>(raw);++p.reads;std::string uri=name;uri=uri.substr(uri.find_last_of('/')+1);for(auto& c:uri)c=char(std::tolower(static_cast<unsigned char>(c)));auto full=p.directory+"/"+uri;if(!std::filesystem::exists(full))return VisualAssetResultV6::missing;bytes=file(full);return VisualAssetResultV6::found;}
static bool skin_debug(void* p,FreshInventoryOwnedV4&,const GearSkinRequestV5& q,std::int32_t& result,std::string& e){auto& c=*static_cast<TextEnvironment*>(p);dh2::character::DebugFileServices24 ds{&c,debug_open,debug_close};if(q.operation==GearSkinOperationV5::debug_load){if(dh2_character_debug_load(c.debug,&ds)!=1){e="V6 Debug Load failed";return false;}return true;}if(q.operation==GearSkinOperationV5::debug_query){unsigned value;if(dh2_character_debug_get(&value,c.debug,q.name,&ds)!=1){e="V6 Debug GetSwitch failed";return false;}std::memcpy(&result,&value,4);return true;}e="V6 unexpected Debug operation";return false;}
struct Live {Context prior;VisualSkinOwnerV6* visual;GearSkinServicesV5 services;};
static bool live_effect(void* p,FreshInventoryOwnedV4& i,const OwnedInventoryRequestV4& q,OwnedInventoryResponseV4& result,std::string& e){auto& c=*static_cast<Live*>(p);if(q.operation==OwnedInventoryOperationV4::skin){++c.prior.skin;return c.prior.gear->update_skin(&c.prior.visual,c.services,e);}return effects(&c.prior,i,q,result,e);}
static std::string next_string(Reader& r){auto n=r.u();std::string out(n,'\0');r.copy(out.data(),n);return out;}
int main(int argc,char** argv){try{ck(argc==11);std::string e;auto cache=std::string(argv[2]);auto bytes=file(cache+"/loot_table_pyarray.bin"),names=file(cache+"/loot_table_pyarraynames.bin"),schema=file(cache+"/loot_table_pystructnames.bin");LootTablesV2 table;ck(table.load({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));cache=argv[3];bytes=file(cache+"/item_powers_pyarray.bin");names=file(cache+"/item_powers_pyarraynames.bin");schema=file(cache+"/item_powers_pystructnames.bin");ItemPowerTablesV5 powers;ck(powers.load({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},e));cache=argv[4];bytes=file(cache+"/character_properties_pyarray.bin");names=file(cache+"/character_properties_pyarraynames.bin");schema=file(cache+"/character_properties_pystructnames.bin");CharacterTable chars;ck(load_characters({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},chars,e));PropertyRules rules;ck(load_property_rules(chars,rules,e));cache=argv[5];bytes=file(cache+"/character_classes_pyarray.bin");names=file(cache+"/character_classes_pyarraynames.bin");schema=file(cache+"/character_classes_pystructnames.bin");ClassTables classes;ck(load_classes({bytes.data(),bytes.size()},{names.data(),names.size()},{schema.data(),schema.size()},classes,e));std::vector<ClassRow> rows;for(auto& x:classes.rows)rows.push_back({x.data(),std::uint32_t(x.size())});TextEnvironment env;env.assets=argv[6];env.private_files=argv[7];ck(env.constants&&env.debug);auto constants=file(env.assets+"/original-cache/data/pydata/common_text_pycst.bin");dh2_script_constants_reload receipt{};ck(!dh2_script_constants_load(env.constants,constants.data(),constants.size(),&receipt));dh2::ui::HudTextV1 text_owner;auto text=file(env.assets+"/original-cache/data/pydata/common_text_pyarray.bin"),text_names=file(env.assets+"/original-cache/data/pydata/common_text_pyarraynames.bin"),text_schema=file(env.assets+"/original-cache/data/pydata/common_text_pystructnames.bin");ck(text_owner.load({text.data(),text.size()},{text_names.data(),text_names.size()},{text_schema.data(),text_schema.size()},e)&&text_owner.switch_pack(0,false,e));dh2::ui::LocalizationServices loc{&env,text_open,text_close,text_debug,text_constant,nullptr,nullptr};dh2::ui::HudTextEnvironmentV1 text_environment{loc};dh2::ui::ItemTextOwnerV5 text_adapter(table.borrow().items(),chars,text_owner,text_environment);
 auto original=file(argv[1]);Reader r{original};ck(r.u()==0x36565349);auto cases=r.u();auto old_gold=file(argv[10]);Reader g{old_gold};ck(g.u()==0x35564547&&g.u()==cases);VisualSkinResourcesV6 resource_owner;ck(resource_owner.load(file(argv[8]),e));WeaponFiles weapons{argv[9]};unsigned steps=0,skin=0,properties=0,vitals=0;std::vector<VisualDrawPartV6> retained;
 for(unsigned k=0;k<cases;++k){auto baseid=r.u(),selected=r.u(),count=r.u();ck(g.u()==baseid&&g.u()==selected&&g.u()==count);auto state=std::make_shared<PropertyState>();reset_properties(rules,*state,&chars.rows.at(baseid));auto view=property_view(rules,*state);ck(dh2_class_recalc_base(rows.data(),rows.size(),state->base.data(),&view)==0);PropertyState initial;g.copy(&initial,sizeof initial);ck(!std::memcmp(state.get(),&initial,sizeof initial));LootRandom8V2 random{1,0};FreshInventoryOwnedV4 inv(0x100000001,table.borrow(),random,12,state);if(selected)inv.swap_equipment();PlayerGearEffectsV5 gear(inv,view,rows.data(),rows.size(),powers.borrow());auto live_scene=resource_owner.borrow().factory_scene();VisualSkinOwnerV6 visual(resource_owner.borrow(),live_scene,{&weapons,read_weapon});ck(visual.initialize(e));Live ctx{{&gear,&text_adapter,&env},&visual,visual.gear_services({&env,skin_debug})};ctx.prior.visual=visual.identity();OwnedInventoryServicesV4 services{&ctx,live_effect};
  for(unsigned j=0;j<count;++j){auto op=r.u(),a=r.u(),b=r.u(),c=r.u(),expected=r.u();ck(g.u()==op&&g.u()==a&&g.u()==b&&g.u()==c&&g.u()==expected);std::array<std::int32_t,4> modules;for(auto& m:modules){auto w=r.u();std::memcpy(&m,&w,4);}auto right=next_string(r),left=next_string(r);std::int32_t result=0;bool delivered=false;
   if(op==0)delivered=inv.add_fixed_loot(std::int32_t(a),services,e);else if(op==2)delivered=inv.character_auto_equip(a,result,services,e);else if(op==5){inv.swap_equipment();delivered=true;}else if(op==4)delivered=inv.unequip_from_slot(a,std::int32_t(b),services,e);else if(op==15)delivered=gear.update_properties(e)&&gear.update_skin(&ctx.prior.visual,ctx.services,e)&&gear.validate_hp_mp(e);if(!delivered)throw std::runtime_error("V6 owned class "+std::to_string(baseid)+" step "+std::to_string(j)+": "+e);ck(std::uint32_t(result)==expected);ck(gear.update_skin(&ctx.prior.visual,ctx.services,e));for(unsigned q=0;q<4;++q)ck(visual.current_module(q)==modules[q]);ck(visual.weapon_uri(1)==right&&visual.weapon_uri(2)==left);PropertyState source;g.copy(&source,sizeof source);ck(!std::memcmp(state.get(),&source,sizeof source));std::vector<VisualDrawPartV6> draw;ck(visual.draw_parts(draw,e)&&!draw.empty());for(auto& part:draw)ck(part.retention&&part.geometry&&!part.positions.empty());if(j==count-1)retained=draw;++steps;
  }skin+=ctx.prior.skin;properties+=ctx.prior.properties;vitals+=ctx.prior.vitals;
 }
 ck(r.at==original.size()&&g.at==old_gold.size());ck(env.opened==env.closed&&!retained.empty()&&!retained[0].geometry->positions.empty());std::cout<<"{\"validation\":\"PASS\",\"source_cases\":"<<cases<<",\"source_inventory_operations\":"<<steps<<",\"same_owned_V4_starter_classes\":3,\"genuine_skin_effects\":"<<skin<<",\"genuine_property_effects\":"<<properties<<",\"genuine_vitals_effects\":"<<vitals<<",\"genuine_weapon_resource_reads\":"<<weapons.reads<<",\"checks\":"<<checks<<",\"mismatches\":0}\n";return 0;
}catch(const std::exception& x){std::cerr<<x.what()<<'\n';return 1;}}
