#include "android_intro_movie_v119.hpp"
#include <mutex>
#include <limits>
namespace dh2::android_ui {namespace {
struct Intro {std::mutex mutex;JavaVM* vm{};jweak activity{};jobject assets{};jmethodID start{},language{};std::uint64_t generation{};enum Phase {idle,requested,prepared,done,failed,closed} phase=idle;std::string name,error;IntroCacheReadV119 cache;};
Intro intro;
bool fail(std::string message,std::string& e){e=std::move(message);return false;}
}
bool bind_android_intro_movie_v119(JNIEnv* env,jobject activity,jobject assets,std::string& e){
 if(!env||!activity||!assets)return fail("Required actual Android intro Activity/assets",e);
 std::lock_guard<std::mutex> lock(intro.mutex);
 if(intro.activity){auto previous=env->NewLocalRef(intro.activity);const bool same=previous&&env->IsSameObject(previous,activity);if(previous)env->DeleteLocalRef(previous);if(same){e.clear();return true;}return fail("Intro Activity replacement requires actual close",e);}
 auto type=env->GetObjectClass(activity);auto start=env->GetMethodID(type,"startSourceIntroV119","(JILjava/lang/String;)V");auto language=env->GetMethodID(type,"platformLanguageV119","()I");env->DeleteLocalRef(type);
 if(env->ExceptionCheck()){env->ExceptionClear();return fail("Missing actual Android intro UI method",e);}if(!start||!language||env->GetJavaVM(&intro.vm)!=JNI_OK)return fail("Required actual Android intro JVM",e);
 intro.activity=env->NewWeakGlobalRef(activity);intro.assets=env->NewGlobalRef(assets);if(!intro.activity||!intro.assets){if(env->ExceptionCheck())env->ExceptionClear();if(intro.activity)env->DeleteWeakGlobalRef(intro.activity);if(intro.assets)env->DeleteGlobalRef(intro.assets);intro.activity=nullptr;intro.assets=nullptr;return fail("Android intro owner allocation failed",e);}
 intro.start=start;intro.language=language;intro.phase=Intro::idle;intro.error.clear();e.clear();return true;
}
bool bind_android_intro_cache_v119(IntroCacheReadV119 callback,std::string& e){std::lock_guard<std::mutex> lock(intro.mutex);if(!callback||intro.phase==Intro::requested||intro.phase==Intro::prepared)return fail("Required idle actual intro cache provider",e);intro.cache=std::move(callback);e.clear();return true;}
bool start_android_intro_movie_v119(std::int32_t language,std::string& e){
 JavaVM* vm{};jweak activity{};jmethodID method{};std::uint64_t generation{};std::string name;
 {std::lock_guard<std::mutex> lock(intro.mutex);if(!intro.activity||!intro.vm||intro.phase!=Intro::idle)return fail("Required idle bound Android intro owner",e);if(intro.generation==std::numeric_limits<std::uint64_t>::max())return fail("Intro generation exhausted",e);generation=++intro.generation;intro.name=language==4?"intro_jp.mp4":language==5?"intro_kr.mp4":"intro.mp4";name=intro.name;intro.phase=Intro::requested;vm=intro.vm;activity=intro.activity;method=intro.start;}
 JNIEnv* env{};bool attached=false;if(vm->GetEnv(reinterpret_cast<void**>(&env),JNI_VERSION_1_6)!=JNI_OK){if(vm->AttachCurrentThread(&env,nullptr)!=JNI_OK)return fail("Android intro JVM thread attachment failed",e);attached=true;}
 //Hold the native reference while converting its weak owner to a local loan.
 jobject receiver{};{std::lock_guard<std::mutex> lock(intro.mutex);if(intro.activity==activity)receiver=env->NewLocalRef(activity);}
 if(receiver){auto text=env->NewStringUTF(name.c_str());if(text)env->CallVoidMethod(receiver,method,static_cast<jlong>(generation),static_cast<jint>(language),text);if(text)env->DeleteLocalRef(text);env->DeleteLocalRef(receiver);}
 const bool exception=env->ExceptionCheck();if(exception)env->ExceptionClear();if(attached)vm->DetachCurrentThread();
 if(!receiver||exception){std::lock_guard<std::mutex> lock(intro.mutex);if(intro.generation==generation){intro.phase=Intro::failed;intro.error="Android intro UI request failed";}return fail("Android intro UI request failed",e);}e.clear();return true;
}
bool intro_finished_v119(bool& done,std::string& e){std::lock_guard<std::mutex> lock(intro.mutex);done=false;if(intro.phase==Intro::failed)return fail(intro.error,e);if(!intro.activity||intro.phase==Intro::idle||intro.phase==Intro::closed)return fail("Required actual requested Android intro lifecycle",e);done=intro.phase==Intro::done;e.clear();return true;}
bool platform_language_v119(std::uint32_t& value,std::string& e){JavaVM* vm{};{std::lock_guard<std::mutex> lock(intro.mutex);vm=intro.vm;if(!vm||!intro.activity||!intro.language)return fail("Required actual Android Locale/Activity owner",e);}JNIEnv* env{};bool attached=false;if(vm->GetEnv(reinterpret_cast<void**>(&env),JNI_VERSION_1_6)!=JNI_OK){if(vm->AttachCurrentThread(&env,nullptr)!=JNI_OK)return fail("Locale JVM attachment failed",e);attached=true;}jobject activity{};jmethodID method{};{std::lock_guard<std::mutex> lock(intro.mutex);if(intro.activity)activity=env->NewLocalRef(intro.activity);method=intro.language;}jint result=0;if(activity&&method)result=env->CallIntMethod(activity,method);const bool exception=env->ExceptionCheck();if(exception)env->ExceptionClear();if(activity)env->DeleteLocalRef(activity);if(attached)vm->DetachCurrentThread();if(!activity||!method||exception||result<0)return fail("Actual Android Locale delivery failed",e);value=static_cast<std::uint32_t>(result);e.clear();return true;}
void close_android_intro_movie_v119(JNIEnv* env){if(!env)return;std::lock_guard<std::mutex> lock(intro.mutex);if(intro.activity)env->DeleteWeakGlobalRef(intro.activity);if(intro.assets)env->DeleteGlobalRef(intro.assets);intro.activity=nullptr;intro.assets=nullptr;intro.start=nullptr;intro.phase=Intro::closed;}
}
extern "C" JNIEXPORT jstring JNICALL Java_com_example_dh2_NativeBridge_bindIntroMovieV119(JNIEnv* env,jclass,jobject activity,jobject assets){std::string e;dh2::android_ui::bind_android_intro_movie_v119(env,activity,assets,e);return e.empty()?nullptr:env->NewStringUTF(e.c_str());}
extern "C" JNIEXPORT void JNICALL Java_com_example_dh2_NativeBridge_closeIntroMovieV119(JNIEnv* env,jclass){dh2::android_ui::close_android_intro_movie_v119(env);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dh2_NativeBridge_introMovieEventV119(JNIEnv* env,jclass,jlong generation,jint event,jstring error){using namespace dh2::android_ui;std::lock_guard<std::mutex> lock(intro.mutex);if(static_cast<std::uint64_t>(generation)!=intro.generation||intro.phase==Intro::done||intro.phase==Intro::failed||intro.phase==Intro::closed)return;if(event==0){if(intro.phase==Intro::requested)intro.phase=Intro::prepared;}else if(event==1||event==2){intro.phase=Intro::done;}else if(event==3){intro.phase=Intro::failed;const char* text=error?env->GetStringUTFChars(error,nullptr):nullptr;intro.error=text?text:"Actual Android intro media error";if(text)env->ReleaseStringUTFChars(error,text);}}
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_example_dh2_NativeBridge_introMovieCacheV119(JNIEnv* env,jclass,jlong generation){using namespace dh2::android_ui;IntroCacheReadV119 read;std::string name;{std::lock_guard<std::mutex> lock(intro.mutex);if(static_cast<std::uint64_t>(generation)!=intro.generation||intro.phase!=Intro::requested)return nullptr;read=intro.cache;name=intro.name;}bool found{};std::vector<std::uint8_t> bytes;std::string e;const bool delivered=read&&read(name,found,bytes,64u*1024u*1024u,e);if(!delivered||bytes.size()>64u*1024u*1024u){std::lock_guard<std::mutex> lock(intro.mutex);if(static_cast<std::uint64_t>(generation)==intro.generation){intro.phase=Intro::failed;intro.error=e.empty()?"Required admitted SAME process intro cache delivery":e;}return nullptr;}if(!found)return nullptr;auto output=env->NewByteArray(static_cast<jsize>(bytes.size()));if(output&&!bytes.empty())env->SetByteArrayRegion(output,0,static_cast<jsize>(bytes.size()),reinterpret_cast<const jbyte*>(bytes.data()));return output;}
