#pragma once
//Original ARM Load switch order, extracted from 4c373c and 4aa250.
namespace dh2::android_ui {
struct ProcessPyDataFileV101 {const char* uri;const char* registration;};
inline constexpr ProcessPyDataFileV101 process_pydata_constants_v101[]={
 {"pydata/ai_pycst.bin","ai_pycst.bin"}, //stage0
 {"pydata/animations_pycst.bin","animations_pycst.bin"}, //stage1
 {"pydata/character_classes_pycst.bin","character_classes_pycst.bin"}, //stage2
 {"pydata/character_properties_pycst.bin","character_properties_pycst.bin"}, //stage3
 {"pydata/design_pycst.bin","design_pycst.bin"}, //stage4
 {"pydata/dialogs_pycst.bin","dialogs_pycst.bin"}, //stage5
 {"pydata/effects_pycst.bin","effects_pycst.bin"}, //stage6
 {"pydata/engine_core_pycst.bin","engine_core_pycst.bin"}, //stage7
 {"pydata/faeries_pycst.bin","faeries_pycst.bin"}, //stage8
 {"pydata/fonts_pycst.bin","fonts_pycst.bin"}, //stage9
 {"pydata/game_objects_pycst.bin","game_objects_pycst.bin"}, //stage10
 {"pydata/item_powers_pycst.bin","item_powers_pycst.bin"}, //stage11
 {"pydata/levels_pycst.bin","levels_pycst.bin"}, //stage12
 {"pydata/loot_audiovisual_pycst.bin","loot_audiovisual_pycst.bin"}, //stage13
 {"pydata/loot_table_pycst.bin","loot_table_pycst.bin"}, //stage14
 {"pydata/multiplayer_pycst.bin","multiplayer_pycst.bin"}, //stage15
 {"pydata/projectiles_pycst.bin","projectiles_pycst.bin"}, //stage16
 {"pydata/scripts_pycst.bin","scripts_pycst.bin"}, //stage17
 {"pydata/skills_pycst.bin","skills_pycst.bin"}, //stage18
 {"pydata/sounds_pycst.bin","sounds_pycst.bin"}, //stage19
 {"pydata/specs_pycst.bin","specs_pycst.bin"}, //stage20
 {"pydata/trophies_pycst.bin","trophies_pycst.bin"}, //stage21
 {"pydata/v2conditions_pycst.bin","v2conditions_pycst.bin"}, //stage22
 {"pydata/v2eventmanager_pycst.bin","v2eventmanager_pycst.bin"}, //stage23
 {"pydata/v2quests_pycst.bin","v2quests_pycst.bin"}, //stage24
 {"pydata/worldmap_pycst.bin","worldmap_pycst.bin"}, //stage25
 {"pydata/common_text_pycst.bin","common_text_pycst.bin"}, //stage26
};
inline constexpr ProcessPyDataFileV101 process_pydata_arrays_v101[]={
 {"pydata/ai_pyarray.bin","ai_pyarray.bin"}, //stage0
 {"pydata/ai_factions_pyarray.bin","ai_factions_pyarray.bin"}, //stage1
 {"pydata/animations_pyarray.bin","animations_pyarray.bin"}, //stage2
 {"pydata/character_classes_pyarray.bin","character_classes_pyarray.bin"}, //stage3
 {"pydata/character_properties_pyarray.bin","character_properties_pyarray.bin"}, //stage4
 {"pydata/character_templates_pyarray.bin","character_templates_pyarray.bin"}, //stage5
 {"pydata/common_pyarray.bin","common_pyarray.bin"}, //stage6
 {"pydata/design_pyarray.bin","design_pyarray.bin"}, //stage7
 {"pydata/dialogs_pyarray.bin","dialogs_pyarray.bin"}, //stage8
 {"pydata/effects_pyarray.bin","effects_pyarray.bin"}, //stage9
 {"pydata/faeries_pyarray.bin","faeries_pyarray.bin"}, //stage10
 {"pydata/fonts_pyarray.bin","fonts_pyarray.bin"}, //stage11
 {"pydata/game_objects_pyarray.bin","game_objects_pyarray.bin"}, //stage12
 {"pydata/help_pages_pyarray.bin","help_pages_pyarray.bin"}, //stage13
 {"pydata/item_powers_pyarray.bin","item_powers_pyarray.bin"}, //stage14
 {"pydata/item_powers_monopoly_pyarray.bin","item_powers_monopoly_pyarray.bin"}, //stage15
 {"pydata/levels_pyarray.bin","levels_pyarray.bin"}, //stage16
 {"pydata/loot_audiovisual_pyarray.bin","loot_audiovisual_pyarray.bin"}, //stage17
 {"pydata/loot_table_pyarray.bin","loot_table_pyarray.bin"}, //stage18
 {"pydata/projectiles_pyarray.bin","projectiles_pyarray.bin"}, //stage19
 {"pydata/skills_pyarray.bin","skills_pyarray.bin"}, //stage20
 {"pydata/sounds_pyarray.bin","sounds_pyarray.bin"}, //stage21
 {"pydata/spawn_groups_pyarray.bin","spawn_groups_pyarray.bin"}, //stage22
 {"pydata/trophies_pyarray.bin","trophies_pyarray.bin"}, //stage23
 {"pydata/v2conditions_pyarray.bin","v2conditions_pyarray.bin"}, //stage24
 {"pydata/v2eventmanager_pyarray.bin","v2eventmanager_pyarray.bin"}, //stage25
 {"pydata/v2quests_pyarray.bin","v2quests_pyarray.bin"}, //stage26
 {"pydata/worldmap_pyarray.bin","worldmap_pyarray.bin"}, //stage27
 {"pydata/character_models_dictionary_pyarray.bin","character_models_dictionary_pyarray.bin"}, //stage28
 {"pydata/animations_dictionary_pyarray.bin","animations_dictionary_pyarray.bin"}, //stage29
 {"pydata/effects_dictionary_pyarray.bin","effects_dictionary_pyarray.bin"}, //stage30
 {"pydata/projectiles_dictionary_pyarray.bin","projectiles_dictionary_pyarray.bin"}, //stage31
 {"pydata/game_objects_dictionary_pyarray.bin","game_objects_dictionary_pyarray.bin"}, //stage32
 {"pydata/common_text_pyarray.bin","common_text_pyarray.bin"}, //stage33
 {"pydata/sdd_dungeon_hunter_2_iphone_pyarray.bin","sdd_dungeon_hunter_2_iphone_pyarray.bin"}, //stage34
 {"pydata/ai_pyarraynames.bin","ai_pyarraynames.bin"}, //stage35
 {"pydata/ai_factions_pyarraynames.bin","ai_factions_pyarraynames.bin"}, //stage36
 {"pydata/animations_pyarraynames.bin","animations_pyarraynames.bin"}, //stage37
 {"pydata/character_classes_pyarraynames.bin","character_classes_pyarraynames.bin"}, //stage38
 {"pydata/character_properties_pyarraynames.bin","character_properties_pyarraynames.bin"}, //stage39
 {"pydata/character_templates_pyarraynames.bin","character_templates_pyarraynames.bin"}, //stage40
 {"pydata/common_pyarraynames.bin","common_pyarraynames.bin"}, //stage41
 {"pydata/design_pyarraynames.bin","design_pyarraynames.bin"}, //stage42
 {"pydata/dialogs_pyarraynames.bin","dialogs_pyarraynames.bin"}, //stage43
 {"pydata/effects_pyarraynames.bin","effects_pyarraynames.bin"}, //stage44
 {"pydata/faeries_pyarraynames.bin","faeries_pyarraynames.bin"}, //stage45
 {"pydata/fonts_pyarraynames.bin","fonts_pyarraynames.bin"}, //stage46
 {"pydata/game_objects_pyarraynames.bin","game_objects_pyarraynames.bin"}, //stage47
 {"pydata/help_pages_pyarraynames.bin","help_pages_pyarraynames.bin"}, //stage48
 {"pydata/item_powers_pyarraynames.bin","item_powers_pyarraynames.bin"}, //stage49
 {"pydata/item_powers_monopoly_pyarraynames.bin","item_powers_monopoly_pyarraynames.bin"}, //stage50
 {"pydata/levels_pyarraynames.bin","levels_pyarraynames.bin"}, //stage51
 {"pydata/loot_audiovisual_pyarraynames.bin","loot_audiovisual_pyarraynames.bin"}, //stage52
 {"pydata/loot_table_pyarraynames.bin","loot_table_pyarraynames.bin"}, //stage53
 {"pydata/projectiles_pyarraynames.bin","projectiles_pyarraynames.bin"}, //stage54
 {"pydata/skills_pyarraynames.bin","skills_pyarraynames.bin"}, //stage55
 {"pydata/sounds_pyarraynames.bin","sounds_pyarraynames.bin"}, //stage56
 {"pydata/spawn_groups_pyarraynames.bin","spawn_groups_pyarraynames.bin"}, //stage57
 {"pydata/trophies_pyarraynames.bin","trophies_pyarraynames.bin"}, //stage58
 {"pydata/v2conditions_pyarraynames.bin","v2conditions_pyarraynames.bin"}, //stage59
 {"pydata/v2eventmanager_pyarraynames.bin","v2eventmanager_pyarraynames.bin"}, //stage60
 {"pydata/v2quests_pyarraynames.bin","v2quests_pyarraynames.bin"}, //stage61
 {"pydata/worldmap_pyarraynames.bin","worldmap_pyarraynames.bin"}, //stage62
 {"pydata/character_models_dictionary_pyarraynames.bin","character_models_dictionary_pyarraynames.bin"}, //stage63
 {"pydata/animations_dictionary_pyarraynames.bin","animations_dictionary_pyarraynames.bin"}, //stage64
 {"pydata/effects_dictionary_pyarraynames.bin","effects_dictionary_pyarraynames.bin"}, //stage65
 {"pydata/projectiles_dictionary_pyarraynames.bin","projectiles_dictionary_pyarraynames.bin"}, //stage66
 {"pydata/game_objects_dictionary_pyarraynames.bin","game_objects_dictionary_pyarraynames.bin"}, //stage67
 {"pydata/common_text_pyarraynames.bin","common_text_pyarraynames.bin"}, //stage68
 {"pydata/sdd_dungeon_hunter_2_iphone_pyarraynames.bin","sdd_dungeon_hunter_2_iphone_pyarraynames.bin"}, //stage69
};
}
