"""Actual isolated shader source DSO: original gold, owned pak and atomic rejects."""
import argparse,hashlib,json,shlex,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def linux(p):return '/mnt/'+p.drive[0].lower()+p.as_posix()[2:]
def main():
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=ROOT/'reports/shader-sources-host-audit.json');a=p.parse_args();folder=REPO/'.local-inputs/fx-render-connection-discovery/host';folder.mkdir(parents=True,exist_ok=True);cpp=ROOT/'shader_sources.cpp';test=ROOT/'tests/shader_sources.cpp';gold=ROOT/'reference/shader-sources/shader-source-fixtures.bin';lib=folder/'libdh2_shader_sources_audit.so';exe=folder/'shader_sources_audit';flags=['-std=c++17','-O1','-g','-fsanitize=address,undefined','-fno-omit-frame-pointer','-Wall','-Wextra','-Werror','-Wno-misleading-indentation']
 def command(argv):
  r=subprocess.run(['wsl','--','bash','-lc',shlex.join(argv)],capture_output=True,text=True);assert r.returncode==0,(r.returncode,r.stdout,r.stderr);return r
 sources=[cpp,ROOT/'shader_sources.hpp',test,Path(__file__)];before={str(x.relative_to(REPO)).replace('\\','/'):sha(x)for x in sources};compiler=command(['g++','--version']).stdout.strip();command(['g++',*flags,'-shared','-fPIC',linux(cpp),'-o',linux(lib)]);command(['g++',*flags,linux(test),'-L'+linux(folder),'-ldh2_shader_sources_audit','-Wl,-rpath,'+linux(folder),'-o',linux(exe)]);result=command(['env','ASAN_OPTIONS=detect_leaks=1:halt_on_error=1','UBSAN_OPTIONS=halt_on_error=1',linux(exe),linux(gold),linux(REPO/'.local-inputs/fx-render-connection-discovery/shaders.pak')]);assert not result.stderr,result.stderr;observed=json.loads(result.stdout);assert before=={str(x.relative_to(REPO)).replace('\\','/'):sha(x)for x in sources};report={**observed,'source_sha256':before,'library_sha256':sha(lib),'executable_sha256':sha(exe),'reference_sha256':sha(gold),'original_instruction_report_sha256':sha(ROOT/'reports/shader-sources-arm64-differential.json'),'isolated_shader_sources_library_executed':True,'main_scene_library_executed':False,'sanitizers':['AddressSanitizer','UndefinedBehaviorSanitizer'],'sanitizer_findings':0,'compiler':compiler,'flags':flags,'scope':'Original source/name/config gold, exact actual stored-ZIP input ownership and malformed container/text contracts. No GPU draw or original archive-reader parity.'};a.output.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items()if k not in ('source_sha256','compiler','flags','scope')}))
if __name__=='__main__':main()
