"""Isolated actual HUD texture DSO replay; leaves central libraries unchanged."""
import argparse,json,shlex,subprocess
from pathlib import Path
from swf_texture_differential import ROOT,REPO,sha
def linux(p):return '/mnt/'+p.drive[0].lower()+p.as_posix()[2:]
def main():
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,default=ROOT/'reports/swf-texture-host-audit.json');a=p.parse_args();folder=REPO/'.local-inputs/swf-render-connection-discovery/host';folder.mkdir(parents=True,exist_ok=True);cpp=ROOT/'swf_texture.cpp';test=ROOT/'tests/swf_texture.cpp';gold=ROOT/'reference/swf-render-connection/swf-texture-fixtures.bin';lib=folder/'libdh2_swf_texture_audit.so';exe=folder/'swf_texture_audit';flags=['-std=c++17','-O1','-g','-fsanitize=address,undefined','-fno-omit-frame-pointer','-fno-fast-math','-ffp-contract=off','-Wall','-Wextra','-Werror','-Wno-misleading-indentation']
 def command(argv):
  r=subprocess.run(['wsl','--','bash','-lc',shlex.join(argv)],capture_output=True,text=True);assert r.returncode==0,(r.returncode,r.stdout,r.stderr);return r
 sources=[cpp,ROOT/'swf_texture.hpp',test,Path(__file__)];before={str(x.relative_to(REPO)).replace('\\','/'):sha(x)for x in sources};compiler=command(['g++','--version']).stdout.strip();command(['g++',*flags,'-shared','-fPIC',linux(cpp),'-o',linux(lib)]);command(['g++',*flags,linux(test),'-L'+linux(folder),'-ldh2_swf_texture_audit','-Wl,-rpath,'+linux(folder),'-o',linux(exe)]);result=command(['env','ASAN_OPTIONS=detect_leaks=1:halt_on_error=1','UBSAN_OPTIONS=halt_on_error=1',linux(exe),linux(gold)]);assert not result.stderr,result.stderr;observed=json.loads(result.stdout);assert before=={str(x.relative_to(REPO)).replace('\\','/'):sha(x)for x in sources};linkage=command(['ldd',linux(exe)]).stdout;assert 'libdh2_swf_texture_audit.so' in linkage;report={'validation':'PASS',**observed,'source_sha256':before,'library_sha256':sha(lib),'executable_sha256':sha(exe),'reference_sha256':sha(gold),'original_instruction_report_sha256':sha(ROOT/'reports/swf-texture-arm64-differential.json'),'isolated_swf_texture_library_executed':True,'main_scene_library_executed':False,'sanitizers':['AddressSanitizer','UndefinedBehaviorSanitizer'],'sanitizer_findings':0,'compiler':compiler,'flags':flags,'scope':'Original-derived filename/archive query/wrap/diffuse/renderpass/table gold and atomic malformed port contracts. Actual GPU/cache/resource lifetime and SWF draw coordinator remain separate providers.'};a.output.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items()if k not in ('source_sha256','compiler','flags','scope')}))
if __name__=='__main__':main()
