"""Isolated O2 SAN SHA256 utility proof, plus NDK29 ELF64 object compile checks.

New port digest implementation, not original-engine or packaged execution proof.
Expected bytes/digests are generated by Python hashlib with fixed standard
vectors and actual DACT/CAI1/PAB1/canonical-cache payloads.
"""
import argparse,hashlib,json,os,shlex,struct,subprocess,zipfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def posix(p):return '/mnt/'+p.resolve().drive[0].lower()+str(p.resolve())[2:].replace('\\','/')
def run(args):
 r=subprocess.run(args,capture_output=True,text=True);assert r.returncode==0,(args,r.returncode,r.stdout,r.stderr);return r
def write(path,raw):
 if path.exists():assert path.read_bytes()==raw,('Refusing different existing fixture',str(path))
 else:path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(raw)
def fixtures(cache):
 rows=[];origins=[]
 def add(label,b):rows.append((label,b,hashlib.sha256(b).digest()))
 fixed=[('standard-empty',b'','e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'),('standard-abc',b'abc','ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'),('standard-56',b'abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq','248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1'),('standard-million-a',b'a'*1000000,'cdc76e5c9914fb9281a1c7e284d73e67f1809a48a497200e046d39ccc7112cd0')]
 for label,b,h in fixed:assert hashlib.sha256(b).hexdigest()==h;add(label,b)
 lengths=list(range(261))+[511,512,513,1023,1024,1025,4095,4096,4097,65535,65536,65537]
 for n in lengths:
  for pattern in range(4):
   b=bytes((0 if pattern==0 else 255 if pattern==1 else i&255 if pattern==2 else (i*73+(i>>3)*19+n*11)&255) for i in range(n));add(f'padding-{n}-{pattern}',b)
 for relative in ('port/android-native/app/src/main/assets/worlds/crypt01.dact','port/level-world/reference/actor-initialization/crypt01-actor-initialization.bin','port/android-native/app/src/main/assets/data/prince-animation-bank.bin'):
  p=REPO/relative;b=p.read_bytes();add(relative,b);origins.append(dict(path=relative,bytes=len(b),sha256=hashlib.sha256(b).hexdigest()))
 with cache.open('rb') as f:assert hashlib.file_digest(f,'sha256').hexdigest()=='3fdf4e4c21d45a780a7c35fb4042abde0e88e76bf75416aad1f227481560b679'
 manifest=json.loads((REPO/'port/android-native/app/src/main/assets/data/prince-animation-bank.json').read_text())
 entries=['com.gameloft.android.GAND.GloftD2SS/files/data/3d/modules/crypt/mgp/'+s for s in ('crypt_cemetery_entrance_01.mgp','crypt_corner_ne_02.mgp','crypt_straight_c_ns_01.mgp')]+[manifest['resources'][0]['cache_entry']]
 with zipfile.ZipFile(cache) as z:
  table=next(n for n in z.namelist() if n.endswith('/character_properties_pyarray.bin'));entries.append(table)
  for entry in entries:
   b=z.read(entry);add(entry,b);origins.append(dict(cache_entry=entry,bytes=len(b),sha256=hashlib.sha256(b).hexdigest()))
 binary=struct.pack('<4sI',b'SHV1',len(rows))
 for label,b,d in rows:
  label=label.encode('ascii');binary+=struct.pack('<I',len(label))+label+struct.pack('<Q',len(b))+d+b
 summary=dict(format='SHV1',comparisons=len(rows),standard_vectors=4,padding_lengths=len(lengths),padding_patterns=4,actual_payloads=origins,cache_sha256='3fdf4e4c21d45a780a7c35fb4042abde0e88e76bf75416aad1f227481560b679',binary_sha256=hashlib.sha256(binary).hexdigest(),producer_sha256=sha(Path(__file__)))
 return binary,summary
def main():
 p=argparse.ArgumentParser();p.add_argument('--cache',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--ndk',type=Path,default=Path(os.environ['LOCALAPPDATA'])/'Android/Sdk/ndk/29.0.14206865');a=p.parse_args();assert not a.output.exists(),'Refusing to overwrite report'
 binary,summary=fixtures(a.cache);gold=ROOT/'reference/sha256/hashlib-fixtures.bin';write(gold,binary);write(ROOT/'reference/sha256/hashlib-fixtures.json',(json.dumps(summary,indent=2)+'\n').encode())
 names=['port/asset-payloads/sha256.hpp','port/asset-payloads/sha256.cpp','port/asset-payloads/tests/sha256.cpp','port/asset-payloads/tests/sha256_host.py'];hashes={n:sha(REPO/n) for n in names};scratch=REPO/'.local-inputs/sha256';scratch.mkdir(parents=True,exist_ok=True);exe=scratch/'sha256_audit'
 cmd=['g++','-std=c++17','-O2','-g','-fno-omit-frame-pointer','-fsanitize=address,undefined','-Wall','-Wextra','-Werror',posix(ROOT/'sha256.cpp'),posix(ROOT/'tests/sha256.cpp'),'-o',posix(exe)];run(['wsl','-e','bash','-lc',shlex.join(cmd)])
 dact=REPO/'port/android-native/app/src/main/assets/worlds/crypt01.dact';result=run(['wsl','-e','env','ASAN_OPTIONS=detect_leaks=1','UBSAN_OPTIONS=halt_on_error=1',posix(exe),posix(gold),posix(dact)]);assert not result.stderr;audit=json.loads(result.stdout);assert audit['hashlib_fixture_comparisons']==summary['comparisons'] and audit['actual_DACT_sha256']==sha(dact)
 clang=a.ndk/'toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe';version=run([str(clang),'--version']).stdout;objects={}
 for abi,target,machine in [('arm64-v8a','aarch64-linux-android26',183),('x86_64','x86_64-linux-android26',62)]:
  obj=scratch/f'sha256-{abi}.o';command=[str(clang),'--target='+target,'-std=c++17','-O2','-fPIC','-Wall','-Wextra','-Werror','-c',str(ROOT/'sha256.cpp'),'-o',str(obj)];run(command);b=obj.read_bytes();assert b[:6]==b'\x7fELF\x02\x01' and struct.unpack_from('<H',b,18)[0]==machine
  objects[abi]=dict(sha256=sha(obj),ELF_class=64,machine=machine,compiler_command=command,execution_verified=False)
 assert hashes=={n:sha(REPO/n) for n in names}
 report=dict(validation='PASS',scope=__doc__,host_audit=audit,source_sha256=hashes,executable_sha256=sha(exe),fixture_sha256=sha(gold),fixture_manifest_sha256=sha(ROOT/'reference/sha256/hashlib-fixtures.json'),actual_payloads=summary['actual_payloads'],standard_vectors=4,padding_lengths=summary['padding_lengths'],mismatches=0,sanitizers=dict(address=True,undefined=True,leaks=True,diagnostics=0),host_compiler_command=cmd,NDK_version=version,NDK29_compile_checks=objects,original_engine_parity=False,packaged_execution=False,NIST_validation_claim=False)
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(dict(validation='PASS',host_audit=audit,standard_vectors=4,padding_lengths=summary['padding_lengths'],NDK29_compile_ABIs=list(objects),fixture_sha256=sha(gold))))
if __name__=='__main__':main()
