#include "character_buffs.hpp"
#include <algorithm>
#include <cstring>
#include <deque>
#include <map>
#include <memory>
#include <string>
#include <vector>
namespace dh2::character {
struct BuffDecl;
struct BuffInst {dh2::data::PropertySheet sheet{};std::uint32_t strength=0;std::int32_t timer=-1;BuffDecl* declaration=nullptr;};
struct BuffDecl {std::int32_t id=-1;std::uintptr_t fx=0;std::string name;std::deque<std::unique_ptr<BuffInst>> instances;};
struct BuffOwner {
 BuffBindings32 bindings;std::map<std::int32_t,BuffDecl> declarations;
 std::vector<std::vector<const std::int32_t*>> sheets;std::vector<dh2::data::PropertyBuffGroup> groups;bool busy=false,allocation_failed=false;
 void refresh(){std::vector<std::vector<const std::int32_t*>> next_sheets;std::vector<dh2::data::PropertyBuffGroup> next_groups;next_sheets.reserve(declarations.size());next_groups.reserve(declarations.size());for(auto&entry:declarations){next_sheets.emplace_back();auto&list=next_sheets.back();list.reserve(entry.second.instances.size());for(auto&inst:entry.second.instances)list.push_back(inst->sheet.data());}for(auto&list:next_sheets)next_groups.push_back({list.data(),static_cast<std::uint32_t>(list.size())});sheets.swap(next_sheets);groups.swap(next_groups);bindings.properties->groups=groups.data();bindings.properties->group_count=static_cast<std::uint32_t>(groups.size());}
};
}
namespace {
using namespace dh2::character;
struct Scope {BuffOwner* owner;explicit Scope(BuffOwner*p):owner(p){p->busy=true;}~Scope(){owner->busy=false;}};
bool valid_bindings(const BuffBindings32&b){if(!b.properties||!b.timers||!b.services||!b.services->invoke||!b.timer_services||b.timer_services->reserved||dh2_property_validate(b.properties))return false;const auto*t=b.timers;if(t->reserved||t->count>t->capacity||t->capacity>0x7fffffffu||(t->capacity&&!t->slots))return false;for(std::uint32_t i=0;i<t->count;++i)if(t->slots[i].reserved||t->slots[i].id!=i)return false;return true;}
bool valid(const BuffOwner*p){return p&&!p->allocation_failed&&valid_bindings(p->bindings);}
bool begin(BuffResult24*out,BuffOwner*p){if(!out||!valid(p)||p->busy)return false;*out={};return true;}
int finish(BuffResult24*out,int status){out->status=status;return status;}
int allocation_failure(BuffResult24*out,BuffOwner*p){p->bindings.properties->groups=nullptr;p->bindings.properties->group_count=0;p->allocation_failed=true;return finish(out,-2);}
bool service(BuffResult24*out,BuffOwner*p,std::uint32_t kind,std::int32_t id=0,std::uintptr_t subject=0,std::int32_t index=0,std::uintptr_t*value=nullptr){BuffRequest32 request{kind,id,index,kind==buff_fx_enable?1u:0u,subject,p->bindings.timers->owner};std::uintptr_t result=0;out->phase=kind+1;++out->calls;if(p->bindings.services->invoke(p->bindings.services->context,p->bindings.properties,&request,&result)!=1)return false;if(value)*value=result;return true;}
bool recalc(BuffResult24*out,BuffOwner*p){p->refresh();return service(out,p,buff_recalculate);}
int remove(BuffResult24*out,BuffOwner*p,std::int32_t id,std::uintptr_t instance){auto found=p->declarations.find(id);if(found==p->declarations.end())return 1;auto&decl=found->second;if(decl.instances.size()==1){auto timer=decl.instances.front()->timer;if(dh2_character_timer_stop(p->bindings.timers,static_cast<std::uint32_t>(timer))<0)return -2;decl.instances.clear();p->refresh();if(!service(out,p,buff_fx_release,0,decl.fx))return -2;p->declarations.erase(found);return recalc(out,p)?1:-2;}if(!instance)return 1;auto it=std::find_if(decl.instances.begin(),decl.instances.end(),[&](const auto&x){return reinterpret_cast<std::uintptr_t>(x.get())==instance;});if(it==decl.instances.end())return 1;if(dh2_character_timer_stop(p->bindings.timers,static_cast<std::uint32_t>((*it)->timer))<0)return -2;decl.instances.erase(it);return recalc(out,p)?1:-2;}
int add(BuffResult24*out,BuffOwner*p,std::int32_t id,std::uint32_t duration,std::int32_t capacity,std::uint32_t strength,std::int32_t fx,const char*name){if(capacity<=0)capacity=128;BuffInst*candidate=nullptr;auto found=p->declarations.find(id);if(found!=p->declarations.end()&&found->second.instances.size()==static_cast<std::uint32_t>(capacity)){for(auto&owned:found->second.instances){auto&inst=*owned;if(inst.strength<strength){candidate=&inst;inst.strength=strength;continue;}if(inst.strength!=strength)continue;if(inst.timer==-1||!candidate){candidate=&inst;continue;}std::uint32_t a=0,ad=0,b=0,bd=0;
 // Original leaves these locals unwritten on invalid TimeLeft. Reject that
 // undefined source storage domain, retaining prior weaker-strength writes.
 if(dh2_character_timer_time_left(&a,&ad,p->bindings.timers,static_cast<std::uint32_t>(candidate->timer))!=1||dh2_character_timer_time_left(&b,&bd,p->bindings.timers,static_cast<std::uint32_t>(inst.timer))!=1)return -2;
 if(a<b)candidate=&inst;}}
 if(candidate){if(dh2_character_timer_stop(p->bindings.timers,static_cast<std::uint32_t>(candidate->timer))<0)return -2;candidate->timer=-1;}else{auto&decl=p->declarations[id];decl.id=id;decl.name=name;p->refresh();if(!decl.fx&&fx!=-1){if(!service(out,p,buff_fx_load,fx,0,0,&decl.fx))return -2;}if(decl.instances.size()>=static_cast<std::uint32_t>(capacity)){p->refresh();return 1;}auto inst=std::make_unique<BuffInst>();inst->strength=strength;inst->declaration=&decl;candidate=inst.get();decl.instances.push_back(std::move(inst));p->refresh();}
 if(duration){candidate->timer=dh2_character_timer_start(p->bindings.timers,duration,0,0x36,reinterpret_cast<std::uintptr_t>(candidate),p->bindings.timer_services);if(candidate->timer==-1)return remove(out,p,id,reinterpret_cast<std::uintptr_t>(candidate));if(candidate->timer< -1)return -2;}
 auto&decl=*candidate->declaration;if(decl.fx&&decl.instances.size()>1){std::uintptr_t object=0;if(!service(out,p,buff_fx_object,0,decl.fx,0,&object)||!service(out,p,buff_fx_enable,0,object,static_cast<std::int32_t>(decl.instances.size()-1)))return -2;}
 std::copy_n(p->bindings.properties->defaults,224,candidate->sheet.begin());std::uint32_t shifted=strength<<8;std::int32_t raw=0;std::memcpy(&raw,&shifted,4);candidate->sheet[172]=raw;p->bindings.properties->resolved[172]=raw;out->instance=reinterpret_cast<std::uintptr_t>(candidate);return 1;}
bool dictionary(const BuffDictionary16*d){if(!d||d->reserved||(d->count&&!d->names))return false;for(std::uint32_t i=0;i<d->count;++i)if(!d->names[i])return false;return true;}
std::int32_t dot_id(const BuffDictionary16*d,std::int32_t element){std::uint32_t base=0xffffffffu;for(std::uint32_t i=0;i<d->count;++i)if(std::strcmp(d->names[i],"AUTO_DOT_01_FIRE")==0){base=i;break;}base+=static_cast<std::uint32_t>(element);std::int32_t result=0;std::memcpy(&result,&base,4);return result;}
}
extern "C" dh2::character::BuffOwner* dh2_character_buffs_create(const dh2::character::BuffBindings32*b){if(!b||!valid_bindings(*b)||b->properties->group_count||b->properties->groups)return nullptr;try{auto p=std::make_unique<dh2::character::BuffOwner>();p->bindings=*b;p->refresh();return p.release();}catch(...){return nullptr;}}
extern "C" int dh2_character_buff_add(BuffResult24*out,BuffOwner*p,std::int32_t id,std::uint32_t duration,std::int32_t cap,std::uint32_t strength,std::int32_t fx,const char*name){if(!name||!begin(out,p))return -1;Scope guard(p);try{return finish(out,add(out,p,id,duration,cap,strength,fx,name));}catch(...){return allocation_failure(out,p);}}
extern "C" int dh2_character_buff_add_dot(BuffResult24*out,BuffOwner*p,std::int32_t duration,std::int32_t amount,std::int32_t element,const BuffDictionary16*ids,const BuffDictionary16*fx){if(duration<=0||amount<0||element< -1||element>4||!dictionary(ids)||!dictionary(fx)||!begin(out,p))return -1;Scope guard(p);try{static const char*names[]={"dot_normal","dot_fire","dot_water","dot_lightning","dot_earth","dot_air"};int status=add(out,p,dot_id(ids,element),static_cast<std::uint32_t>(duration),1,static_cast<std::uint32_t>(amount),dot_id(fx,element),names[element+1]);if(status!=1||!out->instance)return finish(out,status);auto inst=reinterpret_cast<BuffInst*>(out->instance);auto property=static_cast<std::uint32_t>(127+element);inst->sheet[property]=amount;p->refresh();if(p->bindings.properties->types[property]&7){std::int32_t raw=0;if(dh2_property_resolve(p->bindings.properties,static_cast<std::int32_t>(property),&raw))return finish(out,-2);p->bindings.properties->resolved[property]=raw;}return finish(out,1);}catch(...){return allocation_failure(out,p);}}
extern "C" int dh2_character_buff_delete(BuffResult24*out,BuffOwner*p,std::int32_t id,std::uintptr_t inst){if(!begin(out,p))return -1;Scope guard(p);try{return finish(out,remove(out,p,id,inst));}catch(...){return allocation_failure(out,p);}}
extern "C" int dh2_character_buff_expired(BuffResult24*out,BuffOwner*p,const Timer32*t){if(!t||!out||!valid(p)||p->busy)return -1;BuffInst*inst=nullptr;for(auto&entry:p->declarations)for(auto&x:entry.second.instances)if(reinterpret_cast<std::uintptr_t>(x.get())==t->user_ref)inst=x.get();if(!inst)return -1;if(!begin(out,p))return -1;Scope guard(p);try{return finish(out,remove(out,p,inst->declaration->id,reinterpret_cast<std::uintptr_t>(inst)));}catch(...){return allocation_failure(out,p);}}
extern "C" int dh2_character_buffs_remove_all(BuffResult24*out,BuffOwner*p){if(!begin(out,p))return -1;Scope guard(p);try{for(auto&entry:p->declarations){auto&decl=entry.second;for(auto&x:decl.instances)if(dh2_character_timer_stop(p->bindings.timers,static_cast<std::uint32_t>(x->timer))<0)return finish(out,-2);decl.instances.clear();p->refresh();if(!service(out,p,buff_fx_release,0,decl.fx))return finish(out,-2);}p->declarations.clear();return finish(out,recalc(out,p)?1:-2);}catch(...){return allocation_failure(out,p);}}
extern "C" int dh2_character_buffs_destroy(BuffOwner*p){if(!p)return 1;if(!valid_bindings(p->bindings)||p->busy)return -1;p->busy=true;try{BuffResult24 out;for(auto&entry:p->declarations){auto&decl=entry.second;decl.instances.clear();p->refresh();if(decl.fx&&!service(&out,p,buff_fx_release,0,decl.fx)){p->busy=false;return -2;}}p->bindings.properties->groups=nullptr;p->bindings.properties->group_count=0;delete p;return 1;}catch(...){p->busy=false;p->bindings.properties->groups=nullptr;p->bindings.properties->group_count=0;p->allocation_failed=true;return -2;}}
extern "C" std::uint32_t dh2_character_buffs_count(const BuffOwner*p){if(!p)return 0;std::uint32_t n=0;for(auto&entry:p->declarations)n+=static_cast<std::uint32_t>(entry.second.instances.size());return n;}
extern "C" std::uint32_t dh2_character_buffs_declarations(const BuffOwner*p){return p?static_cast<std::uint32_t>(p->declarations.size()):0;}
extern "C" int dh2_character_buff_snapshot(BuffSnapshot48*out,const BuffOwner*p,std::uint32_t index){if(!out||!p)return -1;for(auto&entry:p->declarations)for(auto&x:entry.second.instances){if(!index--){*out={reinterpret_cast<std::uintptr_t>(x.get()),entry.first,x->strength,x->timer,0,x->sheet.data(),entry.second.name.c_str(),entry.second.fx};return 1;}}return 0;}
