#include "character_world_physical_peers_v1.hpp"
#include <stdexcept>
#include <algorithm>
namespace dh2::character {
int WorldPhysicalBaseActorV1::refresh(void* p,skills::WorldTargetActorBorrowV1* out){auto& s=*static_cast<WorldPhysicalBaseActorV1*>(p);if(!out||!s.position_||!s.fields_.visible_written)return -1;s.search_.identity=s.identity_;std::copy_n(s.position_,3,s.search_.position);s.search_.visible=s.fields_.visible80;s.search_.zoned=s.fields_.zoning2ee;s.search_.in_zone=s.fields_.entered2f0;*out={};out->identity=s.identity_;out->search=&s.search_;out->scene=s.scene_;out->target_node=&s.node_;out->target_enabled=&s.fields_.visible80;out->position=s.position_;/* AnimatedDecor IsZonable3884f8 calls MeetCondition; base-byte2ed shortcut must remain unavailable. */return 0;}
skills::WorldActorRegistrationV1 WorldPhysicalBaseActorV1::registration(std::int32_t key,target_providers::Handle16& handle){skills::WorldActorRegistrationV1 r{};r.identity=identity_;r.handle_key=key;r.context=this;r.refresh=refresh;r.shared_handle=&handle;return r;}
bool CharacterWorldPhysicalPeersV1::add(const WorldPhysicalPeerBorrowV1& b){
 error_.clear();if(!b.physical||!b.physical->context||!b.body){error_="Required persistent physical receiver/body borrow";return false;}
 for(const auto& p:peers_)if(p.physical->context==b.physical->context||(b.identity&&p.identity==b.identity)){error_="Duplicate physical context or canonical owner";return false;}
 if(b.identity){skills::WorldTargetActorBorrowV1 a{};if(!b.object_fields||world_.actor(b.identity,&a)||a.identity!=b.identity){error_="Physical owner must borrow the same canonical World object and lifecycle fields";return false;}}
 else if(b.object_fields||b.object_type){error_="Source null physical-owner borrow cannot carry object fields";return false;}
 peers_.push_back(b);return true;
}
bool CharacterWorldPhysicalPeersV1::remove(void* context){error_.clear();for(auto i=peers_.begin();i!=peers_.end();++i)if(i->physical->context==context){if(i->body->body){error_="DestroyBody/End delivery required before removing peer";return false;}peers_.erase(i);return true;}error_="Unknown retained physical context";return false;}
bool CharacterWorldPhysicalPeersV1::clear(){error_.clear();for(const auto& p:peers_)if(p.body->body){error_="Destroy all bodies before clearing physical peer borrows";return false;}peers_.clear();return true;}
bool CharacterWorldPhysicalPeersV1::owner(void* c,std::uintptr_t& value,std::string& e){for(const auto& p:peers_)if(p.physical->context==c){if(p.identity){skills::WorldTargetActorBorrowV1 a{};if(world_.actor(p.identity,&a)||a.identity!=p.identity){e="Physical owner left canonical World before collision teardown";return false;}}value=p.identity;return true;}e="Required registered physical peer context";return false;}
bool CharacterWorldPhysicalPeersV1::enabled(std::uintptr_t id,std::uint8_t& v,std::string& e){for(const auto& p:peers_)if(p.identity==id&&id){skills::WorldTargetActorBorrowV1 a{};if(world_.actor(id,&a)||!p.object_fields->visible_written){e="Required live ObjectBase+80 producer";return false;}v=p.object_fields->visible80;return true;}e="Required canonical physical owner lifecycle";return false;}
bool CharacterWorldPhysicalPeersV1::type(std::uintptr_t id,std::uint32_t& v,std::string& e){for(const auto& p:peers_)if(p.identity==id&&id){if(!p.object_type){e="Required source ObjectBase+f4 type producer";return false;}v=*p.object_type;return true;}e="Required same physical object type borrow";return false;}
bool CharacterWorldPhysicalPeersV1::peer_owner(void* p,void* c,std::uintptr_t& v,std::string& e){return static_cast<CharacterWorldPhysicalPeersV1*>(p)->owner(c,v,e);}
bool CharacterWorldPhysicalPeersV1::enabled80(void* p,std::uintptr_t id,std::uint8_t& v,std::string& e){return static_cast<CharacterWorldPhysicalPeersV1*>(p)->enabled(id,v,e);}
bool CharacterWorldPhysicalPeersV1::object_type(void* p,std::uintptr_t id,std::uint32_t& v,std::string& e){return static_cast<CharacterWorldPhysicalPeersV1*>(p)->type(id,v,e);}
CharacterWorldPhysicalReceiverV1::CharacterWorldPhysicalReceiverV1(CharacterWorldPhysicalPeersV1& p,physical::NativeBody& b,std::uintptr_t id,WorldPhysicalReceiverV1 k,WorldPhysicalCharacterServicesV1 s):peers_(p),body_(b),identity_(id),kind_(k),services_(s){object_.context=this;object_.test=test;object_.contact=contact;object_.velocity=velocity;}
[[noreturn]] void CharacterWorldPhysicalReceiverV1::fail(const char* e){if(error_.empty())error_=e;throw std::runtime_error(error_);}
unsigned CharacterWorldPhysicalReceiverV1::test(void* p,void* other,const physical::Filter* own,const physical::Filter* peer){auto& s=*static_cast<CharacterWorldPhysicalReceiverV1*>(p);s.error_.clear();if(!own||!peer)s.fail("Required actual shape filters");if(s.kind_==WorldPhysicalReceiverV1::character){bool allowed{};if(!s.services_.filter||s.services_.filter(s.services_.context,peer->category,allowed,s.error_))s.fail("Required source POCharacter filter");if(!allowed)return 0;}
 std::uintptr_t owner{};if(!s.peers_.owner(other,owner,s.error_))s.fail("Required physical peer owner");std::uint8_t enabled{};if(s.identity_&&(!s.peers_.enabled(s.identity_,enabled,s.error_)||!enabled)){if(!s.error_.empty())s.fail("Required source owner byte80");return 0;}if(owner&&(!s.peers_.enabled(owner,enabled,s.error_)||!enabled)){if(!s.error_.empty())s.fail("Required source peer byte80");return 0;}
 if(own->group&&own->group==peer->group)return own->group>0;return (peer->category&own->mask)&&(peer->mask&own->category);
}
void CharacterWorldPhysicalReceiverV1::contact(void* p,physical::ContactEvent event,void* other,const float*,unsigned persist){auto& s=*static_cast<CharacterWorldPhysicalReceiverV1*>(p);s.error_.clear();if(s.kind_==WorldPhysicalReceiverV1::base_physical||event==physical::ContactEvent::result)return;std::uintptr_t peer{};if(!s.peers_.owner(other,peer,s.error_))s.fail("Required same contact peer");if(!peer||!s.identity_)return;if(!s.services_.event||s.services_.event(s.services_.context,event,peer,persist,s.error_))s.fail("Required source player Character collision delivery");}
void CharacterWorldPhysicalReceiverV1::velocity(void* p,float* xy){auto& s=*static_cast<CharacterWorldPhysicalReceiverV1*>(p);physical::NativeBodyObservation v{};if(!xy||dh2_native_body_observe(&v,&s.body_))s.fail("Required actual peer body velocity");xy[0]=v.linear_velocity[0]*100.f;xy[1]=v.linear_velocity[1]*100.f;}
}
