#include "character_world_npc_physical_lifecycle_v2.hpp"
#include <algorithm>
#include <exception>
namespace dh2::character {
bool CharacterWorldNpcPhysicalLifecycleV2::has_visual(void*){return true;}
physical::NativeBody* CharacterWorldNpcPhysicalLifecycleV2::physical(void* p){auto& s=*static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p);return s.physical_.phase()>=3&&s.physical_.native().body?&s.physical_.native():nullptr;}
int CharacterWorldNpcPhysicalLifecycleV2::method(void* p,WorldNpcObjectMethodV1 m,std::string& e){auto& s=*static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p);if(m==WorldNpcObjectMethodV1::EnablePhysicalFilter||m==WorldNpcObjectMethodV1::DisablePhysicalFilter){const bool ok=m==WorldNpcObjectMethodV1::EnablePhysicalFilter?s.physical_.enable_filter():s.physical_.disable_filter();if(!ok)e=s.physical_.error();return ok?0:-1;}if(!s.services_.object_method){e="Required actual NPC visibility/CharacterStop producer";return -1;}return s.services_.object_method(s.services_.context,m,e);}
bool CharacterWorldNpcPhysicalLifecycleV2::aabb(void* p,float* v,std::string&){auto& s=*static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p);std::copy_n(s.borrow_.runtime.subobjects.absolute_bounds,6,v);return true;}
bool CharacterWorldNpcPhysicalLifecycleV2::peer(void* p,void* c,std::uintptr_t& v,std::string& e){return static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p)->borrow_.peers.owner(c,v,e);}
bool CharacterWorldNpcPhysicalLifecycleV2::enabled(void* p,std::uintptr_t id,std::uint8_t& v,std::string& e){return static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p)->borrow_.peers.enabled(id,v,e);}
int CharacterWorldNpcPhysicalLifecycleV2::update_pf(void* p,std::uintptr_t id,const physical::NativeBody* b,const physical::NpcBodyProjection* projection,std::string& e){auto& s=*static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p);if(id!=s.borrow_.object.identity||b!=&s.physical_.native()||!projection){e="NPC PF tail must borrow the assigned same physical owner";return -1;}std::copy_n(projection->bounds.relative_box,6,s.borrow_.runtime.subobjects.local_bounds);std::copy_n(projection->bounds.absolute_box,6,s.borrow_.runtime.subobjects.absolute_bounds);if(!s.lifecycle_.update_pf()){e=s.lifecycle_.error();return -1;}return 0;}
bool CharacterWorldNpcPhysicalLifecycleV2::debug(void* p,const char* k,bool& v,std::string& e){auto& s=*static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p);return character_npc_physical_debug_v1(s.borrow_.debug,s.borrow_.debug_files,k,v,e);}
bool CharacterWorldNpcPhysicalLifecycleV2::clock(void* p,std::uint32_t& f,std::uint32_t& dt,std::string& e){auto& s=*static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p);const auto& c=s.services_.collision;if(!c.clock){e="Required actual Application frame/GetDt";return false;}return c.clock(c.context,f,dt,e);}
int CharacterWorldNpcPhysicalLifecycleV2::ais(void* p,std::uintptr_t active,std::uintptr_t method,std::uintptr_t collider,std::uint32_t persist,std::string& e){auto& s=*static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p);const auto& c=s.services_.collision;if(!c.ais_method){e="Required selected active AIS collision override";return -1;}return c.ais_method(c.context,active,method,collider,persist,e);}
int CharacterWorldNpcPhysicalLifecycleV2::cancel(void* p,std::uintptr_t id,std::string& e){auto& s=*static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p);const auto& c=s.services_.collision;if(!c.cancel_sneaking){e="Required actual Character CancelSneaking collision endpoint";return -1;}return c.cancel_sneaking(c.context,id,e);}
bool CharacterWorldNpcPhysicalLifecycleV2::type(void* p,std::uintptr_t id,std::uint32_t& value,std::string& e){return static_cast<CharacterWorldNpcPhysicalLifecycleV2*>(p)->borrow_.peers.type(id,value,e);}
CharacterWorldNpcPhysicalLifecycleV2::CharacterWorldNpcPhysicalLifecycleV2(WorldNpcPhysicalGraphBorrowV2 b,WorldNpcPhysicalGraphServicesV2 s):borrow_(b),services_(s),
 collision_(b.world,b.machine,b.script,b.object,b.ai,b.controller,b.collision_fields,b.collisions,&b.debug,&b.debug_files,{this,clock,ais,cancel,type}),
 lifecycle_(b.object_fields,b.runtime.object,&b.floors,&b.obstacles,b.object.identity,character_pf_services_v1({this,has_visual,physical,method,nullptr,nullptr,nullptr,aabb})),
 physical_(b.physical_world,b.model,collision_,b.object,b.script,{this,peer,enabled,update_pf,debug}),
 scene_(b.world,b.script,b.object,b.ai,b.ai_tables,physical_,b.object_fields,lifecycle_,b.final_fields,b.random,b.network,b.visual,b.scene,b.light40,b.target_node180,b.runtime.rotation,s.scene){}
CharacterWorldNpcPhysicalLifecycleV2::~CharacterWorldNpcPhysicalLifecycleV2(){if((registered_||physical_.native().body)&&!close())std::terminate();}
bool CharacterWorldNpcPhysicalLifecycleV2::initialize(physical::NpcBodyRequest q,const char* name,const std::string& lights){
 error_.clear();if(initialized_||registered_||!name||borrow_.world.state_borrow(borrow_.object.identity)!=&borrow_.machine.state()||q.properties!=&borrow_.script.property_view()||q.ai!=&borrow_.ai_tables||!borrow_.object_fields.visible_written||borrow_.runtime.object.motion.floor!=~0u||borrow_.runtime.object.user){error_="Required fresh same registered NPC graph, source PF constructor and properties";return false;}
 if(!borrow_.peers.add({&physical_.world_object(),&physical_.native(),borrow_.object.identity,&borrow_.object_fields,nullptr})){error_=borrow_.peers.error();return false;}registered_=true;
 std::copy(borrow_.object.position.begin(),borrow_.object.position.end(),q.position);
 q.static_owner=borrow_.object_fields.static84;q.previous_flat=borrow_.source_flat2f9;
 if(!physical_.initialize_source(q)){error_=physical_.error();return false;}
 std::copy_n(physical_.projection().bounds.relative_box,6,borrow_.runtime.subobjects.local_bounds);std::copy_n(physical_.projection().bounds.absolute_box,6,borrow_.runtime.subobjects.absolute_bounds);
 borrow_.source_flat2f9=std::uint8_t(physical_.projection().bounds.flat);
 std::copy(borrow_.object.position.begin(),borrow_.object.position.end(),borrow_.runtime.subobjects.position);
 if(!scene_.receive_init_post(error_))return false;borrow_.runtime.subobjects.rotation=borrow_.runtime.rotation.rotation[2];if(physical_.native().body&&dh2_native_body_refresh_view(&borrow_.runtime.body,&physical_.native())){error_="Required actual initialized physical body observation";return false;}if(!scene_.initialize(name,lights)){error_=scene_.error();return false;}initialized_=true;return true;
}
bool CharacterWorldNpcPhysicalLifecycleV2::actor_phase(actor::RuntimeResult& result,actor::RuntimeRequest q){error_.clear();if(!initialized_||q.state!=&borrow_.runtime||q.binding!=&borrow_.visual||q.scene!=&borrow_.scene||q.geometry!=&borrow_.floors||q.registry!=&borrow_.obstacles||q.key!=borrow_.object.identity||q.resolved224!=borrow_.script.property_view().resolved){error_="Required same NPC runtime/physical/PF/scene/property frame graph";return false;}float target[3];q.target_absolute_position=nullptr;if(borrow_.target_node180){if(!scene_.node_position(borrow_.target_node180,target,error_))return false;q.target_absolute_position=target;}q.native_body=physical_.native().body?&physical_.native():nullptr;q.character_flags=borrow_.machine.state().flags;const int status=actor::update_actor(result,q,error_);std::copy_n(borrow_.runtime.subobjects.position,3,borrow_.object.position.begin());return status==0;}
bool CharacterWorldNpcPhysicalLifecycleV2::enabled(){error_.clear();if(!lifecycle_.enabled()){error_=lifecycle_.error();return false;}return true;}
bool CharacterWorldNpcPhysicalLifecycleV2::disabled(){error_.clear();if(!lifecycle_.disabled()){error_=lifecycle_.error();return false;}return true;}
bool CharacterWorldNpcPhysicalLifecycleV2::close(){error_.clear();if(!registered_&&!physical_.native().body)return true;if(!physical_.release()){error_=physical_.error();return false;}if(!lifecycle_.update_pf()){error_=lifecycle_.error();return false;}if(registered_&&!borrow_.peers.remove(physical_.world_object().context)){error_=borrow_.peers.error();return false;}registered_=initialized_=false;return true;}
}
