#include "trigger_constructors.hpp"
#include "activation_bindings.hpp"
#include "../../source_root_scopes.hpp"
#include "../../source_world_objects.hpp"
#include "../../source_level_config.hpp"
#include "../../original_trigger_contacts.hpp"
#include "../../content_paths.hpp"
#include "../../../level-loader/canonical_source_adapter_v1.hpp"
#include "../../../level-world/canonical_point3d_globals_v1.hpp"
#include "../../../level-world/gameobject_online_update_v5.hpp"
#include <filesystem>
#include <iostream>
#include <stdexcept>
#include <sstream>
using namespace dh::foundation;using namespace dh::foundation::encounters;using namespace dh2::world;
void check(bool x,const std::string&e){if(!x)throw std::runtime_error(e);}
struct Host {bool allow=false,save=true;std::uint8_t sync14=1;std::int32_t condition_state=0,level_id=0,difficulty=0;std::uintptr_t character=100,events=200;bool blocked=false,cutscene=false;unsigned callbacks=0;};
struct Peer {float position[3]{},bounds[6]{};std::uintptr_t physical=0;};
int main(int argc,char**argv){try{
 check(argc==2,"Repository root required");const auto repo=std::filesystem::path(argv[1]);AssetCatalog assets(repo/"port/windows-foundation/assets"),campaign_assets(repo/".local-inputs/windows-encounter-source");const std::string uri="original-cache/data/scene/001_swamp.mlx";std::vector<ActorDefinition>definitions;std::string error;check(load_actor_definitions(assets,uri,definitions,error),error);SourceRootScopes root;check(root.load(assets,uri,definitions,error),error);
 auto cache=std::make_shared<AssetCatalog>(assets.root()/"original-cache");NativeConditionCacheInputsV69 input;input.actual_cache=cache;input.read=[cache](const char*name,bool&found,auto&bytes,std::string&e){try{bytes=cache->read(name);found=true;e.clear();return true;}catch(const std::exception&x){found=false;e=x.what();return false;}};std::shared_ptr<const NativeConditionTableV69>table;check(read_native_condition_table_v69(input,table,error),error);
 OriginalCampaignRuntime campaign;check(campaign.load(campaign_assets,"original-campaign.xml",error),error);const ActorDefinition*authored=nullptr;const NativeConditionRowV69*row=nullptr;
 for(const auto&d:definitions){auto condition=d.properties.find("activate_cond"),script=d.properties.find("script");if(d.gametype!="TriggerZone"||condition==d.properties.end()||script==d.properties.end()||script->second.empty()||campaign.script_id(script->second,false)<0)continue;bool simple=true;for(const char*k:{"is_door_closed","effect_one_player","script_all_player","script_all_player_move_out"}){auto i=d.properties.find(k);if(i!=d.properties.end()&&!i->second.empty())simple=false;}if(!simple)continue;for(const auto&candidate:table->rows())if(candidate.name==condition->second&&candidate.count4==1&&candidate.stubs8[0].op4>=0&&candidate.stubs8[0].op4<=6&&candidate.stubs8[0].op4!=4&&candidate.stubs8[0].op4!=5){authored=&d;row=&candidate;break;}if(authored)break;}
 check(authored&&row,"Original condition-bearing script Trigger fixture unavailable");auto host=std::make_shared<Host>();const auto stub=row->stubs8[0];host->level_id=stub.argument8;host->condition_state=stub.argument_c;
 NativeConditionServicesV69 condition_services;condition_services.transport=host;condition_services.local_player=[host](int n,bool flag,auto&out,std::string&){check(n==0&&flag,"Original local-player request changed");out={host,1,&host->character};return true;};condition_services.current_level=[host](auto&out,std::string&){out={host,10,&host->level_id,&host->events};return true;};
 auto state=[host,stub](auto&out,std::string&){host->condition_state=stub.argument_c;if(stub.op4==1)host->condition_state+=host->allow?-1:0;else if(stub.op4==2)host->condition_state+=host->allow?1:0;else if(!host->allow)++host->condition_state;out={host,&host->condition_state};return true;};
 condition_services.quest_state=[host,stub,state](auto character,int id,int index,auto&out,std::string&e){check(character==host->character&&id==stub.argument8&&index==-1,"Original quest operands changed");return state(out,e);};condition_services.event_state=[host,stub,state](auto events,int id,auto&out,std::string&e){check(events==host->events&&id==stub.argument8,"Original event operands changed");return state(out,e);};if(stub.op4==3)throw std::runtime_error("Fixture selection must expose mutable quest/event state, not level-only condition");std::shared_ptr<NativeConditionRuntimeV69>conditions;check(NativeConditionRuntimeV69::create(table,condition_services,conditions,error),error);
 AdmissionServices admission_services;admission_services.owner=host;admission_services.local_save=[host](bool&character,bool&save,std::uint8_t&sync,std::string&){character=true;save=host->save;sync=host->sync14;return true;};admission_services.current_level=[host](bool&present,int&difficulty,std::string&){present=true;difficulty=host->difficulty;return true;};admission_services.enabled_event=[host](auto&base,bool enabled,std::string&e){++host->callbacks;return base.store_byte(0x85,enabled,e);};auto admission=std::make_shared<Admission>(conditions,admission_services);auto application_random=std::make_shared<ApplicationSpawnRandomOwnerV4>();
 OriginalActorLifecycle lifecycle;OriginalCampaignWorldAdapter adapter(lifecycle);OriginalCampaignWorldProviders world;world.global_controller_blocked=[host](bool blocked,std::string&){host->blocked=blocked;return true;};world.cutscene_mode=[host](bool enter,std::string&){host->cutscene=enter;return true;};adapter.bind(world);
 CampaignSourceServices source;source.owner=host;std::vector<std::pair<int,int>>started;std::vector<bool>received_flags;std::vector<int>source_flag_ids;source.admit_start=[&](int id,int module,bool received,bool&accepted,std::string&){received_flags.push_back(received);accepted=true;started.emplace_back(id,module);return true;};source.script_flags=[&](int global,std::uint8_t&flags,std::string&){source_flag_ids.push_back(global);flags=0;return true;};source.command_skip=[](const auto&,bool&skip,std::string&){skip=false;return true;}; // Explicit transport fixtures, not production flags policy.
 CampaignBinding binding(campaign,adapter,source);check(binding.bind(error),error);
 const SourceModuleTraceEntry*module=nullptr;for(const auto&entry:root.modules().entries())if(entry.occurrence.hostOccurrence==authored->moduleName)module=&entry;check(module,"Authored child occurrence lacks actual Module constructor context");
 dh2::loader::XmlDocumentV1 document;check(document.capture(authored->sourcePath,read_content(assets,authored->sourcePath),error)&&document.borrow().parsed(),error);unsigned element=UINT32_MAX;for(unsigned i=0;i<document.borrow().elements().size();++i){const auto*n=document.borrow().elements()[i].attribute("name");if(n&&*n==authored->name)element=i;}check(element!=UINT32_MAX,"Exact authored MGP element missing");dh2::loader::CanonicalModuleContextV1 context;context.candidate_owner=host;context.occurrence=module->occurrence.element;context.runtime_module_id=module->runtimeId;context.class_position=module->position;dh2::loader::CanonicalSourceBindingV1 declaration;check(dh2::loader::prepare_canonical_source_binding_v1(document.borrow(),element,dh2::loader::ObjectEntryRouteV1::manager,{},context,declaration,error),error);
 dh2::world::CanonicalPropertySourceServicesV1 property_sources;property_sources.position_rotation_default=&canonical_vec3_origin_v1();unsigned template_assertions=0;property_sources.context=&template_assertions;property_sources.load_template_assertion=[](void*p,std::string&){++*static_cast<unsigned*>(p);return true;};auto properties=std::make_shared<CanonicalPropertyMapV1>(property_sources);auto peer=std::make_shared<Peer>();OriginalTriggerContacts contacts;std::vector<std::string>empty_names;
 TriggerConstructorServices constructors;constructors.world_owner=host;constructors.properties=properties;constructors.source_services=[&](const auto&record,TriggerZoneServicesV22&s,std::string&e){std::weak_ptr<TriggerRecord>weak=record;s.owner=host;s.initialization.owner=host;s.initialization.difficulty_names=&empty_names;s.initialization.sound_names=&empty_names;
  ActivationReceiver activation;activation.scope=host;activation.same_base=[weak](CanonicalGameObjectBaseOwnerV1*& base,std::string&e){auto r=weak.lock();if(!r||!r->receiver){e="Actual source Trigger receiver absent";return false;}base=&r->receiver->base();return true;};
  CanonicalSpawnApplicationServicesV4 app;app.application_lease=application_random;app.random=application_random.get();app.handle_as_player=[](bool& player,std::string&){player=false;return true;};app.online_byte5=[](bool& online,std::string&){online=false;return true;}; // Explicit offline transport; SAME application RNG is genuine.
  app.set_visible_false=[](std::string&e){e="Fixture rejects unexpected probability deletion visibility";return false;};app.mark_for_deletion=[](std::string&e){e="Fixture rejects unexpected source MarkForDeletion";return false;};
  if(!bind_source_activation(activation,admission,app,s.initialization,e))return false;
  s.spawn_roll_probability=[weak,check=s.initialization.check_spawn_probability](int&roll,int&prob,std::string&e){auto r=weak.lock();if(!r||!r->receiver){e="Actual source probability receiver absent";return false;}if(!check(roll,e))return false;prob=*r->receiver->base().integer(0x274);return true;};
  s.initialization.set_position=[weak](const float*position,bool destination,std::string&e){auto r=weak.lock();if(!r||!r->receiver){e="Actual source position owner expired";return false;}auto&base=r->receiver->base();std::copy_n(position,3,base.vector3(0x160));if(destination)std::copy_n(position,3,r->runtime.controller.destination);base.update_absolute_aabb();return true;};s.initialization.device_high_performance=[](bool&high,std::string&){high=true;return true;};s.initialization.load_visual=[weak](std::string&e){auto r=weak.lock();if(r&&r->receiver&&r->receiver->base().string(0x290)->empty()&&!*r->receiver->base().pointer(0x2d8))return true;e="Positive visual source provider intentionally unavailable";return false;};
  s.set_bounding_box=[weak](const std::array<float,6>&box,bool move,std::string&e){check(!move,"Original SetBoundingBox move flag changed");auto r=weak.lock();if(!r||!r->receiver){e="Actual box owner expired";return false;}std::copy(box.begin(),box.end(),r->receiver->base().relative_aabb144());r->receiver->base().update_absolute_aabb();return true;};
  s.local_player=[host](int,bool,auto&player,std::string&){player={host->character,0};return true;};s.player_count=[](int&count,std::string&){count=1;return true;};s.player_character=[host](int,bool,std::uintptr_t&id,std::string&){id=host->character;return true;};s.online5=[](bool&online,std::string&){online=false;return true;};s.app_delta_ms=[](int&dt,std::string&){dt=16;return true;};s.is_character=[](auto,bool&yes,std::string&){yes=true;return true;};s.is_player=s.is_character;s.require_online_update=[weak](std::string&e){auto r=weak.lock();if(!r||!r->receiver){e="Actual online source receiver expired";return false;}GameObjectOnlineUpdateServicesV5 services;services.online_byte5=[](void*,bool&online,std::string&){online=false;return true;};return gameobject_require_online_update_v5(r->receiver->base(),services,e);};
  if(!binding.trigger_script_services(s,e))return false;OriginalTriggerPeerProvider p=[peer](std::uintptr_t id,ZonePeerBorrowV83&out,std::string&){out={peer,id,peer->position,peer->bounds,&peer->physical,{}};return true;};return contacts.prepare(authored->sourceId,record->declaration.runtime_module_id,p,s,e);
 };
 TriggerConstructors ctor(constructors);std::uint8_t online=0;SourceLevelConfigNetworkBorrow offline{host,&online};CanonicalObjectManagerServicesV1 manager_services;manager_services.context=&offline;manager_services.assign_network_id=[](void*p,auto&o,std::string&e){return source_level_config_network_leaf(*static_cast<SourceLevelConfigNetworkBorrow*>(p),o,e);};CanonicalObjectManagerV1 manager(manager_services);dh2::loader::CanonicalBoundSourceAttemptV1 attempt(declaration);check(attempt.execute(manager,ctor.services(),error),error);const auto*factory=attempt.factory_attempt();check(factory&&factory->stage()==CanonicalFactoryStageV1::complete,"Actual child source factory prefix incomplete");const auto*object=manager.object(factory->handle().key);check(object,"Actual source manager child handle missing");std::shared_ptr<TriggerRecord>record;check(ctor.record(object->identity,record,error),error);check(record->receiver->base().room64()==module->runtimeId&&record->declaration.source_lease,"Child owner scope/declaration lease not real");check(contacts.attach(authored->sourceId,record->receiver,record,error),error);check(record->receiver->init_post(error),error);check(*record->receiver->base().integer(0x270)==-2&&application_random->channel(0).calls==1,"Source spawn probability cache/shared RNG binding missing");check(!source_flag_ids.empty()&&source_flag_ids.front()==campaign.script_id(authored->properties.at("script"),false),"Trigger local script flags did not resolve actual global source row");
 const auto*bbox=record->receiver->base().absolute_aabb12c();for(unsigned k=0;k<3;++k){peer->position[k]=(bbox[k]+bbox[k+3])*.5f;peer->bounds[k]=peer->position[k]-1;peer->bounds[k+3]=peer->position[k]+1;}
 bool enabled=true;check(admission->test_enable(record->receiver->base(),false,enabled,error)&&!enabled,error);check(contacts.update(authored->sourceId,error)&&started.empty(),"False actual condition admitted script despite live overlap");host->allow=true;host->sync14=0;check(admission->test_enable(record->receiver->base(),false,enabled,error)&&!enabled,"Source unsynchronized Save gate bypassed");host->sync14=1;check(admission->test_enable(record->receiver->base(),false,enabled,error)&&enabled,error);check(contacts.update(authored->sourceId,error),error);const int script=campaign.script_id(authored->properties.at("script"),false);check(started==std::vector<std::pair<int,int>>({{script,module->runtimeId}})&&campaign.running(script)&&!received_flags.front(),"Actual original condition/contact did not queue authored script in actual module context");check(contacts.update(authored->sourceId,error)&&started.size()==1,"Canonical single-fire repeated script start");
 bool got_missing=false;for(unsigned i=0;i<4&&!got_missing;++i)if(!binding.tick(0,error)){got_missing=true;std::cerr<<"Explicit script stop: "<<error<<"\n";check(error.find("Required")!=std::string::npos||error.find("Unsupported")!=std::string::npos||error.find("Unbound")!=std::string::npos,"Missing actual script effect was not explicit");}check(got_missing,"Fixture unexpectedly claimed complete original UI/camera script");
 std::cout<<"PASS actualMGPChildCtor=true condition="<<row->name<<" trigger="<<authored->name<<" script="<<authored->properties.at("script")<<" globalScript="<<script<<" actualModule="<<module->runtimeId<<" falseConditionDenied=true questSyncGate=true contactQueuedOnce=true missingWorldEffectExplicit=true transportFixtures=true\n";
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}








