#include "../audio_gameplay_runtime_v40.hpp"
#include "../audio_source_command_v40.hpp"
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <cstring>
#include <thread>
using namespace dh2::audio;
unsigned checks{};void check(bool ok,const char*why){++checks;if(!ok)throw std::runtime_error(why);}
struct Fixture{std::string root;int phase{},disabled{},draws{},commands{},reads{};bool ready{},throw_trace{},reenter{},nested_rejected{};AudioGameplayRuntimeV40*runtime{};};
std::shared_ptr<const std::vector<std::uint8_t>> read(const std::string&p){std::ifstream f(p,std::ios::binary);if(!f)return {};return std::make_shared<const std::vector<std::uint8_t>>(std::istreambuf_iterator<char>(f),std::istreambuf_iterator<char>());}
bool asset(void*raw,const char*uri,std::shared_ptr<const std::vector<std::uint8_t>>&bytes,std::string&error){auto&f=*static_cast<Fixture*>(raw);++f.reads;const std::string name=uri;std::string file;if(name.rfind("data/pydata/",0)==0)file=f.root+"/port/engine-audio/reference/source-bindings-v38/"+name.substr(12);else if(name.rfind("data/sounds/",0)==0)file=f.root+"/.local-inputs/audio-v34/cache/"+name.substr(12);else{error="Required exact fixture source URI";return false;}bytes=read(file);if(!bytes){error="Required exact source file "+name;return false;}return true;}
int gates(void*raw,const dh2::sound::VoxPlay3DRequestV2&q,dh2::sound::VoxPlay3DResponseV2&r){auto&f=*static_cast<Fixture*>(raw);using O=dh2::sound::VoxPlay3DOperationV2;r={};if(q.operation==O::disabled)r.value=f.disabled;else if(q.operation==O::current_level){r.identity=0x44;r.value=f.phase;}else if(q.operation==O::trace){if(f.throw_trace)throw std::runtime_error("borrowed provider failure");if(f.reenter){std::string e;f.nested_rejected=!f.runtime->submit_actual_play(*q.play,1000000000,e);}}else if(q.operation!=O::online&&q.operation!=O::platform_route)return -1;return 0;}
int main(int argc,char**argv){try{if(argc!=2)return 2;Fixture fixture;fixture.root=argv[1];AudioGameplaySourcesV40 services;services.gates={&fixture,gates};services.exact_assets={&fixture,asset};services.context=&fixture;services.random={&fixture,[](void*p,int&v){v=++static_cast<Fixture*>(p)->draws;return true;}};services.output_ready=[](void*p,std::string&){return static_cast<Fixture*>(p)->ready;};services.source_command=[](void*p,const dh2::character::CombatSoundPlayV1&,const AudioSoundV34&,const AudioGroupV34&,AudioCommandV34&c,std::string&){++static_cast<Fixture*>(p)->commands;c.left=.5f;c.right=.25f;c.native_state=0;return true;};
 auto runtime=std::make_unique<AudioGameplayRuntimeV40>(0xabc,services);fixture.runtime=runtime.get();std::string error;dh2::character::CombatSoundPlayV1 play;play.manager=0xabc;play.sound_id=0;play.source_float0=play.source_float1=-1;
 check(runtime->submit_actual_play(play,1000000000,error)&&runtime->last_source_phase()==2&&fixture.reads==0,"actual phase-zero source early return even before audio IO");check(!runtime->submit_actual_play(play,0,error),"actual event clock required");check(runtime->initialize_exact_source(error),error.c_str());check(runtime->bindings().rows().size()==638&&fixture.reads==3,"exact generated638 and selected XML reads");const int menu=runtime->bindings().source_id("MenuSelect"),event=runtime->bindings().source_id("env_fs_walk_stone"),music=runtime->bindings().source_id("AbbeyRuinsOneAmbientMusic");check(menu>=0&&event>=0&&music>=0,"genuine exact source ordinal lookup");
 fixture.phase=38;play.sound_id=-1;check(runtime->submit_actual_play(play,1000000000,error)&&runtime->last_token()==0&&fixture.draws==0,"negative source ID remains silent after actual prefix gates");play.sound_id=menu;check(!runtime->submit_actual_play(play,1000000000,error)&&fixture.reads==4&&fixture.commands==0,"exact load prefix retained before output-ready failure");
 play.sound_id=event;const auto before=fixture.draws;check(!runtime->submit_actual_play(play,1000000000,error)&&fixture.draws==before+2&&runtime->pinned_samples()==0,"event RNG consumed exactly before output-ready failure");
 fixture.ready=true;runtime->clock().publish({0,1000000000,0,1,32000,true});check(runtime->mixer().set_rate(32000),"fixture actual device rate");play.sound_id=menu;fixture.reenter=true;check(runtime->submit_actual_play(play,1000500000,error)&&fixture.nested_rejected,"nested caller cannot overwrite source event clock");fixture.reenter=false;const auto token=runtime->last_token();check(token&&runtime->pinned_samples()==1&&runtime->voice(token)&&!runtime->voice(token)->started,"queued transport has actual pin but not started acceptance");
 float buffer[64]{};runtime->mixer().render(buffer,32);runtime->pump_receipts();check(runtime->voice(token)&&runtime->voice(token)->started,"started receipt makes actual voice visible");AudioReceiptV34 receipt;unsigned starts=0;while(runtime->take_receipt(receipt))starts+=receipt.kind==AudioReceiptKindV34::started;check(starts==1,"observable actual start receipt");
 auto bytes=read(fixture.root+"/.local-inputs/audio-v34/cache/sfx_menu_select.wav");AudioSampleV34 sample;check(audio_sample_open_v34(bytes,sample,error)&&sample.rate==32000,"actual original menu fixture sample");AudioSampleCursorV34 cursor;check(cursor.bind(&sample,0),"actual PCM cursor");for(unsigned i=0;i<32;++i){if(i<16)check(buffer[2*i]==0&&buffer[2*i+1]==0,"actual event/device clock schedules16 frame boundary");else{float l,r;check(cursor.frame(i-16,l,r),"source PCM fixture frame");check(buffer[2*i]==l*.5f&&buffer[2*i+1]==r*.25f,"positive decoded gameplay runtime output");}}
 fixture.throw_trace=true;check(!runtime->submit_actual_play(play,1001000000,error)&&runtime->last_source_status()==-2,"provider exception preserves failure status and releases submission scope");fixture.throw_trace=false;check(runtime->submit_actual_play(play,1001000000,error),"scope usable after provider exception");
 play.sound_id=33;check(!runtime->submit_actual_play(play,1001000000,error)&&error.find("sfx_chest_opening.wav")!=std::string::npos,"exact missing chest remains required, no fallback");const auto missing_draws=fixture.draws;check(!runtime->load_actual_xml_uid(162,error)&&fixture.draws==missing_draws,"LoadSound exact XML UID does not select events or emit");
 play.sound_id=music;check(runtime->submit_actual_play(play,1001000000,error),error.c_str());const auto music_token=runtime->last_token();runtime->mixer().render(buffer,32);runtime->pump_receipts();while(runtime->take_receipt(receipt)){}check(runtime->native_state(music_token,"combat",error),error.c_str());runtime->mixer().render(buffer,1);check(runtime->native_state(music_token,"ambient",error),error.c_str());runtime->mixer().render(buffer,1);runtime->pump_receipts();check(runtime->voice(music_token)&&runtime->voice(music_token)->control_required,"unsupported rapid music control remains observable nonterminal requirement");while(runtime->take_receipt(receipt)){}
 std::atomic<bool>closed{false},joined{false};AudioControlClosedProofV40 proof{&runtime->mixer(),&closed,&joined};check(!runtime->finalize_after_output_closed(proof,error)&&runtime->pinned_samples()>0,"pin lifetime protected before actual close-and-join proof");check(runtime->stop_world(error),error.c_str());closed=true;check(!runtime->finalize_after_output_closed(proof,error),"close alone cannot authorize second consumer");joined=true;check(runtime->finalize_after_output_closed(proof,error)&&runtime->pinned_samples()==0&&!runtime->mixer().active_voices(),"closed/joined GL sole-consumer stop drain releases all pins");check(!runtime->submit_actual_play(play,1001000000,error),"quiescing source refuses new producer deliveries");
 AudioSourceCommandAuthorityV40 authority;AudioCommandV34 command;command.left=.123f;AudioSoundV34 sound;AudioGroupV34 group;group.position_type=0;
 check(!audio_source_command_v40(authority,play,sound,group,command,error)&&command.left==.123f,"missing actual authority leaves command unchanged");
 authority.manager=play.manager;authority.actual_current_level=0x44;authority.world_epoch=authority.listener_world_epoch=2;authority.soundpack_initialized=authority.manager_general_initialized=authority.listener_initialized=true;
 authority.listener.reference_distance=1000;authority.listener.maximum_distance=1800;authority.listener.rolloff=1;authority.actual_gain=.5f;authority.actual_pitch=1;
 original_vox_manager_general_init_v40(authority.general);
 check(audio_source_command_v40(authority,play,sound,group,command,error),error.c_str());check(command.left>0&&command.right>0&&command.pitch==1,"actual gain pitch and fresh relative emitter spatial command");
 authority.listener_world_epoch=1;command.left=.123f;check(!audio_source_command_v40(authority,play,sound,group,command,error)&&command.left==.123f,"stale World listener cannot emit");authority.listener_world_epoch=2;
 sound.format=2;check(!audio_source_command_v40(authority,play,sound,group,command,error)&&command.left==.123f,"missing actual native music state cannot commit spatial command");authority.actual_native_initial_state=0;check(audio_source_command_v40(authority,play,sound,group,command,error)&&command.native_state==0,"actual native owner state retained");
 AudioClockV40 clock;std::uint64_t frame;check(!clock.frame_at(1000000000,0,frame),"unopened driver clock required");clock.publish({100,1000000000,200,9,48000,true});check(clock.frame_at(1000500000,0,frame)&&frame==324,"actual stream base+timestamp mapping");check(clock.frame_at(999000000,400,frame)&&frame==400,"late source event clamps to written output");clock.invalidate(10);check(!clock.frame_at(1000000000,0,frame),"close invalidates output timeline");
 std::atomic<bool>done{false};std::thread publisher([&](){for(std::uint64_t i=1;i<20000;++i)clock.publish({std::int64_t(i),1000000000,std::uint64_t(i),i,48000,true});done=true;});unsigned snapshots=0;while(!done.load()){AudioDeviceClockV40 v;if(clock.snapshot(v)&&v.ready){check(v.position==std::int64_t(v.generation)&&v.mixer_base_frame==v.generation,"atomic clock generation cannot tear");++snapshots;}}publisher.join();check(snapshots>0,"concurrent published clock read fixture");
 std::cout<<"PASS "<<checks<<" gameplay/clock checks; decoded output true; actual AAudio/World false\n";return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
