#include "../actor_visual_root.hpp"
#include "original_actor_target_position.hpp"
#include "../level-world/actor_rotation.hpp"
#include "../level-world/move_state.hpp"
#include "playable_actor_bodies.hpp"
#include "playable_actor_world.hpp"
#include "original_actor_properties.hpp"
#include <cstring>
#include <algorithm>
#include <iostream>
#include <stdexcept>
using namespace dh::foundation;
using namespace dh::foundation::features;
static void check(bool value,const std::string& error){if(!value)throw std::runtime_error(error);}
struct Fields {ActorState actor;std::array<float,3> destination{};std::uintptr_t attached=0,visual=73;};
struct Visual {CharacterVisual character;};
struct Obstacles {std::array<dh2::navigation::ObstacleEntry,8> entries{};std::array<unsigned,8> floors{};dh2::navigation::ObstacleRegistry registry{entries.data(),0,8,floors.data(),0,8};};
int main(int argc,char**argv){try{
 check(argc==2,"Original shared assets root required");AssetCatalog assets(argv[1]);std::string error;
 auto db=std::make_shared<OriginalPropertyDatabase>();check(load_original_property_tables(assets,"original-cache/data/pydata/",*db,error),error);
 auto ai=std::make_shared<dh2::data::AiTables>();check(load_original_ai_tables(assets,"original-cache/data/pydata/",*ai,error),error);
 OriginalActorProperties resolved;check(resolve_original_actor_properties(db->characters,db->classes,"KnightPlayerBase",{256,true},resolved,error),error);
 auto props=std::make_shared<OriginalCombatProperties>();props->sheets=std::move(resolved.sheets);const auto originalSheets=props->sheets;
 auto fields=std::make_shared<Fields>();fields->actor.id=100;fields->actor.health=19;fields->actor.target_id=991;
 auto visual=std::make_shared<Visual>();CharacterVisualConfig config;config.model_path="models/prince_modular.bdae";config.use_authored_modular_defaults=true;config.consume_root_motion=true;config.motion_node_id="auto";config.template_clip_path="animations/prince_template_anim.bdae";config.clips={{"walk","animations/prince_walk_1hand.bdae"}};check(visual->character.load(assets,config,error),error);
 const auto bytes=assets.read("original-cache/data/3d/modules/swamp/swamp.bdae");dh2::resources::BresView view{};check(dh2_bres_open(&view,bytes.data(),bytes.size())==dh2::resources::BresError::ok,"Floor BRES absent");dh2::scene::Scene scene;check(dh2::scene::load(view,scene,error),error);
 unsigned instance=UINT32_MAX;for(unsigned i=0;i<scene.instances.size();++i)if(scene.graph[scene.instances[i].node_index].name.find("floor")!=std::string::npos){instance=i;break;}check(instance!=UINT32_MAX,"Authored floor absent");
 auto floors=std::make_shared<dh2::floors::World>();OriginalSourceFloorBinding floor;floor.instance=instance;floor.room=0;floor.mesh_local_quaternion={0,0,0,1};floor.mesh_local_scale={1,1,1};check(append_original_module_floors(view,scene,{floor},*floors,error),error);check(dh2::floors::build_graph(*floors,error)&&dh2::floors::post_load(*floors,error),error);
 std::array<float,3> point{};bool found=false;for(const auto& tri:floors->records.front()->triangles){for(unsigned k=0;k<3;++k)point[k]=(tri.points[0][k]+tri.points[1][k]+tri.points[2][k])/3;float z=point[2];if(dh2::floors::height(*floors,point.data(),z)){point[2]=z;found=true;break;}}check(found,"Authored floor lacks diagnostic point");fields->actor.transform.position=point;
 auto root=std::make_shared<ActorVisualRoot>();ActorVisualRootBindings rb;rb.actor_lease=fields;rb.model_lease=visual;rb.actor=&fields->actor;rb.model=&visual->character;rb.visual2d8=&fields->visual;rb.identity=73;std::copy(point.begin(),point.end(),rb.initial_root.position);rb.initial_root.quaternion[3]=1;rb.initial_root.scale[0]=rb.initial_root.scale[1]=.9f;rb.initial_root.scale[2]=1;rb.initial_root.presence=1;rb.update_endpoint=0x470cf0;rb.apply_rotation_endpoint=0x470ccc;rb.scale120=[](auto& out,auto&){out={.9f,.9f,1};return true;};check(root->bind(rb,error),error);
 OriginalActorBodyPlanInput q;q.visual=config;q.properties=&props->sheets;q.ai=ai.get();q.owner_identity=100;q.source_name="KnightPlayerBase";q.position={point[0],point[1],point[2]};OriginalActorBodyPlan plan;check(make_original_actor_body_plan(assets,q,plan,error),error);
 auto world=std::make_shared<dh2::physical::NativeWorld>();const float worldBounds[]{-1000,-1000,1000,1000};world->load(worldBounds);PlayableActorBodies pool;
 OriginalActorPhysicalBindings b;b.actor_lease=fields;b.world_lease=world;b.data_lease=props;b.world=world.get();b.ai=ai.get();b.destination1a8=fields->destination.data();b.attached2e0=&fields->attached;b.visual2d8=&fields->visual;
 b.position.visual_sync_position=[&](auto id,auto& e){check(id==73,"SetPosition borrowed different visual");return root->sync_position(e);};
 b.static84=[](auto& out,auto&){out=0;return true;};b.is_player=[](auto type,auto& out,auto&){out=original_actor_source_is_player(type,"KnightPlayerBase");return true;};b.debug_switch=[](const char*,bool& out,auto&){out=false;return true;};
 b.filter=[](void*,const auto&,const auto&,bool&,auto& e){e="Unbound reached contact filter";return false;};b.contact=[](auto,void*,unsigned,auto& e){e="Unbound reached AIS contact";return false;};check(pool.bind(fields->actor,*props,plan,b,error),error);
 auto obstacles=std::make_shared<Obstacles>();check(pool.initialize_navigation(100,{floors,obstacles,floors.get(),&obstacles->registry},error),error);
 auto path=std::make_shared<dh2::navigation::PathObject>();OriginalActorSubobjectsInput input;input.actor=&fields->actor;check(pool.subobjects_borrow(100,input.owner,error),error);input.navigation_lease=input.owner.owner_lease;input.path_lease=path;input.pf=const_cast<dh2::navigation::NavigationObject*>(pool.navigation(100));input.path=path.get();input.floor_lease=floors;input.obstacle_lease=obstacles;input.floors=floors.get();input.obstacles=&obstacles->registry;input.validating_camera=false;
 input.set_position=[&](const auto& xyz,bool destination,auto& e){return pool.set_position(100,xyz,destination,e);};
 std::uint32_t flags{},movement{};check(!dh2_move_focus_begin(&flags,&movement),"Source Move focus prefix failed");fields->actor.source_flags520=flags;fields->actor.source_movement_type=movement;fields->actor.source_validate_boundary452=1;
 check(visual->character.restart("walk",true,error)&&visual->character.update(.1,error),error);const auto raw=visual->character.take_root_motion();check(raw.x!=0||raw.y!=0,"Real walk authored delta absent");Vec3 sampled{};check(visual->character.sample_source_root_translation("walk",100,sampled,error),error);
 const auto oldActor=fields->actor.transform.position;bool moved=false;check(root->stage_displacement({raw},sampled,moved,error)&&moved,error);const auto staged=root->render_placement();check(fields->actor.transform.position==oldActor&&(staged[12]!=oldActor[0]||staged[13]!=oldActor[1]),"Early visual displacement published actor too soon");
 unsigned submissions=0;Mat4 unit{1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};check(root->submit(unit,[&](const auto& mesh,const auto& matrix,auto&){check(!mesh.vertices.empty()&&matrix==staged,"Renderer submitted actor placement instead of actual visual root");++submissions;return true;},error)&&submissions>0,error);
 auto heading=std::make_shared<dh2::navigation::HeadingState>();const float intent[]{1,0,0};check(!dh2_nav_set_heading(heading.get(),intent,1),"Source heading input failed");
 std::array<float,3> previousPosition{},previousEuler{};OriginalActorMotionFrameBorrow actor{fields,&fields->actor,100,&previousPosition,&previousEuler};OriginalActorMotionFrameServices services;services.runtime_lease=fields;std::vector<std::string> order;
 services.update_path=[&](const auto&,auto& e){order.push_back("path");check(fields->actor.transform.position==oldActor&&previousPosition==oldActor,"Path/snapshot saw future visual placement");OriginalManualHeadingBindings h;h.controller_lease=heading;h.read_heading=[&](auto& out,auto&){out=*heading;return true;};h.publish_heading=[&](const auto& out,auto&){*heading=out;return true;};h.source_policy=[&](auto& out,auto& boundary,auto&){out=*fields->actor.source_flags520;boundary=*fields->actor.source_validate_boundary452;return true;};h.skip_boundary=[](auto& skip,auto&){skip=0;return true;};OriginalManualHeadingResult out;return pool.update_manual_heading(100,h,out,e);};
 services.update_rotation=[&](const auto&,auto& e){order.push_back("rotation");check(fields->actor.transform.position==oldActor,"Late rotation started after early actor publication");float speed{};check(!dh2_move_rotation_speed(&speed,&flags,props->sheets.resolved.data()),"Source rotation speed failed");dh2::actor::RotationState state{};std::copy(fields->actor.transform.rotation.begin(),fields->actor.transform.rotation.end(),state.rotation);state.heading_angle=heading->angle;const dh2::actor::RotationPolicy policy{speed,2000,1,1};unsigned sync{};check(!dh2_actor_update_rotation(&state,&policy,&sync),"Source rotation failed");std::copy(state.rotation,state.rotation+3,fields->actor.transform.rotation.begin());return !sync||root->sync_rotation(e);};
 original_target_position_ctor_prefix(fields->actor.source_target_node180,fields->actor.source_target_position184);std::uintptr_t targetNode{};check(visual->character.source_target_node(targetNode,error),error);fields->actor.source_target_node180=targetNode;
 services.update_target_position=[&](const auto&,auto& e){order.push_back("target");OriginalTargetPositionUpdateResult out;return original_update_target_position(fields->actor.source_target_node180,fields->actor.source_target_position184,[&](auto node,auto& position,auto& failure){Mat4 local;if(!visual->character.source_target_node_world(node,local,failure))return false;const auto worldMatrix=dh2::scene::multiply(root->render_placement(),local);position={worldMatrix[12],worldMatrix[13],worldMatrix[14]};return true;},out,e);};
 ActorFrameResult result;check(reconcile_actor_frame(root,actor,services,input,result,error),error);check(result.motion.completed_mask==31&&result.subobjects.completed&&order==std::vector<std::string>{"path","rotation","target"},"Late source phase coordination differs");check(previousPosition==oldActor&&input.pf->motion.position[0]==fields->actor.transform.position[0],"Source snapshot/PF/actor authority diverged");for(unsigned k=0;k<3;++k)check(root->source_root().position[k]==fields->actor.transform.position[k],"SubObjects did not reconcile actual rendered root");check(root->render_placement()[0]!=staged[0]||root->render_placement()[1]!=staged[1],"Late source rotation was not rendered");
 // Full source setter syncs the canonical root; no unrelated matrix copy.
 check(pool.set_position(100,point,false,error),error);check(root->render_placement()[12]==point[0]&&root->render_placement()[13]==point[1],"Whole source setter lost actual visual receiver");
 // Source nonbase callbacks and changed-scale bounds cannot be placeholders.
 auto other=std::make_shared<ActorVisualRoot>();auto unsupported=rb;unsupported.update_endpoint=0;check(other->bind(unsupported,error),error);OriginalActorSubobjectsVisual service;check(other->subobjects_visual(service,error),error);check(!service.update(error),"Unknown actual visual endpoint silently admitted");unsupported=rb;unsupported.scale120=[](auto& out,auto&){out={1,1,1};return true;};check(other->bind(unsupported,error)&&!other->sync_scaling(error),"Changed source scale omitted mesh-box tail");check(other->source_root().scale[0]==1,"Changed-scale source prefix rolled back");
 // Actual registry count is published by the PlayerManager AddCharacter
 // receiver fixture into its sole count6c4 cell, not a constant supplied to
 // CanMoveTowards. Count1 must precede all unavailable camera providers.
 struct RegistryFixture {Fields* fields;std::int16_t baseId=263;} registryFixture{fields.get()};dh2::player::PlayerManagerServicesV1 pmServices;pmServices.context=&registryFixture;pmServices.invoke=[](void* context,const dh2::player::PlayerManagerRequestV1& request,dh2::player::PlayerManagerResponseV1& response,std::string& e){auto& fixture=*static_cast<RegistryFixture*>(context);using O=dh2::player::PlayerManagerOperationV1;if(request.operation==O::online_enabled){response.value=0;return true;}if(request.operation==O::construct_player_info){*request.player=dh2::player::PlayerInfoFieldsV1{};return true;}if(request.operation==O::character_initialization){request.player->character660=fixture.fields->actor.id;request.player->character_base_id13c8=&fixture.baseId;++*request.character_count6c4;return true;}e="Reached PlayerManager fixture service unbound";return false;};
 auto players=std::make_shared<dh2::player::PlayerManagerOwnerV1>(pmServices);check(players->initialize(error)&&players->add_player(0,0,0,true,error)&&players->add_character(0,error),error);check(*players->character_count_field()==1,"Actual source registry count absent");dh2::world::LevelCanMoveServicesV108 camera;camera.owner=fields;bool accepted=false;check(actor_frame_can_move_towards(players,camera,point.data(),intent,accepted,error)&&accepted,"Count1 route demanded unavailable camera/online dependencies");
 check(fields->actor.health==19&&fields->actor.target_id==991&&!std::memcmp(&props->sheets,&originalSheets,sizeof(originalSheets)),"Feature created another gameplay authority");check(pool.clear(error)&&obstacles->registry.count==0,error);
 std::cout<<"PASS source-authored early visual root render placement; late SAME actor/PF/native heading-rotation-SubObjects-target order; actual registry count1 early camera return; reached visual/bounds failures\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 1;}}


