#include "shader_reflection_v4.hpp"
#include <algorithm>
#include <utility>
namespace dh2::scene { namespace {
struct Entry {const char* name;std::uint16_t semantic;};
const Entry entries[]={
 {"alpha_ref",10},
 {"alpharef",10},
 {"ambient_light",28},
 {"ambient_light_model",28},
 {"ambientcolor",5},
 {"ambientcolormaterial",5},
 {"ambientlight",28},
 {"ambientlightmodel",28},
 {"bone_matrices",11},
 {"bone_quat",14},
 {"bone_texture",12},
 {"bone_texture_params",13},
 {"bonematrices",11},
 {"bonequat",14},
 {"bonetexture",12},
 {"bonetextureparams",13},
 {"camera_pos",58},
 {"camera_position",58},
 {"camerapos",58},
 {"cameraposition",58},
 {"camnearandfar",57},
 {"clip_plane",32},
 {"clipplane",32},
 {"colorgencolor",16},
 {"constant",0},
 {"diffusecolor",6},
 {"diffusecolormaterial",6},
 {"emissioncolor",8},
 {"emissioncolormaterial",8},
 {"eye_pos",58},
 {"eye_position",58},
 {"eyepos",58},
 {"eyeposition",58},
 {"fog.color",31},
 {"fog.density",29},
 {"fog.start_end",30},
 {"fog.startend",30},
 {"fog_color",31},
 {"fog_density",29},
 {"fog_start_end",30},
 {"fog_startend",30},
 {"fogcolor",31},
 {"fogdensity",29},
 {"fogstartend",30},
 {"light.ambient_color",22},
 {"light.ambientcolor",22},
 {"light.attenuation",21},
 {"light.diffuse_color",23},
 {"light.diffusecolor",23},
 {"light.direction",20},
 {"light.position",19},
 {"light.specular_color",24},
 {"light.specularcolor",24},
 {"light.spot_cutoff",26},
 {"light.spot_exponent",25},
 {"light.spotcutoff",26},
 {"light.spotexponent",25},
 {"light_ambient_color",22},
 {"light_attenuation",21},
 {"light_diffuse_color",23},
 {"light_direction",20},
 {"light_position",19},
 {"light_specular_color",24},
 {"light_spot_cutoff",26},
 {"light_spot_exponent",25},
 {"lightambientcolor",22},
 {"lightattenuation",21},
 {"lightcolor",23},
 {"lightdiffusecolor",23},
 {"lightdir",20},
 {"lightdirection",20},
 {"lightpos",19},
 {"lightposition",19},
 {"lightspecularcolor",24},
 {"lightspotcutoff",26},
 {"lightspotexponent",25},
 {"matmodel",35},
 {"matmodeli",40},
 {"matmodelinv",40},
 {"matmodelit",45},
 {"matmodelt",50},
 {"matmodeltrans",50},
 {"matmodelview",38},
 {"matmodelviewi",43},
 {"matmodelviewinv",43},
 {"matmodelviewit",48},
 {"matmodelviewprojection",39},
 {"matmodelviewprojectioni",44},
 {"matmodelviewprojectioninv",44},
 {"matmodelviewprojectionit",49},
 {"matmodelviewprojectiont",53},
 {"matmodelviewprojectiontrans",53},
 {"matmodelviewt",52},
 {"matmodelviewtrans",52},
 {"matprojection",37},
 {"matprojectioni",54},
 {"matprojectioninv",54},
 {"matprojectionit",56},
 {"matprojectiont",55},
 {"matprojectiontrans",55},
 {"mattexcoord",3},
 {"matview",36},
 {"matviewi",41},
 {"matviewinv",41},
 {"matviewit",46},
 {"matviewprojectioni",42},
 {"matviewprojectioninv",42},
 {"matviewprojectionit",47},
 {"matviewt",51},
 {"matviewtrans",51},
 {"matworld",35},
 {"matworldi",40},
 {"matworldinv",40},
 {"matworldit",45},
 {"matworldt",50},
 {"matworldtrans",50},
 {"matworldview",38},
 {"matworldviewi",43},
 {"matworldviewinv",43},
 {"matworldviewit",48},
 {"matworldviewprojection",39},
 {"matworldviewprojectioni",44},
 {"matworldviewprojectioninv",44},
 {"matworldviewprojectionit",49},
 {"matworldviewprojectiont",53},
 {"matworldviewprojectiontrans",53},
 {"matworldviewt",52},
 {"matworldviewtrans",52},
 {"matwvp",39},
 {"modeli",40},
 {"modelinv",40},
 {"modelinverse",40},
 {"modelinversetransposed",45},
 {"modelt",50},
 {"modeltrans",50},
 {"modeltransposed",50},
 {"modelview",38},
 {"modelviewi",43},
 {"modelviewinv",43},
 {"modelviewinverse",43},
 {"modelviewinversetransposed",48},
 {"modelviewit",48},
 {"modelviewmatrix",38},
 {"modelviewprojection",39},
 {"modelviewprojectioni",44},
 {"modelviewprojectioninv",44},
 {"modelviewprojectioninverse",44},
 {"modelviewprojectioninversetransposed",49},
 {"modelviewprojectionit",49},
 {"modelviewprojectiont",53},
 {"modelviewprojectiontrans",53},
 {"modelviewprojectiontransposed",53},
 {"modelviewt",52},
 {"modelviewtrans",52},
 {"modelviewtransposed",52},
 {"pointsize",34},
 {"projection",37},
 {"projectioni",54},
 {"projectioninv",54},
 {"projectioninverse",54},
 {"projectioninversetransposed",56},
 {"projectionit",56},
 {"projectionmatrix",37},
 {"projectiont",55},
 {"projectiontrans",55},
 {"projectiontransposed",55},
 {"sampler",2},
 {"sampler_bias",33},
 {"scene_ambient",28},
 {"scene_ambient_light",28},
 {"sceneambient",28},
 {"sceneambientlight",28},
 {"shininess",9},
 {"shininesscolormaterial",9},
 {"specularcolor",7},
 {"specularcolormaterial",7},
 {"specularpower",9},
 {"systemtime",62},
 {"texture",2},
 {"texture_bias",33},
 {"texture_matrix",3},
 {"textureenvcolor",4},
 {"texturematrix",3},
 {"time",62},
 {"u_fairyposw",17},
 {"view",36},
 {"viewi",41},
 {"viewinv",41},
 {"viewinverse",41},
 {"viewinversetransposed ",46},
 {"viewit",46},
 {"viewmatrix",36},
 {"viewport",59},
 {"viewportdimension",60},
 {"viewportdimensioni",61},
 {"viewportdimensioninv",61},
 {"viewportsize",60},
 {"viewprojectioni",42},
 {"viewprojectioninv",42},
 {"viewprojectioninverse",42},
 {"viewprojectioninversetransposed ",47},
 {"viewprojectionit",47},
 {"viewt",51},
 {"viewtrans",51},
 {"weight_mask",15},
 {"weightmask",15},
 {"world",35},
 {"worldi",40},
 {"worldinv",40},
 {"worldinverse",40},
 {"worldinversetransposed",45},
 {"worldit",45},
 {"worldmatrix",35},
 {"worldt",50},
 {"worldtrans",50},
 {"worldtransposed",50},
 {"worldview",38},
 {"worldviewi",43},
 {"worldviewinv",43},
 {"worldviewinverse",43},
 {"worldviewinversetransposed",48},
 {"worldviewit",48},
 {"worldviewmatrix",38},
 {"worldviewprojection",39},
 {"worldviewprojectioni",44},
 {"worldviewprojectioninv",44},
 {"worldviewprojectioninverse",44},
 {"worldviewprojectioninversetransposed",49},
 {"worldviewprojectionit",49},
 {"worldviewprojectionmatrix",39},
 {"worldviewprojectiont",53},
 {"worldviewprojectiontrans",53},
 {"worldviewprojectiontransposed",53},
 {"worldviewt",52},
 {"worldviewtrans",52},
 {"worldviewtransposed",52},
 {"wvp",39},
 {"wvpt",53},
};
char lower(char c){return c>='A'&&c<='Z'?char(c+'a'-'A'):c;}
bool digit(char c){return c>='0'&&c<='9';}
std::uint8_t numbered(const std::string& name,const char* prefix){
 std::string s=name;for(auto& c:s)c=lower(c);
 auto at=s.find(prefix);if(at==std::string::npos)return 255;
 at+=std::char_traits<char>::length(prefix);
 while(at<s.size()&&!digit(s[at]))++at;
 if(at==s.size())return 255;
 std::uint8_t value=0;while(at<s.size()&&digit(s[at]))value=std::uint8_t(value*10+unsigned(s[at++]-'0'));
 return value;
}
std::uint8_t sub(const std::string& name,unsigned semantic){
 std::uint8_t n=255;
 if(semantic>=19&&semantic<=27)n=numbered(name,"light");
 else if(semantic>=29&&semantic<=31)n=numbered(name,"fog");
 else if(semantic==2||semantic==33){n=numbered(name,"sampler");if(n==255)n=numbered(name,"texture");}
 else if(semantic==32){n=numbered(name,"clipplane");if(n==255)n=numbered(name,"clip_plane");}
 else if(semantic==14){n=numbered(name,"bonequat");if(n==255)n=numbered(name,"bone_quat");return n;}
 else return 255;
 return n==255?0:n;
}
std::uint8_t type(unsigned gl){switch(gl){
 case 0x1406:return 5;case 0x1404:case 0x8b56:return 1;
 case 0x8b50:return 6;case 0x8b51:return 7;case 0x8b52:return 8;
 case 0x8b53:case 0x8b57:return 2;case 0x8b54:case 0x8b58:return 3;case 0x8b55:case 0x8b59:return 4;
 case 0x8b5a:return 9;case 0x8b5b:return 10;case 0x8b5c:return 11;
 case 0x8b5e:return 12;case 0x8b5f:return 13;case 0x8b60:return 14;case 0x8b63:return 15;
 default:return 255;}}
}
void shader_uniform_reflect_v4(ShaderUniformReflectionV4& u){
 std::string normalized;int brackets=0;
 for(char c:u.name){if(c=='['){++brackets;continue;}if(c==']'){--brackets;continue;}if(!brackets&&!digit(c))normalized+=lower(c);}
 unsigned semantic=255;for(const auto& e:entries)if(normalized==e.name){semantic=e.semantic;break;}
 u.type=type(u.gl_type);
 if(semantic==255){u.semantic=(u.type>=12&&u.type<=15)?2:0;u.sub_id=std::uint8_t(u.semantic);}
 else{u.semantic=std::uint16_t(semantic);u.sub_id=sub(u.name,semantic);}
}
std::uint32_t shader_uniform_partition_v4(std::vector<ShaderUniformReflectionV4>& u){
 auto end=std::stable_partition(u.begin(),u.end(),[](const auto& x){return x.semantic>=34&&x.semantic<=62;});
 return std::uint32_t(end-u.begin());
}
}
