"""B057: export the requirement-gate art of menu_InventorySheetDetails (additive; does not touch original_inventory_art.cpp).

Authored behaviour (authored-actions.txt 0001c98b / 0001d2ee): a list row whose ItemEquippable is false gotoAndStop("No") on its
Status clip (sprite 101 frame 1, the red X); the selected item's btn_EquipItem (sprite 179) gotoAndStop("disabled") (frame 19).
Writes original_inventory_gate_art.inc, included by original_inventory_art.cpp.
"""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[4]
p=ROOT/'port/windows-foundation/features/character_menu/export_art.py'
env={'__file__':str(p)}
exec(p.read_text().split('tabs=placement')[0],env)
swf=env['swf'];sprites=env['sprites'];labels=env['labels']
def numbers(v):return '{'+','.join(swf.cpp_number(float(n))for n in v)+'}'
def batches(art):return '{'+','.join('{'+json.dumps(path)+','+str(char)+',{'+','.join(numbers(v)for v in verts)+'}}'for path,char,verts in art)+'}'
def fields(text):
 return '{'+','.join('{'+json.dumps(path)+','+str(char)+','+str(rec['font'])+','+swf.cpp_number(rec['height_twips']/20)+','+numbers(bounds)+',{'+','.join(str(c)for c in rec['rgba'])+'},'+str(rec['layout'].get('align',0))+','+numbers(m[:4]+[m[4]/20,m[5]/20])+','+numbers([v/20 for v in rec['bounds_twips']])+','+numbers([rec['layout'].get(k,0)/20 for k in('left_margin','right_margin','indent')])+','+swf.cpp_number(rec['layout'].get('leading',0)/20)+'}'for path,char,rec,bounds,m in text)+'}'
def solids(records):return '{'+','.join('{{'+json.dumps(path)+','+str(char)+',{'+','.join(numbers(v)for v in verts)+'}},'+numbers(rgba)+','+json.dumps(after)+'}'for path,char,verts,rgba,after in records)+'}'
def variant(sprite,frame,matrix,path):
 old=sprites[sprite];sprites[sprite]=[old[frame]];a=[];t=[];first=len(env['source_solids'])
 env['walk'](sprite,matrix,path,a,t);sprites[sprite]=old
 return '{'+batches(a)+','+fields(t)+','+solids(env['source_solids'][first:])+'}'
details=env['placement']('menu_InventorySheetDetails');dm=details['matrix'];dp='menu_InventorySheetDetails'
old_list=sprites[111]
# --- btn_EquipItem 'disabled' state
eq=swf.placed_path(sprites[456],'btn_EquipItem');assert eq['character']==179 and labels[179]['disabled']==19
equip_disabled=variant(179,labels[179]['disabled'],swf.multiply(dm,eq['matrix']),dp+'/btn_EquipItem')
# --- list rows: Status clip at its 'No' frame (red X), for the Unselected/Selected row frames
list_p=swf.placed_path(sprites[456],'list');lm=swf.multiply(dm,list_p['matrix'])
rows=[]
for name,relative in [('btn_pre3',-4),('btn_pre2',-3),('btn_pre1',-2),('btn_pre0',-1),('btn_0',0),('btn_post0',1),('btn_post1',2),('btn_post2',3)]:
 row=swf.placed_path([old_list[3]],name);rm=swf.multiply(lm,row['matrix']);rp=dp+'/list/'+name;pair=[]
 for frame in (0,1):
  st=sprites[108][frame][1];assert st['name']=='Status' and st['character']==101 and labels[101]['No']==1
  pair.append(variant(101,labels[101]['No'],swf.multiply(rm,st['matrix']),rp+'/Status'))
 rows.append('{'+str(relative)+','+','.join(pair)+'}')
out=['// Generated by export_inventory_gate_art.py (B057). Do not edit.',
 'const DetailGateArt& original_inventory_gate_art(){static const DetailGateArt art{'+equip_disabled+',{'+','.join(rows)+'}};return art;}']
Path(__file__).with_name('original_inventory_gate_art.inc').write_text('\n'.join(out)+'\n')
print('exported gate art: equip disabled + 8 row status No states')
