#include "canonical_decor_v15.hpp"
#include "canonical_point3d_globals_v1.hpp"
#include <cstdio>
#include <cstdlib>
using namespace dh2::world;
unsigned checks{},rows{};void check(bool x){++checks;if(!x){std::fprintf(stderr,"FAIL %u\n",checks);std::exit(1);}}
bool assertion(void*,std::string&){return true;}
template<class T>void properties(T& owner,std::map<std::string,std::string>& attrs){std::string e;owner.base().class_name20()=attrs["gametype"]=="Decor"?"Decor":"SpawnPoint";auto a=owner.properties();CanonicalPropertyMapV1 m({nullptr,&canonical_vec3_origin_v1(),assertion});check(m.init_properties(a,e)&&m.load_defaults(a,e));CanonicalSourceObjectRequestV1 q;q.source_lease=std::make_shared<int>(1);q.source_context=&attrs;q.attribute=[](void* c,std::uint32_t,const char* n)->const char*{auto& a=*static_cast<std::map<std::string,std::string>*>(c);auto i=a.find(n);return i==a.end()?nullptr:i->second.c_str();};check(m.load_overrides(a,q,e));check(owner.base().byte(0x87)!=nullptr);}
template<class T>void publication(T& o,std::map<std::string,std::string>& attrs){
 auto lease=std::shared_ptr<void>(&o,[](void*){});CanonicalObjectManagerV1 manager({});auto b=o.canonical(lease);dh2::target_providers::Handle16 handle{};std::string e;
 check(manager.add(b,attrs["name"].c_str(),attrs["gametype"].c_str(),0,false,handle,e));
 check(handle.key==1&&b.shared_handle->key==1&&manager.object(1)->identity==o.base().identity());
 check(manager.object(1)->shared_handle==&o.base().shared_handle());
}
void run(std::map<std::string,std::string>& attrs){++rows;dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);std::string e;
 if(attrs["gametype"]=="Decor"){CanonicalDecorV15 o(pin,r,{},{});check(o.base().type_f4()==20&&o.base().lifecycle().static84==1&&o.load_floor()==1&&o.solid()==1);publication(o,attrs);properties(o,attrs);check(o.load_floor_map(e));check(o.load_floor()==1);}
 else{CanonicalSpawnPointV15 o(pin,r,{},{});check(o.base().type_f4()==13&&o.entrypoint()==-1&&o.script_id()==-1&&o.script_name().empty());publication(o,attrs);properties(o,attrs);check(!o.place_object(42,e));}
}
int main(){
#include "canonical_swamp_family_declarations_v15.inc"
 check(rows==21);
 {dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);std::string e;std::vector<std::string> calls;std::uint32_t flags=4;bool fail=false;DecorServicesV15 s;s.visual_root=[&](auto v,auto& out,std::string&){check(v==9);calls.push_back("root");out=10;return true;};s.load_room=[&](auto root,auto room,const auto& name,auto& out,auto*& f,std::string&){check(root==10&&room==3&&name=="ActualDecor");calls.push_back("load");out=11;f=&flags;return true;};s.extend_bounds=[&](auto id,const float* box,std::string&){check(id==11&&box==r.subobjects.absolute_bounds);calls.push_back("bounds");return !fail;};CanonicalDecorV15 o(pin,r,{},s);*o.base().pointer(0x2d8)=9;o.base().room64()=3;*o.base().string(0x30)="ActualDecor";fail=true;check(!o.load_floor_map(e)&&flags==5&&o.load_floor()==1);fail=false;check(o.load_floor_map(e)&&o.load_floor()==0);auto count=calls.size();check(o.load_floor_map(e)&&calls.size()==count);}
 {dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);std::string e;std::vector<std::string> calls;SpawnPointServicesV15 s;s.set_object_position=[&](auto id,const float* p,bool b,std::string&){check(id==42&&p==r.subobjects.position&&b);calls.push_back("position");return true;};s.set_object_rotation=[&](auto id,const float* p,std::string&){check(id==42&&p==r.rotation.rotation);calls.push_back("rotation");return true;};CanonicalSpawnPointV15 o(pin,r,{},s);check(o.place_object(42,e)&&calls==std::vector<std::string>({"position","rotation"}));}
 {dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);std::string e;std::vector<std::string> calls;GameObjectInitializationServicesV1 init;init.owner=pin;init.condition_init=[&](auto offset,std::string&){calls.push_back(offset==0x8c?"condition8c":"conditionb0");return true;};init.check_spawn_probability=[&](auto& roll,std::string&){calls.push_back("spawn");roll=100;return true;};SpawnPointServicesV15 s;s.script_id=[&](const auto& name,bool create,auto& id,std::string&){if(name!="original-script"||create)std::fprintf(stderr,"script [%s] create%d\n",name.c_str(),create);check(name=="original-script"&&!create);calls.push_back("script");id=17;return true;};s.set_object_position=[&](auto,const float*,bool,std::string&){calls.push_back("position");return true;};s.set_object_rotation=[&](auto,const float*,std::string&){calls.push_back("rotation");return true;};s.start_script=[&](auto id,auto room,bool async,std::string&){check(id==17&&room==2&&!async);calls.push_back("start");return true;};CanonicalSpawnPointV15 o(pin,r,init,s);std::map<std::string,std::string> attrs{{"gametype","SpawnPoint"},{"script","original-script"}};properties(o,attrs);o.base().room64()=2;auto done=o.init_post(e);if(!done)std::fprintf(stderr,"InitPost %s\n",e.c_str());check(done&&o.script_id()==17);check(calls==std::vector<std::string>({"condition8c","conditionb0","spawn","script"}));check(o.place_object(42,e));check(calls.back()=="start");}
 {dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);std::string e;std::vector<std::string> calls;GameObjectInitializationServicesV1 init;init.owner=pin;init.condition_init=[&](auto,std::string&){calls.push_back("condition");return true;};init.check_spawn_probability=[&](auto& v,std::string&){calls.push_back("spawn");v=100;return true;};DecorServicesV15 s;s.visual_sync=[&](auto v,std::string&){check(v==9);calls.push_back("sync");return true;};s.visual_physical=[&](auto,bool& p,std::string&){calls.push_back("physical");p=true;return true;};s.construct_podecor=[&](auto& base,auto& body,std::string&){check(base.identity()!=0);calls.push_back("construct");body=12;return true;};s.set_physical=[&](auto b,bool update,std::string&){check(b==12&&!update);calls.push_back("assign");return true;};s.visual_root=[&](auto,auto& root,std::string&){calls.push_back("root");root=10;return true;};s.load_room=[&](auto,auto,const auto&,auto& room,auto*& flags,std::string&){calls.push_back("room");room=0;flags=nullptr;return true;};CanonicalDecorV15 o(pin,r,init,s);std::map<std::string,std::string> attrs{{"gametype","Decor"}};properties(o,attrs);*o.base().pointer(0x2d8)=9;check(o.init_post(e)&&o.load_floor()==0);check(calls==std::vector<std::string>({"condition","condition","spawn","sync","physical","construct","assign","root","room"}));}
 std::printf("Canonical Decor/SpawnPoint PASS %u actual parsed declarations %u checks; inherited required graph services explicit\n",rows,checks);
}
