#include "../retained_character_actor_v1.hpp"
#include "../canonical_existing_actor_publication_v3.hpp"
#include <cassert>
#include <iostream>
int main(){using namespace dh2;using namespace dh2::character;using namespace dh2::world;std::string error;auto world=std::make_shared<int>(1);auto actor=std::make_shared<RetainedCharacterActorV1>(0x100000006ull,world,"Character");auto original=actor->canonical(actor);assert(original.set_name(original.context,"ActualDactActor",error));assert(original.set_archetype(original.context,"",error));auto properties=std::make_shared<data::PropertyState>();auto life=std::make_shared<data::CombatActorState>();actor->object=std::make_shared<ScriptCharacterObject>(original.identity,"ActualDactActor",properties,life,std::array<float,3>{12,34,56});
 CanonicalObjectBorrowV1 out;out.identity=99;auto before=actor->shared_handle();assert(!actor->canonical_adoption_v2(actor,"different","",-1,out,error));assert(out.identity==99&&actor->shared_handle().key==before.key);
 assert(actor->canonical_adoption_v2(actor,actor->source_name(),actor->source_archetype(),-1,out,error));assert(out.identity==original.identity&&out.shared_handle==original.shared_handle&&out.type_f4==original.type_f4&&out.room64==original.room64&&out.lease==original.lease);
 assert(!out.set_name(out.context,"different",error));assert(!out.set_archetype(out.context,"different",error));assert(actor->object->properties==properties&&actor->object->life==life);
 CanonicalObjectManagerV1 manager({});CanonicalExistingActorPublicationV3 publication(manager);target_providers::Handle16 result;const CanonicalExistingActorV3 existing{out,&actor->source_name(),&actor->source_archetype()};assert(publication.publish(existing,actor->source_name().c_str(),actor->source_archetype().c_str(),-1,false,result,error));assert(manager.source_count50()==1&&manager.characters()==std::vector<std::uintptr_t>{actor->object->identity});assert(manager.object(result.key)->identity==actor->object->identity&&actor->shared_handle().key==result.key);assert(actor->object->properties==properties&&actor->object->life==life);assert(!publication.publish(existing,actor->source_name().c_str(),actor->source_archetype().c_str(),-1,false,result,error));assert(manager.source_count50()==1);
 assert(result.key==1&&manager.source_next_key4c()==2&&publication.completed_v4(actor->object->identity));
 std::cout<<"Canonical existing retained Character adoption PASS same identity/Handle/property/life/name/room, preflight and single source allocation/publication; script VM lifecycle not claimed\n";
}
