#include "canonical_destructible_container_v16.hpp"
#include "canonical_point3d_globals_v1.hpp"
#include "destructible_container_data_connection_v16.hpp"
#include "destructible_dictionary_fixture_v16.inc"
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include "destructible_data_fixture_v16.inc"
using namespace dh2::world;
unsigned checks{};void check(bool v){++checks;if(!v){std::fprintf(stderr,"FAIL %u\n",checks);std::exit(1);}}
bool assertion(void*,std::string&){return true;}
void defaults(CanonicalDestructibleContainerV16& o,const char* name){std::string e;o.base().class_name20()="DestructibleContainer";auto a=o.properties();CanonicalPropertyMapV1 m({nullptr,&canonical_vec3_origin_v1(),assertion});check(m.init_properties(a,e)&&m.load_defaults(a,e));check(m.set_property(a,"data_desc",name,e));}
int main(){std::string e;auto table=std::make_shared<DestructibleContainerTableV16>();check(table->load(destructible_group0_records_bin,sizeof destructible_group0_records_bin,destructible_group0_names_bin,sizeof destructible_group0_names_bin,e)&&table->size()==37);
 auto run_declaration=[&](std::map<std::string,std::string>& attrs){dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);DestructibleContainerServicesV16 services;services.table=table;auto o=std::make_shared<CanonicalDestructibleContainerV16>(pin,r,GameObjectInitializationServicesV1{},services);o->base().class_name20()="DestructibleContainer";CanonicalObjectManagerV1 manager({});auto b=o->canonical(o);dh2::target_providers::Handle16 handle{};check(manager.add(b,attrs["name"].c_str(),"DestructibleContainer",0,false,handle,e));check(manager.object(handle.key)->shared_handle==&o->base().shared_handle());auto a=o->properties();CanonicalPropertyMapV1 map({nullptr,&canonical_vec3_origin_v1(),assertion});check(map.init_properties(a,e)&&map.load_defaults(a,e));CanonicalSourceObjectRequestV1 q;q.source_lease=pin;q.source_context=&attrs;q.attribute=[](void* c,std::uint32_t,const char* key)->const char*{auto& attrs=*static_cast<std::map<std::string,std::string>*>(c);auto i=attrs.find(key);return i==attrs.end()?nullptr:i->second.c_str();};check(map.load_overrides(a,q,e));std::int32_t id{};check(o->get_data_id(id,e)&&id>=0&&table->row(id)->visual()>=0);};
#include "destructible_declarations_v16.inc"
 {dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);unsigned init_final_calls{};DestructibleContainerServicesV16 services;services.common.spawn_roll_and_probability=[&](std::int32_t& roll,std::int32_t& probability,std::string&){++init_final_calls;roll=100;probability=100;return true;};auto actual=std::make_shared<CanonicalDestructibleContainerV16>(pin,r,GameObjectInitializationServicesV1{},services);auto receiver=CanonicalDestructibleContainerV16::factory_receiver(actual,pin);bool game_object{};check(receiver.is_game_object&&receiver.is_game_object(game_object,e)&&game_object);check(static_cast<bool>(receiver.source_init_final_v95));check(receiver.source_init_final_v95(e));check(init_final_calls==1);}
 {auto run_final=[&](std::int32_t state,bool update){dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);std::vector<std::string> calls;GameObjectInitializationServicesV1 init;init.owner=pin;init.check_spawn_probability=[&](auto& roll,std::string&){calls.push_back("GameObject.CheckSpawnProbability");roll=0;return true;};init.init_pf_object=[&](bool,const float*,float,std::uintptr_t,std::string&){calls.push_back("GameObject.InitPF");return true;};init.visual_sync=[&](auto,std::string&){calls.push_back("Visual.Sync");return true;};init.light_set_id=[&](const auto&,auto& id,std::string&){calls.push_back("LightSet.Lookup");id=0;return true;};init.visual_set_light_set=[&](auto,auto,std::string&){calls.push_back("Visual.SetLightSet");return true;};init.visual_root=[&](auto,auto& root,std::string&){calls.push_back("Visual.Root");root=0;return true;};init.update_pf_object=[&](std::string&){calls.push_back("GameObject.UpdatePFObject");return true;};DestructibleContainerServicesV16 services;services.common.spawn_roll_and_probability=[&](auto& roll,auto& probability,std::string&){calls.push_back("Container.CheckSpawnProbability");roll=0;probability=100;return true;};services.common.scene_flags=[&](auto,auto,std::string&){calls.push_back("Container.SetState");return true;};services.common.source_on_interact=[&](std::string&){calls.push_back("GameObject.Update");return true;};services.common.create_attach_po_decor=[&](std::string&){calls.push_back("PODecor.SetPhysical");return true;};auto actual=std::make_shared<CanonicalDestructibleContainerV16>(pin,r,init,services);*actual->base().integer(0x274)=100;*actual->base().pointer(0x2d8)=1;if(state!=2){check(actual->source_set_state_v91(static_cast<std::uint8_t>(state),e));calls.clear();}auto receiver=CanonicalDestructibleContainerV16::factory_receiver(actual,pin);check(static_cast<bool>(receiver.source_init_final_v95));check(receiver.source_init_final_v95(e));std::vector<std::string> expected={"Container.CheckSpawnProbability","GameObject.CheckSpawnProbability","GameObject.InitPF","Visual.Sync","LightSet.Lookup","Visual.SetLightSet","Visual.Root","GameObject.UpdatePFObject"};if(update)expected.push_back("GameObject.Update");expected.push_back("PODecor.SetPhysical");check(calls==expected);};run_final(2,true);run_final(3,false);run_final(4,false);}
 auto dictionary=std::make_shared<dh2::data::GameObjectDictionaryV11>();check(dictionary->load(game_objects_dictionary_pyarray_bin,sizeof game_objects_dictionary_pyarray_bin,game_objects_dictionary_pyarraynames_bin,sizeof game_objects_dictionary_pyarraynames_bin,e)&&dictionary->size()==85);DestructibleContainerDataConnectionV16 connection(table,dictionary);
 for(auto name:actual_data_names){std::int32_t id{};const DestructibleContainerRowV16* row{};check(connection.resolve(name,id,row,e)&&row);dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);CanonicalGameObjectBaseOwnerV1 base(123,1,pin,r);check(connection.visual_asset(base,row->visual(),e));check(!base.string(0x290)->empty()&&base.string(0x290)->find(".bdae")!=std::string::npos);}
 const unsigned char* gold=rows_original_v16_bin+8;
 for(int i=0;i<37;++i){auto* row=table->row(i);check(!std::memcmp(row->prefix4_1c.data(),gold,28));gold+=28;check(row->keep_physics20==*gold++);check(!std::memcmp(&row->raw24,gold,4));gold+=4;check(!std::memcmp(&row->loot28,gold,4));gold+=4;check(!std::memcmp(&row->script_length2c,gold,4));gold+=4;check(!std::memcmp(row->script30.data(),gold,row->script30.size()));gold+=row->script30.size();check(!std::memcmp(row->tail34_40.data(),gold,16));gold+=16;check(table->data_id(table->names()[i])==i);}
 check(gold==rows_original_v16_bin+sizeof rows_original_v16_bin);
 for(auto name:actual_data_names){dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);DestructibleContainerServicesV16 s;s.table=table;CanonicalDestructibleContainerV16 o(pin,r,{},s);defaults(o,name);check(o.base().type_f4()==1&&o.state()==2&&o.stages()==0&&o.remaining()==0);check(*o.base().pointer(0x100)==reinterpret_cast<std::uintptr_t>(&o.network(0)));check(*o.base().pointer(0x104)==reinterpret_cast<std::uintptr_t>(&o.network(1)));check(o.network(0).count()==3&&o.network(1).member(2)->mask==32);std::int32_t id{};check(o.get_data_id(id,e));check(id==table->data_id(name));check(!o.init_post(e)&&!e.empty());}
 {dh2::actor::RuntimeState r{};auto pin=std::make_shared<int>(1);std::vector<std::string> calls;GameObjectInitializationServicesV1 init;init.owner=pin;DestructibleContainerServicesV16 s;s.owner=pin;s.table=table;
  s.common.spawn_roll_and_probability=[&](auto& roll,auto& prob,std::string&){roll=100;prob=100;calls.push_back("spawn");return true;};s.bind_callbacks=[&](bool derived,std::string&){check(derived);calls.push_back("callbacks");return true;};s.animation_count=[&](auto& count,std::string&){count=5;calls.push_back("count");return true;};s.play_index=[&](auto index,bool loop,std::string&){check((index==1||index==2)&&!loop);calls.push_back("index"+std::to_string(index));return true;};s.common.play_sound_3d=[&](auto id,std::string&){check(id==-1);calls.push_back("sound");return true;};s.constant=[&](const char* group,const char* key,auto& id,std::string&){check(std::string(group)=="v2QuestObjectiveType"&&std::string(key)=="DestroyGameObject");id=17;calls.push_back("constant");return true;};s.raise_quest=[&](const auto& event,std::string&){check(event.id==17&&(event.actor==42||event.actor==0)&&event.room==3&&event.data_id==-1&&event.relation==-1);calls.push_back("quest");return true;};s.common.scene_flags=[&](auto,auto,std::string&){calls.push_back("state");return true;};s.common.play_animation=[&](const char* name,bool& played,std::string&){check(std::string(name)=="activate");played=true;calls.push_back("activate");return true;};s.common.detach_physical=[&](std::string&){calls.push_back("detach");return true;};s.common.drop_loot_table=[&](auto id,auto actor,auto powers,bool converted,std::string&){check(id==-1&&actor==42&&powers==-1&&!converted);calls.push_back("loot");return true;};s.common.has_script=[&](bool& b,std::string&){b=false;calls.push_back("script");return true;};s.common.source_on_interact=[&](std::string&){calls.push_back("update");return true;};s.as_character=[&](auto actor,bool& yes,std::string&){check(actor==42);yes=false;calls.push_back("aschar");return true;};
  CanonicalDestructibleContainerV16 o(pin,r,init,s);defaults(o,"");o.base().room64()=3;*o.base().pointer(0x2d8)=99;check(o.init_post(e)&&o.stages()==2&&o.remaining()==2);calls.clear();check(o.interact(42,e)&&o.remaining()==1);check(calls==std::vector<std::string>({"index1","sound"}));calls.clear();check(o.interact(42,e)&&o.remaining()==0);check(calls==std::vector<std::string>({"index2","sound"}));calls.clear();check(o.interact(42,e)&&o.state()==3);check(calls==std::vector<std::string>({"constant","quest","state","detach","state","activate","sound","update","aschar"}));calls.clear();check(o.animation_event("opened",e));check(calls==std::vector<std::string>({"constant","quest","loot","script"}));check(o.animation_event("fx",e));}
 std::printf("DestructibleContainer actual37 rows/original projections +9 authored names +same canonical staged interaction PASS %u checks; external services declared fixtures\n",checks);
}
