#define main historical_session_audit_main
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wreturn-type"
#include "character_script_session.cpp"
#pragma GCC diagnostic pop
#undef main
#include "../character_script_init_vitals.hpp"
#include "../../game-data/skill_tables.hpp"
namespace {
struct Skills {unsigned configure=0,update=0;static int invoke(void* p,CharacterScriptSession&,const ScriptLifecycleRequest32& r){auto& t=*static_cast<Skills*>(p);if(r.service==script_configure_skills)++t.configure;else if(r.service==script_update_skills)++t.update;else return -1;return 0;}};
}
int main(int argc,char** argv){try{
 check(argc==5);Inputs raw(argv[1]);auto common=file(argv[2]),monster=file(argv[3]);auto actors=placements(file(argv[4]));check(actors.size()==11);CharacterGameDesign design;std::string error;check(design.initialize(raw.input,error));auto d=design.borrow();Host h;h.rows.resize(d.levels()->levels.size());for(unsigned i=0;i<h.rows.size();++i)std::memcpy(&h.rows[i],d.levels()->levels[i].scalar.words+12,24);auto at=std::find(d.levels()->level_names.begin(),d.levels()->level_names.end(),"GOTHICUS_CRYPT_01");check(at!=d.levels()->level_names.end());h.level={int(at-d.levels()->level_names.begin()),0};auto player=std::make_shared<dh2::data::PropertyState>();dh2::data::reset_properties(*d.rules(),*player,&d.characters()->rows[263]);check(dh2::data::recalc_properties_with_class(*d.classes(),*d.rules(),*player,error));auto pv=dh2::data::property_view(*d.rules(),*player);check(!dh2_character_host_context_sync_level(&h.player,&pv));HostContextBindings16 host{{&h,Host::invoke}};
 MissingSave missing;DebugFileServices24 files{&missing,MissingSave::open,MissingSave::close};auto* debug=dh2_character_debug_create();check(debug);DebugLevelBinding16 level_binding{debug,&files};LevelServices16 level{&level_binding,dh2_character_debug_level_service};auto* modules=dh2_fx_debug_modules_create(debug,&files);check(modules);dh2::fx::PreloadServices16 debug_services{modules,dh2_fx_debug_preload_service};Skills skill_fixture;CharacterInitServices16 skill_services{&skill_fixture,Skills::invoke};unsigned completed=0,identity_guards=0,missing_skills=0;
 for(unsigned i=0;i<actors.size();++i){auto actor=actors[i];auto row=std::find(d.characters()->names.begin(),d.characters()->names.end(),actor.row);check(row!=d.characters()->names.end());CharacterScriptSessionInput in;in.identity=0xabcdef0123000000ull+i+1;in.name=actor.name;in.properties=std::make_shared<dh2::data::PropertyState>();in.combat=std::make_shared<dh2::data::CombatActorState>();in.position=actor.position;in.source_is_character=1;in.common={common.data(),common.size()};in.external={monster.data(),monster.size()};in.host=&host;in.level=&level;dh2::data::reset_properties(*d.rules(),*in.properties,&d.characters()->rows[row-d.characters()->names.begin()]);check(dh2::data::recalc_properties_with_class(*d.classes(),*d.rules(),*in.properties,error));auto session=CharacterScriptSession::create(design.borrow(),in,error);check(bool(session));check(session->start()==0&&session->error().empty());auto expected=*session->properties();auto expected_view=dh2::data::property_view(*d.rules(),expected);dh2::data::VitalsChange hp{},mp{};check(!dh2_vitals_initialize(&expected_view,&hp,&mp));auto combat=*session->combat_state();ScriptSessionInit32 binding{in.identity,&debug_services,&skill_services,0};CharacterInitServices16 service{&binding,dh2_character_script_session_init_service};
  const ScriptLifecycleRequest32 refresh{script_refresh_vitals,0,0,0,in.identity,0};auto bad=refresh;bad.subject^=0x100000000ull;auto before=*session->properties();check(dh2_character_script_session_init_service(&binding,*session,bad)==-1&&!std::memcmp(&before,session->properties().get(),sizeof(before)));++identity_guards;
  check(service.invoke(service.context,*session,refresh)==0);check(!std::memcmp(&expected,session->properties().get(),sizeof(expected))&&!std::memcmp(&combat,session->combat_state().get(),sizeof(combat)));check(session->properties()==in.properties&&session->combat_state()==in.combat);++completed;
  const ScriptLifecycleRequest32 configure{script_configure_skills,0,0,0,0,0},update{script_update_skills,0,0,0,0,0};check(!service.invoke(service.context,*session,configure)&&!service.invoke(service.context,*session,update));binding.skills=nullptr;check(service.invoke(service.context,*session,configure)!=0&&service.invoke(service.context,*session,update)!=0);++missing_skills;
 }
 check(skill_fixture.configure==11&&skill_fixture.update==11);unsigned count=0,loaded=0;check(dh2_character_debug_snapshot(debug,&loaded,&count)==1&&loaded);bool found=false;for(unsigned i=0;i<count;++i){const char* name=nullptr;unsigned value=1;check(dh2_character_debug_entry(debug,i,&name,&value)==1);if(!std::strcmp(name,"isTracingChar_Stats")){check(!value);found=true;}}check(found);dh2_fx_debug_modules_destroy(modules);dh2_character_debug_destroy(debug);
 std::cout<<"{\"validation\":\"PASS\",\"actual_Crypt_session_vitals\":"<<completed<<",\"identity_atomic_guards\":"<<identity_guards<<",\"missing_skills_rejected\":"<<missing_skills<<",\"skills_fixture_configure\":"<<skill_fixture.configure<<",\"skills_fixture_update\":"<<skill_fixture.update<<",\"genuine_DebugSwitches_missing_file_fixture_deliveries\":"<<missing.opened<<",\"host_fixture_projection_reads\":"<<h.reads<<",\"combat_state_unchanged\":true,\"checks\":"<<checks<<",\"mismatches\":0}\n";
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
