"""Original buff gold in a sanitizer DSO, linked to genuine central timers/data."""
import argparse,hashlib,json,struct,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def linux(p):return '/mnt/c/'+str(p.resolve()).replace('\\','/')[3:]
def words(*xs):return struct.pack('<'+'I'*len(xs),*(x&0xffffffff for x in xs))
def text(s):v=s.encode();return words(len(v))+v
def main():
 p=argparse.ArgumentParser();p.add_argument('--main-linked',action='store_true');p.add_argument('--output',type=Path);a=p.parse_args();scratch=REPO/'.local-inputs/character-buffs-discovery';ref=ROOT/'reference/character-buffs';gold=ref/'buff-fixtures.json';source=json.loads(gold.read_text());opcodes=dict(add=0,delete=1,expire=2,elapsed=3,remove_all=4,dot=5,destroy=6);tracecodes=dict(start=0,stop=1,time_left=2,fx_load=3,fx_release=4,fx_object=5,fx_enable=6,recalc=7);encoded=bytearray(b'BUF1'+words(len(source['records']))+struct.pack('<448i',*source['defaults'],*source['types']))
 for r in source['records']:
  op=r['operation'];params=r['args'];names=[]
  if op=='add':params=params[:5];names=[r['args'][5]]
  elif op=='dot':params=r['args'][:3]+[len(r['args'][3])];names=r['args'][3]+r['args'][4]
  encoded+=words(opcodes[op],len(params),*params,len(names))+b''.join(text(n) for n in names);s=r['snapshot'];encoded+=words(r['result'],s['declarations'],len(s['instances']),len(s['timers']))
  for serial,id,strength,timer,name,fx,sheet in s['instances']:encoded+=words(serial,id,strength,timer)+text(name)+words(fx)+bytes.fromhex(sheet)
  encoded+=bytes.fromhex(s['properties'])+b''.join(words(*row) for row in s['timers']);encoded+=words(len(r['trace']))
  for row in r['trace']:encoded+=words(len(row),tracecodes[row[0]],*row[1:])
 hostgold=scratch/'host-fixtures.bin';hostgold.write_bytes(encoded);commands=[]
 def run(*arguments):
  r=subprocess.run(['wsl','--cd',linux(REPO),*arguments],capture_output=True,text=True,timeout=120);commands.append(dict(arguments=arguments,returncode=r.returncode,stdout=r.stdout,stderr=r.stderr));assert r.returncode==0 and not r.stderr.strip(),dict(arguments=arguments,returncode=r.returncode,stdout=r.stdout[-2000:],stderr=r.stderr[-6000:]);return r.stdout.strip()
 flags=['-std=c++17','-O1','-g','-fno-fast-math','-ffp-contract=off','-fsanitize=address,undefined','-fno-omit-frame-pointer','-Wall','-Wextra','-Werror'];worlddir='/home/adampalace/dh2-world-build';runtimedir=worlddir+'/script-runtime';datadir=worlddir+'/game-data';world=worlddir+'/libdh2_level_world.so';runtime=runtimedir+'/libdh2_script_runtime.so';data=datadir+'/libdh2_game_data.so';before={x:run('sha256sum',x).split()[0] for x in [world,runtime,data]};links=['-L'+worlddir,'-ldh2_level_world','-L'+datadir,'-ldh2_game_data','-L'+runtimedir,'-ldh2_script_runtime','-Wl,-rpath,'+worlddir,'-Wl,-rpath,'+datadir,'-Wl,-rpath,'+runtimedir];library=linux(scratch/'libcharacter_buffs_audit.so');exe=linux(scratch/'host');files=[ROOT/x for x in ['character_buffs.hpp','character_buffs.cpp','tests/character_buffs.cpp','tests/character_buffs_host.py','tests/character_buffs_differential.py','tests/character_buffs_oracle.cpp']];sources={str(x.relative_to(REPO)):sha(x) for x in files}
 if a.main_linked:library=world;modulelinks=[]
 else:run('g++',*flags,'-fPIC','-shared',linux(ROOT/'character_buffs.cpp'),*links,'-o',library);modulelinks=['-L'+linux(scratch),'-lcharacter_buffs_audit']
 run('g++',*flags,linux(ROOT/'tests/character_buffs.cpp'),'-I'+linux(ROOT),*modulelinks,*links,'-Wl,--export-dynamic','-Wl,-rpath,'+linux(scratch),'-ldl','-o',exe);env=['env','LD_LIBRARY_PATH='+worlddir+':'+datadir+':'+runtimedir+':'+linux(scratch),'ASAN_OPTIONS=detect_leaks=1:abort_on_error=1','UBSAN_OPTIONS=halt_on_error=1'];assets=REPO/'port/android-native/app/src/main/assets/data';audit=json.loads(run(*env,exe,linux(hostgold),linux(assets)));checklibs=run(*env,'ldd',exe);assert audit['validation']=='PASS' and audit['module_library']==library and audit['world_library']==world and audit['data_library']==data;assert all(x in checklibs for x in [world,runtime,data,'libasan.so','libubsan.so']);binaries={x:run('sha256sum',x).split()[0] for x in [world,runtime,data,library,exe]};assert all(binaries[x]==v for x,v in before.items());assert all(sha(REPO/x)==v for x,v in sources.items());arm=ROOT/'reports/character-buffs-arm64-differential.json';armproof=json.loads(arm.read_text());assert armproof['validation']=='PASS' and armproof['gold_sha256']==sha(gold);assert all(sha(REPO/x)==v for x,v in armproof['source_sha256'].items());inputs={str(x.relative_to(REPO)):sha(x) for x in [gold,hostgold,assets/'character_classes_pyarray.bin',assets/'character_classes_pyarraynames.bin',assets/'character_classes_pystructnames.bin']};report=dict(validation='PASS',scope=__doc__,host_audit=audit,source_sha256=sources,binary_sha256=binaries,input_sha256=inputs,original_sha256=armproof['original_sha256'],arm64_report_sha256=sha(arm),sanitizers=['AddressSanitizer','UndefinedBehaviorSanitizer'],sanitizer_findings=0,main_world_library_executed=True,module_in_main_world=a.main_linked,full_FX_or_damage_application=False,packaged_APK=False,commands=commands,linked_dependencies=checklibs);out=a.output or ROOT/('reports/character-buffs-main-linked-host-audit.json' if a.main_linked else 'reports/character-buffs-host-audit.json');out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(dict(validation='PASS',host=audit)))
if __name__=='__main__':main()
