"""Source Kill gold replay and genuine dependency prefixes in sanitizer DSOs.

Properties/Character classification/handle, real event2 dispatcher and cached
quest constants execute from actual sanitizer DSOs.
Level/empty-aggro/local projections are explicit fixture inputs. Actual required
loot, XP and OnDied backends fail; no fake quest, animation or physics delivery.
"""
import argparse,hashlib,json,struct,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def linux(p):return '/mnt/c/'+str(p.resolve()).replace('\\','/')[3:]
def words(*xs):return struct.pack('<'+'I'*len(xs),*(x&0xffffffff for x in xs))
def text(s):b=s.encode();return words(len(b))+b
def vector(xs):return words(len(xs),*xs)
def main():
 p=argparse.ArgumentParser();p.add_argument('--main-linked',action='store_true');p.add_argument('--output',type=Path);a=p.parse_args();scratch=REPO/'.local-inputs/character-kill-discovery';gold=ROOT/'reference/character-kill/kill-fixtures.json';source=json.loads(gold.read_text());ai=ROOT/'reports/character-target-providers-arm64-differential.json';aidata=json.loads(ai.read_text());assert aidata['validation']=='PASS' and aidata['ai_asset_sha256']==sha(REPO/'port/android-native/app/src/main/assets/data/ai_pyarray.bin');encoded=bytearray(b'KIL1'+words(len(source['records']))+struct.pack('<448i',*source['defaults'],*source['types'])+vector(aidata['types']))
 constants=REPO/'port/android-native/app/src/main/assets/data/v2quests_pycst.bin';inventory=REPO/'port/script-runtime/reports/design-constants-bundled-assets.json';items=json.loads(inventory.read_text());assert items['validation']=='PASS';record=next(x for x in items['bundled_assets'] if Path(x['path'])==constants.relative_to(REPO));assert record['sha256']==sha(constants) and record['bytes']==constants.stat().st_size
 keys=['online','loot_gate','killer','oid','property','template','dead_byte','suppress','is_character','cast','remote','trophy_id','mutate_op','mutate_oid','mutate_property','mutate_template','mutate_suppress','mutate_killer']
 for r in source['records']:
  x=r['config'];encoded+=words(r['wrapper'])+b''.join(struct.pack('<224i',*s) for part in r['sheets'] for s in part)+words(r['attacker'],r['force'])+b''.join(words(*x[k]) for k in ['players','local','owners','targets','constant_values'])+b''.join(vector(x[k]) for k in ['dead','levels','counts','entries'])+words(*(x.get(k,-1 if k=='mutate_op' else 0) for k in keys))+words(len(r['trace']))+b''.join(words(op,subject,target,arg)+text(name)+text(key)+vector(payload)+words(index) for op,subject,target,arg,name,key,payload,index in r['trace'])+b''.join(words(*s) for s in r['state'])+b''.join(bytes.fromhex(s) for part in r['final_sheets'] for s in part)+words(*r['output'])
 encoded+=words(len(source['reentry']))
 for r in source['reentry']:
  x=r['config'];assert len(r['nested'])==1;encoded+=words(x['reentry_op'],x['nested_wrapper'],x['nested_force'],r['wrapper'],r['force'])+b''.join(struct.pack('<224i',*s) for part in r['sheets'] for s in part)
  for tr in [r['trace'],r['nested'][0]['trace']]:encoded+=words(len(tr))+b''.join(words(op,subject,target,arg)+text(name)+text(key)+vector(payload)+words(index) for op,subject,target,arg,name,key,payload,index in tr)
  encoded+=b''.join(words(*s) for s in r['state'])+b''.join(bytes.fromhex(s) for part in r['final_sheets'] for s in part)+words(*r['output'])+words(*r['nested'][0]['output'])
 hostgold=scratch/'host-fixtures.bin';hostgold.write_bytes(encoded);commands=[]
 def run(*args):
  r=subprocess.run(['wsl','--cd',linux(REPO),*args],capture_output=True,text=True,timeout=120);commands.append(dict(arguments=args,returncode=r.returncode,stdout=r.stdout,stderr=r.stderr));assert r.returncode==0 and not r.stderr.strip(),dict(args=args,returncode=r.returncode,stdout=r.stdout[-1800:],stderr=r.stderr[-6500:]);return r.stdout.strip()
 flags=['-std=c++17','-O1','-g','-fno-fast-math','-ffp-contract=off','-fsanitize=address,undefined','-fno-omit-frame-pointer','-Wall','-Wextra','-Werror'];worlddir='/home/adampalace/dh2-world-build';datadir=worlddir+'/game-data';runtimedir=worlddir+'/script-runtime';world=worlddir+'/libdh2_level_world.so';data=datadir+'/libdh2_game_data.so';runtime=runtimedir+'/libdh2_script_runtime.so';before={x:run('sha256sum',x).split()[0] for x in [world,data,runtime]};links=['-L'+worlddir,'-ldh2_level_world','-L'+datadir,'-ldh2_game_data','-L'+runtimedir,'-ldh2_script_runtime','-Wl,-rpath,'+worlddir,'-Wl,-rpath,'+datadir,'-Wl,-rpath,'+runtimedir];library=linux(scratch/'libcharacter_kill_audit.so');exe=linux(scratch/'host');files=[ROOT/x for x in ['character_kill.hpp','character_kill.cpp','tests/character_kill.cpp','tests/character_kill_host.py','tests/character_kill_differential.py']];sources={str(x.relative_to(REPO)):sha(x) for x in files}
 if a.main_linked:library=world;modulelinks=[]
 else:run('g++',*flags,'-fPIC','-shared',linux(ROOT/'character_kill.cpp'),*links,'-o',library);modulelinks=['-L'+linux(scratch),'-lcharacter_kill_audit']
 run('g++',*flags,linux(ROOT/'tests/character_kill.cpp'),'-I'+linux(ROOT),*modulelinks,*links,'-Wl,-rpath,'+linux(scratch),'-ldl','-o',exe);env=['env','LD_LIBRARY_PATH='+worlddir+':'+datadir+':'+runtimedir+':'+linux(scratch),'ASAN_OPTIONS=detect_leaks=1:abort_on_error=1','UBSAN_OPTIONS=halt_on_error=1'];audit=json.loads(run(*env,exe,linux(hostgold),linux(constants)));linked=run(*env,'ldd',exe);assert audit['validation']=='PASS' and audit['module_library']==library and audit['world_library']==world and audit['data_library']==data and audit['runtime_library']==runtime;assert all(x in linked for x in [world,data,runtime,'libasan.so','libubsan.so']);binaries={x:run('sha256sum',x).split()[0] for x in [world,data,runtime,library,exe]};assert all(binaries[x]==v for x,v in before.items());assert all(sha(REPO/x)==v for x,v in sources.items());arm=ROOT/'reports/character-kill-arm64-differential.json';proof=json.loads(arm.read_text());assert proof['validation']=='PASS' and proof['gold_sha256']==sha(gold);assert all(sha(REPO/x)==v for x,v in proof['source_sha256'].items());report=dict(validation='PASS',scope=__doc__,host_audit=audit,source_sha256=sources,binary_sha256=binaries,input_sha256={str(x.relative_to(REPO)):sha(x) for x in [gold,hostgold,ai,constants,inventory]},original_sha256=proof['original_sha256'],arm64_report_sha256=sha(arm),sanitizers=['AddressSanitizer','UndefinedBehaviorSanitizer'],sanitizer_findings=0,main_world_library_executed=True,module_in_main_world=a.main_linked,full_loot_xp_quest_AI_backends=False,packaged_APK=False,commands=commands,linked_dependencies=linked);out=a.output or ROOT/('reports/character-kill-main-linked-host-audit.json' if a.main_linked else 'reports/character-kill-host-audit.json');out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(dict(validation='PASS',host=audit)))
if __name__=='__main__':main()
