#include "../character_skills.hpp"
#include <array>
#include <fstream>
#include <iostream>
#include <cstring>
#include <functional>
using namespace dh2::character::skills;
namespace {unsigned checks=0;void check(bool b){++checks;if(!b)throw std::runtime_error("Skills check "+std::to_string(checks));}unsigned word(std::istream& f){unsigned n;f.read(reinterpret_cast<char*>(&n),4);check(bool(f));return n;}std::string text(std::istream& f){std::string s(word(f),0);f.read(s.data(),s.size());check(bool(f));return s;}
struct Params {unsigned count[2],existing[2],mutation,empty,fail,state,status,returned,update;};
struct Item {std::string name;Instance32 value;};
struct Fixture {
 Params p;State40 state{0xabcdef0123000011ull,{},{}};std::vector<const Instance32*> slots[2];std::vector<std::unique_ptr<Item>> items;List16 lists[2]{};std::array<Row16,4> rows[2];std::array<std::string,4> names[2];std::string paths[2]={"original/path/0/","original/path/1/"};unsigned active=0,charactive=0;bool touched=false;std::vector<std::string> trace;std::vector<std::unique_ptr<std::string>> saved;Services16 cb{this,invoke};unsigned deliveries=0,fail_at=0;
 explicit Fixture(Params v):p(v){for(unsigned k=0;k<2;++k){lists[k]={nullptr,p.count[k],0};for(unsigned i=0;i<4;++i){names[k][i]=p.empty&(1u<<(k*4+i))?"":std::string(k?"spell":"skill")+std::to_string(i);rows[k][i]={names[k][i].c_str(),static_cast<unsigned>(names[k][i].size()),0};}for(unsigned i=0;i<p.existing[k];++i)slots[k].push_back(instance("existing"+std::to_string(i),k?-1:static_cast<int>(i)));}sync();}
 const Instance32* instance(const std::string& name,int index){auto p=std::make_unique<Item>();p->name=name;p->value={state.owner,p->name.c_str(),static_cast<unsigned>(index),-1,static_cast<float>(index),0};const auto* result=&p->value;items.push_back(std::move(p));return result;}
 void sync(){state.skills={slots[0].data(),static_cast<unsigned>(slots[0].size()),0};state.spells={slots[1].data(),static_cast<unsigned>(slots[1].size()),0};}
 void event(const std::string& op,std::initializer_list<std::string> args={}){std::string row=op;for(const auto& a:args)row+='|'+a;trace.push_back(row);auto trigger=p.mutation==7?"debug_switch":p.mutation>=2&&p.mutation<=4?"declare":p.mutation==1?"load":"set_skill";if(!touched&&op==trigger){touched=true;switch(p.mutation){case 1:case 7:active=charactive=1;break;case 2:lists[0].count=1;break;case 3:lists[0].count=3;break;case 4:slots[1].push_back(instance("reentered",-1));sync();break;case 8:charactive=1;break;case 9:for(auto& s:slots){auto copy=s;s.swap(copy);}sync();break;case 10:slots[1].push_back(instance("added_spell",-1));sync();break;case 11:check(dh2_character_skills_update(&state,&cb)==1);break;default:break;}}}
 static int invoke(void* p,State40* state,const Request48* r,Response32* out){auto& f=*static_cast<Fixture*>(p);check(state==&f.state&&r&&out);if(++f.deliveries==f.fail_at)return -1;auto s=[](unsigned n){return std::to_string(n);};auto aid=static_cast<unsigned>(r->script-0xabcdef0123000051ull);switch(r->operation){
 case debug_load:f.event("debug_load");break;case debug_switch:f.event("debug_switch",{r->name});break;case active_script:out->object=0xabcdef0123000051ull+(r->kind?f.charactive:f.active);break;
 case capture_path:f.event("capture_path",{f.paths[aid]});f.saved.push_back(std::make_unique<std::string>(f.paths[aid]));out->object=reinterpret_cast<std::uintptr_t>(f.saved.back().get());break;
 case assign_path:{auto name=r->name?std::string(r->name):*reinterpret_cast<const std::string*>(r->payload);f.paths[aid]=name;f.event("path",{s(aid),name});break;}case release_path:break;
 case get_list:f.event("list",{s(r->kind)});out->list=&f.lists[r->kind];break;case reserve_slots:f.event("reserve",{s(r->kind),s(r->count)});f.slots[r->kind].reserve(r->count);f.sync();break;
 case arguments_begin:case arguments_end:break;case get_row:f.event("row",{s(r->kind),s(r->index)});out->row=&f.rows[r->kind][r->index];break;
 case load_file:{std::string name=r->name;f.event("load",{s(aid),name,f.paths[aid]});int i=name=="_commons"?-1:name.back()-'0'+(name.find("spell")==0?4:0);out->count=i<0||!(f.p.fail&(1u<<i));break;}
 case declare_skill:{unsigned bits;std::memcpy(&bits,&r->instance->argument_index,4);f.event("declare",{s(aid),r->name,r->instance->script,s(bits)});break;}case reset_declaration:f.event("reset",{s(aid),r->name});break;
 case construct_instance:out->object=reinterpret_cast<std::uintptr_t>(f.instance(r->name,static_cast<int>(r->instance->index)));break;case append_slot:f.slots[r->kind].push_back(reinterpret_cast<const Instance32*>(r->payload));f.sync();break;
 case init_vcb:f.event("init_vcb",{s(aid)});break;case state_predicate:f.event("predicate",{s(r->index),s(f.p.state)});out->count=f.p.state==r->index;break;
 case set_skill:{unsigned bits;std::memcpy(&bits,&r->instance->argument_index,4);f.event("set_skill",{s(aid),r->name,r->instance->script,s(bits)});out->source_error=f.p.status;out->count=f.p.returned;out->object=0xabcdef0123000077ull;break;}
 case erase_results:f.event("erase_results",{s(r->count)});break;case call_update:f.event("update_skill",{s(aid),r->name});break;case call_cleanup:f.event("cleanup_skill",{s(aid),r->name});break;case release_results:break;default:check(false);}
 return 0;}
};}
int main(int argc,char** argv){try{check(argc==2);std::ifstream f(argv[1],std::ios::binary);check(word(f)==0x314f4b53);auto n=word(f);unsigned requests=0,nested=0;for(unsigned i=0;i<n;++i){Params p{};f.read(reinterpret_cast<char*>(&p),44);check(bool(f));Fixture x(p);auto nt=word(f);std::vector<std::string> want;for(unsigned j=0;j<nt;++j)want.push_back(text(f));std::vector<std::pair<std::string,unsigned>> slots[2];for(unsigned k=0;k<2;++k){auto ns=word(f);for(unsigned j=0;j<ns;++j){auto present=word(f);auto name=present?text(f):"";auto index=present?word(f):0;slots[k].emplace_back(name,index);}}auto path0=text(f),path1=text(f);auto active=word(f);check((p.update?dh2_character_skills_update(&x.state,&x.cb):dh2_character_skills_configure(&x.state,&x.cb))==1);check(x.trace==want&&x.paths[0]==path0&&x.paths[1]==path1&&x.active==active);for(unsigned k=0;k<2;++k){check(x.slots[k].size()==slots[k].size());for(unsigned j=0;j<x.slots[k].size();++j){auto* item=x.slots[k][j];check(item?slots[k][j].first==item->script&&slots[k][j].second==item->index:slots[k][j].first.empty());}}requests+=nt;if(p.mutation==11&&p.state!=6&&p.state!=7)++nested;}
 check(f.peek()==EOF);Params p{{1,1},{0,0},0,0,0,3,0,1,0};unsigned guards=0,prefixes=0;for(unsigned failure=1;failure<30;++failure){Fixture x(p);x.fail_at=failure;auto r=dh2_character_skills_configure(&x.state,&x.cb);if(x.deliveries>=failure){check(r==-2);++prefixes;}}
 Fixture x(p);auto before=x.state;x.state.skills.reserved=1;check(dh2_character_skills_configure(&x.state,&x.cb)==-1&&x.deliveries==0);++guards;x.state=before;check(dh2_character_skills_cleanup(&x.state,2,&x.cb)==-1&&x.deliveries==0);++guards;Services16 absent{};check(dh2_character_skills_update(&x.state,&absent)==-1);++guards;
 Params q{{0,0},{2,1},0,0,0,3,0,2,1};Fixture cleanup(q);auto count=cleanup.state.skills.count;check(dh2_character_skills_cleanup(&cleanup.state,0,&cleanup.cb)==1&&cleanup.state.skills.count==count);unsigned cleanup_calls=0;for(auto& e:cleanup.trace)cleanup_calls+=e.find("cleanup_skill|")==0;check(cleanup_calls==2);
 std::cout<<"{\"validation\":\"PASS\",\"comparisons\":"<<n<<",\"ordered_requests\":"<<requests<<",\"nested_reentry_cases\":"<<nested<<",\"native_atomic_guards\":"<<guards<<",\"required_failure_prefixes\":"<<prefixes<<",\"cleanup_keeps_slots\":true,\"checks\":"<<checks<<",\"mismatches\":0}\n";
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
