"""Source HitFor gold, failure prefixes and genuine DSO dependency composition.

Real properties, handle/classification, missing-file DebugSwitches, aggression,
DoT and vitals execute. Game/online/Application/party remain declared fixtures.
Full Kill and scene FX are required; real compositions stop at their failures.
"""
import argparse,hashlib,json,struct,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def linux(p):return '/mnt/c/'+str(p.resolve()).replace('\\','/')[3:]
def words(*xs):return struct.pack('<'+'I'*len(xs),*(x&0xffffffff for x in xs))
def text(s):b=s.encode();return words(len(b))+b
def main():
 p=argparse.ArgumentParser();p.add_argument('--main-linked',action='store_true');p.add_argument('--output',type=Path);a=p.parse_args();scratch=REPO/'.local-inputs/character-hit-discovery';gold=ROOT/'reference/character-hit/hit-fixtures.json';source=json.loads(gold.read_text());ai=ROOT/'reports/character-target-providers-arm64-differential.json';aidata=json.loads(ai.read_text());assert aidata['validation']=='PASS' and aidata['ai_asset_sha256']==sha(REPO/'port/android-native/app/src/main/assets/data/ai_pyarray.bin');types=aidata['types'];encoded=bytearray(b'HIT1'+words(len(source['records']))+struct.pack('<448i',*source['defaults'],*source['types'])+words(len(types),*types))
 keys=['dead','main_present','main_dead','god','monster','online','oneshot','app_oneshot','attacker_player','character','remote','attacker','cached','key','oldframe','frame','mutate_op','mutate_hp']
 for r in source['records']:
  x=r['config'];encoded+=b''.join(struct.pack('<224i',*s) for s in r['sheets'])+words(r['damage'],*(x.get(k,-1 if k=='mutate_op' else 0) for k in keys),len(x['players']),*x['players'])+words(len(r['trace']))+b''.join(words(op,subject,target)+text(name) for op,subject,target,name in r['trace'])+words(*r['state'][:4],len(r['state'][4]))+b''.join(words(*entry) for entry in r['state'][4])+b''.join(bytes.fromhex(s) for s in r['final_sheets'])+words(*r['output'])
 hostgold=scratch/'host-fixtures.bin';hostgold.write_bytes(encoded);commands=[]
 def run(*args):
  r=subprocess.run(['wsl','--cd',linux(REPO),*args],capture_output=True,text=True,timeout=120);commands.append(dict(arguments=args,returncode=r.returncode,stdout=r.stdout,stderr=r.stderr));assert r.returncode==0 and not r.stderr.strip(),dict(args=args,returncode=r.returncode,stdout=r.stdout[-1800:],stderr=r.stderr[-6500:]);return r.stdout.strip()
 flags=['-std=c++17','-O1','-g','-fno-fast-math','-ffp-contract=off','-fsanitize=address,undefined','-fno-omit-frame-pointer','-Wall','-Wextra','-Werror'];worlddir='/home/adampalace/dh2-world-build';datadir=worlddir+'/game-data';runtimedir=worlddir+'/script-runtime';world=worlddir+'/libdh2_level_world.so';data=datadir+'/libdh2_game_data.so';runtime=runtimedir+'/libdh2_script_runtime.so';before={x:run('sha256sum',x).split()[0] for x in [world,data,runtime]};links=['-L'+worlddir,'-ldh2_level_world','-L'+datadir,'-ldh2_game_data','-L'+runtimedir,'-ldh2_script_runtime','-Wl,-rpath,'+worlddir,'-Wl,-rpath,'+datadir,'-Wl,-rpath,'+runtimedir];library=linux(scratch/'libcharacter_hit_audit.so');exe=linux(scratch/'host');files=[ROOT/x for x in ['character_hit.hpp','character_hit.cpp','tests/character_hit.cpp','tests/character_hit_host.py','tests/character_hit_differential.py']];sources={str(x.relative_to(REPO)):sha(x) for x in files}
 if a.main_linked:library=world;modulelinks=[]
 else:run('g++',*flags,'-fPIC','-shared',linux(ROOT/'character_hit.cpp'),*links,'-o',library);modulelinks=['-L'+linux(scratch),'-lcharacter_hit_audit']
 run('g++',*flags,linux(ROOT/'tests/character_hit.cpp'),'-I'+linux(ROOT),*modulelinks,*links,'-Wl,-rpath,'+linux(scratch),'-ldl','-o',exe);env=['env','LD_LIBRARY_PATH='+worlddir+':'+datadir+':'+runtimedir+':'+linux(scratch),'ASAN_OPTIONS=detect_leaks=1:abort_on_error=1','UBSAN_OPTIONS=halt_on_error=1'];audit=json.loads(run(*env,exe,linux(hostgold),linux(scratch/'genuine-missing-DebugSwitches.savegame')));linked=run(*env,'ldd',exe);assert audit['validation']=='PASS' and audit['module_library']==library and audit['world_library']==world and audit['data_library']==data;assert all(x in linked for x in [world,data,runtime,'libasan.so','libubsan.so']);binaries={x:run('sha256sum',x).split()[0] for x in [world,data,runtime,library,exe]};assert all(binaries[x]==v for x,v in before.items());assert all(sha(REPO/x)==v for x,v in sources.items());arm=ROOT/'reports/character-hit-arm64-differential.json';proof=json.loads(arm.read_text());assert proof['validation']=='PASS' and proof['gold_sha256']==sha(gold);assert all(sha(REPO/x)==v for x,v in proof['source_sha256'].items());report=dict(validation='PASS',scope=__doc__,host_audit=audit,source_sha256=sources,binary_sha256=binaries,input_sha256={str(x.relative_to(REPO)):sha(x) for x in [gold,hostgold,ai]},original_sha256=proof['original_sha256'],arm64_report_sha256=sha(arm),sanitizers=['AddressSanitizer','UndefinedBehaviorSanitizer'],sanitizer_findings=0,main_world_library_executed=True,module_in_main_world=a.main_linked,full_Kill_backend=False,packaged_APK=False,commands=commands,linked_dependencies=linked);out=a.output or ROOT/('reports/character-hit-main-linked-host-audit.json' if a.main_linked else 'reports/character-hit-host-audit.json');out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(dict(validation='PASS',host=audit)))
if __name__=='__main__':main()
