"""Original host-global gold and actual world GetLevel/game-data Level decoder/private float32 Lua DSOs."""
import argparse,hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def linux(p):return '/mnt/c/'+str(p.resolve()).replace('\\','/')[3:]
def main():
 p=argparse.ArgumentParser();p.add_argument('--main-linked',action='store_true');p.add_argument('--output',type=Path);a=p.parse_args();scratch=REPO/'.local-inputs/character-host-context';scratch.mkdir(exist_ok=True);commands=[]
 def run(*arguments):
  r=subprocess.run(['wsl','--cd',linux(REPO),*arguments],capture_output=True,text=True,timeout=120);commands.append(dict(arguments=arguments,returncode=r.returncode,stdout=r.stdout,stderr=r.stderr));assert r.returncode==0 and not r.stderr.strip(),commands[-1];return r.stdout.strip()
 flags=['-std=c++17','-O1','-g','-fno-fast-math','-ffp-contract=off','-fsanitize=address,undefined','-fno-omit-frame-pointer','-Wall','-Wextra','-Werror'];world_dir='/home/adampalace/dh2-world-build';runtime_dir=world_dir+'/script-runtime';data_dir=world_dir+'/game-data';world=world_dir+'/libdh2_level_world.so';runtime=runtime_dir+'/libdh2_script_runtime.so';data=data_dir+'/libdh2_game_data.so';library=linux(scratch/'libcharacter_host_context_audit.so');exe=linux(scratch/'host');gold=ROOT/'reference/character-host-context/host-context-fixtures.bin';rows=REPO/'port/game-data/reference/level-tables'
 files=[ROOT/x for x in ['character_host_context.hpp','character_host_context.cpp','tests/character_host_context.cpp','tests/character_host_context_host.py','character_level.hpp','character_level.cpp']]+[REPO/'port/script-runtime'/x for x in ['script_runtime.h','script_runtime.c']]+[REPO/'port/game-data'/x for x in ['level_tables.hpp','level_tables.cpp','properties.hpp','properties.cpp']];sources={str(x.relative_to(REPO)):sha(x) for x in files};before={x:run('sha256sum',x).split()[0] for x in [world,runtime,data]};links=['-L'+runtime_dir,'-ldh2_script_runtime','-L'+world_dir,'-ldh2_level_world','-L'+data_dir,'-ldh2_game_data','-Wl,-rpath,'+runtime_dir,'-Wl,-rpath,'+world_dir,'-Wl,-rpath,'+data_dir]
 if a.main_linked:library=world;module_links=[]
 else:run('g++',*flags,'-shared','-fPIC',linux(ROOT/'character_host_context.cpp'),*links,'-o',library);module_links=['-L'+linux(scratch),'-lcharacter_host_context_audit']
 run('g++',*flags,linux(ROOT/'tests/character_host_context.cpp'),'-I'+linux(ROOT),*module_links,*links,'-Wl,-rpath,'+linux(scratch),'-ldl','-o',exe)
 env=['env','LD_LIBRARY_PATH='+world_dir+':'+runtime_dir+':'+data_dir+':'+linux(scratch),'ASAN_OPTIONS=detect_leaks=1:abort_on_error=1','UBSAN_OPTIONS=halt_on_error=1'];audit=json.loads(run(*env,exe,linux(gold),linux(rows)));assert audit['validation']=='PASS' and audit['module_library']==library and audit['GetLevel_library']==world and audit['runtime_library']==runtime and audit['level_decoder_library']==data
 dependencies=run(*env,'ldd',exe);assert all(x in dependencies for x in [world,runtime,data,'libasan.so','libubsan.so']);binaries={x:run('sha256sum',x).split()[0] for x in [world,runtime,data,library,exe]};assert all(binaries[x]==v for x,v in before.items()) and all(sha(REPO/x)==v for x,v in sources.items());arm=ROOT/'reports/character-host-context-arm64-differential.json';reference=json.loads(arm.read_text());assert reference['validation']=='PASS' and reference['gold_sha256']==sha(gold);capture=rows/'original-loader-capture.json';captured=json.loads(capture.read_text());assert captured['validation']=='SOURCE_CAPTURED' and captured['original_sha256']==reference['original_sha256'];assets={str((rows/x).relative_to(REPO)):sha(rows/x) for x in ['levels_pyarray.bin','levels_pyarraynames.bin','levels_pystructnames.bin']};assert all(assets[str((rows/x).relative_to(REPO))]==v for x,v in captured['assets_sha256'].items())
 report=dict(validation='PASS',scope=__doc__,host_audit=audit,source_sha256=sources,binary_sha256=binaries,original_sha256=reference['original_sha256'],original_gold_sha256=sha(gold),arm64_report_sha256=sha(arm),Level_original_loader_capture_sha256=sha(capture),Level_assets_sha256=assets,sanitizers=['AddressSanitizer','UndefinedBehaviorSanitizer'],sanitizer_findings=0,main_world_library_executed=True,module_in_main_world=a.main_linked,full_monster_Init=False,source_manager_and_Application_ownership_bound=False,packaged_APK=False,commands=commands,linked_dependencies=dependencies);out=a.output or ROOT/('reports/character-host-context-main-linked-host-audit.json' if a.main_linked else 'reports/character-host-context-host-audit.json');out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(dict(validation='PASS',host=audit)))
if __name__=='__main__':main()
