"""Source-derived gold and genuine state-owner/table/constant/stance DSO prefixes."""
import argparse,hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def linux(p):return '/mnt/c/'+str(p.resolve()).replace('\\','/')[3:]
def main():
 p=argparse.ArgumentParser();p.add_argument('--main-linked',action='store_true');p.add_argument('--output',type=Path);a=p.parse_args();scratch=REPO/'.local-inputs/character-dead-select-discovery';commands=[]
 def run(*args):
  r=subprocess.run(['wsl','--cd',linux(REPO),*args],capture_output=True,text=True,timeout=120);commands.append(dict(arguments=args,returncode=r.returncode,stdout=r.stdout,stderr=r.stderr));assert r.returncode==0 and not r.stderr.strip(),dict(args=args,stdout=r.stdout[-1800:],stderr=r.stderr[-8000:]);return r.stdout.strip()
 build='/home/adampalace/dh2-world-build';deps=[build+'/libdh2_level_world.so',build+'/game-data/libdh2_game_data.so',build+'/script-runtime/libdh2_script_runtime.so'];before={x:run('sha256sum',x).split()[0] for x in deps};flags=['-std=c++17','-O1','-g','-fno-fast-math','-ffp-contract=off','-fsanitize=address,undefined','-fno-omit-frame-pointer','-Wall','-Wextra','-Werror','-Wno-misleading-indentation'];links=[]
 for sub,name in [('', 'level_world'),('/game-data','game_data'),('/script-runtime','script_runtime')]:links+=['-L'+build+sub,'-ldh2_'+name,'-Wl,-rpath,'+build+sub]
 module=linux(scratch/'libcharacter_dead_select_audit.so');exe=linux(scratch/'host');modulelinks=[]
 files=[ROOT/x for x in ['character_dead_select.hpp','character_dead_select.cpp','tests/character_dead_select.cpp','tests/character_dead_select_host.py','tests/character_dead_select_differential.py']];sources={str(x.relative_to(REPO)):sha(x) for x in files}
 if a.main_linked:module=deps[0]
 else:
  run('g++',*flags,'-fPIC','-shared',linux(ROOT/'character_dead_select.cpp'),*links,'-Wl,--no-undefined','-o',module);modulelinks=['-L'+linux(scratch),'-lcharacter_dead_select_audit']
 run('g++',*flags,linux(ROOT/'tests/character_dead_select.cpp'),'-I'+linux(ROOT),'-rdynamic',*modulelinks,*links,'-Wl,-rpath,'+linux(scratch),'-ldl','-o',exe)
 env=['env','LD_LIBRARY_PATH='+':'.join([build,build+'/game-data',build+'/script-runtime',linux(scratch)]),'ASAN_OPTIONS=detect_leaks=1:abort_on_error=1','UBSAN_OPTIONS=halt_on_error=1'];gold=ROOT/'reference/character-dead-select/dead-select-fixtures.bin';assets=REPO/'port/android-native/app/src/main/assets/data';audit=json.loads(run(*env,exe,linux(gold),linux(assets)));linked=run(*env,'ldd',exe);assert audit['validation']=='PASS' and audit['module_library']==module and audit['world_library']==deps[0] and audit['data_library']==deps[1] and audit['runtime_library']==deps[2];assert all(x in linked for x in [*deps,'libasan.so','libubsan.so']);binary={x:run('sha256sum',x).split()[0] for x in [*deps,module,exe]};assert all(binary[x]==v for x,v in before.items());assert all(sha(REPO/x)==v for x,v in sources.items());arm=ROOT/'reports/character-dead-select-arm64-differential.json';proof=json.loads(arm.read_text());assert proof['validation']=='PASS' and proof['binary_gold_sha256']==sha(gold);assert all(sha(REPO/x)==v for x,v in proof['source_sha256'].items());inputs=[gold]+[assets/n for n in ['animations_pyarray.bin','animations_pyarraynames.bin','animations_pystructnames.bin','animations_dictionary_pyarraynames.bin','animations_dictionary_pyarray.bin','animations_pycst.bin']];report=dict(validation='PASS',scope=__doc__,host_audit=audit,source_sha256=sources,binary_sha256=binary,input_sha256={str(x.relative_to(REPO)):sha(x) for x in inputs},original_sha256=proof['original_sha256'],arm64_report_sha256=sha(arm),sanitizers=['AddressSanitizer','UndefinedBehaviorSanitizer'],sanitizer_findings=0,main_world_library_executed=True,module_in_main_world=a.main_linked,registered_behavior_backends_complete=False,packaged_APK=False,commands=commands,linked_dependencies=linked);out=a.output or ROOT/('reports/character-dead-select-main-linked-host-audit.json' if a.main_linked else 'reports/character-dead-select-host-audit.json');out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(dict(validation='PASS',host=audit)))
if __name__=='__main__':main()
