"""Missing-file DebugSwitches gold, genuine constants/timers, and six real monster Init calls through sanitized DSOs."""
import argparse,hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def linux(p):return '/mnt/c/'+str(p.resolve()).replace('\\','/')[3:]
def main():
 p=argparse.ArgumentParser();p.add_argument('--main-linked',action='store_true');p.add_argument('--output',type=Path);a=p.parse_args();scratch=REPO/'.local-inputs/character-design-services';scratch.mkdir(exist_ok=True);(scratch/'files').mkdir(exist_ok=True);commands=[]
 def run(*arguments):
  r=subprocess.run(['wsl','--cd',linux(REPO),*arguments],capture_output=True,text=True,timeout=120);commands.append(dict(arguments=arguments,returncode=r.returncode,stdout=r.stdout,stderr=r.stderr));assert r.returncode==0 and not r.stderr.strip(),dict(arguments=arguments,returncode=r.returncode,stdout=r.stdout[:3000],stderr=r.stderr[:3000]);return r.stdout.strip()
 flags=['-std=c++17','-O1','-g','-fno-fast-math','-ffp-contract=off','-fsanitize=address,undefined','-fno-omit-frame-pointer','-Wall','-Wextra','-Werror'];world_dir='/home/adampalace/dh2-world-build';runtime_dir=world_dir+'/script-runtime';data_dir=world_dir+'/game-data';world=world_dir+'/libdh2_level_world.so';runtime=runtime_dir+'/libdh2_script_runtime.so';data=data_dir+'/libdh2_game_data.so';library=linux(scratch/'libcharacter_design_services_audit.so');exe=linux(scratch/'host');gold=ROOT/'reference/character-design-services/debug-services-fixtures.bin';inputs=ROOT/'reference/character-game-design/real-cache-inputs.bin';scripts=REPO/'.local-inputs/character-script-owner-extension';common=scripts/'_commons.luac';monster=scripts/'monster.luac'
 names=['character_design_services.hpp','character_design_services.cpp','tests/character_design_services.cpp','tests/character_design_services_host.py','character_game_design.hpp','character_game_design.cpp','character_level.hpp','character_level.cpp','character_host_context.hpp','character_host_context.cpp','character_script_lifecycle.hpp','character_script_lifecycle.cpp','character_timers.hpp','character_timers.cpp'];files=[ROOT/x for x in names]+[REPO/'port/script-runtime'/x for x in ['script_runtime.h','script_runtime.c']];sources={str(x.relative_to(REPO)):sha(x) for x in files};before={x:run('sha256sum',x).split()[0] for x in [world,runtime,data]};links=['-L'+runtime_dir,'-ldh2_script_runtime','-L'+world_dir,'-ldh2_level_world','-L'+data_dir,'-ldh2_game_data','-Wl,-rpath,'+runtime_dir,'-Wl,-rpath,'+world_dir,'-Wl,-rpath,'+data_dir]
 if a.main_linked:library=world;module_links=[]
 else:run('g++',*flags,'-shared','-fPIC',linux(ROOT/'character_design_services.cpp'),*links,'-o',library);module_links=['-L'+linux(scratch),'-lcharacter_design_services_audit']
 run('g++',*flags,linux(ROOT/'tests/character_design_services.cpp'),'-I'+linux(ROOT),*module_links,*links,'-Wl,-rpath,'+linux(scratch),'-ldl','-o',exe)
 env=['env','LD_LIBRARY_PATH='+world_dir+':'+runtime_dir+':'+data_dir+':'+linux(scratch),'ASAN_OPTIONS=detect_leaks=1:abort_on_error=1','UBSAN_OPTIONS=halt_on_error=1'];audit=json.loads(run(*env,exe,linux(gold),linux(inputs),linux(scratch/'files'),linux(common),linux(monster)));assert audit['validation']=='PASS' and audit['module_library']==library and audit['world_library']==world and audit['runtime_library']==runtime
 dependencies=run(*env,'ldd',exe);assert all(x in dependencies for x in [world,runtime,data,'libasan.so','libubsan.so']);binaries={x:run('sha256sum',x).split()[0] for x in [world,runtime,data,library,exe]};assert all(binaries[x]==v for x,v in before.items()) and all(sha(REPO/x)==v for x,v in sources.items());arm=ROOT/'reports/character-design-services-arm64-differential.json';reference=json.loads(arm.read_text());assert reference['validation']=='PASS' and reference['gold_sha256']==sha(gold);assert all(sha(REPO/x)==v for x,v in reference['source_sha256'].items())
 report=dict(validation='PASS',scope=__doc__,host_audit=audit,source_sha256=sources,binary_sha256=binaries,original_sha256=reference['original_sha256'],original_gold_sha256=sha(gold),arm64_report_sha256=sha(arm),cache_inputs_sha256=sha(inputs),scripts_sha256={str(x.relative_to(REPO)):sha(x) for x in [common,monster]},sanitizers=['AddressSanitizer','UndefinedBehaviorSanitizer'],sanitizer_findings=0,main_world_library_executed=True,module_in_main_world=a.main_linked,source_file_parser_supported=False,source_Application_and_world_ownership_bound=False,packaged_APK=False,commands=commands,linked_dependencies=dependencies);out=a.output or ROOT/('reports/character-design-services-main-linked-host-audit.json' if a.main_linked else 'reports/character-design-services-host-audit.json');out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(dict(validation='PASS',host=audit)))
if __name__=='__main__':main()
