#define main historical_session_audit_main
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wreturn-type"
#include "character_script_session.cpp"
#pragma GCC diagnostic pop
#undef main
#include "../character_skills_session.hpp"
namespace sk=dh2::character::skills;
namespace {
struct Unit {
 std::unique_ptr<CharacterScriptSession> session;
 State state{};NativeFsm24 fsm{};
 std::unique_ptr<sk::CharacterSkillSessionServices> services;
 std::unique_ptr<sk::CharacterSkillOwner> skills;
};
struct Busy {sk::CharacterSkillOwner* owner;unsigned calls=0;static int call(void* p,const dh2_script_value*,unsigned,dh2_script_value*,unsigned,unsigned* count,char*,std::size_t){auto& t=*static_cast<Busy*>(p);check(t.owner->update()==-2);++t.calls;*count=0;return 0;}};
}
int main(int argc,char** argv){try{check(argc==12);Inputs raw(argv[1]);auto common=file(argv[2]),monster=file(argv[3]);auto actors=placements(file(argv[4]));CharacterGameDesign design;std::string error;check(design.initialize(raw.input,error));auto d=design.borrow();Host h;h.rows.resize(d.levels()->levels.size());for(unsigned i=0;i<h.rows.size();++i)std::memcpy(&h.rows[i],d.levels()->levels[i].scalar.words+12,24);auto at=std::find(d.levels()->level_names.begin(),d.levels()->level_names.end(),"GOTHICUS_CRYPT_01");check(at!=d.levels()->level_names.end());h.level={int(at-d.levels()->level_names.begin()),0};auto player=std::make_shared<dh2::data::PropertyState>();dh2::data::reset_properties(*d.rules(),*player,&d.characters()->rows[263]);check(dh2::data::recalc_properties_with_class(*d.classes(),*d.rules(),*player,error));auto pv=dh2::data::property_view(*d.rules(),*player);check(!dh2_character_host_context_sync_level(&h.player,&pv));HostContextBindings16 host{{&h,Host::invoke}};MissingSave missing;DebugFileServices24 files{&missing,MissingSave::open,MissingSave::close};auto* debug=dh2_character_debug_create();check(debug);std::unique_ptr<DebugSwitches,decltype(&dh2_character_debug_destroy)> debug_owner(debug,dh2_character_debug_destroy);DebugLevelBinding16 level_binding{debug,&files};LevelServices16 level{&level_binding,dh2_character_debug_level_service};auto* modules=dh2_fx_debug_modules_create(debug,&files);check(modules);std::unique_ptr<dh2::fx::DebugModules,decltype(&dh2_fx_debug_modules_destroy)> module_owner(modules,dh2_fx_debug_modules_destroy);dh2::fx::PreloadServices16 debug_services{modules,dh2_fx_debug_preload_service};
 dh2::data::SkillTables tables;dh2::data::FaeryTables faeries;auto s0=file(argv[5]),s1=file(argv[6]),s2=file(argv[7]),f0=file(argv[8]),f1=file(argv[9]),f2=file(argv[10]),skill_common=file(argv[11]);check(tables.load({s0.data(),s0.size()},{s1.data(),s1.size()},{s2.data(),s2.size()},error));check(faeries.load({f0.data(),f0.size()},{f1.data(),f1.size()},{f2.data(),f2.size()},error));auto sb=tables.borrow();auto fb=faeries.borrow();
 const std::string fixture="RegisterSkillEx({check=function()return false,false end,pre=function()return false end,skill=function()return false end,update=function() skill_updates=(skill_updates or 0)+1; return setmetatable({}, {__index=function(_,k) if k=='_this' then skill_projection=(skill_projection or 0)+1 end end}) end,cleanup=function() skill_cleanup=(skill_cleanup or 0)+1 end})";
 unsigned list=0;for(;list<sb.lists().size();++list){bool present=false;for(auto id:sb.lists()[list])if(id>=0&&std::size_t(id)<sb.skills().size())present|=!sb.skills()[id].script.empty();if(present)break;}check(list<sb.lists().size());
 std::vector<std::unique_ptr<Unit>> units;unsigned null_slots=0,post_init_verified=0;for(unsigned i=0;i<actors.size();++i){auto unit=std::make_unique<Unit>();const auto& actor=actors[i];auto row=std::find(d.characters()->names.begin(),d.characters()->names.end(),actor.row);check(row!=d.characters()->names.end());CharacterScriptSessionInput in;in.identity=0xabcdef0123000000ull+i+1;in.name=actor.name;in.properties=std::make_shared<dh2::data::PropertyState>();in.combat=std::make_shared<dh2::data::CombatActorState>();in.position=actor.position;in.source_is_character=1;in.common={common.data(),common.size()};in.external={monster.data(),monster.size()};in.host=&host;in.level=&level;in.include_files.push_back({"data/scripts/skills/_commons.luac",skill_common});
  std::vector<std::string> added;auto add=[&](const std::string& name){if(name.empty()||std::find(added.begin(),added.end(),name)!=added.end())return;added.push_back(name);in.include_files.push_back({"data/scripts/skills/"+name+".luac",{fixture.begin(),fixture.end()}});};for(auto id:sb.lists()[list])add(sb.skills().at(id).script);for(auto id:fb.lists()[1])add(fb.faeries().at(id).script);
  dh2::data::reset_properties(*d.rules(),*in.properties,&d.characters()->rows[row-d.characters()->names.begin()]);check(dh2::data::recalc_properties_with_class(*d.classes(),*d.rules(),*in.properties,error));unit->session=CharacterScriptSession::create(design.borrow(),in,error);check(bool(unit->session));check(unit->session->start()==0&&unit->session->error().empty());for(unsigned j=0;j<2;++j){std::int32_t value;check(!dh2_property_resolve(&unit->session->property_view(),28+j,&value)&&value==-1);}++post_init_verified;
  unit->state.current=3;unit->fsm={&unit->state,in.identity,1,0};unit->services=std::make_unique<sk::CharacterSkillSessionServices>(*unit->session,debug_services,unit->fsm);unit->skills=std::make_unique<sk::CharacterSkillOwner>(in.identity,&unit->session->property_view(),tables.borrow(),faeries.borrow(),unit->services->services());auto view=active(*unit->session);std::string before;check(!unit->session->owner().copy_path(view.identity,before));auto flags=view.callback_flags;check(unit->skills->configure()==1&&unit->skills->error().empty());std::string after;check(!unit->session->owner().copy_path(view.identity,after)&&before==after);check(unit->skills->state().skills.count==0&&unit->skills->state().spells.count==5);for(unsigned j=0;j<5;++j){check(!unit->skills->state().spells.items[j]);++null_slots;}check(active(*unit->session).callback_flags==flags);check(unit->skills->configure()==1&&unit->skills->state().spells.count==5);check(unit->skills->update()==1&&unit->skills->cleanup_spells()==1);units.push_back(std::move(unit));
 }
 // Real owner path/cache/alias/call/VCB with genuine skills commons; scripts
 // below are explicitly controlled callback fixtures using actual table names.
 auto& first=*units[0];auto view=active(*first.session);// Controlled authored base-sheet inputs: these OIDs are not runtime-writable properties.
 first.session->properties()->base[28]=list;first.session->properties()->base[29]=1;std::int32_t selected_skill,selected_faery;check(!dh2_property_resolve(&first.session->property_view(),28,&selected_skill)&&selected_skill==int(list));check(!dh2_property_resolve(&first.session->property_view(),29,&selected_faery)&&selected_faery==1);first.skills=std::make_unique<sk::CharacterSkillOwner>(first.session->timers().owner,&first.session->property_view(),tables.borrow(),faeries.borrow(),first.services->services());{auto code=first.skills->configure();if(code!=1||first.session->owner().last_source_load_status()!=0)throw std::runtime_error("configure="+std::to_string(code)+"; owner="+first.session->owner().error()+"; skills="+first.skills->error()+"; services="+first.services->error());}unsigned nonnull=0;for(auto* slots:{&first.skills->state().skills,&first.skills->state().spells})for(unsigned i=0;i<slots->count;++i)nonnull+=slots->items[i]!=nullptr;if(nonnull<5){std::int32_t a,b;dh2_property_resolve(&first.session->property_view(),28,&a);dh2_property_resolve(&first.session->property_view(),29,&b);throw std::runtime_error("nonnull="+std::to_string(nonnull)+" props="+std::to_string(a)+","+std::to_string(b)+" counts="+std::to_string(first.skills->state().skills.count)+","+std::to_string(first.skills->state().spells.count)+";owner="+first.session->owner().error());}
 load(view.vm,"base_set_skill=SetSkill; function RedirectSetSkill(n,i) base_set_skill(n,i); return setmetatable({}, {__index=function(_,k) if k=='_this' then set_skill_projection=(set_skill_projection or 0)+1 end end}),nil,9 end; AddToVFTable('SetSkill','RedirectSetSkill')");check(first.skills->update()==1);{auto u=get(view.vm,"skill_updates"),s=get(view.vm,"set_skill_projection"),p=get(view.vm,"skill_projection");if(u.number!=float(nonnull)||s.number!=float(nonnull)||p.number!=float(nonnull))throw std::runtime_error("counters="+std::to_string(u.number)+","+std::to_string(s.number)+","+std::to_string(p.number)+" expected="+std::to_string(nonnull)+";owner="+first.session->owner().error());}check(first.skills->cleanup_skills()==1&&first.skills->cleanup_spells()==1&&get(view.vm,"skill_cleanup").number==float(nonnull));
 auto count=first.skills->state().spells.count;load(view.vm,"function RedirectSetSkill() error('authored SetSkill diagnostic') end");check(first.skills->update()==1&&first.skills->state().spells.count==count&&get(view.vm,"skill_updates").number==float(nonnull));load(view.vm,"function RedirectSetSkill() Attack() end");check(first.skills->update()==-2);load(view.vm,"function RedirectSetSkill() local ok=pcall(Attack);assert(not ok) end");check(first.skills->update()==-2);load(view.vm,"function RedirectSetSkill(n,i)base_set_skill(n,i)end");
 Busy busy{first.skills.get()};check(!dh2_script_vm_bind_source_values(view.vm,"AttemptSkills",Busy::call,&busy));std::uint32_t source_error=0;check(!first.session->owner().call_discard(view.identity,"AttemptSkills",nullptr,0,source_error)&&source_error==0&&busy.calls==1);
 // Borrowed inputs and table facades may die; owners retain immutable backing.
 sb={};fb={};tables=dh2::data::SkillTables{};faeries=dh2::data::FaeryTables{};s0.clear();s1.clear();s2.clear();f0.clear();f1.clear();f2.clear();check(first.skills->update()==1);unsigned shutdowns=units.size();units.clear();module_owner.reset();debug_owner.reset();
 std::cout<<"{\"validation\":\"PASS\",\"actual_Crypt_OnInit_property_inventories\":"<<post_init_verified<<",\"real_ScriptOwner_setup_compositions\":11,\"retained_null_spell_slots\":"<<null_slots<<",\"nonempty_controlled_skill_instances\":"<<nonnull<<",\"actual_skills_common_VM\":true,\"alias_return_projection_checks\":"<<nonnull*3<<",\"authored_error_skips_updates\":true,\"caught_and_uncaught_required_failures_rejected\":true,\"busy_scope_rejections\":"<<busy.calls<<",\"independent_owner_shutdowns\":"<<shutdowns<<",\"table_inputs_destroyed_while_pinned\":true,\"DebugSwitches_missing_file_fixture_deliveries\":"<<missing.opened<<",\"Host_fixture_projection_reads\":"<<h.reads<<",\"checks\":"<<checks<<",\"whole_authored_skill_scripts\":false,\"full_AI\":false}\n";
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
