#include "../character_player_skills_v3.hpp"
#include "../character_script_player_vcb_v2.hpp"
#include "../character_script_init_vitals.hpp"
#include "../character_design_services.hpp"
#include "../../engine-ui/hud_text_v1.hpp"
#include "../character_hud_skill_text_v1.hpp"
#include "../../script-runtime/script_return_observer_v1.h"
#include "../character_script_assets_v1.hpp"
#include "../../asset-payloads/zip_asset_pack_v1.hpp"
#include <fcntl.h>
#include <unistd.h>
#include <sys/stat.h>
#include <cerrno>
#include <algorithm>
#include <cstring>
#include <fstream>
#include <iostream>
#include <iterator>
using namespace dh2;using namespace dh2::character;namespace sk=dh2::character::skills;
namespace {
using Raw=std::vector<std::uint8_t>;unsigned checks=0;
void check(bool value,const std::string& e="Check failed",int line=__builtin_LINE()){++checks;if(!value)throw std::runtime_error(e+" at line "+std::to_string(line)+" check "+std::to_string(checks));}
Raw file(const std::string& p){std::ifstream f(p,std::ios::binary);check(bool(f),p);return {std::istreambuf_iterator<char>(f),{}};}
data::Bytes bytes(const Raw& b){return {b.data(),b.size()};}
std::uint32_t word(std::istream& f){std::uint32_t v{};check(bool(f.read(reinterpret_cast<char*>(&v),4)),"Truncated word");return v;}
std::string text(std::istream& f){std::string s(word(f),0);check(bool(f.read(s.data(),s.size())),"Truncated text");return s;}
Raw blob(std::istream& f){Raw b(word(f));check(bool(f.read(reinterpret_cast<char*>(b.data()),b.size())),"Truncated blob");return b;}
struct Inputs {std::array<std::array<Raw,3>,5> tables;std::vector<Raw> constants;std::vector<data::Bytes> views;GameDesignInputs256 input{};
 explicit Inputs(const char* p){std::ifstream f(p,std::ios::binary);check(word(f)==0x314f4447);for(auto& t:tables)for(auto& v:t)v=blob(f);auto n=word(f);while(n--){text(f);constants.push_back(blob(f));}n=word(f);while(n--)text(f);check(f.peek()==EOF);GameDesignTableInput48* out[]{&input.characters,&input.classes,&input.ai,&input.factions,&input.levels};for(unsigned i=0;i<5;++i)*out[i]={bytes(tables[i][0]),bytes(tables[i][1]),bytes(tables[i][2])};for(auto& b:constants)views.push_back(bytes(b));input.constants=views.data();input.constant_count=views.size();}
};
struct Debug {unsigned opens=0;static int open(void* p,const char* name,std::uintptr_t* out){check(!std::strcmp(name,"DebugSwitches.savegame"));++static_cast<Debug*>(p)->opens;*out=0;return 0;}static int close(void*,std::uintptr_t){return -1;}};
struct Vitals {const fx::PreloadServices16* debug;unsigned calls=0;static int invoke(void* p,CharacterScriptSessionV3& s,const ScriptLifecycleRequest32& q){auto& t=*static_cast<Vitals*>(p);check(q.service==script_refresh_vitals&&q.subject==s.timers().owner);ScriptInitVitals32 in{s.timers().owner,&s.property_view(),*t.debug};ScriptInitVitals24 out{};++t.calls;return dh2_character_script_init_vitals(&out,&in)==1?0:-1;}};
struct Unit {State fsm_state{};NativeFsm24 fsm{};std::array<std::uintptr_t,51> ai_keys{},ais_keys{};AIEventOwner48 event_owner{};AIEventState64 events{};sk::SkillAIOwnerV3 skill_owner{};std::shared_ptr<data::PlayerSavegameV1> saved;CharacterScriptAssetsV1::Borrow scripts;std::int32_t difficulty=0;unsigned difficulty_reads=0;std::unique_ptr<sk::CharacterPlayerSkillsV3> player;
 static int selected(void* p,std::int32_t* out){auto& t=*static_cast<Unit*>(p);++t.difficulty_reads;*out=t.difficulty;return 0;}
 static int cached(void* p,const char* path,data::Bytes* out,bool* found){auto& t=*static_cast<Unit*>(p);auto* bytes=t.scripts.find(path);*found=bytes!=nullptr;*out=bytes?data::Bytes{bytes->data(),bytes->size()}:data::Bytes{};return 0;}
};
struct Archive {int fd;std::uint64_t size;explicit Archive(const char* path):fd(open(path,O_RDONLY)),size(0){check(fd>=0,"Open original ZIP");struct stat s{};check(!fstat(fd,&s)&&s.st_size>0);size=s.st_size;}~Archive(){close(fd);}};
CharacterScriptAssetsV1 script_assets(const char* path,data::SkillTables::Borrow skills){auto source=std::make_shared<Archive>(path);assets::ZipBackingV1 backing{source,source->size,{}};
 backing.read=[source](std::uint64_t at,void* out,std::size_t n,std::string& error){std::size_t done=0;while(done<n){auto count=pread(source->fd,static_cast<unsigned char*>(out)+done,n-done,off_t(at+done));if(count<0&&errno==EINTR)continue;if(count<=0){error="Short original ZIP read";return false;}done+=count;}return true;};
 auto pack=std::make_shared<assets::ZipAssetPackV1>();std::string e;check(pack->mount(backing,"com.gameloft.android.GAND.GloftD2SS/files/",e),e);ScriptAssetServicesV1 provider;
 provider.directory=[pack](auto& out,auto&){for(auto& entry:pack->entries())out.push_back(entry.uri);return true;};provider.read=[pack](const auto& p,auto& found,auto& out,auto& error){return pack->read(p,found,out,error);};CharacterScriptAssetsV1 owner;check(owner.load(provider,std::move(skills),e),e);return owner;
}
struct Actor {sk::CharacterPlayerSkillsV3* player;sk::SkillInfoSessionsV3 info;sk::SkillInfoServicesV1 services;std::shared_ptr<data::PropertySheet> temp;
 Actor(sk::CharacterPlayerSkillsV3& p,std::shared_ptr<data::PropertySheet> t):player(&p),temp(std::move(t)){info.context=&p;info.resolve=[](void* c,std::uintptr_t id)->CharacterScriptSessionV3*{auto& p=*static_cast<sk::CharacterPlayerSkillsV3*>(c);return p.session().timers().owner==id?&p.session():nullptr;};services={&info,sk::skill_info_session_invoke_v3};}
 static bool resolve(void* c,std::uintptr_t id,sk::State40*& state,const sk::SkillInfoServicesV1*& services,PropertySheet16& sheet){auto& t=*static_cast<Actor*>(c);if(id!=t.player->session().timers().owner)return false;state=const_cast<sk::State40*>(&t.player->state());services=&t.services;sheet={t.temp->data(),224,0};return true;}
};
struct TextFiles {std::string assets;dh2_script_constants* constants=dh2_script_constants_create();unsigned opens=0,closes=0;~TextFiles(){dh2_script_constants_destroy(constants);}
 static bool constant(void* p,const char* g,const char* k,std::uint32_t& out,std::string&){std::int32_t v;if(dh2_script_constants_get(static_cast<TextFiles*>(p)->constants,g,k,&v))return false;std::memcpy(&out,&v,4);return true;}
 static bool open(void* p,const char* name,bool& found,Raw& out,std::uintptr_t& lease,std::string&){auto& t=*static_cast<TextFiles*>(p);std::ifstream f(t.assets+"/original-cache/data/"+name,std::ios::binary);found=bool(f);if(!found)return true;out={std::istreambuf_iterator<char>(f),{}};lease=++t.opens;return true;}
 static bool close(void* p,std::uintptr_t,std::string&){++static_cast<TextFiles*>(p)->closes;return true;}
 static bool debug(void*,const char*,std::string&){return true;} // Text-only Debug service fixture, not game switch values.
};
struct Busy {sk::CharacterPlayerSkillsV3* player;unsigned calls=0;static int call(void* p,const dh2_script_value*,unsigned,dh2_script_value*,unsigned,unsigned* n,char*,std::size_t){auto& t=*static_cast<Busy*>(p);float fraction=17;check(t.player->info(0,0,&fraction)==-2&&fraction==17,"Busy GetInfo rejected before observer");check(t.player->update()==-2,"Busy source update rejected");++t.calls;*n=0;return 0;}};
struct First {unsigned count=0,type=0;float value=0;static int observe(void* p,const dh2_script_first_return_v1* v,char*,std::size_t){auto& t=*static_cast<First*>(p);t={v->count,v->type,v->number};return 0;}};
struct Closing {unsigned calls=0;static int call(void* p,const dh2_script_value* a,unsigned n,dh2_script_value*,unsigned,unsigned* out,char*,std::size_t){check(n==1&&a[0].type==DH2_SCRIPT_NUMBER&&a[0].number==0,"Saved backing alive during original VM close");++static_cast<Closing*>(p)->calls;*out=0;return 0;}};
void load_vm(dh2_script_vm* vm,const char* text){check(!dh2_script_vm_load_source_file(vm,text,std::strlen(text)),dh2_script_vm_error(vm));}
}
int main(int argc,char** argv){try{
 check(argc==6,"Usage: player_skills game-design-inputs assets extracted-cache skill-class-gold original-cache.zip");Inputs raw(argv[1]);const std::string assets=argv[2],cache=argv[3];auto design=std::make_unique<CharacterGameDesign>();std::string error;check(design->initialize(raw.input,error),error);auto d=design->borrow();
 data::SkillTables skills;data::FaeryTables faeries;auto load=[&](auto& owner,const std::string& base){auto a=file(base+"_pyarray.bin"),b=file(base+"_pyarraynames.bin"),c=file(base+"_pystructnames.bin");check(owner.load(bytes(a),bytes(b),bytes(c),error),error);};load(skills,assets+"/data/skills");load(faeries,cache+"/data/pydata/faeries");auto sb=skills.borrow();auto cache_owner=script_assets(argv[5],skills.borrow());auto full_cache=cache_owner.borrow();check(full_cache.files().size()==219,"Complete original script cache");
 Debug debug_files;DebugFileServices24 files{&debug_files,Debug::open,Debug::close};auto* debug=dh2_character_debug_create();check(debug);std::unique_ptr<DebugSwitches,decltype(&dh2_character_debug_destroy)> debug_owner(debug,dh2_character_debug_destroy);auto* modules=dh2_fx_debug_modules_create(debug,&files);check(modules);std::unique_ptr<fx::DebugModules,decltype(&dh2_fx_debug_modules_destroy)> module_owner(modules,dh2_fx_debug_modules_destroy);fx::PreloadServices16 debug_services{modules,dh2_fx_debug_preload_service};Vitals vitals{&debug_services};sk::PlayerSkillInitServicesV3 init{&vitals,Vitals::invoke};
 auto temp=std::make_shared<data::PropertySheet>();std::vector<std::unique_ptr<Unit>> units;unsigned loaded_instances=0,registered_writers=0,vcb_checks=0;
 for(const auto& name:{std::string("KnightPlayerBase"),std::string("MagePlayerBase"),std::string("RoguePlayerBase")}){
  auto at=std::find(d.characters()->names.begin(),d.characters()->names.end(),name);check(at!=d.characters()->names.end());auto unit=std::make_unique<Unit>();const auto id=std::uintptr_t(0xabcdef0200000000ull+units.size()+1);unit->fsm_state.current=3;unit->fsm={&unit->fsm_state,id,1,0};unit->event_owner={id,id+1,reinterpret_cast<std::uintptr_t>(&unit->fsm_state),id+2,0,0,0,0};unit->ai_keys[0x90/4]=0x3d0ca0;unit->ais_keys[0x90/4]=0x3dcc80;unit->events={id+3,&unit->event_owner,unit->ai_keys.data(),0,unit->ais_keys.data(),0,0,0,0,0,0};CharacterScriptSessionInputV3 in;in.identity=id;in.name="Player";in.source_is_character=1;in.properties=std::make_shared<data::PropertyState>();in.combat=std::make_shared<data::CombatActorState>();in.temporary=temp;data::reset_properties(*d.rules(),*in.properties,&d.characters()->rows[at-d.characters()->names.begin()]);check(data::recalc_properties_with_class(*d.classes(),*d.rules(),*in.properties,error),error);
  unit->saved=std::make_shared<data::PlayerSavegameV1>();unit->saved->set_character(id);const auto list=in.properties->resolved[28]>=0&&std::size_t(in.properties->resolved[28])<sb.lists().size()?std::size_t(in.properties->resolved[28]):3;check(unit->saved->initialize_skills(sb.lists()[list],error),error);unit->saved->initialize_faeries();in.savegame=unit->saved;unit->scripts=full_cache;
  in.common=full_cache.common();in.cached_file_context=unit.get();in.cached_file=Unit::cached;
  auto player_init=init;player_init.gameplay.ai=&unit->events;unit->skill_owner={id,0,0};player_init.gameplay.skill_owner=&unit->skill_owner;player_init.gameplay.difficulty_context=unit.get();player_init.gameplay.difficulty=Unit::selected;unit->player=sk::CharacterPlayerSkillsV3::create(design->borrow(),in,skills.borrow(),faeries.borrow(),debug_services,unit->fsm,player_init,error);check(bool(unit->player),error);check(!unit->player->session().owner().lifecycle().active,"No premature active publication");const auto code=unit->player->initialize(1);check(code==1,"Initialize="+std::to_string(code)+" "+unit->player->error()+" / "+unit->player->session().error());check(unit->player->ready()&&unit->player->initialize(1)==0,"Actual active guard");check(unit->player->skill_ai().current==-1&&!unit->player->skill_ai().continued&&!unit->player->skill_ai().last,"Source AI constructor fields");
  ScriptSessionView view{};check(unit->player->session().owner().active(view)&&view.kind==script_player_iphone&&view.identity==unit->player->session().owner().lifecycle().pending,"Same original pending/active owner");std::uint32_t flags=123;check(!dh2_character_script_player_vcb_v2(&flags,view.aliases)&&flags==view.callback_flags,"Authoritative player flags");++vcb_checks;check(view.loaded_files>0&&unit->player->state().skills.count==sb.lists()[list].size(),"Actual ordered source instances");for(auto* p:unit->player->state().skills.items?std::vector<const sk::Instance32*>(unit->player->state().skills.items,unit->player->state().skills.items+unit->player->state().skills.count):std::vector<const sk::Instance32*>())loaded_instances+=p!=nullptr;
  for(auto& registration:unit->player->session().registrations())if(registration.original_callback==0x3b7eac||registration.original_callback==0x3b82e4||registration.original_callback==0x3babdc||registration.original_callback==0x3b8f9c){check(registration.supported,"Source writer registration missing");++registered_writers;}
  units.push_back(std::move(unit));
 }
 TextFiles text_files;text_files.assets=assets;for(const auto& n:{assets+"/original-cache/data/pydata/common_text_pycst.bin",assets+"/data/fonts_pycst.bin"}){auto b=file(n);dh2_script_constants_reload r{};check(!dh2_script_constants_load(text_files.constants,b.data(),b.size(),&r)&&r.consumed==b.size());}ui::HudTextV1 text_owner;auto a=file(assets+"/original-cache/data/pydata/common_text_pyarray.bin"),b=file(assets+"/original-cache/data/pydata/common_text_pyarraynames.bin"),c=file(assets+"/original-cache/data/pydata/common_text_pystructnames.bin");check(text_owner.load({a.data(),a.size()},{b.data(),b.size()},{c.data(),c.size()},error)&&text_owner.switch_pack(0,false,error),error);ui::HudTextEnvironmentV1 env{{&text_files,TextFiles::open,TextFiles::close,TextFiles::debug,TextFiles::constant,nullptr,nullptr}};
 std::ifstream gold(argv[4],std::ios::binary);check(word(gold)==0x31435348);const auto cases=word(gold);unsigned sheet_words=0,strings=0,queries=0;for(unsigned i=0;i<cases;++i){auto size=word(gold);auto start=gold.tellg();auto script=text(gold),actor=text(gold),class_name=text(gold);auto actor_id=word(gold),class_id=word(gold),level=word(gold);(void)class_name;(void)class_id;check(d.characters()->names[actor_id]==actor);data::PropertySheet expected;check(bool(gold.read(reinterpret_cast<char*>(expected.data()),896)));auto current=text(gold),next=text(gold);check(gold.tellg()-start==std::streamoff(size));auto& player=*units[actor=="MagePlayerBase"?1:0]->player;const auto& state=player.state();auto pos=std::find_if(state.skills.items,state.skills.items+state.skills.count,[&](auto* p){return p&&p->script==script;});check(pos!=state.skills.items+state.skills.count,"Real registered skill script missing");unsigned index=pos-state.skills.items;Actor live(player,temp);character::CharacterHudSkillTextV1 frame(text_owner,env,&live,Actor::resolve);ui::HudInitRequest64 q{};ui::HudInitResponse32 r{};q.operation=ui::HudInitOperation::skill_info;q.subject=player.session().timers().owner;q.index=index;q.value=level;check(frame.query(q,r,error)==1,error);check(*temp==expected&&r.fraction==0,"Original full skill sheet/fraction");sheet_words+=224;++queries;
  const auto skill=std::find_if(sb.skills().begin(),sb.skills().end(),[&](auto& s){return s.script==script;});check(skill!=sb.skills().end());for(unsigned p=0;p<2;++p){q={};q.operation=ui::HudInitOperation::arguments_create;check(frame.query(q,r,error)==1,error);auto arguments=r.identity;for(auto id:skill->display_props){q={};q.operation=ui::HudInitOperation::property;q.subject=player.session().timers().owner;q.index=id;check(frame.query(q,r,error)==1,error);auto v=r.value;q={};q.operation=ui::HudInitOperation::arguments_append;q.subject=arguments;q.value=v>>8;q.number=float(v)*(1.f/256.f);check(frame.query(q,r,error)==1,error);}q={};q.operation=ui::HudInitOperation::string_symbol;auto w=skill->scalar.words[p?17:12];std::memcpy(&q.value,&w,4);check(frame.query(q,r,error)==1,error);auto* raw_text=r.text;q={};q.operation=ui::HudInitOperation::parse_text;q.subject=arguments;q.text=raw_text;check(frame.query(q,r,error)==1,error);check(r.text&&std::string(r.text)==(p?next:current),"Original localized detail");++strings;}
 }
 check(gold.peek()==EOF&&text_files.opens==text_files.closes);
 auto& first=*units[0]->player;ScriptSessionView view{};check(first.session().owner().active(view));auto original_flags=view.callback_flags;check(!dh2_script_alias_push(view.aliases)&&!dh2_script_alias_add(view.aliases,"OnKill","AbsentKillGlobal"));check(!first.session().init_vcb(view.identity));check(first.session().owner().active(view)&&view.callback_flags==(original_flags|0x400),"Actual owned VCB flag write");check(!dh2_script_alias_pop(view.aliases)&&!first.session().init_vcb(view.identity));check(first.session().owner().active(view)&&view.callback_flags==original_flags);
 First result;for(auto& u:units){ScriptSessionView selected{};check(u->player->session().owner().active(selected));for(unsigned tier=0;tier<3;++tier){u->difficulty=tier;check(u->saved->set_faery_level(0,17+tier,tier,error),error);auto before=u->difficulty_reads;check(!dh2_script_vm_call_first_source_v1(selected.vm,"GetCurrentSpellInfo",nullptr,0,First::observe,&result)&&result.count==1&&result.value==float(17+tier),"Same-owner original spell query");check(u->difficulty_reads==before+3,"Three fresh source difficulty reads");check(u->saved->set_faery_level(0,0,tier,error),error);}u->difficulty=0;}
 dh2_script_value argument{};argument.type=DH2_SCRIPT_NUMBER;argument.number=0;check(units[0]->saved->set_skill_level(0,19,error),error);check(!dh2_script_vm_call_first_source_v1(view.vm,"GetCurrentSkillInfo__",&argument,1,First::observe,&result)&&result.count==1&&result.type==3&&result.value==19,"Live saved-row level, not dictionary ID");check(units[0]->saved->set_skill_level(0,0,error),error);
 argument.number=-1;check(dh2_script_vm_call_first_source_v1(view.vm,"GetCurrentSkillInfo__",&argument,1,First::observe,&result)==DH2_SCRIPT_REQUIRED_FAILURE_STATUS,"Unsafe source assertion domain explicitly rejected");argument={};argument.type=DH2_SCRIPT_STRING;argument.text="0";argument.text_bytes=1;check(dh2_script_vm_call_first_source_v1(view.vm,"GetCurrentSkillInfo__",&argument,1,First::observe,&result)==DH2_SCRIPT_REQUIRED_FAILURE_STATUS,"Source string-number provider remains required");
 Busy busy{&first};check(!dh2_script_vm_bind_source_values(view.vm,"AttemptPlayerSkillReentry",Busy::call,&busy));unsigned source_error=0;check(!first.session().owner().call_discard(view.identity,"AttemptPlayerSkillReentry",nullptr,0,source_error)&&!source_error&&busy.calls==1);
 // Controlled GetInfo alias supplies only a returned timer ID. Timer ownership
 // and elapsed/duration lookup are the same real Session; no authored gameplay
 // cooldown creation/provider is claimed by this boundary check.
 TimerServices32 timer_services{};auto timer=dh2_character_timer_start(&first.session().timers(),200,-1,0x35,0,&timer_services);check(timer>=0,"Source timer start="+std::to_string(timer));auto& store=first.session().timers();store.slots[timer].elapsed_ms=50;load_vm(view.vm,("function AuditTimerInfo()return "+std::to_string(timer)+" end").c_str());check(!dh2_script_alias_push(view.aliases)&&!dh2_script_alias_add(view.aliases,"OnSkillInfo","AuditTimerInfo"),"Timer alias install");float fraction=17;check(!first.info(0,0,&fraction)&&fraction==.75f,"Same-session source timer fraction");check(!dh2_script_alias_pop(view.aliases),"Timer alias restore");check(dh2_character_timer_stop(&store,timer)==1,"Source timer stop");
 unsigned passive_callbacks=0,ai_calls=0;for(unsigned actor=0;actor<3;++actor){auto& u=*units[actor];auto& p=*u.player;const char* script=actor==2?"prince_rogue_acrobat":actor?"prince_mage_staffmaster":"prince_warrior_hardiness";const auto& state=p.state();auto it=std::find_if(state.skills.items,state.skills.items+state.skills.count,[&](auto* i){return i&&!std::strcmp(i->script,script);});check(it!=state.skills.items+state.skills.count,"Passive present");auto index=unsigned(it-state.skills.items);const auto baseline=p.buff_count();check(u.saved->set_skill_level(index,3,error),error);check(p.update()==1,p.error());check(p.buff_count()==baseline+1,"Actual nonzero passive Buff added above full-cache faery Buffs");BuffSnapshot48 buff{};bool found=false;for(unsigned bi=0;bi<p.buff_count();++bi){check(p.buff_snapshot(&buff,bi)==1);if(buff.strength==3&&buff.sheet&&buff.sheet[172]==3*256){found=true;break;}}check(found&&buff.strength==3&&buff.timer_id==-1&&buff.sheet&&buff.sheet[172]==3*256,"Authored permanent Buff strength/sheet");for(unsigned op=0;op<5;++op){unsigned answer=17;check(!p.callback(index,op,&answer),p.error());check(answer==(op==sk::skill_check_usable_v3?0u:op==sk::skill_post_v3?0u:1u),"Actual passive callback returns");++passive_callbacks;}unsigned answer=17;check(!p.skill_ai(sk::skill_ai_usable_v3,index,&answer)&&answer==0,"Genuine passive usable callback");++ai_calls;check(!p.skill_ai(sk::skill_ai_active_v3,index,&answer)&&answer==1,"Genuine passive second return");++ai_calls;auto record=std::find_if(sb.skills().begin(),sb.skills().end(),[&](auto& r){return r.script==script;});check(record!=sb.skills().end());check(!p.skill_ai(sk::skill_ai_begin_v3,index,&answer)&&answer==(record->scalar.words[18]==1?1u:0u),"Source Begin toggle/usable branch");++ai_calls;check(p.skill_ai().current==-1&&!p.skill_ai().continued&&!p.skill_ai().last,"Passive Begin leaves source AI fields untouched");p.skill_ai().current=int(index);for(unsigned phase:{sk::skill_ai_focus_v3,sk::skill_ai_event_v3,sk::skill_ai_blur_v3}){check(!p.skill_ai(phase,0,&answer),p.error());++ai_calls;}p.skill_ai().current=-1;check(p.update()==1&&p.buff_count()==baseline+1,"Passive replacement removes previous owned Buff");check(u.saved->set_skill_level(index,0,error),error);check(p.update()==1&&p.buff_count()==baseline,"Authored passive level0 removes only its Buff");}
 // Actual shared Lua cooldown producer: SetSkill selects the retained
 // instance, SetSkillCooldown creates Timer35 and writes that same instance.
 // Source AI/DoT tick bodies are outside this test, so explicitly stop those
 // independently produced timers before exercising the script-only clock.
 for(auto& timer:store.slots?std::vector<Timer32>(store.slots,store.slots+store.count):std::vector<Timer32>())if(timer.event==0x33||timer.event==0x34)check(first.session().stop_timer(timer.id)==1);
 const auto& source_slots=first.state().skills;const char* charge="prince_warrior_charge";auto charge_it=std::find_if(source_slots.items,source_slots.items+source_slots.count,[&](auto* i){return i&&!std::strcmp(i->script,charge);});check(charge_it!=source_slots.items+source_slots.count);auto charge_index=unsigned(charge_it-source_slots.items);dh2_script_value set_args[2]{};set_args[0].type=DH2_SCRIPT_STRING;set_args[0].text=charge;set_args[0].text_bytes=std::strlen(charge);set_args[1].type=DH2_SCRIPT_NUMBER;set_args[1].number=(*charge_it)->argument_index;check(!first.session().owner().call_discard(view.identity,"SetSkill",set_args,2,source_error)&&!source_error);dh2_script_value delay{};delay.type=DH2_SCRIPT_NUMBER;delay.number=25;check(!first.session().owner().call_discard(view.identity,"SetSkillCooldown",&delay,1,source_error)&&!source_error,"Actual authored cooldown producer");auto cooldown_timer=(*charge_it)->word18;check(cooldown_timer>=0&&store.slots[cooldown_timer].event==0x35&&store.slots[cooldown_timer].duration_ms==25&&store.slots[cooldown_timer].repeat==0,"One source store/owned instance cooldown ID");check(!first.session().owner().call_discard(view.identity,"HasSkillCooldown",nullptr,0,source_error)&&!source_error);float raw_cooldown=17; // OnSkillInfo returns authored local cooldown, not its timer ID in this skill.
 check(first.info(charge_index,1,&raw_cooldown)==-2&&raw_cooldown==17,"Charge Info requires genuine HasShield provider");check(first.update_timers(24,0)==1&&(*charge_it)->word18==cooldown_timer&&store.slots[cooldown_timer].active,"Before source cooldown boundary");check(first.update_timers(1,1)==1&&store.slots[cooldown_timer].elapsed_ms==24,"Blocked clock preserves cooldown");check(first.update_timers(1,0)==1&&(*charge_it)->word18==-1&&!store.slots[cooldown_timer].active,"Actual Timer35->CharAI->selected AIS->same VM expiry clears native field");
 // Native caller and Lua producer share lowest-free-ID allocation/growth.
 auto native_timer=first.session().start_timer(100,0,0x35);check(native_timer==cooldown_timer,"Typed native timer reuses same store ID");check(first.session().stop_timer(native_timer)==1);
 const auto startups=vitals.calls;Closing close;std::weak_ptr<data::PlayerSavegameV1> saved_lifetime=units[0]->saved;for(auto& u:units)u->saved.reset();check(!saved_lifetime.expired(),"Session pins saved backing");sb={};skills=data::SkillTables{};faeries=data::FaeryTables{};full_cache={};cache_owner=CharacterScriptAssetsV1{};d={};design.reset();raw.constants.clear();for(auto& table:raw.tables)for(auto& b:table)b.clear();check(first.update()==1,"Owners pin actual table/cache backing");check(!dh2_script_vm_bind_source_values(view.vm,"ObservePlayerSkillClose",Closing::call,&close));load_vm(view.vm,"local u=newproxy(true);getmetatable(u).__gc=function()ObservePlayerSkillClose(GetCurrentSkillInfo__(0))end; audit_close=u");units.clear();check(close.calls==1&&saved_lifetime.expired(),"Pinned callbacks survive close and release afterward");module_owner.reset();debug_owner.reset();std::cout<<"{\"validation\":\"PASS\",\"genuine_player_sessions\":3,\"complete_original_scripts\":219,\"same_owner_spell_queries\":9,\"source_init_vitals\":"<<startups<<",\"source_skill_instances\":"<<loaded_instances<<",\"ordered_writer_registrations\":"<<registered_writers<<",\"authoritative_player_vcb\":"<<vcb_checks<<",\"skill_queries\":"<<queries<<",\"original_sheet_words\":"<<sheet_words<<",\"original_formatted_strings\":"<<strings<<",\"busy_rejections\":2,\"required_number_and_index_failures\":2,\"same_owner_saved_mutation\":true,\"same_owner_timer_lookup_controlled_return_fixture\":true,\"borrowed_inputs_destroyed_while_pinned\":true,\"actual_vm_finalizer_checks\":"<<close.calls<<",\"authored_cooldown_creation_and_expiry\":true,\"source_skill_ai_calls\":"<<ai_calls<<",\"passive_callbacks\":"<<passive_callbacks<<",\"checks\":"<<checks<<",\"missing_debug_file_fixture\":true,\"source_idle_fsm_projection_fixture\":true,\"full_campaign_or_gameplay\":false}\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
