#include "character_target_providers.hpp"
#include <array>
#include <vector>
#include <fstream>
#include <iterator>
#include <cstring>
#include <cmath>
#include <cstdio>
#include <cstdlib>
using namespace dh2::target_providers;
using Words2=std::array<unsigned,2>;
static void need(bool b,const char*m){if(!b){std::fprintf(stderr,"%s\n",m);std::abort();}}
struct Reader{std::vector<unsigned char>d;size_t at=0;unsigned word(){need(at+4<=d.size(),"truncated corpus");unsigned v;std::memcpy(&v,d.data()+at,4);at+=4;return v;}template<size_t N>std::array<unsigned,N> array(){std::array<unsigned,N>a{};for(auto&x:a)x=word();return a;}std::vector<Words2> pairs(unsigned n){std::vector<Words2>a(n);for(auto&x:a)x=array<2>();return a;}};
static const char* names[]={"PlayerCharacter","Other","PlayerCharacterPrince","xPlayerCharacter","Player","","PlayerCharacte","playerCharacter"};
struct QueryFixture{
 std::array<unsigned,15> row;std::vector<std::int32_t> types;Types16 table{};dh2::character::CombatProperties896 props[2]{};Character32 chars[2]{};Services16 services{this,&invoke};std::vector<Words2>trace;bool triggered=false,mutated=false;int failure=0;
 QueryFixture(const std::vector<std::int32_t>&t,const std::array<unsigned,15>&r):row(r),types(t){auto aid=row[1];if(row[2]!=0xffffffff){types[0]=static_cast<int>(row[2]);aid=0;}unsigned other=aid!=1?1:2;types[other]=static_cast<int>(row[5]);table={types.data(),static_cast<unsigned>(types.size()),0};for(unsigned i=0;i<2;++i){props[i].words[1]=static_cast<int>(i?other:aid);chars[i]={i+1,&props[i],names[i?0:row[3]-1],i?0x2000:row[10],static_cast<unsigned char>(i?0:row[6]),static_cast<unsigned char>(i?0:row[7]),static_cast<unsigned char>(i?1:row[8]),static_cast<unsigned char>(i?1:row[9])};}}
 static int invoke(void*p,const Request24*q,std::uintptr_t*out){auto&f=*static_cast<QueryFixture*>(p);if(f.failure)return 1;f.trace.push_back({q->service,static_cast<unsigned>(q->subject)});auto&c=f.chars[q->subject-1];
  if(q->service==virtual_dead){*out=c.dead1449;if(q->subject==1&&f.row[14]&&!f.mutated){f.mutated=true;f.props[0].words[1]=44;f.chars[0].visible8a=0;f.chars[0].flags520=f.row[10]^0x2000;}if(f.row[13]&&!f.triggered){f.triggered=true;f.trace.push_back({7,1});int value=0;need(dh2_character_target_query(&value,is_zonable,&f.chars[0],f.row[4]?&f.chars[1]:nullptr,&f.table,&f.services)==0,"nested predicate failed");f.trace.push_back({8,1});}}
  else if(q->service==virtual_player){int v=0;need(dh2_character_target_query(&v,is_player,&c,nullptr,&f.table,&f.services)==0,"virtual player failed");*out=v;}
  else if(q->service==ai_friend||q->service==ai_enemy){need(q->subject==1&&q->other==2,"faction arguments");*out=f.row[q->service==ai_friend?11:12];}
  else need(false,"unknown query service");
  return 0;
 }
};
struct HandleFixture{
 std::array<Record16,16>records{};Registry24 registry{records.data(),4,16,0,0};Handle16 local{},shared{};Services16 services{this,&invoke};std::vector<Words2>trace;bool reentry=false,triggered=false;int failure=0;
 explicit HandleFixture(const std::array<unsigned,5>&r){records[0]={-9,0,1};records[1]={-1,0,2};records[2]={2,0,3};records[3]={0x7fffffff,0,4};shared={static_cast<int>(r[0]),r[2],r[1]};registry.frame=r[3];reentry=r[4];}
 static int invoke(void*p,const Request24*q,std::uintptr_t*out){auto&f=*static_cast<HandleFixture*>(p);if(f.failure)return 1;need(q->service==virtual_character&&q->other==0,"handle service arguments");f.trace.push_back({5,static_cast<unsigned>(q->subject)});if(f.reentry&&!f.triggered){f.triggered=true;f.trace.push_back({7,0});Handle16 local{},shared{-5,f.registry.frame,3};std::uintptr_t v;need(dh2_target_handle_character(&v,&local,&shared,&f.registry,&f.services)==0&&v==3,"nested handle failure");f.trace.push_back({8,0});}*out=q->subject%2;return 0;}
};
static unsigned bits(float f){unsigned x;std::memcpy(&x,&f,4);return x;}static float fl(unsigned x){float f;std::memcpy(&f,&x,4);return f;}static bool equal(unsigned a,unsigned b){return a==b||(std::isnan(fl(a))&&std::isnan(fl(b)));}
int main(int argc,char**argv){need(argc==2,"usage: providers_audit corpus");Reader r;std::ifstream file(argv[1],std::ios::binary);r.d={std::istreambuf_iterator<char>(file),std::istreambuf_iterator<char>()};need(r.word()==0x31445650,"bad corpus");auto nt=r.word(),nq=r.word(),nh=r.word(),nr=r.word(),nb=r.word();std::vector<std::int32_t>types(nt);for(auto&x:types)x=static_cast<int>(r.word());unsigned callbacks=0,guards=0,failures=0,sneak=0;
 for(unsigned i=0;i<nq;++i){auto row=r.array<15>();unsigned want=r.word(),name=r.word();auto after=r.array<3>();auto trace=r.pairs(r.word());QueryFixture f(types,row);int out=0;need(dh2_character_target_query(&out,row[0],&f.chars[0],row[4]?&f.chars[1]:nullptr,&f.table,&f.services)==0,"predicate rejected");if(static_cast<unsigned>(out)!=want||f.trace!=trace||f.chars[0].name!=names[name-1]){std::fprintf(stderr,"case %u op %u actual %u expected %u traces %zu/%zu\n",i,row[0],static_cast<unsigned>(out),want,f.trace.size(),trace.size());for(auto v:f.trace)std::fprintf(stderr,"actual %u %u\n",v[0],v[1]);for(auto v:trace)std::fprintf(stderr,"expected %u %u\n",v[0],v[1]);}need(static_cast<unsigned>(out)==want&&f.trace==trace&&f.chars[0].name==names[name-1],"predicate/ordered callback mismatch");need(static_cast<unsigned>(f.props[0].words[1])==after[0]&&f.chars[0].flags520==after[1]&&f.chars[0].visible8a==after[2],"live mutation mismatch");callbacks+=trace.size();
  auto bad=[&](int v){need(v==1&&out==0x12345678,"predicate atomic guard");++guards;};out=0x12345678;bad(dh2_character_target_query(&out,0,&f.chars[0],nullptr,&f.table,&f.services));bad(dh2_character_target_query(&out,row[0],reinterpret_cast<Character32*>(reinterpret_cast<std::uintptr_t>(&f.chars[0])+1),nullptr,&f.table,&f.services));bad(dh2_character_target_query(&out,row[0],&f.chars[0],nullptr,nullptr,&f.services));auto saved=f.table;f.table.count=8;bad(dh2_character_target_query(&out,row[0],&f.chars[0],nullptr,&f.table,&f.services));f.table=saved;
  need(dh2_character_target_query(reinterpret_cast<int*>(&f.props[0]),row[0],&f.chars[0],nullptr,&f.table,&f.services)==1,"property alias accepted");++guards;
  if(row[0]>=6&&row[0]<=8&&!trace.empty()){f.failure=1;need(dh2_character_target_query(&out,row[0],&f.chars[0],row[4]?&f.chars[1]:nullptr,&f.table,&f.services)==2&&out==0x12345678,"provider failure wrote output");++failures;}
  f.props[0].words[1]=0;f.types[0]=0;f.chars[0].name=nullptr;out=0x12345678;bad(dh2_character_target_query(&out,is_player,&f.chars[0],nullptr,&f.table,&f.services));
 }
 for(unsigned i=0;i<nh;++i){auto row=r.array<5>();unsigned result=r.word();auto local=r.array<3>(),shared=r.array<3>();unsigned ne=r.word(),nc=r.word();auto entries=r.pairs(ne),trace=r.pairs(nc);HandleFixture f(row);std::uintptr_t out=0;need(dh2_target_handle_character(&out,&f.local,&f.shared,&f.registry,&f.services)==0,"handle rejected");need(out==result&&f.local.key==static_cast<int>(local[0])&&f.local.frame==local[1]&&f.local.cached==local[2]&&f.shared.key==static_cast<int>(shared[0])&&f.shared.frame==shared[1]&&f.shared.cached==shared[2]&&f.registry.count==ne&&f.trace==trace,"handle state/order mismatch");for(unsigned j=0;j<ne;++j)need(f.records[j].key==static_cast<int>(entries[j][0])&&f.records[j].object==entries[j][1],"map effects mismatch");callbacks+=trace.size();
  auto before=f.shared;need(dh2_target_handle_character(&out,&f.shared,&f.shared,&f.registry,&f.services)==1&&std::memcmp(&before,&f.shared,sizeof(before))==0,"shared/local alias accepted");++guards;need(dh2_target_handle_character(reinterpret_cast<std::uintptr_t*>(f.records.data()),&f.local,&f.shared,&f.registry,&f.services)==1,"output/map alias accepted");++guards;
  auto rr=f.registry;f.registry.records=reinterpret_cast<Record16*>(reinterpret_cast<std::uintptr_t>(f.records.data())+1);need(dh2_target_handle_character(&out,&f.local,&f.shared,&f.registry,&f.services)==1,"unaligned records accepted");++guards;f.registry=rr;
  f.failure=1;f.shared.key=2;f.shared.cached=3;out=0x1234;need(dh2_target_handle_character(&out,&f.local,&f.shared,&f.registry,&f.services)==2&&out==0x1234&&f.shared.frame==f.registry.frame,"classification failure ordering");++failures;
  f.failure=0;f.registry.capacity=f.registry.count;f.shared={123,f.registry.frame^1,0};out=0x1234;need(dh2_target_handle_character(&out,&f.local,&f.shared,&f.registry,&f.services)==2&&out==0x1234&&f.shared.frame==f.registry.frame&&f.local.key==123&&f.local.frame==f.registry.frame&&f.local.cached==0,"capacity failure ordering");++failures;
 }
 for(unsigned i=0;i<nr;++i){auto w=r.array<7>();float aabb[6];for(unsigned j=0;j<6;++j)aabb[j]=fl(w[j]);float out;need(dh2_gameobject_interaction_radius(&out,aabb)==0&&equal(bits(out),w[6]),"IEEE radius mismatch");auto saved=bits(aabb[0]);need(dh2_gameobject_interaction_radius(aabb,aabb)==1&&bits(aabb[0])==saved,"radius alias accepted");++guards;}
 for(unsigned i=0;i<nb;++i){auto w=r.array<3>();int out;need(dh2_gameobject_target_query(&out,w[0],static_cast<unsigned char>(w[1]))==0&&static_cast<unsigned>(out)==w[2],"base policy mismatch");}
 need(r.at==r.d.size(),"trailing corpus");for(unsigned a:{0u,0x80000000u,0x7fffffffu,0xffffffffu,0x12345678u})for(unsigned b:{0u,0x80000000u,0x7fffffffu,0xffffffffu,0x87654321u}){dh2::character::CombatProperties896 p{};p.words[198]=static_cast<int>(a);p.words[199]=static_cast<int>(b);int out[2]{};need(dh2_character_sneak_fields(out,&p)==0&&static_cast<unsigned>(out[0])==a&&static_cast<unsigned>(out[1])==b,"resolved sneak projection");need(dh2_character_sneak_fields(p.words+198,&p)==1,"sneak overlap");++sneak;++guards;}
 std::printf("{\"validation\":\"PASS\",\"comparisons\":%u,\"predicate_cases\":%u,\"handle_cases\":%u,\"radius_cases\":%u,\"base_cases\":%u,\"ordered_callbacks\":%u,\"atomic_rejection_checks\":%u,\"provider_failure_checks\":%u,\"resolved_sneak_projection_checks\":%u,\"mismatches\":0}\n",nq+nh+nr+nb,nq,nh,nr,nb,callbacks,guards,failures,sneak);
}
