"""Isolated new CancelSneaking coordinator/source gold/actual cache sanitizer replay."""
import hashlib,json,subprocess
from pathlib import Path
WORLD=Path(__file__).resolve().parents[1];ROOT=WORLD.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def linux(p):return '/mnt/'+p.drive[0].lower()+p.as_posix()[2:]
def main():
 scratch=ROOT/'.local-inputs/character-cancel-sneaking';sources=[WORLD/'character_cancel_sneaking.cpp',WORLD/'character_cancel_sneaking.hpp',WORLD/'tests/character_cancel_sneaking.cpp',Path(__file__),WORLD/'character_property_bindings.hpp'];inputs=[WORLD/'reference/character-cancel-sneaking/cancel-sneaking-fixtures.bin',scratch/'skills_pyarray.bin'];proof=WORLD/'reports/character-cancel-sneaking-arm64-differential.json';paths=sources+inputs+[proof,WORLD/'reference/character-cancel-sneaking/original-functions.json',WORLD/'reference/character-cancel-sneaking/reference/original-functions.asm',WORLD/'reference/character-cancel-sneaking/skill-layout/original-functions.json',WORLD/'reference/character-cancel-sneaking/skill-layout/reference/original-functions.asm'];before={p.relative_to(ROOT).as_posix():sha(p) for p in paths}
 executable=scratch/'character_cancel_sneaking_host';command=['wsl.exe','--','g++','-std=c++17','-O1','-g','-fsanitize=address,undefined','-fno-omit-frame-pointer','-fno-fast-math','-ffp-contract=off','-Wall','-Wextra','-Werror','-Wno-misleading-indentation',linux(sources[0]),linux(sources[2]),'-o',linux(executable)];r=subprocess.run(command,text=True,capture_output=True,timeout=60);assert not r.returncode,(r.stdout,r.stderr)
 run=['wsl.exe','--','env','ASAN_OPTIONS=detect_leaks=1:halt_on_error=1','UBSAN_OPTIONS=halt_on_error=1',linux(executable),*map(linux,inputs)];r=subprocess.run(run,text=True,capture_output=True,timeout=60);assert not r.returncode and not r.stderr,(r.stdout,r.stderr);audit=json.loads(r.stdout);assert audit['validation']=='PASS' and audit['cases']==976 and audit['actual_cache_cases']==152
 assert before=={p.relative_to(ROOT).as_posix():sha(p) for p in paths};report=dict(validation='PASS',host_audit=audit,source_and_input_sha256=before,executable_sha256=sha(executable),compiler_command=command,run_command=run,sanitizer_findings=0,sanitizers=['AddressSanitizer','UndefinedBehaviorSanitizer','LeakSanitizer'],scope=__doc__,central_DSO_rebuilt=False,full_DelBuff=False,full_skill_VM=False,cache_projection_only=True);(WORLD/'reports/character-cancel-sneaking-host-audit.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(audit))
if __name__=='__main__':main()
