"""Original source effect gold plus actual linked CharacterTimers and native Box2D pin prefix; no fabricated state8/9 acceptance."""
import argparse,hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def linux(p):return '/mnt/c/'+str(p.resolve()).replace('\\','/')[3:]
def main():
 p=argparse.ArgumentParser();p.add_argument('--main-linked',action='store_true');p.add_argument('--output',type=Path);a=p.parse_args();scratch=REPO/'.local-inputs/character-native-effects';scratch.mkdir(exist_ok=True);commands=[]
 def run(*args):
  r=subprocess.run(['wsl','--cd',linux(REPO),*args],capture_output=True,text=True,timeout=120);commands.append(dict(arguments=args,returncode=r.returncode,stdout=r.stdout,stderr=r.stderr));assert not r.returncode and not r.stderr.strip(),commands[-1];return r.stdout.strip()
 flags=['-std=c++17','-O1','-g','-fno-fast-math','-ffp-contract=off','-fsanitize=address,undefined','-fno-omit-frame-pointer','-Wall','-Wextra','-Werror'];world_dir='/home/adampalace/dh2-world-build';world=world_dir+'/libdh2_level_world.so';library=linux(scratch/'libcharacter_native_effects_audit.so');exe=linux(scratch/'host');gold=ROOT/'reference/character-native-effects/effect-fixtures.bin';runtime_dir=world_dir+'/script-runtime';links=['-L'+world_dir,'-ldh2_level_world','-Wl,-rpath,'+world_dir,'-Wl,-rpath,'+runtime_dir]
 sources={str((ROOT/name).relative_to(REPO)):sha(ROOT/name) for name in ['character_native_effects.hpp','character_native_effects.cpp','tests/character_native_effects.cpp','tests/character_native_effects_host.py','character_native_fsm.hpp','character_state.hpp','character_timers.hpp','character_timers.cpp','native_body.hpp','native_body.cpp']};before=run('sha256sum',world).split()[0]
 if a.main_linked:library=world;module_links=[]
 else:run('g++',*flags,'-shared','-fPIC',linux(ROOT/'character_native_effects.cpp'),*links,'-o',library);module_links=['-L'+linux(scratch),'-lcharacter_native_effects_audit']
 run('g++',*flags,linux(ROOT/'tests/character_native_effects.cpp'),'-I'+linux(ROOT),'-isystem',linux(REPO/'port/physics-backend/box2d-2.0.1/Include'),*module_links,*links,'-Wl,-rpath,'+linux(scratch),'-ldl','-o',exe)
 env=['env','LD_LIBRARY_PATH='+world_dir+':'+runtime_dir+':'+linux(scratch),'ASAN_OPTIONS=detect_leaks=1:abort_on_error=1','UBSAN_OPTIONS=halt_on_error=1'];audit=json.loads(run(*env,exe,linux(gold)));assert audit['validation']=='PASS' and audit['module_library']==library and audit['timer_library']==audit['body_library']==world
 dependencies=run(*env,'ldd',exe);assert world in dependencies and 'libasan.so' in dependencies and 'libubsan.so' in dependencies;binaries={path:run('sha256sum',path).split()[0] for path in [world,library,exe]};assert binaries[world]==before and all(sha(REPO/name)==digest for name,digest in sources.items());arm_path=ROOT/'reports/character-native-effects-arm64-differential.json';arm=json.loads(arm_path.read_text());assert arm['validation']=='PASS' and arm['gold_sha256']==sha(gold)
 report=dict(validation='PASS',scope=__doc__,host_audit=audit,source_sha256=sources,binary_sha256=binaries,original_sha256=arm['original_sha256'],original_gold_sha256=sha(gold),arm64_report_sha256=sha(arm_path),sanitizers=['AddressSanitizer','UndefinedBehaviorSanitizer'],sanitizer_findings=0,main_world_library_executed=True,module_in_main_world=a.main_linked,native_registered_state_owner=False,full_timer_expiry_transition=False,focus_random_heading_and_init_implemented=False,packaged_APK=False,commands=commands,linked_dependencies=dependencies);output=a.output or ROOT/('reports/character-native-effects-main-linked-host-audit.json' if a.main_linked else 'reports/character-native-effects-host-audit.json');output.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(dict(validation='PASS',host=audit)))
if __name__=='__main__':main()
