"""Original effect gold through sanitizer DSO; real TimerStore→RaiseAIEvent→effects/FSM/debug, explicit positive DoT failure."""
import argparse,hashlib,json,struct,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPO=ROOT.parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def linux(p):return '/mnt/c/'+str(p.resolve()).replace('\\','/')[3:]
def main():
 p=argparse.ArgumentParser();p.add_argument('--main-linked',action='store_true');p.add_argument('--output',type=Path);a=p.parse_args();scratch=REPO/'.local-inputs/character-timer-effects-discovery';scratch.mkdir(exist_ok=True);(scratch/'files').mkdir(exist_ok=True);ref=ROOT/'reference/character-timer-effects';assets=REPO/'port/android-native/app/src/main/assets/data/character_properties_pyarray.bin';raw=assets.read_bytes();gold=ref/'timer-effects-fixtures.bin';source=gold.read_bytes();assert source[:4]==b'TEF1';count=struct.unpack_from('<I',source,4)[0];pos=8;converted=bytearray(b'TEH1'+struct.pack('<I',count)+raw[4:1796])
 for i in range(count):
  event,n=struct.unpack_from('<II',source,pos);pos+=8;record=json.loads(source[pos:pos+n]);pos+=n;params=record['params'];states=params['states'];dead=params['dead'];converted+=struct.pack('<8I',event,params['inhibited'],params['aggro'],params['aggroed'],params.get('mutation',0),params.get('dot_mutation',0),len(states),len(dead))+struct.pack('<'+'i'*len(states),*states)+struct.pack('<'+'i'*len(dead),*dead);converted+=struct.pack('<I',len(record['trace']))
  for op,p,amount,element,name in record['trace']:name=name.encode();converted+=struct.pack('<IIiiI',op,p,amount,element,len(name))+name
  converted+=struct.pack('<I',len(record['adds']))
  for p,amount in record['adds']:converted+=struct.pack('<Ii',p,amount)
  converted+=struct.pack('<I',len(record['results']))+b''.join(bytes.fromhex(x) for x in record['results'])+source[pos:pos+7168];pos+=7168
 assert pos==len(source);hostgold=scratch/'host-fixtures.bin';hostgold.write_bytes(converted);commands=[]
 def run(*arguments):
  r=subprocess.run(['wsl','--cd',linux(REPO),*arguments],capture_output=True,text=True,timeout=120);commands.append(dict(arguments=arguments,returncode=r.returncode,stdout=r.stdout,stderr=r.stderr));assert not r.returncode and not r.stderr.strip(),dict(arguments=arguments,returncode=r.returncode,stdout=r.stdout[:1000],stderr=r.stderr[:4000]);return r.stdout.strip()
 flags=['-std=c++17','-O1','-g','-fno-fast-math','-ffp-contract=off','-fsanitize=address,undefined','-fno-omit-frame-pointer','-Wall','-Wextra','-Werror'];world_dir='/home/adampalace/dh2-world-build';runtime_dir=world_dir+'/script-runtime';data_dir=world_dir+'/game-data';world=world_dir+'/libdh2_level_world.so';runtime=runtime_dir+'/libdh2_script_runtime.so';data=data_dir+'/libdh2_game_data.so';library=linux(scratch/'libcharacter_timer_effects_audit.so');exe=linux(scratch/'host');files=[ROOT/x for x in ['character_timer_effects.hpp','character_timer_effects.cpp','tests/character_timer_effects.cpp','tests/character_timer_effects_host.py','character_design_services.hpp','character_design_services.cpp','character_native_fsm.hpp','character_native_fsm.cpp','character_ai_events.hpp','character_ai_events.cpp','character_timers.hpp','character_timers.cpp']];sources={str(x.relative_to(REPO)):sha(x) for x in files};before={x:run('sha256sum',x).split()[0] for x in [world,runtime,data]};links=['-L'+runtime_dir,'-ldh2_script_runtime','-L'+world_dir,'-ldh2_level_world','-L'+data_dir,'-ldh2_game_data','-Wl,-rpath,'+runtime_dir,'-Wl,-rpath,'+world_dir,'-Wl,-rpath,'+data_dir]
 if a.main_linked:library=world;module_links=[]
 else:run('g++',*flags,'-shared','-fPIC',linux(ROOT/'character_timer_effects.cpp'),*links,'-o',library);module_links=['-L'+linux(scratch),'-lcharacter_timer_effects_audit']
 run('g++',*flags,linux(ROOT/'tests/character_timer_effects.cpp'),'-I'+linux(ROOT),*module_links,*links,'-Wl,-rpath,'+linux(scratch),'-ldl','-o',exe);env=['env','LD_LIBRARY_PATH='+world_dir+':'+runtime_dir+':'+data_dir+':'+linux(scratch),'ASAN_OPTIONS=detect_leaks=1:abort_on_error=1','UBSAN_OPTIONS=halt_on_error=1'];audit=json.loads(run(*env,exe,linux(hostgold),linux(ref/'cached-reset-fixtures.bin'),linux(ref/'owner-query-fixtures.bin'),linux(assets),linux(scratch/'files')));assert audit['validation']=='PASS' and audit['module_library']==library and audit['world_library']==audit['debug_library']==world and audit['data_library']==data
 dependencies=run(*env,'ldd',exe);assert all(x in dependencies for x in [world,runtime,data,'libasan.so','libubsan.so']);binaries={x:run('sha256sum',x).split()[0] for x in [world,runtime,data,library,exe]};assert all(binaries[x]==v for x,v in before.items()) and all(sha(REPO/x)==v for x,v in sources.items());arm=ROOT/'reports/character-timer-effects-arm64-differential.json';reference=json.loads(arm.read_text());assert reference['validation']=='PASS' and reference['gold_sha256']==sha(gold);assert all(sha(REPO/x)==v for x,v in reference['source_sha256'].items())
 report=dict(validation='PASS',scope=__doc__,host_audit=audit,source_sha256=sources,binary_sha256=binaries,original_sha256=reference['original_sha256'],original_gold_sha256=sha(gold),derived_host_gold_sha256=sha(hostgold),arm64_report_sha256=sha(arm),property_assets_sha256=sha(assets),sanitizers=['AddressSanitizer','UndefinedBehaviorSanitizer'],sanitizer_findings=0,main_world_library_executed=True,module_in_main_world=a.main_linked,full_DoT_buff_registry_or_application=False,packaged_APK=False,commands=commands,linked_dependencies=dependencies);out=a.output or ROOT/('reports/character-timer-effects-main-linked-host-audit.json' if a.main_linked else 'reports/character-timer-effects-host-audit.json');out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(dict(validation='PASS',host=audit)))
if __name__=='__main__':main()
