#include "character_world_skill_execution_v6_fixture.inc"
#include "../character_world_skill_execution_v6.hpp"
#include "../character_world_aggro_event_v1.hpp"
namespace {
struct ExecutionActor {CombatActor* actor;character::CharacterConstructorCombatFieldsV1 fields{};std::uintptr_t controller{};const data::FreshInventoryOwnedV4* inventory{};bool controller_available=true;
 static int refresh(void*p,sk::WorldSkillExecutionActorV6*out){auto&x=*static_cast<ExecutionActor*>(p);auto&a=*x.actor;a.facts.state=a.machine.current;a.facts.combo_hits=x.fields.combo;
 *out={a.id,&a.view,&a.life,&a.facts,&a.machine,&x.fields,x.inventory,nullptr,nullptr,nullptr,x.controller_available?&x.controller:nullptr,&a.outgoing,&a.incoming};return 0;}
};
int debug_missing(void*,const char*,std::uintptr_t*out){*out=0;return 0;}int debug_close(void*,std::uintptr_t){return -1;}
struct ExecutionProviders {Providers base;
 static int hit(void*p,character::HitActor32*a,const character::HitRequest32*q,std::uintptr_t*out){if(q->service==sk::hit_local_player_v6){*out=1;return 0;}return Providers::hit(&static_cast<ExecutionProviders*>(p)->base,a,q,out);}
};
}
int main(int argc,char**argv){try{check(argc==2);const std::string root=argv[1];std::string error;Inputs raw((root+"/port/level-world/reference/character-game-design/real-cache-inputs.bin").c_str());CharacterGameDesign design;check(design.initialize(raw.input,error),error);auto d=design.borrow();CombatActor player,enemy;
auto selected=std::find(d.characters()->names.begin(),d.characters()->names.end(),"KnightPlayerBase");check(selected!=d.characters()->names.end());data::reset_properties(*d.rules(),player.properties,&d.characters()->rows[selected-d.characters()->names.begin()]);check(data::recalc_properties_with_class(*d.classes(),*d.rules(),player.properties,error),error);
bool found=false;for(const auto&r:d.characters()->rows){data::reset_properties(*d.rules(),enemy.properties,&r);if(!data::recalc_properties_with_class(*d.classes(),*d.rules(),enemy.properties,error))continue;auto ai=data::ai_props(*d.ai(),enemy.properties.resolved[1]);if(ai&&ai->type==4&&enemy.properties.resolved[36]>1024){found=true;break;}}check(found);player.initialize(0x100000001,*d.rules());enemy.initialize(0x200000002,*d.rules());
sk::CharacterWorldRuntimeV1 world(*d.ai());check(!world.add({player.id,1,&player,CombatActor::world,&player.machine,&player.shared,&player.current}));check(!world.add({enemy.id,2,&enemy,CombatActor::world,&enemy.machine,&enemy.shared,&enemy.current}));
data::LootTablesV2 loots;data::SkillTables skills;auto load=[&](auto&owner,const std::string&base){auto a=file(base+"_pyarray.bin"),b=file(base+"_pyarraynames.bin"),c=file(base+"_pystructnames.bin");check(owner.load(bytes(a),bytes(b),bytes(c),error),error);};load(loots,root+"/.local-inputs/skill-execution-assets-v6/loot_table");load(skills,root+"/port/android-native/app/src/main/assets/data/skills");
auto same_properties=std::shared_ptr<data::PropertyState>(&player.properties,[](auto*){});data::LootRandom8V2 loot_rng{1,0};data::FreshInventoryOwnedV4 gear(player.id,loots.borrow(),loot_rng,-1,same_properties);character::NativeFsm24 fsm{&player.machine,player.id,0,0};sk::SkillManaServicesV5 mana{};sk::CharacterSkillNativeReadOnlyBindingsV6 readonly(gear,fsm,mana,world.native_world(player.id,nullptr));
character::DebugFileServices24 files{nullptr,debug_missing,debug_close};auto*debug=dh2_character_debug_create();check(debug);auto a=file(root+"/.local-inputs/trophy-owner-assets-v1/trophies_pyarray.bin"),b=file(root+"/.local-inputs/trophy-owner-assets-v1/trophies_pyarraynames.bin"),c=file(root+"/.local-inputs/trophy-owner-assets-v1/trophies_pystructnames.bin");auto catalog=dh2::trophies::TrophyCatalogV1::load(bytes(a),bytes(b),bytes(c),error);check(bool(catalog),error);auto trophy=dh2::trophies::TrophyManagerOwnerV1::create(catalog,debug,&files,{},error);check(bool(trophy),error);dh2::trophies::TrophyNativeBindingsV1 trophy_native(*trophy);
ExecutionProviders providers;providers.base.main=player.id;sk::WorldSkillCombatBackendsV6 backends{{&providers,ExecutionProviders::hit},{&providers.base,Providers::app,nullptr},&providers.base,Providers::aggro,nullptr};character::DotCombatContext32 common_cf{};data::CombatRandom shared_rng{17,0};sk::CharacterWorldSkillExecutionV6 execution(world,*d.ai(),readonly,gear,fsm,skills.borrow(),common_cf,shared_rng,*debug,files,&trophy_native,backends);
ExecutionActor pa{&player},ea{&enemy};pa.controller=player.id+10;pa.inventory=&gear;ea.controller=enemy.id+10;check(!execution.add({player.id,&pa,ExecutionActor::refresh}),execution.error());check(!execution.add({enemy.id,&ea,ExecutionActor::refresh}),execution.error());
const auto hp=enemy.view.resolved[36];data::CombatResult result;result.amount=256;result.mask=0x20200000;sk::SkillApplyOutputV6 output{};check(execution.combat().apply(&output,&result,player.id,enemy.id)==-2);execution.publish_compatibility_fields();check(enemy.view.resolved[36]==hp-256,"Same exact property HP prefix");check(output.hit.status==1,"Actual TrophyManager lets complete nonlethal HitFor reach later tail");check(player.life.combo_hits==pa.fields.combo&&pa.fields.combo==1);check(execution.error()=="Required SkillApply provider 7","Missing source HitFX explicit after HP");check(!enemy.life.dead&&enemy.outgoing.count==1&&player.incoming.count==1&&providers.base.aggro_events==1);check(!trophy->is_unlocked(10),"No fake achievement unlock");
ea.controller_available=false;const auto prior=enemy.view.resolved[36];result.amount=256;check(execution.combat().apply(&output,&result,player.id,enemy.id)==-2);execution.publish_compatibility_fields();check(enemy.view.resolved[36]==prior,"Missing controller field leaves Hit unavailable before HP");
auto saved=ea.actor->facts.properties;ea.actor->facts.properties=player.view.resolved;check(execution.combat().apply(&output,&result,player.id,enemy.id)==-1,"Reject foreign property facts");ea.actor->facts.properties=saved;
std::uintptr_t selected_methods[51]{};character::AIEventState64 selected_ai{};selected_ai.ai=enemy.id+50;
check(!character::world_aggro_event_v1(selected_ai,player.id,debug,&files,{},error),"Source null selected AIS after Debug prefix");
selected_ai.active=enemy.id+60;selected_ai.ais_virtuals=selected_methods;selected_methods[0x38/4]=0x3dbea4;
check(!character::world_aggro_event_v1(selected_ai,player.id,debug,&files,{},error),"Genuine selected inherited Default OnAggro body");
selected_methods[0x38/4]=0x3ddb70;check(character::world_aggro_event_v1(selected_ai,player.id,debug,&files,{},error)==-2,"Reject unavailable Player OnAggro continuation");
check(!execution.remove(enemy.id));check(execution.remove(enemy.id)==-1);dh2_character_debug_destroy(debug);
std::cout<<"{\"validation\":\"PASS\",\"checks\":"<<checks<<",\"actual_cache_tables\":true,\"same_gear_fsm_hp_life_rng\":true,\"genuine_hit_trophy_capture\":true,\"explicit_missing_fx_tail\":true,\"native_vm_execution\":false,\"full_skill_application\":false}"<<std::endl;return 0;
}catch(const std::exception&e){std::cerr<<e.what()<<std::endl;return 1;}}
