#include "../gameplay_camera_scene_v3.hpp"
#include "../gameplay_camera_level_v4.hpp"
#include "../gameplay_camera_design_v5.hpp"
#include "../canonical_point3d_globals_v1.hpp"
#include <fstream>
#include <iterator>
#include <cassert>
#include <iostream>
using namespace dh2;
int main(int argc,char** argv){try{if(argc!=2)return 2;std::string e;std::vector<std::vector<std::uint8_t>> files;files.reserve(4);auto bytes=[&](const char* n){std::ifstream f(std::string(argv[1])+"/"+n,std::ios::binary);if(!f)throw std::runtime_error(std::string("Required actual file ")+n);files.push_back({std::istreambuf_iterator<char>(f),{}});auto& b=files.back();return data::Bytes{b.data(),b.size()};};data::DesignSettingsOwner design;if(!design.load(bytes("design_pyarray.bin"),bytes("design_pyarraynames.bin"),bytes("design_pystructnames.bin"),e))throw std::runtime_error(e);auto borrow=design.borrow();float lower,upper;assert(camera::source_zoom_bounds_v5(borrow,false,lower,upper,e));std::cout<<"Actual zoom bounds "<<lower<<' '<<upper<<'\n';camera::AutoZoomDesignV5 autozoom;assert(camera::source_autozoom_design_v5(borrow,autozoom,e));
 auto resource=bytes("cameratests.bdae");auto graph=std::make_shared<camera::GameplayCameraSceneV3>();if(!graph->load({resource.data,resource.data+resource.size},e))throw std::runtime_error(e);std::uint32_t selected;assert(graph->select("PlayerCamera_Default",selected,e));const auto camera_parent=graph->graph().graph[graph->cameras()[selected].node].translation[0];camera::PointV2 anchor{100,200,300};bool disabled=false;std::uint32_t dt=16;std::string order;
 camera::LevelServicesV4 s;s.target.scene_lease=graph;s.target.root_present=true;s.camera_present=true;s.target.source_origin=&world::canonical_vec3_origin_v1();
 // Application/World/local-party/Debug are explicit service fixtures. Design
 // and camera graph are genuine cache-backed retained owners.
 s.active_is_this=[&](auto& yes,auto&){order+='A';yes=true;return true;};s.target.actor_anchor=[&](auto id,auto& p,auto&){assert(id==7);order+='T';p=anchor;return true;};s.target.application_dt=[&](auto& value,auto&){order+='D';value=dt;return true;};s.target.root_position=[&](auto& p,auto& err){order+='R';return graph->root_position(p.data(),err);};s.target.root_set_position=[&](const auto& p,auto& err){order+='S';return graph->set_root_position(p.data(),err);};s.handle_centering=[&](auto&,auto&){order+='C';return true;};s.debug_infinite_zoom=[&](auto& value,auto&){order+='Z';value=false;return true;};s.zoom_bounds=[&](bool mode,float& l,float& u,auto& err){order+='B';return camera::source_zoom_bounds_v5(borrow,mode,l,u,err);};s.camera_set_position=[&](const auto& p,auto& err){order+='P';return graph->set_camera_instance_position(selected,p.data(),err);};s.actor_disabled81=[&](auto id,auto& value,auto&){assert(id==7);order+='X';value=disabled;return true;};s.actor_position=[&](auto id,auto& p,auto&){assert(id==7);order+='p';p=anchor;return true;};
 camera::GameplayCameraLevelV4 owner(s);assert(owner.target().set_target(7,0,e));owner.fields().default_distance94=3000;assert(owner.update(e)&&order=="ADTS");order.clear();assert(owner.update(e)&&order=="ATCZBPRRDSX");assert(owner.fields().applied_zoom90==lower);assert(graph->graph().graph[graph->cameras()[selected].node].translation[0]==camera_parent);assert(graph->cameras()[selected].instance_position[2]==(-lower)*3000);float eye[3],destination[3];assert(graph->eye_and_target(selected,eye,destination,e));
 owner.fields().mode85=true;owner.fields().offset98={10,20,30};order.clear();assert(owner.update(e)&&order=="ApCZBPRRDSX");owner.fields().shake84=true;owner.fields().hold_zoom_a4=false;owner.fields().applied_zoom90=.4f;order.clear();assert(owner.update(e)&&order=="ApCPRRDSX"&&owner.fields().applied_zoom90==.3f);owner.source_animation_callback();assert(!owner.fields().shake84);disabled=true;order.clear();assert(owner.update(e)&&owner.target().fields().target==0&&order.back()=='X');
 std::cout<<"Actual camera Level frame/design/child-instance prefix PASS; source body order and disabled target cleanup; explicit World/Debug fixtures, AnimSetController not constructed\n";
}catch(const std::exception& ex){std::cerr<<ex.what()<<'\n';return 1;}}
