#include "../module_pf_room_v3.hpp"
#include "../module_static_scene_bounds_v3.hpp"
#include <cmath>
#include <fstream>
#include <iterator>
#include <iostream>
#include <cassert>
int main(){using namespace dh2;std::ifstream f("/data/local/tmp/dh2-swamp-module-v2.bdae",std::ios::binary);assert(f);auto bytes=std::make_shared<std::vector<std::uint8_t>>((std::istreambuf_iterator<char>(f)),std::istreambuf_iterator<char>{});resources::BresView b{};assert(dh2_bres_open(&b,bytes->data(),bytes->size())==resources::BresError::ok);
auto world=std::make_shared<floors::World>();auto registry=std::make_shared<world::GameObjectSceneRootRegistryV1>();auto map=std::make_shared<world::SceneManagerMapOwnerV2>(registry);unsigned debug_calls=0;world::ModulePFDebugV3 debug;debug.owner=bytes;debug.query=[&](const char* key,bool& value,std::string& e){assert(std::string(key)=="isTracingNavMeshLoadTime");++debug_calls;value=false;e.clear();return true;};world::ModulePFRoomsV3 rooms(world,map,debug);std::string e;unsigned expected_exits=0;
{world::ModuleSelectedSceneV2 selected;bool found=false;assert(world::module_selected_scene_v2(b,"_module_obj_4of4_brdwalk_sw_00",selected,found,e)&&found);float p[]{0.0f,0.0f,0.0f},r[]{0.0f,0.0f,0.0f},scale[]{1.0f,1.0f,1.0f};physical::ObjectVisualTransformV1 trs{};assert(dh2_object_visual_transform_v1(&trs,p,r,scale)==0);world::ModuleStaticSceneV2 scene;assert(scene.initialize(std::move(selected),trs,e)&&scene.optimize_static(e));for(const auto& instance:scene.selected().scene.instances)if(scene.selected().scene.graph[instance.node_index].name.find("_exit_")!=std::string::npos)++expected_exits;std::array<float,6> before{},expected{};bool any=false;
for(const auto& instance:scene.selected().scene.instances){assets::Mesh mesh{};assert(dh2_mesh_open(&mesh,&b,instance.geometry)==assets::Error::ok);octree::Box local{},absolute{};std::copy_n(mesh.minimum,3,local.minimum);std::copy_n(mesh.maximum,3,local.maximum);selector::Matrix matrix{};std::copy_n(instance.world.data(),16,matrix.values);assert(!dh2_floor_transform_bounds(&absolute,&local,&matrix));for(unsigned k=0;k<3;++k){if(!any){expected[k]=absolute.minimum[k];expected[k+3]=absolute.maximum[k];}else{expected[k]=std::min(expected[k],absolute.minimum[k]);expected[k+3]=std::max(expected[k+3],absolute.maximum[k]);}}any=true;}
assert(any&&world::module_static_scene_bounds_v3(b,scene,before,e));for(unsigned k=0;k<6;++k)assert(std::abs(before[k]-expected[k])<0.01f);assert(!(scene.root_flags()&0x100u));
std::shared_ptr<world::ModulePFRoomV3> room;if(!rooms.load(b,bytes,scene,0,"obj_4of4_brdwalk_sw_00_0",room,e)){std::cerr<<e;return 1;}std::array<float,6> after{};assert(world::module_static_scene_query_bounds_v3(scene,after,e)&&before==after);assert(room&&room->id==0&&!room->clones.empty());for(const auto& clone:room->clones){assert(clone->parent()==map->identity()&&(clone->flags()&1u)==0);assert(clone->floor().room==0);}for(unsigned j=0;j<scene.selected().scene.instances.size();++j)if(scene.selected().scene.graph[scene.selected().scene.instances[j].node_index].name.find("floor")!=std::string::npos)assert(!scene.mesh_attached(j));}
{world::ModuleSelectedSceneV2 selected;bool found=false;assert(world::module_selected_scene_v2(b,"_module_obj_3of4_brdwalk_sw_00",selected,found,e)&&found);float p[]{-6000.0f,0.0f,0.0f},r[]{0.0f,0.0f,0.0f},scale[]{1.0f,1.0f,1.0f};physical::ObjectVisualTransformV1 trs{};assert(dh2_object_visual_transform_v1(&trs,p,r,scale)==0);world::ModuleStaticSceneV2 scene;assert(scene.initialize(std::move(selected),trs,e)&&scene.optimize_static(e));for(const auto& instance:scene.selected().scene.instances)if(scene.selected().scene.graph[instance.node_index].name.find("_exit_")!=std::string::npos)++expected_exits;std::array<float,6> before{},expected{};bool any=false;
for(const auto& instance:scene.selected().scene.instances){assets::Mesh mesh{};assert(dh2_mesh_open(&mesh,&b,instance.geometry)==assets::Error::ok);octree::Box local{},absolute{};std::copy_n(mesh.minimum,3,local.minimum);std::copy_n(mesh.maximum,3,local.maximum);selector::Matrix matrix{};std::copy_n(instance.world.data(),16,matrix.values);assert(!dh2_floor_transform_bounds(&absolute,&local,&matrix));for(unsigned k=0;k<3;++k){if(!any){expected[k]=absolute.minimum[k];expected[k+3]=absolute.maximum[k];}else{expected[k]=std::min(expected[k],absolute.minimum[k]);expected[k+3]=std::max(expected[k+3],absolute.maximum[k]);}}any=true;}
assert(any&&world::module_static_scene_bounds_v3(b,scene,before,e));for(unsigned k=0;k<6;++k)assert(std::abs(before[k]-expected[k])<0.01f);assert(!(scene.root_flags()&0x100u));
std::shared_ptr<world::ModulePFRoomV3> room;if(!rooms.load(b,bytes,scene,1,"obj_3of4_brdwalk_sw_00_1",room,e)){std::cerr<<e;return 1;}std::array<float,6> after{};assert(world::module_static_scene_query_bounds_v3(scene,after,e)&&before==after);assert(room&&room->id==1&&!room->clones.empty());for(const auto& clone:room->clones){assert(clone->parent()==map->identity()&&(clone->flags()&1u)==0);assert(clone->floor().room==1);}for(unsigned j=0;j<scene.selected().scene.instances.size();++j)if(scene.selected().scene.graph[scene.selected().scene.instances[j].node_index].name.find("floor")!=std::string::npos)assert(!scene.mesh_attached(j));}
{world::ModuleSelectedSceneV2 selected;bool found=false;assert(world::module_selected_scene_v2(b,"_module_obj_1of4_brdwalk_nse_00",selected,found,e)&&found);float p[]{-6000.0f,6000.0f,0.0f},r[]{0.0f,0.0f,0.0f},scale[]{1.0f,1.0f,1.0f};physical::ObjectVisualTransformV1 trs{};assert(dh2_object_visual_transform_v1(&trs,p,r,scale)==0);world::ModuleStaticSceneV2 scene;assert(scene.initialize(std::move(selected),trs,e)&&scene.optimize_static(e));for(const auto& instance:scene.selected().scene.instances)if(scene.selected().scene.graph[instance.node_index].name.find("_exit_")!=std::string::npos)++expected_exits;std::array<float,6> before{},expected{};bool any=false;
for(const auto& instance:scene.selected().scene.instances){assets::Mesh mesh{};assert(dh2_mesh_open(&mesh,&b,instance.geometry)==assets::Error::ok);octree::Box local{},absolute{};std::copy_n(mesh.minimum,3,local.minimum);std::copy_n(mesh.maximum,3,local.maximum);selector::Matrix matrix{};std::copy_n(instance.world.data(),16,matrix.values);assert(!dh2_floor_transform_bounds(&absolute,&local,&matrix));for(unsigned k=0;k<3;++k){if(!any){expected[k]=absolute.minimum[k];expected[k+3]=absolute.maximum[k];}else{expected[k]=std::min(expected[k],absolute.minimum[k]);expected[k+3]=std::max(expected[k+3],absolute.maximum[k]);}}any=true;}
assert(any&&world::module_static_scene_bounds_v3(b,scene,before,e));for(unsigned k=0;k<6;++k)assert(std::abs(before[k]-expected[k])<0.01f);assert(!(scene.root_flags()&0x100u));
std::shared_ptr<world::ModulePFRoomV3> room;if(!rooms.load(b,bytes,scene,2,"obj_1of4_brdwalk_nse_00_2",room,e)){std::cerr<<e;return 1;}std::array<float,6> after{};assert(world::module_static_scene_query_bounds_v3(scene,after,e)&&before==after);assert(room&&room->id==2&&!room->clones.empty());for(const auto& clone:room->clones){assert(clone->parent()==map->identity()&&(clone->flags()&1u)==0);assert(clone->floor().room==2);}for(unsigned j=0;j<scene.selected().scene.instances.size();++j)if(scene.selected().scene.graph[scene.selected().scene.instances[j].node_index].name.find("floor")!=std::string::npos)assert(!scene.mesh_attached(j));}
{world::ModuleSelectedSceneV2 selected;bool found=false;assert(world::module_selected_scene_v2(b,"_module_corner_ruin_ws_00",selected,found,e)&&found);float p[]{-6000.0f,12000.0f,0.0f},r[]{0.0f,0.0f,0.0f},scale[]{1.0f,1.0f,1.0f};physical::ObjectVisualTransformV1 trs{};assert(dh2_object_visual_transform_v1(&trs,p,r,scale)==0);world::ModuleStaticSceneV2 scene;assert(scene.initialize(std::move(selected),trs,e)&&scene.optimize_static(e));for(const auto& instance:scene.selected().scene.instances)if(scene.selected().scene.graph[instance.node_index].name.find("_exit_")!=std::string::npos)++expected_exits;std::array<float,6> before{},expected{};bool any=false;
for(const auto& instance:scene.selected().scene.instances){assets::Mesh mesh{};assert(dh2_mesh_open(&mesh,&b,instance.geometry)==assets::Error::ok);octree::Box local{},absolute{};std::copy_n(mesh.minimum,3,local.minimum);std::copy_n(mesh.maximum,3,local.maximum);selector::Matrix matrix{};std::copy_n(instance.world.data(),16,matrix.values);assert(!dh2_floor_transform_bounds(&absolute,&local,&matrix));for(unsigned k=0;k<3;++k){if(!any){expected[k]=absolute.minimum[k];expected[k+3]=absolute.maximum[k];}else{expected[k]=std::min(expected[k],absolute.minimum[k]);expected[k+3]=std::max(expected[k+3],absolute.maximum[k]);}}any=true;}
assert(any&&world::module_static_scene_bounds_v3(b,scene,before,e));for(unsigned k=0;k<6;++k)assert(std::abs(before[k]-expected[k])<0.01f);assert(!(scene.root_flags()&0x100u));
std::shared_ptr<world::ModulePFRoomV3> room;if(!rooms.load(b,bytes,scene,3,"corner_ruin_ws_00_3",room,e)){std::cerr<<e;return 1;}std::array<float,6> after{};assert(world::module_static_scene_query_bounds_v3(scene,after,e)&&before==after);assert(room&&room->id==3&&!room->clones.empty());for(const auto& clone:room->clones){assert(clone->parent()==map->identity()&&(clone->flags()&1u)==0);assert(clone->floor().room==3);}for(unsigned j=0;j<scene.selected().scene.instances.size();++j)if(scene.selected().scene.graph[scene.selected().scene.instances[j].node_index].name.find("floor")!=std::string::npos)assert(!scene.mesh_attached(j));}
{world::ModuleSelectedSceneV2 selected;bool found=false;assert(world::module_selected_scene_v2(b,"_module_merchantcamp_ruins_swe_00",selected,found,e)&&found);float p[]{-12000.0f,12000.0f,0.0f},r[]{0.0f,0.0f,0.0f},scale[]{1.0f,1.0f,1.0f};physical::ObjectVisualTransformV1 trs{};assert(dh2_object_visual_transform_v1(&trs,p,r,scale)==0);world::ModuleStaticSceneV2 scene;assert(scene.initialize(std::move(selected),trs,e)&&scene.optimize_static(e));for(const auto& instance:scene.selected().scene.instances)if(scene.selected().scene.graph[instance.node_index].name.find("_exit_")!=std::string::npos)++expected_exits;std::array<float,6> before{},expected{};bool any=false;
for(const auto& instance:scene.selected().scene.instances){assets::Mesh mesh{};assert(dh2_mesh_open(&mesh,&b,instance.geometry)==assets::Error::ok);octree::Box local{},absolute{};std::copy_n(mesh.minimum,3,local.minimum);std::copy_n(mesh.maximum,3,local.maximum);selector::Matrix matrix{};std::copy_n(instance.world.data(),16,matrix.values);assert(!dh2_floor_transform_bounds(&absolute,&local,&matrix));for(unsigned k=0;k<3;++k){if(!any){expected[k]=absolute.minimum[k];expected[k+3]=absolute.maximum[k];}else{expected[k]=std::min(expected[k],absolute.minimum[k]);expected[k+3]=std::max(expected[k+3],absolute.maximum[k]);}}any=true;}
assert(any&&world::module_static_scene_bounds_v3(b,scene,before,e));for(unsigned k=0;k<6;++k)assert(std::abs(before[k]-expected[k])<0.01f);assert(!(scene.root_flags()&0x100u));
std::shared_ptr<world::ModulePFRoomV3> room;if(!rooms.load(b,bytes,scene,4,"merchantcamp_ruins_swe_00_4",room,e)){std::cerr<<e;return 1;}std::array<float,6> after{};assert(world::module_static_scene_query_bounds_v3(scene,after,e)&&before==after);assert(room&&room->id==4&&!room->clones.empty());for(const auto& clone:room->clones){assert(clone->parent()==map->identity()&&(clone->flags()&1u)==0);assert(clone->floor().room==4);}for(unsigned j=0;j<scene.selected().scene.instances.size();++j)if(scene.selected().scene.graph[scene.selected().scene.instances[j].node_index].name.find("floor")!=std::string::npos)assert(!scene.mesh_attached(j));}
{world::ModuleSelectedSceneV2 selected;bool found=false;assert(world::module_selected_scene_v2(b,"_module_corner_brdwalk_se_00",selected,found,e)&&found);float p[]{-12000.0f,18000.0f,0.0f},r[]{0.0f,0.0f,0.0f},scale[]{1.0f,1.0f,1.0f};physical::ObjectVisualTransformV1 trs{};assert(dh2_object_visual_transform_v1(&trs,p,r,scale)==0);world::ModuleStaticSceneV2 scene;assert(scene.initialize(std::move(selected),trs,e)&&scene.optimize_static(e));for(const auto& instance:scene.selected().scene.instances)if(scene.selected().scene.graph[instance.node_index].name.find("_exit_")!=std::string::npos)++expected_exits;std::array<float,6> before{},expected{};bool any=false;
for(const auto& instance:scene.selected().scene.instances){assets::Mesh mesh{};assert(dh2_mesh_open(&mesh,&b,instance.geometry)==assets::Error::ok);octree::Box local{},absolute{};std::copy_n(mesh.minimum,3,local.minimum);std::copy_n(mesh.maximum,3,local.maximum);selector::Matrix matrix{};std::copy_n(instance.world.data(),16,matrix.values);assert(!dh2_floor_transform_bounds(&absolute,&local,&matrix));for(unsigned k=0;k<3;++k){if(!any){expected[k]=absolute.minimum[k];expected[k+3]=absolute.maximum[k];}else{expected[k]=std::min(expected[k],absolute.minimum[k]);expected[k+3]=std::max(expected[k+3],absolute.maximum[k]);}}any=true;}
assert(any&&world::module_static_scene_bounds_v3(b,scene,before,e));for(unsigned k=0;k<6;++k)assert(std::abs(before[k]-expected[k])<0.01f);assert(!(scene.root_flags()&0x100u));
std::shared_ptr<world::ModulePFRoomV3> room;if(!rooms.load(b,bytes,scene,5,"corner_brdwalk_se_00_5",room,e)){std::cerr<<e;return 1;}std::array<float,6> after{};assert(world::module_static_scene_query_bounds_v3(scene,after,e)&&before==after);assert(room&&room->id==5&&!room->clones.empty());for(const auto& clone:room->clones){assert(clone->parent()==map->identity()&&(clone->flags()&1u)==0);assert(clone->floor().room==5);}for(unsigned j=0;j<scene.selected().scene.instances.size();++j)if(scene.selected().scene.graph[scene.selected().scene.instances[j].node_index].name.find("floor")!=std::string::npos)assert(!scene.mesh_attached(j));}
{world::ModuleSelectedSceneV2 selected;bool found=false;assert(world::module_selected_scene_v2(b,"_module_deadend_brdwalk_w_00",selected,found,e)&&found);float p[]{-6000.0f,18000.0f,0.0f},r[]{0.0f,0.0f,0.0f},scale[]{1.0f,1.0f,1.0f};physical::ObjectVisualTransformV1 trs{};assert(dh2_object_visual_transform_v1(&trs,p,r,scale)==0);world::ModuleStaticSceneV2 scene;assert(scene.initialize(std::move(selected),trs,e)&&scene.optimize_static(e));for(const auto& instance:scene.selected().scene.instances)if(scene.selected().scene.graph[instance.node_index].name.find("_exit_")!=std::string::npos)++expected_exits;std::array<float,6> before{},expected{};bool any=false;
for(const auto& instance:scene.selected().scene.instances){assets::Mesh mesh{};assert(dh2_mesh_open(&mesh,&b,instance.geometry)==assets::Error::ok);octree::Box local{},absolute{};std::copy_n(mesh.minimum,3,local.minimum);std::copy_n(mesh.maximum,3,local.maximum);selector::Matrix matrix{};std::copy_n(instance.world.data(),16,matrix.values);assert(!dh2_floor_transform_bounds(&absolute,&local,&matrix));for(unsigned k=0;k<3;++k){if(!any){expected[k]=absolute.minimum[k];expected[k+3]=absolute.maximum[k];}else{expected[k]=std::min(expected[k],absolute.minimum[k]);expected[k+3]=std::max(expected[k+3],absolute.maximum[k]);}}any=true;}
assert(any&&world::module_static_scene_bounds_v3(b,scene,before,e));for(unsigned k=0;k<6;++k)assert(std::abs(before[k]-expected[k])<0.01f);assert(!(scene.root_flags()&0x100u));
std::shared_ptr<world::ModulePFRoomV3> room;if(!rooms.load(b,bytes,scene,6,"deadend_brdwalk_w_00_7",room,e)){std::cerr<<e;return 1;}std::array<float,6> after{};assert(world::module_static_scene_query_bounds_v3(scene,after,e)&&before==after);assert(room&&room->id==6&&!room->clones.empty());for(const auto& clone:room->clones){assert(clone->parent()==map->identity()&&(clone->flags()&1u)==0);assert(clone->floor().room==6);}for(unsigned j=0;j<scene.selected().scene.instances.size();++j)if(scene.selected().scene.graph[scene.selected().scene.instances[j].node_index].name.find("floor")!=std::string::npos)assert(!scene.mesh_attached(j));}
{world::ModuleSelectedSceneV2 selected;bool found=false;assert(world::module_selected_scene_v2(b,"_module_bossroom_ruins_ns_",selected,found,e)&&found);float p[]{-18000.0f,12000.0f,0.0f},r[]{0.0f,0.0f,0.0f},scale[]{1.0f,1.0f,1.0f};physical::ObjectVisualTransformV1 trs{};assert(dh2_object_visual_transform_v1(&trs,p,r,scale)==0);world::ModuleStaticSceneV2 scene;assert(scene.initialize(std::move(selected),trs,e)&&scene.optimize_static(e));for(const auto& instance:scene.selected().scene.instances)if(scene.selected().scene.graph[instance.node_index].name.find("_exit_")!=std::string::npos)++expected_exits;std::array<float,6> before{},expected{};bool any=false;
for(const auto& instance:scene.selected().scene.instances){assets::Mesh mesh{};assert(dh2_mesh_open(&mesh,&b,instance.geometry)==assets::Error::ok);octree::Box local{},absolute{};std::copy_n(mesh.minimum,3,local.minimum);std::copy_n(mesh.maximum,3,local.maximum);selector::Matrix matrix{};std::copy_n(instance.world.data(),16,matrix.values);assert(!dh2_floor_transform_bounds(&absolute,&local,&matrix));for(unsigned k=0;k<3;++k){if(!any){expected[k]=absolute.minimum[k];expected[k+3]=absolute.maximum[k];}else{expected[k]=std::min(expected[k],absolute.minimum[k]);expected[k+3]=std::max(expected[k+3],absolute.maximum[k]);}}any=true;}
assert(any&&world::module_static_scene_bounds_v3(b,scene,before,e));for(unsigned k=0;k<6;++k)assert(std::abs(before[k]-expected[k])<0.01f);assert(!(scene.root_flags()&0x100u));
std::shared_ptr<world::ModulePFRoomV3> room;if(!rooms.load(b,bytes,scene,7,"bossroom_ruins_ns__8",room,e)){std::cerr<<e;return 1;}std::array<float,6> after{};assert(world::module_static_scene_query_bounds_v3(scene,after,e)&&before==after);assert(room&&room->id==7&&!room->clones.empty());for(const auto& clone:room->clones){assert(clone->parent()==map->identity()&&(clone->flags()&1u)==0);assert(clone->floor().room==7);}for(unsigned j=0;j<scene.selected().scene.instances.size();++j)if(scene.selected().scene.graph[scene.selected().scene.instances[j].node_index].name.find("floor")!=std::string::npos)assert(!scene.mesh_attached(j));}
{world::ModuleSelectedSceneV2 selected;bool found=false;assert(world::module_selected_scene_v2(b,"_module_obj_2of4_brdwalk_sw_00",selected,found,e)&&found);float p[]{0.0f,6000.0f,0.0f},r[]{0.0f,0.0f,0.0f},scale[]{1.0f,1.0f,1.0f};physical::ObjectVisualTransformV1 trs{};assert(dh2_object_visual_transform_v1(&trs,p,r,scale)==0);world::ModuleStaticSceneV2 scene;assert(scene.initialize(std::move(selected),trs,e)&&scene.optimize_static(e));for(const auto& instance:scene.selected().scene.instances)if(scene.selected().scene.graph[instance.node_index].name.find("_exit_")!=std::string::npos)++expected_exits;std::array<float,6> before{},expected{};bool any=false;
for(const auto& instance:scene.selected().scene.instances){assets::Mesh mesh{};assert(dh2_mesh_open(&mesh,&b,instance.geometry)==assets::Error::ok);octree::Box local{},absolute{};std::copy_n(mesh.minimum,3,local.minimum);std::copy_n(mesh.maximum,3,local.maximum);selector::Matrix matrix{};std::copy_n(instance.world.data(),16,matrix.values);assert(!dh2_floor_transform_bounds(&absolute,&local,&matrix));for(unsigned k=0;k<3;++k){if(!any){expected[k]=absolute.minimum[k];expected[k+3]=absolute.maximum[k];}else{expected[k]=std::min(expected[k],absolute.minimum[k]);expected[k+3]=std::max(expected[k+3],absolute.maximum[k]);}}any=true;}
assert(any&&world::module_static_scene_bounds_v3(b,scene,before,e));for(unsigned k=0;k<6;++k)assert(std::abs(before[k]-expected[k])<0.01f);assert(!(scene.root_flags()&0x100u));
std::shared_ptr<world::ModulePFRoomV3> room;if(!rooms.load(b,bytes,scene,8,"obj_2of4_brdwalk_sw_00_9",room,e)){std::cerr<<e;return 1;}std::array<float,6> after{};assert(world::module_static_scene_query_bounds_v3(scene,after,e)&&before==after);assert(room&&room->id==8&&!room->clones.empty());for(const auto& clone:room->clones){assert(clone->parent()==map->identity()&&(clone->flags()&1u)==0);assert(clone->floor().room==8);}for(unsigned j=0;j<scene.selected().scene.instances.size();++j)if(scene.selected().scene.graph[scene.selected().scene.instances[j].node_index].name.find("floor")!=std::string::npos)assert(!scene.mesh_attached(j));}
assert(rooms.rooms().size()==9&&world->records.size()==16&&map->children().size()==16&&debug_calls==16);assert(rooms.exits().size()==expected_exits);assert(world->floor_graphs.size()==16&&world->graph.node_count>0);assert(registry->roots().size()==1);for(auto id:map->children())assert(map->remove(id,e));assert(map->release(e)&&registry->roots().empty());std::cout<<"Actual SWAMP ctor world-bounds + cached queries + PFRoom PASS 9 rooms 16 floors "<<expected_exits<<" exits\n";}
