#include "openable_container_data_connection_v11.hpp"
#include "openable_container_real_cache_fixture_v1.hpp"
#include <fstream>
#include <iostream>
#include <stdexcept>
using namespace dh2;
int main(int argc,char** argv){try{if(argc!=2)return 2;unsigned checks{};auto check=[&](bool yes,const std::string& error){++checks;if(!yes)throw std::runtime_error(error);};auto file=[&](const char* name){std::ifstream f(std::string(argv[1])+"/"+name,std::ios::binary);check(bool(f),name);return std::vector<std::uint8_t>{std::istreambuf_iterator<char>(f),{}};};
 auto records=file("game_objects_dictionary_pyarray.bin"),names=file("game_objects_dictionary_pyarraynames.bin");world::OpenableContainerDataConnectionV11 data;std::string e;check(data.load(source_openable_records,sizeof source_openable_records,source_openable_names,sizeof source_openable_names,records.data(),records.size(),names.data(),names.size(),e),e);check(data.container_count()==68&&data.dictionary_count()==85,"actual cache counts");
 actor::RuntimeState runtime{};world::CanonicalGameObjectBaseOwnerV1 base(reinterpret_cast<std::uintptr_t>(&runtime),7,std::make_shared<int>(1),runtime);
 for(const char* name:{"Swamp_Normal_Chest","SwampCave_Big_Chest","Swamp2_Rotten_Chest"}){std::int32_t id{};world::OpenableContainerRowV1 row;check(data.resolve_row(name,id,row,e)&&id>=0,e);check(data.visual_asset(base,row.visual,e),e);const std::string path=*base.string(0x290);check(path.find("data/3D/GameObjects/go_chest_swamp")==0&&path.find(".bdae")!=std::string::npos,"actual dictionary URI");if(std::string(name)=="Swamp_Normal_Chest")check(row.visual==47&&row.loot==227&&row.sound==33&&path=="data/3D/GameObjects/go_chest_swamp.bdae","actual first Swamp data");}
 std::int32_t id{};world::OpenableContainerRowV1 row;check(data.resolve_row("",id,row,e)&&id==-1,e);check(data.resolve_row("missing-original-name",id,row,e)&&id==-1,e);auto previous=*base.string(0x290);check(!data.visual_asset(base,85,e)&&*base.string(0x290)==previous,"invalid dictionary row prefix");check(!data.load(source_openable_records,sizeof source_openable_records,source_openable_names,sizeof source_openable_names,records.data(),records.size(),names.data(),names.size(),e),"live cache reload guard");
 data::GameObjectDictionaryV11 dictionary;check(dictionary.load(records.data(),records.size(),names.data(),names.size(),e),e);check(dictionary.find("go_chest_swamp",id,e)&&id==47,e);for(unsigned i=0;i<85;++i){const std::string* path{};check(dictionary.file(i,path,e)&&path&&!path->empty(),e);}std::cout<<"PASS actual68 OpenableContainers +85 GameObjectDict owner/GetDataId/row/same CString290 callbacks, real Swamp URIs and failure/reload guards checks="<<checks<<'\n';return 0;
 }catch(const std::exception& ex){std::cerr<<ex.what();return 1;}}
