#include "../retained_character_position_owner_v7.hpp"
#include "../physical_world.hpp"
#include <iostream>
#include <algorithm>
#include <cstring>
using namespace dh2;
static unsigned checks;
static void check(bool value,const char* text){++checks;if(!value)throw std::runtime_error(text);}
int main(){try{
 auto world=std::make_shared<int>(1);character::RetainedCharacterActorV1 actor(0x70,world,"Character",character::RetainedCharacterConstructionV7::fresh_canonical);auto& fields=actor.position_fields_v7();std::string error;check(fields.constructed,"source ctor fields");
 auto properties=std::make_shared<data::PropertyState>();auto life=std::make_shared<data::CombatActorState>();auto object=std::make_shared<character::ScriptCharacterObject>(0x70,"position-constructor-audit",properties,life,std::array<float,3>{});check(actor.construct_fields(object,{}),"same actual retained fields");
 character::RetainedCharacterPositionOwnerV7 before_init(actor,fields,{});const float first[3]{100,200,300};check(before_init.set_position(first,true,error),"constructor-null backend branches");check(object->position[0]==100&&actor.runtime.subobjects.position[0]==100&&actor.runtime.controller.destination[0]==100,"same authority/destination");check(actor.runtime.object.motion.floor==~0u,"no PF floor fabrication");
 physical::NativeWorld physical_world;const float bounds[4]{-1000,-1000,1000,1000};physical_world.load(bounds);physical::NativeBody body{};physical::CharacterBodyInput input{};input.owner=reinterpret_cast<void*>(object->identity);input.new_physical=&body;input.character_type=2;input.absolute_bounds[0]=-100;input.absolute_bounds[1]=-100;input.absolute_bounds[2]=100;input.absolute_bounds[3]=100;physical::CharacterBodyConfig config;check(dh2_character_body_config(&config,&input)==0,"original body-definition fixture");physical::WorldObject physical_object{};body={physical_world.create_character(config,&physical_object),config.radius,config.pinned};check(body.body,"real native body");
 check(before_init.publish_physical(object->identity,reinterpret_cast<std::uintptr_t>(&body),&body,true,error),"actual body assignment publishes sole2dc");character::RetainedCharacterPositionBackendsV7 services;services.world=world;services.physical_body=[&](auto id,physical::NativeBody*& out,auto&){check(id==fields.physical2dc,"same actual physical identity");out=&body;return true;};
 // InitCam publishes its retained Anchor into Character+0x2e0. SpawnPoint's
 // later SetPosition must move that exact Anchor+0x0c by the same XYZ delta.
 fields.attached2e0=0xA00;float attached_xyz[3]{10,20,30};services.attached_position=[&](auto id,float*& out,auto&){check(id==0xA00,"same actual attached Character Anchor identity");out=attached_xyz;return true;};
 unsigned visual_calls=0;services.visual_sync_position=[&](auto id,auto&){check(id==0x123,"declared visual receiver fixture");check(object->position[0]==250&&actor.runtime.subobjects.absolute_bounds[0]==150,"published position/bounds before visual");++visual_calls;return true;};actor.source_visual()=0x123;
 character::RetainedCharacterPositionOwnerV7 after_init(actor,fields,services);const float next[3]{250,375,500};check(after_init.set_position(next,false,error),"whole actual body and attached Anchor delivery");check(attached_xyz[0]==160&&attached_xyz[1]==195&&attached_xyz[2]==230,"attached Anchor receives source SetPosition delta");physical::NativeBodyObservation observation;check(dh2_native_body_observe(&observation,&body)==0&&observation.position[0]==2.5f&&observation.position[1]==3.75f,"source physical gameXY-to-body units");check(visual_calls==1&&actor.runtime.controller.destination[0]==100,"source destinationfalse leaves prior target");
 services.physical_body=[](auto,physical::NativeBody*&,std::string& e){e="missing exact source physical receiver";return false;};character::RetainedCharacterPositionOwnerV7 missing(actor,fields,services);const float third[3]{400,500,600};check(!missing.set_position(third,true,error)&&error=="missing exact source physical receiver","required error preserved");check(object->position[0]==400&&actor.runtime.controller.destination[0]==100,"failure prefix without retry/reset");
 actor.source_visual()=0;physical_world.destroy(body.body);check(after_init.publish_physical(object->identity,reinterpret_cast<std::uintptr_t>(&body),&body,false,error)&&fields.physical2dc==0,"actual destruction clears sole2dc");check(actor.object->properties==properties&&actor.object->life==life,"no alternate stats/life");
 character::RetainedCharacterActorV1 adopted(0x80,world,"Character");check(!adopted.position_fields_v7().constructed,"existing actor requires actual pointer projection");
 adopted.runtime.controller.destination[0]=777;adopted.runtime.subobjects.local_bounds[0]=-123;adopted.runtime.object.motion.floor=42;adopted.runtime.controller.path_requested=1;
 const auto preserved=adopted.runtime;check(adopted.position_fields_v7().adopt(0x991,0x992,error),"actual adoption pointer values");check(std::memcmp(&preserved,&adopted.runtime,sizeof(preserved))==0,"adoption cannot replay runtime ctor/defaults");check(!adopted.position_fields_v7().construct(adopted.runtime,error)&&std::memcmp(&preserved,&adopted.runtime,sizeof(preserved))==0,"fresh constructor refuses adopted fields without mutation");
 check(adopted.position_fields_v7().physical2dc==0x991&&adopted.position_fields_v7().attached2e0==0x992,"same physical and camera-anchor source slots");
 std::cout<<"{\"validation\":\"PASS\",\"checks\":"<<checks<<",\"actual_body\":true,\"visual_fixture\":true,\"fresh_vs_adoption_no_replay\":true,\"no_PF_floor_or_path_override\":true}"<<std::endl;
 }catch(const std::exception& e){std::cerr<<e.what()<<std::endl;return 1;}}
