"""Freeze the completed isolated whole-player V3 proof and integration contract."""
import difflib,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];REF=ROOT/'port/level-world/reference/character-skill-gameplay-v3'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(name,data):(REF/name).write_text(json.dumps(data,indent=2)+'\n')
def main():
 names=['character_skill_callbacks_v3','character_skill_buff_bindings_v3','character_script_session_v3','character_skills_session_v3','character_skill_info_session_v3','character_player_skills_v3','character_skills_owner_v3','character_skill_callback_session_v3','character_skill_class_v3','character_skill_cooldown_v3','character_faery_element_v3','character_skill_ai_v3']
 production=['port/level-world/'+n+s for n in names for s in('.hpp','.cpp')]+['port/script-runtime/script_return_observer_v3.h','port/script-runtime/script_runtime_return_v3.c']
 world=['port/level-world/'+n+'.cpp'for n in names]
 tests=[dict(target='character_player_skills_v3_audit',source='port/level-world/tests/character_player_skills_v3.cpp',args=['port/level-world/reference/character-game-design/real-cache-inputs.bin','port/android-native/app/src/main/assets','.local-inputs/character-skill-session-v2/cache','port/engine-ui/reference/hud-formatting-v1/skill-class-gold.bin',r'C:\Users\adamc\Downloads\dungeonhunter2\Dungeon-Hunter-2-HD-v1-0-2-cache.zip']),dict(target='character_skill_ai_v3_audit',source='port/level-world/tests/character_skill_ai_v3.cpp',args=['port/level-world/reference/character-skill-gameplay-v3/ai-gold-v3.bin']),dict(target='character_skill_callbacks_v3_audit',source='port/level-world/tests/character_skill_callbacks_v3.cpp',args=['port/level-world/reference/character-skill-gameplay-v3/callback-gold.bin']),dict(target='script_indexed_return_v3_audit',source='port/script-runtime/tests/script_indexed_return_v3.cpp',args=[])]
 save('integration.json',dict(validation='PASS',production_world_sources=world,runtime_replace=dict(previous='port/script-runtime/script_runtime_return_v1.c',replacement='port/script-runtime/script_runtime_return_v3.c',never_compile_together=['port/script-runtime/script_runtime_return_v1.c','port/script-runtime/script_runtime.c'],new_header='port/script-runtime/script_return_observer_v3.h'),existing_dependencies=['CharacterGameDesign/real constants and DebugSwitches','CharacterScriptOwnerV2','CharacterCurrentSkillV2','CharacterScriptPlayerVCBV2','CharacterCurrentSpellV1','CharacterScriptAssetsV1/ZipAssetPackV1 (zlib)','Skill/Faery/Class/Property/Buff/Timer/native FSM/native AI events','SkillInfo/HUD text formatting V1'],tests=tests,build_policy='Tests link actual selected runtime/world/data/UI DSOs; do not compile production CPPs or a second runtime/core into test executables.',live_inputs=['Borrow SAME NativeFSM24 and Character/property/life owners; destroy V2 before selecting V3.','Borrow coherent full CharAI/controller/static AI/AIS callable projections.','Borrow actual current World/host difficulty callback.','Provide same live owner flags and typed SetSkillState/Animator/trophy/network effects; no autoaccepted handlers.','Borrow retained cached file provider with genuine archive case/path semantics.','Route all native/Lua timer starts/stops/updates to the SAME SessionV3 TimerStore; advance dt only once.','Nonempty active effects, combat/target/search/FX and full SkillFSM6 remain required services.'],ndk_scope='New pure kernels verified O2 ARM64; complete owner/runtime NDK central closure remains root integration proof, not claimed here.'))
 mapping=json.loads((REF/'versioning-map.json').read_text());differences=[]
 for row in mapping['files']:
  original=ROOT/row['source'];target=ROOT/row['target'];assert sha(original)==row['source_sha256'],'Frozen source changed: '+row['source']
  text=original.read_text()
  for old,new in row.get('renames',{}).items():text=text.replace(old,new)
  differences.append(dict(source=row['source'],source_sha256=sha(original),target=row['target'],final_sha256=sha(target),initial_mechanical_sha256=row['mechanical_versioned_sha256'],normalized_diff=list(difflib.unified_diff(text.splitlines(),target.read_text().splitlines(),fromfile='mechanically-versioned '+row['source'],tofile=row['target'],lineterm=''))))
 save('versioning-final.json',dict(validation='PASS',scope='Exact frozen originals are unchanged. Diffs show additive V3 ownership/provider/runtime changes; pure copied portions retain their prior source evidence. Owner header selection is a subset as recorded by initial versioning-map.',files=differences))
 reports=sorted((ROOT/'port/level-world/reports').glob('character-skill-gameplay-v3-*.json'));report_data={p.name:json.loads(p.read_text())for p in reports};assert len(reports)==8
 for r in report_data.values():assert r['validation']=='PASS'
 arm=ROOT/'.local-inputs/character-skill-gameplay-v3/libskill_gameplay_v3_oracle.so';arm_hash=sha(arm)
 for name,r in report_data.items():
  if 'arm64-differential' in name:assert r.get('optimized_arm64_sha256',r.get('arm64_sha256'))==arm_hash,(name,arm_hash)
 player=report_data['character-skill-gameplay-v3-player-host-audit.json'];runtime=report_data['character-skill-gameplay-v3-indexed-runtime-host-audit.json']
 for path in production:
  captured=runtime['compiler_inputs_sha256'] if path.startswith('port/script-runtime')else player['source_and_inputs_sha256'];assert captured[path]==sha(ROOT/path),'Production differs from completed sanitizer build: '+path
 assert player['results']['player']['complete_original_scripts']==219 and player['results']['callbacks']['original_cases']==1920 and player['results']['ai']['original_cases']==2304
 evidence=[p for p in REF.rglob('*')if p.is_file()and p.name!='freeze-manifest.json']
 code=[ROOT/x for x in production]+[ROOT/t['source']for t in tests]+list((ROOT/'port/level-world/tests').glob('character_skill*_*v3*.py'))+[ROOT/'port/level-world/tests/character_faery_queries_v3_differential.py',ROOT/'port/level-world/tests/character_skill_ai_v3_differential.py',ROOT/'port/level-world/tests/character_skill_timer_identity_v3_original.py',ROOT/'port/level-world/tools/build_character_skill_gameplay_v3_oracle.ps1',Path(__file__)]
 paths=sorted(set(p for p in evidence+reports+code if p.is_file()));hashes={p.relative_to(ROOT).as_posix():sha(p)for p in paths}
 functions={}
 for p in REF.rglob('original-functions.json'):
  for fn in json.loads(p.read_text())['functions']:
   old=functions.get(fn['elf_address']);assert old is None or old['sha256']==fn['sha256'];functions[fn['elf_address']]=fn
 freeze=dict(validation='PASS',stage='Whole same-owner player skill V3, complete source cache/AI/callback/Buff/timer/Faery producer composition',source_and_evidence_sha256=hashes,production_sources=production,optimized_arm64_oracle=dict(path=arm.relative_to(ROOT).as_posix(),sha256=arm_hash,original_differential_cases=8800),original_functions=functions,original_only_timer_id_cases=256,sanitizers=dict(address=True,undefined=True,leaks=True,findings=0),host_results=player['results'],runtime_results=runtime['results'],existing_dependent_receipts=['port/engine-ui/reference/hud-formatting-v1/freeze-manifest.json','port/level-world/reference/character-current-spell-v1/freeze-manifest.json'],scope_limits=['Native borrowed providers remain explicit; no fabricated active SkillFSM6/search/combat/network/trophy/nonnull FX effects.','Actual retained passive Focus/Event/Blur uses controlled current-index fixture.','Saved levels/duration/difficulty/Idle-FSM inputs are explicit fixtures, no fresh campaign/full Character frame proof.','Private coherent main120 transitive DSOs are historical compiler provenance; no current packaged Android/GPU proof.','No shared source/CMake/renderer/APK mutation.'])
 save('freeze-manifest.json',freeze);print(json.dumps(dict(validation='PASS',freeze=str(REF/'freeze-manifest.json'),sha256=sha(REF/'freeze-manifest.json'),source_evidence_files=len(hashes),captured_unique_functions=len(functions),original_arm64_cases=8800,host_results=player['results'])))
if __name__=='__main__':main()
