"""Derive immutable source-ordered method catalog from executed registration."""
import hashlib,json
from pathlib import Path
WORLD=Path(__file__).resolve().parents[1]
probe=WORLD/'reference/gameobject-lua-representation/object-producer-probe.json'
rows=json.loads(probe.read_text())['cases']
lines=['// Generated by tools/generate_gameobject_lua_catalog.py.\n',
       '// Original registration probe SHA256 '+hashlib.sha256(probe.read_bytes()).hexdigest()+'\n']
for name,index in [('gameobject_methods',1),('character_methods',3)]:
    values=rows[index]['bindings'];assert len(values)==(41 if index==1 else 130)
    lines.append('static const dh2_script_object_method '+name+'[]={\n')
    for text,address in values:lines.append(' {'+json.dumps(text)+',0x'+format(address,'x')+',0},\n')
    lines.append('};\n')
(WORLD/'gameobject_lua_catalog.inc').write_text(''.join(lines))
print(json.dumps({'validation':'PASS','methods':171}))
